package me.kright.gametools.pga3d

import scala.annotation.targetName
import me.kright.gametools.flatarray.FlatDoubleSerializer


/**
 * A vector: the difference between two points, a direction with magnitude; an ideal point with w = 0.
 * Stored in dual representation with fields x, y, z. Translators move points but do not change vectors.
 *
 * Variable fields: x, y, z.
 * Basis blade coefficients: wyz = -x, wxz = y, wxy = -z.
 *
 * Generated by pgaNdCodeGen (me.kright.gametools.pga.codegen.scalagen.pga3d.runScalaCodeGen).
 * Do not edit by hand: change the generator and re-run it.
 */
final case class Pga3dVector(x: Double = 0.0,
                             y: Double = 0.0,
                             z: Double = 0.0) derives CanEqual, FlatDoubleSerializer:

  inline def wyz: Double = -x

  inline def wxz: Double = y

  inline def wxy: Double = -z

  override def toString: String =
    s"Pga3dVector(x = $x, y = $y, z = $z)"

  def dual: Pga3dPlaneIdeal =
    Pga3dPlaneIdeal(
      x = x,
      y = y,
      z = z,
    )

  def weight: Pga3dVector =
    this

  @targetName("unaryMinus")
  def unary_- : Pga3dVector =
    Pga3dVector(
      x = -x,
      y = -y,
      z = -z,
    )

  def reverse: Pga3dVector =
    -this

  def antiReverse: Pga3dVector =
    this

  def weightNormSquare: Double =
    (x * x + y * y + z * z)

  def weightNorm: Double =
    Math.sqrt(weightNormSquare)

  def normalizedByWeight =
    this / weightNorm

  def normSquare: Double =
    (x * x + y * y + z * z)

  def norm: Double =
    Math.sqrt(normSquare)

  def normalizedByNorm =
    this / norm

  @targetName("times")
  def *(r: Double): Pga3dVector =
    Pga3dVector(
      x = r * x,
      y = r * y,
      z = r * z,
    )

  /** multiplies by the reciprocal: one division instead of one per component, at the cost of one extra rounding (~0.5 ulp) */
  @targetName("div")
  def /(r: Double): Pga3dVector =
    this * (1.0 / r)

  infix def min(other: Pga3dVector): Pga3dVector =
    Pga3dVector(math.min(x, other.x), math.min(y, other.y), math.min(z, other.z))

  infix def max(other: Pga3dVector): Pga3dVector =
    Pga3dVector(math.max(x, other.x), math.max(y, other.y), math.max(z, other.z))

  @targetName("plus")
  def +(r: Pga3dProjectivePoint): Pga3dProjectivePoint =
    Pga3dProjectivePoint(
      x = (r.x + x),
      y = (r.y + y),
      z = (r.z + z),
      w = r.w,
    )

  @targetName("minus")
  def -(r: Pga3dProjectivePoint): Pga3dProjectivePoint =
    Pga3dProjectivePoint(
      x = (x - r.x),
      y = (y - r.y),
      z = (z - r.z),
      w = -r.w,
    )

  def madd(r: Pga3dProjectivePoint, mult: Double): Pga3dProjectivePoint =
    Pga3dProjectivePoint(
      x = (x + mult * r.x),
      y = (y + mult * r.y),
      z = (z + mult * r.z),
      w = mult * r.w,
    )

  @targetName("plus")
  def +(r: Pga3dPoint): Pga3dPoint =
    Pga3dPoint(
      x = (r.x + x),
      y = (r.y + y),
      z = (r.z + z),
    )

  @targetName("minus")
  def -(r: Pga3dPoint): Pga3dProjectivePoint =
    Pga3dProjectivePoint(
      x = (x - r.x),
      y = (y - r.y),
      z = (z - r.z),
      w = -1.0,
    )

  def madd(r: Pga3dPoint, mult: Double): Pga3dProjectivePoint =
    Pga3dProjectivePoint(
      x = (x + mult * r.x),
      y = (y + mult * r.y),
      z = (z + mult * r.z),
      w = mult,
    )

  @targetName("plus")
  def +(r: Pga3dVector): Pga3dVector =
    Pga3dVector(
      x = (r.x + x),
      y = (r.y + y),
      z = (r.z + z),
    )

  @targetName("minus")
  def -(r: Pga3dVector): Pga3dVector =
    Pga3dVector(
      x = (x - r.x),
      y = (y - r.y),
      z = (z - r.z),
    )

  def madd(r: Pga3dVector, mult: Double): Pga3dVector =
    Pga3dVector(
      x = (x + mult * r.x),
      y = (y + mult * r.y),
      z = (z + mult * r.z),
    )

  /** componentwise product on the raw fields; NOT a geometric-algebra operation (basis-dependent) */
  def scale(r: Pga3dVector): Pga3dVector =
    Pga3dVector(
      x = x * r.x,
      y = y * r.y,
      z = z * r.z,
    )

  /** componentwise 1/x on the raw fields (a zero field yields Infinity); NOT the multiplicative inverse */
  def reciprocal: Pga3dVector =
    Pga3dVector(
      x = 1.0 / x,
      y = 1.0 / y,
      z = 1.0 / z,
    )

  def toMultivector: Pga3dMultivector =
    Pga3dMultivector(
      s = 0.0,
      w = 0.0,
      x = 0.0,
      y = 0.0,
      z = 0.0,
      wx = 0.0,
      wy = 0.0,
      wz = 0.0,
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      wxy = -z,
      wxz = y,
      wyz = -x,
      xyz = 0.0,
      i = 0.0,
    )

  def toProjectivePoint: Pga3dProjectivePoint =
    Pga3dProjectivePoint(
      x = x,
      y = y,
      z = z,
      w = 0.0,
    )

  def toPointUnsafe: Pga3dPoint =
    Pga3dPoint(
      x = x,
      y = y,
      z = z,
    )

  infix def geometric(r: Pga3dMotor): Pga3dMultivector =
    Pga3dMultivector(
      s = 0.0,
      w = (r.xy * z + r.yz * x - r.xz * y),
      x = 0.0,
      y = 0.0,
      z = 0.0,
      wx = 0.0,
      wy = 0.0,
      wz = 0.0,
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      wxy = (-r.s * z - r.xz * x - r.yz * y),
      wxz = (r.s * y + r.xy * x - r.yz * z),
      wyz = (r.xy * y + r.xz * z - r.s * x),
      xyz = 0.0,
      i = 0.0,
    )

  infix def geometric(r: Pga3dPlane): Pga3dMotor =
    Pga3dMotor(
      s = 0.0,
      wx = (r.z * y - r.y * z),
      wy = (r.x * z - r.z * x),
      wz = (r.y * x - r.x * y),
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      i = (-r.x * x - r.y * y - r.z * z),
    )

  infix def geometric(r: Pga3dBivector): Pga3dMultivector =
    Pga3dMultivector(
      s = 0.0,
      w = (r.xy * z + r.yz * x - r.xz * y),
      x = 0.0,
      y = 0.0,
      z = 0.0,
      wx = 0.0,
      wy = 0.0,
      wz = 0.0,
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      wxy = (-r.xz * x - r.yz * y),
      wxz = (r.xy * x - r.yz * z),
      wyz = (r.xy * y + r.xz * z),
      xyz = 0.0,
      i = 0.0,
    )

  infix def geometric(r: Pga3dProjectivePoint): Pga3dBivectorWeight =
    Pga3dBivectorWeight(
      wx = r.w * x,
      wy = r.w * y,
      wz = r.w * z,
    )

  infix def geometric(r: Pga3dRotor): Pga3dMultivector =
    Pga3dMultivector(
      s = 0.0,
      w = (r.xy * z + r.yz * x - r.xz * y),
      x = 0.0,
      y = 0.0,
      z = 0.0,
      wx = 0.0,
      wy = 0.0,
      wz = 0.0,
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      wxy = (-r.s * z - r.xz * x - r.yz * y),
      wxz = (r.s * y + r.xy * x - r.yz * z),
      wyz = (r.xy * y + r.xz * z - r.s * x),
      xyz = 0.0,
      i = 0.0,
    )

  infix def geometric(r: Pga3dProjectiveTranslator): Pga3dVector =
    Pga3dVector(
      x = r.s * x,
      y = r.s * y,
      z = r.s * z,
    )

  infix def geometric(r: Pga3dTranslator): Pga3dVector =
    this

  infix def geometric(r: Pga3dPoint): Pga3dBivectorWeight =
    Pga3dBivectorWeight(
      wx = x,
      wy = y,
      wz = z,
    )

  infix def geometric(r: Pga3dPlaneIdeal): Pga3dMotor =
    Pga3dMotor(
      s = 0.0,
      wx = (r.z * y - r.y * z),
      wy = (r.x * z - r.z * x),
      wz = (r.y * x - r.x * y),
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      i = (-r.x * x - r.y * y - r.z * z),
    )

  infix def geometric(r: Pga3dBivectorBulk): Pga3dMultivector =
    Pga3dMultivector(
      s = 0.0,
      w = (r.xy * z + r.yz * x - r.xz * y),
      x = 0.0,
      y = 0.0,
      z = 0.0,
      wx = 0.0,
      wy = 0.0,
      wz = 0.0,
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      wxy = (-r.xz * x - r.yz * y),
      wxz = (r.xy * x - r.yz * z),
      wyz = (r.xy * y + r.xz * z),
      xyz = 0.0,
      i = 0.0,
    )

  infix def geometric(r: Pga3dPointCenter.type): Pga3dBivectorWeight =
    Pga3dBivectorWeight(
      wx = x,
      wy = y,
      wz = z,
    )

  infix def dot(r: Pga3dMotor): Pga3dMultivector =
    Pga3dMultivector(
      s = 0.0,
      w = (r.xy * z + r.yz * x - r.xz * y),
      x = 0.0,
      y = 0.0,
      z = 0.0,
      wx = 0.0,
      wy = 0.0,
      wz = 0.0,
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      wxy = -r.s * z,
      wxz = r.s * y,
      wyz = -r.s * x,
      xyz = 0.0,
      i = 0.0,
    )

  infix def dot(r: Pga3dPlane): Pga3dBivectorWeight =
    Pga3dBivectorWeight(
      wx = (r.z * y - r.y * z),
      wy = (r.x * z - r.z * x),
      wz = (r.y * x - r.x * y),
    )

  infix def dot(r: Pga3dBivector): Pga3dPlane =
    Pga3dPlane(
      x = 0.0,
      y = 0.0,
      z = 0.0,
      w = (r.xy * z + r.yz * x - r.xz * y),
    )

  infix def dot(r: Pga3dRotor): Pga3dMultivector =
    Pga3dMultivector(
      s = 0.0,
      w = (r.xy * z + r.yz * x - r.xz * y),
      x = 0.0,
      y = 0.0,
      z = 0.0,
      wx = 0.0,
      wy = 0.0,
      wz = 0.0,
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      wxy = -r.s * z,
      wxz = r.s * y,
      wyz = -r.s * x,
      xyz = 0.0,
      i = 0.0,
    )

  infix def dot(r: Pga3dProjectiveTranslator): Pga3dVector =
    Pga3dVector(
      x = r.s * x,
      y = r.s * y,
      z = r.s * z,
    )

  infix def dot(r: Pga3dTranslator): Pga3dVector =
    this

  infix def dot(r: Pga3dPlaneIdeal): Pga3dBivectorWeight =
    Pga3dBivectorWeight(
      wx = (r.z * y - r.y * z),
      wy = (r.x * z - r.z * x),
      wz = (r.y * x - r.x * y),
    )

  infix def dot(r: Pga3dBivectorBulk): Pga3dPlane =
    Pga3dPlane(
      x = 0.0,
      y = 0.0,
      z = 0.0,
      w = (r.xy * z + r.yz * x - r.xz * y),
    )

  infix def wedge(r: Pga3dMotor): Pga3dVector =
    Pga3dVector(
      x = r.s * x,
      y = r.s * y,
      z = r.s * z,
    )

  inline infix def ^(r: Pga3dMotor): Pga3dVector = wedge(r)

  inline infix def meet(r: Pga3dMotor): Pga3dVector = wedge(r)

  infix def wedge(r: Pga3dPlane): Pga3dPseudoScalar =
    Pga3dPseudoScalar(
      i = (-r.x * x - r.y * y - r.z * z),
    )

  inline infix def ^(r: Pga3dPlane): Pga3dPseudoScalar = wedge(r)

  inline infix def meet(r: Pga3dPlane): Pga3dPseudoScalar = wedge(r)

  infix def wedge(r: Pga3dRotor): Pga3dVector =
    Pga3dVector(
      x = r.s * x,
      y = r.s * y,
      z = r.s * z,
    )

  inline infix def ^(r: Pga3dRotor): Pga3dVector = wedge(r)

  inline infix def meet(r: Pga3dRotor): Pga3dVector = wedge(r)

  infix def wedge(r: Pga3dProjectiveTranslator): Pga3dVector =
    Pga3dVector(
      x = r.s * x,
      y = r.s * y,
      z = r.s * z,
    )

  inline infix def ^(r: Pga3dProjectiveTranslator): Pga3dVector = wedge(r)

  inline infix def meet(r: Pga3dProjectiveTranslator): Pga3dVector = wedge(r)

  infix def wedge(r: Pga3dTranslator): Pga3dVector =
    this

  inline infix def ^(r: Pga3dTranslator): Pga3dVector = wedge(r)

  inline infix def meet(r: Pga3dTranslator): Pga3dVector = wedge(r)

  infix def wedge(r: Pga3dPlaneIdeal): Pga3dPseudoScalar =
    Pga3dPseudoScalar(
      i = (-r.x * x - r.y * y - r.z * z),
    )

  inline infix def ^(r: Pga3dPlaneIdeal): Pga3dPseudoScalar = wedge(r)

  inline infix def meet(r: Pga3dPlaneIdeal): Pga3dPseudoScalar = wedge(r)

  infix def antiGeometric(r: Pga3dMotor): Pga3dMultivector =
    Pga3dMultivector(
      s = 0.0,
      w = (r.wx * x + r.wy * y + r.wz * z),
      x = (r.s * x + r.xy * y + r.xz * z),
      y = (r.s * y + r.yz * z - r.xy * x),
      z = (r.s * z - r.xz * x - r.yz * y),
      wx = 0.0,
      wy = 0.0,
      wz = 0.0,
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      wxy = (r.wy * x - r.i * z - r.wx * y),
      wxz = (r.i * y + r.wz * x - r.wx * z),
      wyz = (r.wz * y - r.i * x - r.wy * z),
      xyz = (r.xz * y - r.xy * z - r.yz * x),
      i = 0.0,
    )

  infix def antiGeometric(r: Pga3dPlane): Pga3dMotor =
    Pga3dMotor(
      s = (r.x * x + r.y * y + r.z * z),
      wx = r.w * x,
      wy = r.w * y,
      wz = r.w * z,
      xy = (r.x * y - r.y * x),
      xz = (r.x * z - r.z * x),
      yz = (r.y * z - r.z * y),
      i = 0.0,
    )

  infix def antiGeometric(r: Pga3dBivector): Pga3dMultivector =
    Pga3dMultivector(
      s = 0.0,
      w = (r.wx * x + r.wy * y + r.wz * z),
      x = (r.xy * y + r.xz * z),
      y = (r.yz * z - r.xy * x),
      z = (-r.xz * x - r.yz * y),
      wx = 0.0,
      wy = 0.0,
      wz = 0.0,
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      wxy = (r.wy * x - r.wx * y),
      wxz = (r.wz * x - r.wx * z),
      wyz = (r.wz * y - r.wy * z),
      xyz = (r.xz * y - r.xy * z - r.yz * x),
      i = 0.0,
    )

  infix def antiGeometric(r: Pga3dProjectivePoint): Pga3dMotor =
    Pga3dMotor(
      s = 0.0,
      wx = (r.z * y - r.y * z),
      wy = (r.x * z - r.z * x),
      wz = (r.y * x - r.x * y),
      xy = -r.w * z,
      xz = r.w * y,
      yz = -r.w * x,
      i = (r.x * x + r.y * y + r.z * z),
    )

  infix def antiGeometric(r: Pga3dRotor): Pga3dMultivector =
    Pga3dMultivector(
      s = 0.0,
      w = 0.0,
      x = (r.s * x + r.xy * y + r.xz * z),
      y = (r.s * y + r.yz * z - r.xy * x),
      z = (r.s * z - r.xz * x - r.yz * y),
      wx = 0.0,
      wy = 0.0,
      wz = 0.0,
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      wxy = 0.0,
      wxz = 0.0,
      wyz = 0.0,
      xyz = (r.xz * y - r.xy * z - r.yz * x),
      i = 0.0,
    )

  infix def antiGeometric(r: Pga3dProjectiveTranslator): Pga3dMultivector =
    Pga3dMultivector(
      s = 0.0,
      w = (r.wx * x + r.wy * y + r.wz * z),
      x = r.s * x,
      y = r.s * y,
      z = r.s * z,
      wx = 0.0,
      wy = 0.0,
      wz = 0.0,
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      wxy = (r.wy * x - r.wx * y),
      wxz = (r.wz * x - r.wx * z),
      wyz = (r.wz * y - r.wy * z),
      xyz = 0.0,
      i = 0.0,
    )

  infix def antiGeometric(r: Pga3dTranslator): Pga3dMultivector =
    Pga3dMultivector(
      s = 0.0,
      w = (r.wx * x + r.wy * y + r.wz * z),
      x = x,
      y = y,
      z = z,
      wx = 0.0,
      wy = 0.0,
      wz = 0.0,
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      wxy = (r.wy * x - r.wx * y),
      wxz = (r.wz * x - r.wx * z),
      wyz = (r.wz * y - r.wy * z),
      xyz = 0.0,
      i = 0.0,
    )

  infix def antiGeometric(r: Pga3dVector): Pga3dMotor =
    Pga3dMotor(
      s = 0.0,
      wx = (r.z * y - r.y * z),
      wy = (r.x * z - r.z * x),
      wz = (r.y * x - r.x * y),
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      i = (r.x * x + r.y * y + r.z * z),
    )

  infix def antiGeometric(r: Pga3dPoint): Pga3dMotor =
    Pga3dMotor(
      s = 0.0,
      wx = (r.z * y - r.y * z),
      wy = (r.x * z - r.z * x),
      wz = (r.y * x - r.x * y),
      xy = -z,
      xz = y,
      yz = -x,
      i = (r.x * x + r.y * y + r.z * z),
    )

  infix def antiGeometric(r: Pga3dPlaneIdeal): Pga3dRotor =
    Pga3dRotor(
      s = (r.x * x + r.y * y + r.z * z),
      xy = (r.x * y - r.y * x),
      xz = (r.x * z - r.z * x),
      yz = (r.y * z - r.z * y),
    )

  infix def antiGeometric(r: Pga3dBivectorBulk): Pga3dMultivector =
    Pga3dMultivector(
      s = 0.0,
      w = 0.0,
      x = (r.xy * y + r.xz * z),
      y = (r.yz * z - r.xy * x),
      z = (-r.xz * x - r.yz * y),
      wx = 0.0,
      wy = 0.0,
      wz = 0.0,
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      wxy = 0.0,
      wxz = 0.0,
      wyz = 0.0,
      xyz = (r.xz * y - r.xy * z - r.yz * x),
      i = 0.0,
    )

  infix def antiGeometric(r: Pga3dBivectorWeight): Pga3dMultivector =
    Pga3dMultivector(
      s = 0.0,
      w = (r.wx * x + r.wy * y + r.wz * z),
      x = 0.0,
      y = 0.0,
      z = 0.0,
      wx = 0.0,
      wy = 0.0,
      wz = 0.0,
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      wxy = (r.wy * x - r.wx * y),
      wxz = (r.wz * x - r.wx * z),
      wyz = (r.wz * y - r.wy * z),
      xyz = 0.0,
      i = 0.0,
    )

  infix def antiGeometric(r: Pga3dPseudoScalar): Pga3dVector =
    Pga3dVector(
      x = r.i * x,
      y = r.i * y,
      z = r.i * z,
    )

  infix def antiGeometric(r: Pga3dPointCenter.type): Pga3dBivectorBulk =
    Pga3dBivectorBulk(
      xy = -z,
      xz = y,
      yz = -x,
    )

  infix def antiDot(r: Pga3dMotor): Pga3dMultivector =
    Pga3dMultivector(
      s = 0.0,
      w = 0.0,
      x = r.s * x,
      y = r.s * y,
      z = r.s * z,
      wx = 0.0,
      wy = 0.0,
      wz = 0.0,
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      wxy = (r.wy * x - r.i * z - r.wx * y),
      wxz = (r.i * y + r.wz * x - r.wx * z),
      wyz = (r.wz * y - r.i * x - r.wy * z),
      xyz = (r.xz * y - r.xy * z - r.yz * x),
      i = 0.0,
    )

  infix def antiDot(r: Pga3dPlane): Pga3dBivector =
    Pga3dBivector(
      wx = r.w * x,
      wy = r.w * y,
      wz = r.w * z,
      xy = (r.x * y - r.y * x),
      xz = (r.x * z - r.z * x),
      yz = (r.y * z - r.z * y),
    )

  infix def antiDot(r: Pga3dBivector): Pga3dProjectivePoint =
    Pga3dProjectivePoint(
      x = (r.wy * z - r.wz * y),
      y = (r.wz * x - r.wx * z),
      z = (r.wx * y - r.wy * x),
      w = (r.xz * y - r.xy * z - r.yz * x),
    )

  infix def antiDot(r: Pga3dProjectivePoint): Pga3dPseudoScalar =
    Pga3dPseudoScalar(
      i = (r.x * x + r.y * y + r.z * z),
    )

  infix def antiDot(r: Pga3dRotor): Pga3dMultivector =
    Pga3dMultivector(
      s = 0.0,
      w = 0.0,
      x = r.s * x,
      y = r.s * y,
      z = r.s * z,
      wx = 0.0,
      wy = 0.0,
      wz = 0.0,
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      wxy = 0.0,
      wxz = 0.0,
      wyz = 0.0,
      xyz = (r.xz * y - r.xy * z - r.yz * x),
      i = 0.0,
    )

  infix def antiDot(r: Pga3dProjectiveTranslator): Pga3dMultivector =
    Pga3dMultivector(
      s = 0.0,
      w = 0.0,
      x = r.s * x,
      y = r.s * y,
      z = r.s * z,
      wx = 0.0,
      wy = 0.0,
      wz = 0.0,
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      wxy = (r.wy * x - r.wx * y),
      wxz = (r.wz * x - r.wx * z),
      wyz = (r.wz * y - r.wy * z),
      xyz = 0.0,
      i = 0.0,
    )

  infix def antiDot(r: Pga3dTranslator): Pga3dMultivector =
    Pga3dMultivector(
      s = 0.0,
      w = 0.0,
      x = x,
      y = y,
      z = z,
      wx = 0.0,
      wy = 0.0,
      wz = 0.0,
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      wxy = (r.wy * x - r.wx * y),
      wxz = (r.wz * x - r.wx * z),
      wyz = (r.wz * y - r.wy * z),
      xyz = 0.0,
      i = 0.0,
    )

  infix def antiDot(r: Pga3dVector): Pga3dPseudoScalar =
    Pga3dPseudoScalar(
      i = (r.x * x + r.y * y + r.z * z),
    )

  infix def antiDot(r: Pga3dPoint): Pga3dPseudoScalar =
    Pga3dPseudoScalar(
      i = (r.x * x + r.y * y + r.z * z),
    )

  infix def antiDot(r: Pga3dPlaneIdeal): Pga3dBivectorBulk =
    Pga3dBivectorBulk(
      xy = (r.x * y - r.y * x),
      xz = (r.x * z - r.z * x),
      yz = (r.y * z - r.z * y),
    )

  infix def antiDot(r: Pga3dBivectorBulk): Pga3dProjectivePoint =
    Pga3dProjectivePoint(
      x = 0.0,
      y = 0.0,
      z = 0.0,
      w = (r.xz * y - r.xy * z - r.yz * x),
    )

  infix def antiDot(r: Pga3dBivectorWeight): Pga3dVector =
    Pga3dVector(
      x = (r.wy * z - r.wz * y),
      y = (r.wz * x - r.wx * z),
      z = (r.wx * y - r.wy * x),
    )

  infix def antiDot(r: Pga3dPseudoScalar): Pga3dVector =
    Pga3dVector(
      x = r.i * x,
      y = r.i * y,
      z = r.i * z,
    )

  infix def antiDotI(r: Pga3dProjectivePoint): Double =
    (r.x * x + r.y * y + r.z * z)

  infix def antiDotI(r: Pga3dVector): Double =
    (r.x * x + r.y * y + r.z * z)

  infix def antiDotI(r: Pga3dPoint): Double =
    (r.x * x + r.y * y + r.z * z)

  infix def antiWedge(r: Pga3dMotor): Pga3dMultivector =
    Pga3dMultivector(
      s = 0.0,
      w = (r.wx * x + r.wy * y + r.wz * z),
      x = (r.xy * y + r.xz * z),
      y = (r.yz * z - r.xy * x),
      z = (-r.xz * x - r.yz * y),
      wx = 0.0,
      wy = 0.0,
      wz = 0.0,
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      wxy = -r.i * z,
      wxz = r.i * y,
      wyz = -r.i * x,
      xyz = 0.0,
      i = 0.0,
    )

  inline infix def v(r: Pga3dMotor): Pga3dMultivector = antiWedge(r)

  inline infix def join(r: Pga3dMotor): Pga3dMultivector = antiWedge(r)

  infix def antiWedge(r: Pga3dPlane): Double =
    (r.x * x + r.y * y + r.z * z)

  inline infix def v(r: Pga3dPlane): Double = antiWedge(r)

  inline infix def join(r: Pga3dPlane): Double = antiWedge(r)

  infix def antiWedge(r: Pga3dBivector): Pga3dPlane =
    Pga3dPlane(
      x = (r.xy * y + r.xz * z),
      y = (r.yz * z - r.xy * x),
      z = (-r.xz * x - r.yz * y),
      w = (r.wx * x + r.wy * y + r.wz * z),
    )

  inline infix def v(r: Pga3dBivector): Pga3dPlane = antiWedge(r)

  inline infix def join(r: Pga3dBivector): Pga3dPlane = antiWedge(r)

  infix def antiWedge(r: Pga3dProjectivePoint): Pga3dBivector =
    Pga3dBivector(
      wx = (r.z * y - r.y * z),
      wy = (r.x * z - r.z * x),
      wz = (r.y * x - r.x * y),
      xy = -r.w * z,
      xz = r.w * y,
      yz = -r.w * x,
    )

  inline infix def v(r: Pga3dProjectivePoint): Pga3dBivector = antiWedge(r)

  inline infix def join(r: Pga3dProjectivePoint): Pga3dBivector = antiWedge(r)

  infix def antiWedge(r: Pga3dRotor): Pga3dPlaneIdeal =
    Pga3dPlaneIdeal(
      x = (r.xy * y + r.xz * z),
      y = (r.yz * z - r.xy * x),
      z = (-r.xz * x - r.yz * y),
    )

  inline infix def v(r: Pga3dRotor): Pga3dPlaneIdeal = antiWedge(r)

  inline infix def join(r: Pga3dRotor): Pga3dPlaneIdeal = antiWedge(r)

  infix def antiWedge(r: Pga3dProjectiveTranslator): Pga3dPlane =
    Pga3dPlane(
      x = 0.0,
      y = 0.0,
      z = 0.0,
      w = (r.wx * x + r.wy * y + r.wz * z),
    )

  inline infix def v(r: Pga3dProjectiveTranslator): Pga3dPlane = antiWedge(r)

  inline infix def join(r: Pga3dProjectiveTranslator): Pga3dPlane = antiWedge(r)

  infix def antiWedge(r: Pga3dTranslator): Pga3dPlane =
    Pga3dPlane(
      x = 0.0,
      y = 0.0,
      z = 0.0,
      w = (r.wx * x + r.wy * y + r.wz * z),
    )

  inline infix def v(r: Pga3dTranslator): Pga3dPlane = antiWedge(r)

  inline infix def join(r: Pga3dTranslator): Pga3dPlane = antiWedge(r)

  infix def antiWedge(r: Pga3dVector): Pga3dBivectorWeight =
    Pga3dBivectorWeight(
      wx = (r.z * y - r.y * z),
      wy = (r.x * z - r.z * x),
      wz = (r.y * x - r.x * y),
    )

  inline infix def v(r: Pga3dVector): Pga3dBivectorWeight = antiWedge(r)

  inline infix def join(r: Pga3dVector): Pga3dBivectorWeight = antiWedge(r)

  infix def antiWedge(r: Pga3dPoint): Pga3dBivector =
    Pga3dBivector(
      wx = (r.z * y - r.y * z),
      wy = (r.x * z - r.z * x),
      wz = (r.y * x - r.x * y),
      xy = -z,
      xz = y,
      yz = -x,
    )

  inline infix def v(r: Pga3dPoint): Pga3dBivector = antiWedge(r)

  inline infix def join(r: Pga3dPoint): Pga3dBivector = antiWedge(r)

  infix def antiWedge(r: Pga3dPlaneIdeal): Double =
    (r.x * x + r.y * y + r.z * z)

  inline infix def v(r: Pga3dPlaneIdeal): Double = antiWedge(r)

  inline infix def join(r: Pga3dPlaneIdeal): Double = antiWedge(r)

  infix def antiWedge(r: Pga3dBivectorBulk): Pga3dPlaneIdeal =
    Pga3dPlaneIdeal(
      x = (r.xy * y + r.xz * z),
      y = (r.yz * z - r.xy * x),
      z = (-r.xz * x - r.yz * y),
    )

  inline infix def v(r: Pga3dBivectorBulk): Pga3dPlaneIdeal = antiWedge(r)

  inline infix def join(r: Pga3dBivectorBulk): Pga3dPlaneIdeal = antiWedge(r)

  infix def antiWedge(r: Pga3dBivectorWeight): Pga3dPlane =
    Pga3dPlane(
      x = 0.0,
      y = 0.0,
      z = 0.0,
      w = (r.wx * x + r.wy * y + r.wz * z),
    )

  inline infix def v(r: Pga3dBivectorWeight): Pga3dPlane = antiWedge(r)

  inline infix def join(r: Pga3dBivectorWeight): Pga3dPlane = antiWedge(r)

  infix def antiWedge(r: Pga3dPseudoScalar): Pga3dVector =
    Pga3dVector(
      x = r.i * x,
      y = r.i * y,
      z = r.i * z,
    )

  inline infix def v(r: Pga3dPseudoScalar): Pga3dVector = antiWedge(r)

  inline infix def join(r: Pga3dPseudoScalar): Pga3dVector = antiWedge(r)

  infix def antiWedge(r: Pga3dPointCenter.type): Pga3dBivectorBulk =
    Pga3dBivectorBulk(
      xy = -z,
      xz = y,
      yz = -x,
    )

  inline infix def v(r: Pga3dPointCenter.type): Pga3dBivectorBulk = antiWedge(r)

  inline infix def join(r: Pga3dPointCenter.type): Pga3dBivectorBulk = antiWedge(r)

  infix def cross(r: Pga3dMotor): Pga3dVector =
    Pga3dVector(
      x = (-r.xy * y - r.xz * z),
      y = (r.xy * x - r.yz * z),
      z = (r.xz * x + r.yz * y),
    )

  infix def cross(r: Pga3dPlane): Pga3dPseudoScalar =
    Pga3dPseudoScalar(
      i = (-r.x * x - r.y * y - r.z * z),
    )

  infix def cross(r: Pga3dBivector): Pga3dVector =
    Pga3dVector(
      x = (-r.xy * y - r.xz * z),
      y = (r.xy * x - r.yz * z),
      z = (r.xz * x + r.yz * y),
    )

  infix def cross(r: Pga3dProjectivePoint): Pga3dBivectorWeight =
    Pga3dBivectorWeight(
      wx = r.w * x,
      wy = r.w * y,
      wz = r.w * z,
    )

  infix def cross(r: Pga3dRotor): Pga3dVector =
    Pga3dVector(
      x = (-r.xy * y - r.xz * z),
      y = (r.xy * x - r.yz * z),
      z = (r.xz * x + r.yz * y),
    )

  infix def cross(r: Pga3dPoint): Pga3dBivectorWeight =
    Pga3dBivectorWeight(
      wx = x,
      wy = y,
      wz = z,
    )

  infix def cross(r: Pga3dPlaneIdeal): Pga3dPseudoScalar =
    Pga3dPseudoScalar(
      i = (-r.x * x - r.y * y - r.z * z),
    )

  infix def cross(r: Pga3dBivectorBulk): Pga3dVector =
    Pga3dVector(
      x = (-r.xy * y - r.xz * z),
      y = (r.xy * x - r.yz * z),
      z = (r.xz * x + r.yz * y),
    )

  infix def cross(r: Pga3dPointCenter.type): Pga3dBivectorWeight =
    Pga3dBivectorWeight(
      wx = x,
      wy = y,
      wz = z,
    )


object Pga3dVector:

  inline val componentsCount = 3

  val zero: Pga3dVector = Pga3dVector(0.0, 0.0, 0.0)

  def blade3(wxy: Double, wxz: Double, wyz: Double): Pga3dVector =
    Pga3dVector(
      x = -wyz,
      y = wxz,
      z = -wxy,
    )

  def interpolate(a: Pga3dVector, b: Pga3dVector, t: Double): Pga3dVector =
    a * (1.0 - t) + b * t