package me.kright.gametools.pga3d

import scala.annotation.targetName
import me.kright.gametools.flatarray.FlatDoubleSerializer


/**
 * A rotor: rotation around an axis passing through the origin, applied with rotor.sandwich(obj).
 * A rotor is the exponent of a Pga3dBivectorBulk (bivectorBulk.exp), and rotor.log returns that bivector back.
 *
 * Variable fields: s, xy, xz, yz.
 *
 * Generated by pgaNdCodeGen (me.kright.gametools.pga.codegen.scalagen.pga3d.runScalaCodeGen).
 * Do not edit by hand: change the generator and re-run it.
 */
final case class Pga3dRotor(s: Double = 0.0,
                            xy: Double = 0.0,
                            xz: Double = 0.0,
                            yz: Double = 0.0) derives CanEqual, FlatDoubleSerializer:

  override def toString: String =
    s"Pga3dRotor(s = $s, xy = $xy, xz = $xz, yz = $yz)"

  def dual: Pga3dMotor =
    Pga3dMotor(
      s = 0.0,
      wx = yz,
      wy = -xz,
      wz = xy,
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      i = s,
    )

  def bulk: Pga3dRotor =
    this

  @targetName("unaryMinus")
  def unary_- : Pga3dRotor =
    Pga3dRotor(
      s = -s,
      xy = -xy,
      xz = -xz,
      yz = -yz,
    )

  def reverse: Pga3dRotor =
    Pga3dRotor(
      s = s,
      xy = -xy,
      xz = -xz,
      yz = -yz,
    )

  def antiReverse: Pga3dRotor =
    Pga3dRotor(
      s = s,
      xy = -xy,
      xz = -xz,
      yz = -yz,
    )

  def bulkNormSquare: Double =
    (s * s + xy * xy + xz * xz + yz * yz)

  def bulkNorm: Double =
    Math.sqrt(bulkNormSquare)

  def normalizedByBulk =
    this / bulkNorm

  def normSquare: Double =
    (s * s + xy * xy + xz * xz + yz * yz)

  def norm: Double =
    Math.sqrt(normSquare)

  def normalizedByNorm =
    this / norm

  @targetName("times")
  def *(r: Double): Pga3dRotor =
    Pga3dRotor(
      s = r * s,
      xy = r * xy,
      xz = r * xz,
      yz = r * yz,
    )

  /** multiplies by the reciprocal: one division instead of one per component, at the cost of one extra rounding (~0.5 ulp) */
  @targetName("div")
  def /(r: Double): Pga3dRotor =
    this * (1.0 / r)

  @targetName("plus")
  def +(r: Pga3dRotor): Pga3dRotor =
    Pga3dRotor(
      s = (r.s + s),
      xy = (r.xy + xy),
      xz = (r.xz + xz),
      yz = (r.yz + yz),
    )

  @targetName("minus")
  def -(r: Pga3dRotor): Pga3dRotor =
    Pga3dRotor(
      s = (s - r.s),
      xy = (xy - r.xy),
      xz = (xz - r.xz),
      yz = (yz - r.yz),
    )

  def madd(r: Pga3dRotor, mult: Double): Pga3dRotor =
    Pga3dRotor(
      s = (s + mult * r.s),
      xy = (xy + mult * r.xy),
      xz = (xz + mult * r.xz),
      yz = (yz + mult * r.yz),
    )

  /** componentwise product on the raw fields; NOT a geometric-algebra operation (basis-dependent) */
  def scale(r: Pga3dRotor): Pga3dRotor =
    Pga3dRotor(
      s = s * r.s,
      xy = xy * r.xy,
      xz = xz * r.xz,
      yz = yz * r.yz,
    )

  /** componentwise 1/x on the raw fields (a zero field yields Infinity); NOT the multiplicative inverse */
  def reciprocal: Pga3dRotor =
    Pga3dRotor(
      s = 1.0 / s,
      xy = 1.0 / xy,
      xz = 1.0 / xz,
      yz = 1.0 / yz,
    )

  def log: Pga3dBivectorBulk =
    val scalar = s
    if (s < 0.0) {
      return (-this).log
    }

    val lenXYZ = Math.sqrt(xy * xy + xz * xz + yz * yz)
    val angle = Math.atan2(lenXYZ, scalar)

    // for a normalized rotor sin(angle) = lenXYZ, so this is angle / sin(angle); the series branch:
    // x/sin(x) = 1 / (sin(x)/x) = 1 / (1 - x^2/6 + x^4/120 - ...);
    // substitute v = x^2/6 - x^4/120 + ... into 1/(1 - v) = 1 + v + v^2 + ...:
    //   x/sin(x) = 1 + x^2/6 + (1/36 - 1/120)*x^4 + ...
    //            = 1 + x^2/6 + 7*x^4/360 + ...
    // at x <= 1e-5 the dropped 7*x^4/360 <= 2e-22 relative term is far below 1e-17,
    // so the second-order form is exact in double
    val b = if (Math.abs(angle) > 1e-5) {
      angle / lenXYZ
    } else {
      1.0 + angle * angle / 6.0
    }

    Pga3dBivectorBulk(
      xy = b * xy,
      xz = b * xz,
      yz = b * yz,
    )


  /** the fractional power of the motion: pow(0.5) is the half motion, pow(2.0) applies it twice */
  def pow(t: Double): Pga3dRotor =
    log.exp(t)

  def toMultivector: Pga3dMultivector =
    Pga3dMultivector(
      s = s,
      w = 0.0,
      x = 0.0,
      y = 0.0,
      z = 0.0,
      wx = 0.0,
      wy = 0.0,
      wz = 0.0,
      xy = xy,
      xz = xz,
      yz = yz,
      wxy = 0.0,
      wxz = 0.0,
      wyz = 0.0,
      xyz = 0.0,
      i = 0.0,
    )

  def toMotor: Pga3dMotor =
    Pga3dMotor(
      s = s,
      wx = 0.0,
      wy = 0.0,
      wz = 0.0,
      xy = xy,
      xz = xz,
      yz = yz,
      i = 0.0,
    )

  def toBivectorUnsafe: Pga3dBivector =
    Pga3dBivector(
      wx = 0.0,
      wy = 0.0,
      wz = 0.0,
      xy = xy,
      xz = xz,
      yz = yz,
    )

  def toProjectiveTranslatorUnsafe: Pga3dProjectiveTranslator =
    Pga3dProjectiveTranslator(
      s = s,
      wx = 0.0,
      wy = 0.0,
      wz = 0.0,
    )

  def toBivectorBulkUnsafe: Pga3dBivectorBulk =
    Pga3dBivectorBulk(
      xy = xy,
      xz = xz,
      yz = yz,
    )

  def axisX: Pga3dVector =
    Pga3dVector(
      x = (s * s + yz * yz - xy * xy - xz * xz),
      y = 2.0 * (-s * xy - xz * yz),
      z = 2.0 * (xy * yz - s * xz),
    )

  def axisY: Pga3dVector =
    Pga3dVector(
      x = 2.0 * (s * xy - xz * yz),
      y = (s * s + xz * xz - xy * xy - yz * yz),
      z = 2.0 * (-s * yz - xy * xz),
    )

  def axisZ: Pga3dVector =
    Pga3dVector(
      x = 2.0 * (s * xz + xy * yz),
      y = 2.0 * (s * yz - xy * xz),
      z = (s * s + xy * xy - xz * xz - yz * yz),
    )

  def projectToRotationInPlane(plane: Pga3dPlaneCentral): Pga3dRotor =
    val q = this.normalizedByNorm
    val qPart = Pga3dRotor.rotation(q.sandwich(plane), plane)
    return qPart.geometric(q)

  def restoreRotationInPlane(plane: Pga3dPlaneCentral): Double =
    val q0 = this.projectToRotationInPlane(plane)
    val logDual = q0.log.dual
    return 2.0 * (logDual.wx * plane.x + logDual.wy * plane.y + logDual.wz * plane.z) / plane.norm

  def restoreRotationInPlaneX: Double =
    restoreRotationInPlane(Pga3dPlaneCentral(1, 0, 0))

  def restoreRotationInPlaneY: Double =
    restoreRotationInPlane(Pga3dPlaneCentral(0, 1, 0))

  def restoreRotationInPlaneZ: Double =
    restoreRotationInPlane(Pga3dPlaneCentral(0, 0, 1))

  /**
   * Spherical linear interpolation along the geodesic from this (t = 0) to b (t = 1),
   * with constant angular velocity. Computes this * (this.reverse.geometric(b))^t via log/exp.
   * Assumes both this and b are normalized; the result is normalized.
   * Near-antipodal inputs (b close to -this) are ill-conditioned: the geodesic is undefined
   * there and the interpolation direction becomes numerically unstable.
   */
  def slerp(b: Pga3dRotor, t: Double): Pga3dRotor =
    this.geometric(this.reverse.geometric(b).log.exp(t))

  /**
   * Normalized linear interpolation: the componentwise lerp this * (1 - t) + b * t, renormalized.
   * A fast APPROXIMATION of slerp: the angular velocity is not constant, so intermediate values
   * deviate from the true geodesic. The error is negligible for small angles between this and b
   * and grows toward the midpoint of large rotations. Assumes both inputs are normalized.
   */
  def nlerp(b: Pga3dRotor, t: Double): Pga3dRotor =
    (this * (1.0 - t) + b * t).normalizedByNorm

  infix def geometric(r: Pga3dMotor): Pga3dMotor =
    Pga3dMotor(
      s = (r.s * s - r.xy * xy - r.xz * xz - r.yz * yz),
      wx = (r.wx * s + r.wy * xy + r.wz * xz - r.i * yz),
      wy = (r.i * xz + r.wy * s + r.wz * yz - r.wx * xy),
      wz = (r.wz * s - r.i * xy - r.wx * xz - r.wy * yz),
      xy = (r.s * xy + r.xy * s + r.xz * yz - r.yz * xz),
      xz = (r.s * xz + r.xz * s + r.yz * xy - r.xy * yz),
      yz = (r.s * yz + r.xy * xz + r.yz * s - r.xz * xy),
      i = (r.i * s + r.wx * yz + r.wz * xy - r.wy * xz),
    )

  infix def geometric(r: Pga3dPlane): Pga3dMultivector =
    Pga3dMultivector(
      s = 0.0,
      w = r.w * s,
      x = (r.x * s + r.y * xy + r.z * xz),
      y = (r.y * s + r.z * yz - r.x * xy),
      z = (r.z * s - r.x * xz - r.y * yz),
      wx = 0.0,
      wy = 0.0,
      wz = 0.0,
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      wxy = r.w * xy,
      wxz = r.w * xz,
      wyz = r.w * yz,
      xyz = (r.x * yz + r.z * xy - r.y * xz),
      i = 0.0,
    )

  infix def geometric(r: Pga3dBivector): Pga3dMotor =
    Pga3dMotor(
      s = (-r.xy * xy - r.xz * xz - r.yz * yz),
      wx = (r.wx * s + r.wy * xy + r.wz * xz),
      wy = (r.wy * s + r.wz * yz - r.wx * xy),
      wz = (r.wz * s - r.wx * xz - r.wy * yz),
      xy = (r.xy * s + r.xz * yz - r.yz * xz),
      xz = (r.xz * s + r.yz * xy - r.xy * yz),
      yz = (r.xy * xz + r.yz * s - r.xz * xy),
      i = (r.wx * yz + r.wz * xy - r.wy * xz),
    )

  infix def geometric(r: Pga3dProjectivePoint): Pga3dMultivector =
    Pga3dMultivector(
      s = 0.0,
      w = (r.x * yz + r.z * xy - r.y * xz),
      x = -r.w * yz,
      y = r.w * xz,
      z = -r.w * xy,
      wx = 0.0,
      wy = 0.0,
      wz = 0.0,
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      wxy = (r.x * xz + r.y * yz - r.z * s),
      wxz = (r.y * s + r.z * yz - r.x * xy),
      wyz = (-r.x * s - r.y * xy - r.z * xz),
      xyz = r.w * s,
      i = 0.0,
    )

  infix def geometric(r: Pga3dRotor): Pga3dRotor =
    Pga3dRotor(
      s = (r.s * s - r.xy * xy - r.xz * xz - r.yz * yz),
      xy = (r.s * xy + r.xy * s + r.xz * yz - r.yz * xz),
      xz = (r.s * xz + r.xz * s + r.yz * xy - r.xy * yz),
      yz = (r.s * yz + r.xy * xz + r.yz * s - r.xz * xy),
    )

  infix def geometric(r: Pga3dProjectiveTranslator): Pga3dMotor =
    Pga3dMotor(
      s = r.s * s,
      wx = (r.wx * s + r.wy * xy + r.wz * xz),
      wy = (r.wy * s + r.wz * yz - r.wx * xy),
      wz = (r.wz * s - r.wx * xz - r.wy * yz),
      xy = r.s * xy,
      xz = r.s * xz,
      yz = r.s * yz,
      i = (r.wx * yz + r.wz * xy - r.wy * xz),
    )

  infix def geometric(r: Pga3dTranslator): Pga3dMotor =
    Pga3dMotor(
      s = s,
      wx = (r.wx * s + r.wy * xy + r.wz * xz),
      wy = (r.wy * s + r.wz * yz - r.wx * xy),
      wz = (r.wz * s - r.wx * xz - r.wy * yz),
      xy = xy,
      xz = xz,
      yz = yz,
      i = (r.wx * yz + r.wz * xy - r.wy * xz),
    )

  infix def geometric(r: Pga3dVector): Pga3dMultivector =
    Pga3dMultivector(
      s = 0.0,
      w = (r.x * yz + r.z * xy - r.y * xz),
      x = 0.0,
      y = 0.0,
      z = 0.0,
      wx = 0.0,
      wy = 0.0,
      wz = 0.0,
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      wxy = (r.x * xz + r.y * yz - r.z * s),
      wxz = (r.y * s + r.z * yz - r.x * xy),
      wyz = (-r.x * s - r.y * xy - r.z * xz),
      xyz = 0.0,
      i = 0.0,
    )

  infix def geometric(r: Pga3dPoint): Pga3dMultivector =
    Pga3dMultivector(
      s = 0.0,
      w = (r.x * yz + r.z * xy - r.y * xz),
      x = -yz,
      y = xz,
      z = -xy,
      wx = 0.0,
      wy = 0.0,
      wz = 0.0,
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      wxy = (r.x * xz + r.y * yz - r.z * s),
      wxz = (r.y * s + r.z * yz - r.x * xy),
      wyz = (-r.x * s - r.y * xy - r.z * xz),
      xyz = s,
      i = 0.0,
    )

  infix def geometric(r: Pga3dPlaneCentral): Pga3dMultivector =
    Pga3dMultivector(
      s = 0.0,
      w = 0.0,
      x = (r.x * s + r.y * xy + r.z * xz),
      y = (r.y * s + r.z * yz - r.x * xy),
      z = (r.z * s - r.x * xz - r.y * yz),
      wx = 0.0,
      wy = 0.0,
      wz = 0.0,
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      wxy = 0.0,
      wxz = 0.0,
      wyz = 0.0,
      xyz = (r.x * yz + r.z * xy - r.y * xz),
      i = 0.0,
    )

  infix def geometric(r: Pga3dBivectorBulk): Pga3dRotor =
    Pga3dRotor(
      s = (-r.xy * xy - r.xz * xz - r.yz * yz),
      xy = (r.xy * s + r.xz * yz - r.yz * xz),
      xz = (r.xz * s + r.yz * xy - r.xy * yz),
      yz = (r.xy * xz + r.yz * s - r.xz * xy),
    )

  infix def geometric(r: Pga3dBivectorWeight): Pga3dMotor =
    Pga3dMotor(
      s = 0.0,
      wx = (r.wx * s + r.wy * xy + r.wz * xz),
      wy = (r.wy * s + r.wz * yz - r.wx * xy),
      wz = (r.wz * s - r.wx * xz - r.wy * yz),
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      i = (r.wx * yz + r.wz * xy - r.wy * xz),
    )

  infix def geometric(r: Pga3dPseudoScalar): Pga3dMotor =
    Pga3dMotor(
      s = 0.0,
      wx = -r.i * yz,
      wy = r.i * xz,
      wz = -r.i * xy,
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      i = r.i * s,
    )

  infix def geometric(r: Pga3dPointCenter.type): Pga3dMultivector =
    Pga3dMultivector(
      s = 0.0,
      w = 0.0,
      x = -yz,
      y = xz,
      z = -xy,
      wx = 0.0,
      wy = 0.0,
      wz = 0.0,
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      wxy = 0.0,
      wxz = 0.0,
      wyz = 0.0,
      xyz = s,
      i = 0.0,
    )

  infix def dot(r: Pga3dMotor): Pga3dMotor =
    Pga3dMotor(
      s = (r.s * s - r.xy * xy - r.xz * xz - r.yz * yz),
      wx = (r.wx * s - r.i * yz),
      wy = (r.i * xz + r.wy * s),
      wz = (r.wz * s - r.i * xy),
      xy = (r.s * xy + r.xy * s),
      xz = (r.s * xz + r.xz * s),
      yz = (r.s * yz + r.yz * s),
      i = r.i * s,
    )

  infix def dot(r: Pga3dPlane): Pga3dPlane =
    Pga3dPlane(
      x = (r.x * s + r.y * xy + r.z * xz),
      y = (r.y * s + r.z * yz - r.x * xy),
      z = (r.z * s - r.x * xz - r.y * yz),
      w = r.w * s,
    )

  infix def dot(r: Pga3dBivector): Pga3dMotor =
    Pga3dMotor(
      s = (-r.xy * xy - r.xz * xz - r.yz * yz),
      wx = r.wx * s,
      wy = r.wy * s,
      wz = r.wz * s,
      xy = r.xy * s,
      xz = r.xz * s,
      yz = r.yz * s,
      i = 0.0,
    )

  infix def dot(r: Pga3dProjectivePoint): Pga3dMultivector =
    Pga3dMultivector(
      s = 0.0,
      w = (r.x * yz + r.z * xy - r.y * xz),
      x = -r.w * yz,
      y = r.w * xz,
      z = -r.w * xy,
      wx = 0.0,
      wy = 0.0,
      wz = 0.0,
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      wxy = -r.z * s,
      wxz = r.y * s,
      wyz = -r.x * s,
      xyz = r.w * s,
      i = 0.0,
    )

  infix def dot(r: Pga3dRotor): Pga3dRotor =
    Pga3dRotor(
      s = (r.s * s - r.xy * xy - r.xz * xz - r.yz * yz),
      xy = (r.s * xy + r.xy * s),
      xz = (r.s * xz + r.xz * s),
      yz = (r.s * yz + r.yz * s),
    )

  infix def dot(r: Pga3dProjectiveTranslator): Pga3dMotor =
    Pga3dMotor(
      s = r.s * s,
      wx = r.wx * s,
      wy = r.wy * s,
      wz = r.wz * s,
      xy = r.s * xy,
      xz = r.s * xz,
      yz = r.s * yz,
      i = 0.0,
    )

  infix def dot(r: Pga3dTranslator): Pga3dMotor =
    Pga3dMotor(
      s = s,
      wx = r.wx * s,
      wy = r.wy * s,
      wz = r.wz * s,
      xy = xy,
      xz = xz,
      yz = yz,
      i = 0.0,
    )

  infix def dot(r: Pga3dVector): Pga3dMultivector =
    Pga3dMultivector(
      s = 0.0,
      w = (r.x * yz + r.z * xy - r.y * xz),
      x = 0.0,
      y = 0.0,
      z = 0.0,
      wx = 0.0,
      wy = 0.0,
      wz = 0.0,
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      wxy = -r.z * s,
      wxz = r.y * s,
      wyz = -r.x * s,
      xyz = 0.0,
      i = 0.0,
    )

  infix def dot(r: Pga3dPoint): Pga3dMultivector =
    Pga3dMultivector(
      s = 0.0,
      w = (r.x * yz + r.z * xy - r.y * xz),
      x = -yz,
      y = xz,
      z = -xy,
      wx = 0.0,
      wy = 0.0,
      wz = 0.0,
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      wxy = -r.z * s,
      wxz = r.y * s,
      wyz = -r.x * s,
      xyz = s,
      i = 0.0,
    )

  infix def dot(r: Pga3dPlaneCentral): Pga3dPlaneCentral =
    Pga3dPlaneCentral(
      x = (r.x * s + r.y * xy + r.z * xz),
      y = (r.y * s + r.z * yz - r.x * xy),
      z = (r.z * s - r.x * xz - r.y * yz),
    )

  infix def dot(r: Pga3dBivectorBulk): Pga3dRotor =
    Pga3dRotor(
      s = (-r.xy * xy - r.xz * xz - r.yz * yz),
      xy = r.xy * s,
      xz = r.xz * s,
      yz = r.yz * s,
    )

  infix def dot(r: Pga3dBivectorWeight): Pga3dBivectorWeight =
    Pga3dBivectorWeight(
      wx = r.wx * s,
      wy = r.wy * s,
      wz = r.wz * s,
    )

  infix def dot(r: Pga3dPseudoScalar): Pga3dMotor =
    Pga3dMotor(
      s = 0.0,
      wx = -r.i * yz,
      wy = r.i * xz,
      wz = -r.i * xy,
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      i = r.i * s,
    )

  infix def dot(r: Pga3dPointCenter.type): Pga3dMultivector =
    Pga3dMultivector(
      s = 0.0,
      w = 0.0,
      x = -yz,
      y = xz,
      z = -xy,
      wx = 0.0,
      wy = 0.0,
      wz = 0.0,
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      wxy = 0.0,
      wxz = 0.0,
      wyz = 0.0,
      xyz = s,
      i = 0.0,
    )

  infix def wedge(r: Pga3dMotor): Pga3dMotor =
    Pga3dMotor(
      s = r.s * s,
      wx = r.wx * s,
      wy = r.wy * s,
      wz = r.wz * s,
      xy = (r.s * xy + r.xy * s),
      xz = (r.s * xz + r.xz * s),
      yz = (r.s * yz + r.yz * s),
      i = (r.i * s + r.wx * yz + r.wz * xy - r.wy * xz),
    )

  inline infix def ^(r: Pga3dMotor): Pga3dMotor = wedge(r)

  inline infix def meet(r: Pga3dMotor): Pga3dMotor = wedge(r)

  infix def wedge(r: Pga3dPlane): Pga3dMultivector =
    Pga3dMultivector(
      s = 0.0,
      w = r.w * s,
      x = r.x * s,
      y = r.y * s,
      z = r.z * s,
      wx = 0.0,
      wy = 0.0,
      wz = 0.0,
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      wxy = r.w * xy,
      wxz = r.w * xz,
      wyz = r.w * yz,
      xyz = (r.x * yz + r.z * xy - r.y * xz),
      i = 0.0,
    )

  inline infix def ^(r: Pga3dPlane): Pga3dMultivector = wedge(r)

  inline infix def meet(r: Pga3dPlane): Pga3dMultivector = wedge(r)

  infix def wedge(r: Pga3dBivector): Pga3dMotor =
    Pga3dMotor(
      s = 0.0,
      wx = r.wx * s,
      wy = r.wy * s,
      wz = r.wz * s,
      xy = r.xy * s,
      xz = r.xz * s,
      yz = r.yz * s,
      i = (r.wx * yz + r.wz * xy - r.wy * xz),
    )

  inline infix def ^(r: Pga3dBivector): Pga3dMotor = wedge(r)

  inline infix def meet(r: Pga3dBivector): Pga3dMotor = wedge(r)

  infix def wedge(r: Pga3dProjectivePoint): Pga3dProjectivePoint =
    Pga3dProjectivePoint(
      x = r.x * s,
      y = r.y * s,
      z = r.z * s,
      w = r.w * s,
    )

  inline infix def ^(r: Pga3dProjectivePoint): Pga3dProjectivePoint = wedge(r)

  inline infix def meet(r: Pga3dProjectivePoint): Pga3dProjectivePoint = wedge(r)

  infix def wedge(r: Pga3dRotor): Pga3dRotor =
    Pga3dRotor(
      s = r.s * s,
      xy = (r.s * xy + r.xy * s),
      xz = (r.s * xz + r.xz * s),
      yz = (r.s * yz + r.yz * s),
    )

  inline infix def ^(r: Pga3dRotor): Pga3dRotor = wedge(r)

  inline infix def meet(r: Pga3dRotor): Pga3dRotor = wedge(r)

  infix def wedge(r: Pga3dProjectiveTranslator): Pga3dMotor =
    Pga3dMotor(
      s = r.s * s,
      wx = r.wx * s,
      wy = r.wy * s,
      wz = r.wz * s,
      xy = r.s * xy,
      xz = r.s * xz,
      yz = r.s * yz,
      i = (r.wx * yz + r.wz * xy - r.wy * xz),
    )

  inline infix def ^(r: Pga3dProjectiveTranslator): Pga3dMotor = wedge(r)

  inline infix def meet(r: Pga3dProjectiveTranslator): Pga3dMotor = wedge(r)

  infix def wedge(r: Pga3dTranslator): Pga3dMotor =
    Pga3dMotor(
      s = s,
      wx = r.wx * s,
      wy = r.wy * s,
      wz = r.wz * s,
      xy = xy,
      xz = xz,
      yz = yz,
      i = (r.wx * yz + r.wz * xy - r.wy * xz),
    )

  inline infix def ^(r: Pga3dTranslator): Pga3dMotor = wedge(r)

  inline infix def meet(r: Pga3dTranslator): Pga3dMotor = wedge(r)

  infix def wedge(r: Pga3dVector): Pga3dVector =
    Pga3dVector(
      x = r.x * s,
      y = r.y * s,
      z = r.z * s,
    )

  inline infix def ^(r: Pga3dVector): Pga3dVector = wedge(r)

  inline infix def meet(r: Pga3dVector): Pga3dVector = wedge(r)

  infix def wedge(r: Pga3dPoint): Pga3dProjectivePoint =
    Pga3dProjectivePoint(
      x = r.x * s,
      y = r.y * s,
      z = r.z * s,
      w = s,
    )

  inline infix def ^(r: Pga3dPoint): Pga3dProjectivePoint = wedge(r)

  inline infix def meet(r: Pga3dPoint): Pga3dProjectivePoint = wedge(r)

  infix def wedge(r: Pga3dPlaneCentral): Pga3dMultivector =
    Pga3dMultivector(
      s = 0.0,
      w = 0.0,
      x = r.x * s,
      y = r.y * s,
      z = r.z * s,
      wx = 0.0,
      wy = 0.0,
      wz = 0.0,
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      wxy = 0.0,
      wxz = 0.0,
      wyz = 0.0,
      xyz = (r.x * yz + r.z * xy - r.y * xz),
      i = 0.0,
    )

  inline infix def ^(r: Pga3dPlaneCentral): Pga3dMultivector = wedge(r)

  inline infix def meet(r: Pga3dPlaneCentral): Pga3dMultivector = wedge(r)

  infix def wedge(r: Pga3dBivectorBulk): Pga3dBivectorBulk =
    Pga3dBivectorBulk(
      xy = r.xy * s,
      xz = r.xz * s,
      yz = r.yz * s,
    )

  inline infix def ^(r: Pga3dBivectorBulk): Pga3dBivectorBulk = wedge(r)

  inline infix def meet(r: Pga3dBivectorBulk): Pga3dBivectorBulk = wedge(r)

  infix def wedge(r: Pga3dBivectorWeight): Pga3dMotor =
    Pga3dMotor(
      s = 0.0,
      wx = r.wx * s,
      wy = r.wy * s,
      wz = r.wz * s,
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      i = (r.wx * yz + r.wz * xy - r.wy * xz),
    )

  inline infix def ^(r: Pga3dBivectorWeight): Pga3dMotor = wedge(r)

  inline infix def meet(r: Pga3dBivectorWeight): Pga3dMotor = wedge(r)

  infix def wedge(r: Pga3dPseudoScalar): Pga3dPseudoScalar =
    Pga3dPseudoScalar(
      i = r.i * s,
    )

  inline infix def ^(r: Pga3dPseudoScalar): Pga3dPseudoScalar = wedge(r)

  inline infix def meet(r: Pga3dPseudoScalar): Pga3dPseudoScalar = wedge(r)

  infix def wedge(r: Pga3dPointCenter.type): Pga3dProjectivePoint =
    Pga3dProjectivePoint(
      x = 0.0,
      y = 0.0,
      z = 0.0,
      w = s,
    )

  inline infix def ^(r: Pga3dPointCenter.type): Pga3dProjectivePoint = wedge(r)

  inline infix def meet(r: Pga3dPointCenter.type): Pga3dProjectivePoint = wedge(r)

  infix def antiGeometric(r: Pga3dMotor): Pga3dRotor =
    Pga3dRotor(
      s = (r.i * s + r.wx * yz + r.wz * xy - r.wy * xz),
      xy = (r.i * xy - r.wx * xz - r.wy * yz - r.wz * s),
      xz = (r.i * xz + r.wx * xy + r.wy * s - r.wz * yz),
      yz = (r.i * yz + r.wy * xy + r.wz * xz - r.wx * s),
    )

  infix def antiGeometric(r: Pga3dPlane): Pga3dMultivector =
    Pga3dMultivector(
      s = 0.0,
      w = 0.0,
      x = -r.w * yz,
      y = r.w * xz,
      z = -r.w * xy,
      wx = 0.0,
      wy = 0.0,
      wz = 0.0,
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      wxy = 0.0,
      wxz = 0.0,
      wyz = 0.0,
      xyz = -r.w * s,
      i = 0.0,
    )

  infix def antiGeometric(r: Pga3dBivector): Pga3dRotor =
    Pga3dRotor(
      s = (r.wx * yz + r.wz * xy - r.wy * xz),
      xy = (-r.wx * xz - r.wy * yz - r.wz * s),
      xz = (r.wx * xy + r.wy * s - r.wz * yz),
      yz = (r.wy * xy + r.wz * xz - r.wx * s),
    )

  infix def antiGeometric(r: Pga3dProjectivePoint): Pga3dMultivector =
    Pga3dMultivector(
      s = 0.0,
      w = 0.0,
      x = (r.y * xy + r.z * xz - r.x * s),
      y = (r.z * yz - r.x * xy - r.y * s),
      z = (-r.x * xz - r.y * yz - r.z * s),
      wx = 0.0,
      wy = 0.0,
      wz = 0.0,
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      wxy = 0.0,
      wxz = 0.0,
      wyz = 0.0,
      xyz = (r.x * yz + r.z * xy - r.y * xz),
      i = 0.0,
    )

  infix def antiGeometric(r: Pga3dProjectiveTranslator): Pga3dRotor =
    Pga3dRotor(
      s = (r.wx * yz + r.wz * xy - r.wy * xz),
      xy = (-r.wx * xz - r.wy * yz - r.wz * s),
      xz = (r.wx * xy + r.wy * s - r.wz * yz),
      yz = (r.wy * xy + r.wz * xz - r.wx * s),
    )

  infix def antiGeometric(r: Pga3dTranslator): Pga3dRotor =
    Pga3dRotor(
      s = (r.wx * yz + r.wz * xy - r.wy * xz),
      xy = (-r.wx * xz - r.wy * yz - r.wz * s),
      xz = (r.wx * xy + r.wy * s - r.wz * yz),
      yz = (r.wy * xy + r.wz * xz - r.wx * s),
    )

  infix def antiGeometric(r: Pga3dVector): Pga3dMultivector =
    Pga3dMultivector(
      s = 0.0,
      w = 0.0,
      x = (r.y * xy + r.z * xz - r.x * s),
      y = (r.z * yz - r.x * xy - r.y * s),
      z = (-r.x * xz - r.y * yz - r.z * s),
      wx = 0.0,
      wy = 0.0,
      wz = 0.0,
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      wxy = 0.0,
      wxz = 0.0,
      wyz = 0.0,
      xyz = (r.x * yz + r.z * xy - r.y * xz),
      i = 0.0,
    )

  infix def antiGeometric(r: Pga3dPoint): Pga3dMultivector =
    Pga3dMultivector(
      s = 0.0,
      w = 0.0,
      x = (r.y * xy + r.z * xz - r.x * s),
      y = (r.z * yz - r.x * xy - r.y * s),
      z = (-r.x * xz - r.y * yz - r.z * s),
      wx = 0.0,
      wy = 0.0,
      wz = 0.0,
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      wxy = 0.0,
      wxz = 0.0,
      wyz = 0.0,
      xyz = (r.x * yz + r.z * xy - r.y * xz),
      i = 0.0,
    )

  infix def antiGeometric(r: Pga3dBivectorWeight): Pga3dRotor =
    Pga3dRotor(
      s = (r.wx * yz + r.wz * xy - r.wy * xz),
      xy = (-r.wx * xz - r.wy * yz - r.wz * s),
      xz = (r.wx * xy + r.wy * s - r.wz * yz),
      yz = (r.wy * xy + r.wz * xz - r.wx * s),
    )

  infix def antiGeometric(r: Pga3dPseudoScalar): Pga3dRotor =
    Pga3dRotor(
      s = r.i * s,
      xy = r.i * xy,
      xz = r.i * xz,
      yz = r.i * yz,
    )

  infix def antiDot(r: Pga3dMotor): Pga3dRotor =
    Pga3dRotor(
      s = r.i * s,
      xy = (r.i * xy - r.wz * s),
      xz = (r.i * xz + r.wy * s),
      yz = (r.i * yz - r.wx * s),
    )

  infix def antiDot(r: Pga3dPlane): Pga3dProjectivePoint =
    Pga3dProjectivePoint(
      x = 0.0,
      y = 0.0,
      z = 0.0,
      w = -r.w * s,
    )

  infix def antiDot(r: Pga3dBivector): Pga3dBivectorBulk =
    Pga3dBivectorBulk(
      xy = -r.wz * s,
      xz = r.wy * s,
      yz = -r.wx * s,
    )

  infix def antiDot(r: Pga3dProjectivePoint): Pga3dMultivector =
    Pga3dMultivector(
      s = 0.0,
      w = 0.0,
      x = -r.x * s,
      y = -r.y * s,
      z = -r.z * s,
      wx = 0.0,
      wy = 0.0,
      wz = 0.0,
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      wxy = 0.0,
      wxz = 0.0,
      wyz = 0.0,
      xyz = (r.x * yz + r.z * xy - r.y * xz),
      i = 0.0,
    )

  infix def antiDot(r: Pga3dProjectiveTranslator): Pga3dBivectorBulk =
    Pga3dBivectorBulk(
      xy = -r.wz * s,
      xz = r.wy * s,
      yz = -r.wx * s,
    )

  infix def antiDot(r: Pga3dTranslator): Pga3dBivectorBulk =
    Pga3dBivectorBulk(
      xy = -r.wz * s,
      xz = r.wy * s,
      yz = -r.wx * s,
    )

  infix def antiDot(r: Pga3dVector): Pga3dMultivector =
    Pga3dMultivector(
      s = 0.0,
      w = 0.0,
      x = -r.x * s,
      y = -r.y * s,
      z = -r.z * s,
      wx = 0.0,
      wy = 0.0,
      wz = 0.0,
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      wxy = 0.0,
      wxz = 0.0,
      wyz = 0.0,
      xyz = (r.x * yz + r.z * xy - r.y * xz),
      i = 0.0,
    )

  infix def antiDot(r: Pga3dPoint): Pga3dMultivector =
    Pga3dMultivector(
      s = 0.0,
      w = 0.0,
      x = -r.x * s,
      y = -r.y * s,
      z = -r.z * s,
      wx = 0.0,
      wy = 0.0,
      wz = 0.0,
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      wxy = 0.0,
      wxz = 0.0,
      wyz = 0.0,
      xyz = (r.x * yz + r.z * xy - r.y * xz),
      i = 0.0,
    )

  infix def antiDot(r: Pga3dBivectorWeight): Pga3dBivectorBulk =
    Pga3dBivectorBulk(
      xy = -r.wz * s,
      xz = r.wy * s,
      yz = -r.wx * s,
    )

  infix def antiDot(r: Pga3dPseudoScalar): Pga3dRotor =
    Pga3dRotor(
      s = r.i * s,
      xy = r.i * xy,
      xz = r.i * xz,
      yz = r.i * yz,
    )

  infix def antiWedge(r: Pga3dMotor): Pga3dRotor =
    Pga3dRotor(
      s = (r.i * s + r.wx * yz + r.wz * xy - r.wy * xz),
      xy = r.i * xy,
      xz = r.i * xz,
      yz = r.i * yz,
    )

  inline infix def v(r: Pga3dMotor): Pga3dRotor = antiWedge(r)

  inline infix def join(r: Pga3dMotor): Pga3dRotor = antiWedge(r)

  infix def antiWedge(r: Pga3dBivector): Double =
    (r.wx * yz + r.wz * xy - r.wy * xz)

  inline infix def v(r: Pga3dBivector): Double = antiWedge(r)

  inline infix def join(r: Pga3dBivector): Double = antiWedge(r)

  infix def antiWedge(r: Pga3dProjectivePoint): Pga3dPlaneCentral =
    Pga3dPlaneCentral(
      x = (r.y * xy + r.z * xz),
      y = (r.z * yz - r.x * xy),
      z = (-r.x * xz - r.y * yz),
    )

  inline infix def v(r: Pga3dProjectivePoint): Pga3dPlaneCentral = antiWedge(r)

  inline infix def join(r: Pga3dProjectivePoint): Pga3dPlaneCentral = antiWedge(r)

  infix def antiWedge(r: Pga3dProjectiveTranslator): Double =
    (r.wx * yz + r.wz * xy - r.wy * xz)

  inline infix def v(r: Pga3dProjectiveTranslator): Double = antiWedge(r)

  inline infix def join(r: Pga3dProjectiveTranslator): Double = antiWedge(r)

  infix def antiWedge(r: Pga3dTranslator): Double =
    (r.wx * yz + r.wz * xy - r.wy * xz)

  inline infix def v(r: Pga3dTranslator): Double = antiWedge(r)

  inline infix def join(r: Pga3dTranslator): Double = antiWedge(r)

  infix def antiWedge(r: Pga3dVector): Pga3dPlaneCentral =
    Pga3dPlaneCentral(
      x = (r.y * xy + r.z * xz),
      y = (r.z * yz - r.x * xy),
      z = (-r.x * xz - r.y * yz),
    )

  inline infix def v(r: Pga3dVector): Pga3dPlaneCentral = antiWedge(r)

  inline infix def join(r: Pga3dVector): Pga3dPlaneCentral = antiWedge(r)

  infix def antiWedge(r: Pga3dPoint): Pga3dPlaneCentral =
    Pga3dPlaneCentral(
      x = (r.y * xy + r.z * xz),
      y = (r.z * yz - r.x * xy),
      z = (-r.x * xz - r.y * yz),
    )

  inline infix def v(r: Pga3dPoint): Pga3dPlaneCentral = antiWedge(r)

  inline infix def join(r: Pga3dPoint): Pga3dPlaneCentral = antiWedge(r)

  infix def antiWedge(r: Pga3dBivectorWeight): Double =
    (r.wx * yz + r.wz * xy - r.wy * xz)

  inline infix def v(r: Pga3dBivectorWeight): Double = antiWedge(r)

  inline infix def join(r: Pga3dBivectorWeight): Double = antiWedge(r)

  infix def antiWedge(r: Pga3dPseudoScalar): Pga3dRotor =
    Pga3dRotor(
      s = r.i * s,
      xy = r.i * xy,
      xz = r.i * xz,
      yz = r.i * yz,
    )

  inline infix def v(r: Pga3dPseudoScalar): Pga3dRotor = antiWedge(r)

  inline infix def join(r: Pga3dPseudoScalar): Pga3dRotor = antiWedge(r)

  infix def sandwich(r: Pga3dMotor): Pga3dMotor =
    val sMs = s * s
    val sMxy = s * xy
    val sMxz = s * xz
    val sMyz = s * yz
    val xyMxy = xy * xy
    val xyMxz = xy * xz
    val xyMyz = xy * yz
    val xzMxz = xz * xz
    val xzMyz = xz * yz
    val yzMyz = yz * yz
    Pga3dMotor(
      s = r.s * (sMs + xyMxy + xzMxz + yzMyz),
      wx = (2.0 * (r.wy * (sMxy - xzMyz) + r.wz * (sMxz + xyMyz)) + r.wx * (sMs + yzMyz - xyMxy - xzMxz)),
      wy = (2.0 * (r.wx * (-sMxy - xzMyz) + r.wz * (sMyz - xyMxz)) + r.wy * (sMs + xzMxz - xyMxy - yzMyz)),
      wz = (2.0 * (r.wx * (xyMyz - sMxz) + r.wy * (-sMyz - xyMxz)) + r.wz * (sMs + xyMxy - xzMxz - yzMyz)),
      xy = (2.0 * (r.xz * (sMyz + xyMxz) + r.yz * (xyMyz - sMxz)) + r.xy * (sMs + xyMxy - xzMxz - yzMyz)),
      xz = (2.0 * (r.xy * (xyMxz - sMyz) + r.yz * (sMxy + xzMyz)) + r.xz * (sMs + xzMxz - xyMxy - yzMyz)),
      yz = (2.0 * (r.xy * (sMxz + xyMyz) + r.xz * (xzMyz - sMxy)) + r.yz * (sMs + yzMyz - xyMxy - xzMxz)),
      i = r.i * (sMs + xyMxy + xzMxz + yzMyz),
    )

  infix def sandwich(r: Pga3dPlane): Pga3dPlane =
    val sMs = s * s
    val sMxy = s * xy
    val sMxz = s * xz
    val sMyz = s * yz
    val xyMxy = xy * xy
    val xyMxz = xy * xz
    val xyMyz = xy * yz
    val xzMxz = xz * xz
    val xzMyz = xz * yz
    val yzMyz = yz * yz
    Pga3dPlane(
      x = (2.0 * (r.y * (sMxy - xzMyz) + r.z * (sMxz + xyMyz)) + r.x * (sMs + yzMyz - xyMxy - xzMxz)),
      y = (2.0 * (r.x * (-sMxy - xzMyz) + r.z * (sMyz - xyMxz)) + r.y * (sMs + xzMxz - xyMxy - yzMyz)),
      z = (2.0 * (r.x * (xyMyz - sMxz) + r.y * (-sMyz - xyMxz)) + r.z * (sMs + xyMxy - xzMxz - yzMyz)),
      w = r.w * (sMs + xyMxy + xzMxz + yzMyz),
    )

  infix def sandwich(r: Pga3dBivector): Pga3dBivector =
    val sMs = s * s
    val sMxy = s * xy
    val sMxz = s * xz
    val sMyz = s * yz
    val xyMxy = xy * xy
    val xyMxz = xy * xz
    val xyMyz = xy * yz
    val xzMxz = xz * xz
    val xzMyz = xz * yz
    val yzMyz = yz * yz
    Pga3dBivector(
      wx = (2.0 * (r.wy * (sMxy - xzMyz) + r.wz * (sMxz + xyMyz)) + r.wx * (sMs + yzMyz - xyMxy - xzMxz)),
      wy = (2.0 * (r.wx * (-sMxy - xzMyz) + r.wz * (sMyz - xyMxz)) + r.wy * (sMs + xzMxz - xyMxy - yzMyz)),
      wz = (2.0 * (r.wx * (xyMyz - sMxz) + r.wy * (-sMyz - xyMxz)) + r.wz * (sMs + xyMxy - xzMxz - yzMyz)),
      xy = (2.0 * (r.xz * (sMyz + xyMxz) + r.yz * (xyMyz - sMxz)) + r.xy * (sMs + xyMxy - xzMxz - yzMyz)),
      xz = (2.0 * (r.xy * (xyMxz - sMyz) + r.yz * (sMxy + xzMyz)) + r.xz * (sMs + xzMxz - xyMxy - yzMyz)),
      yz = (2.0 * (r.xy * (sMxz + xyMyz) + r.xz * (xzMyz - sMxy)) + r.yz * (sMs + yzMyz - xyMxy - xzMxz)),
    )

  infix def sandwich(r: Pga3dProjectivePoint): Pga3dProjectivePoint =
    val sMs = s * s
    val sMxy = s * xy
    val sMxz = s * xz
    val sMyz = s * yz
    val xyMxy = xy * xy
    val xyMxz = xy * xz
    val xyMyz = xy * yz
    val xzMxz = xz * xz
    val xzMyz = xz * yz
    val yzMyz = yz * yz
    Pga3dProjectivePoint(
      x = (2.0 * (r.y * (sMxy - xzMyz) + r.z * (sMxz + xyMyz)) + r.x * (sMs + yzMyz - xyMxy - xzMxz)),
      y = (2.0 * (r.x * (-sMxy - xzMyz) + r.z * (sMyz - xyMxz)) + r.y * (sMs + xzMxz - xyMxy - yzMyz)),
      z = (2.0 * (r.x * (xyMyz - sMxz) + r.y * (-sMyz - xyMxz)) + r.z * (sMs + xyMxy - xzMxz - yzMyz)),
      w = r.w * (sMs + xyMxy + xzMxz + yzMyz),
    )

  infix def sandwich(r: Pga3dRotor): Pga3dRotor =
    val sMs = s * s
    val sMxy = s * xy
    val sMxz = s * xz
    val sMyz = s * yz
    val xyMxy = xy * xy
    val xyMxz = xy * xz
    val xyMyz = xy * yz
    val xzMxz = xz * xz
    val xzMyz = xz * yz
    val yzMyz = yz * yz
    Pga3dRotor(
      s = r.s * (sMs + xyMxy + xzMxz + yzMyz),
      xy = (2.0 * (r.xz * (sMyz + xyMxz) + r.yz * (xyMyz - sMxz)) + r.xy * (sMs + xyMxy - xzMxz - yzMyz)),
      xz = (2.0 * (r.xy * (xyMxz - sMyz) + r.yz * (sMxy + xzMyz)) + r.xz * (sMs + xzMxz - xyMxy - yzMyz)),
      yz = (2.0 * (r.xy * (sMxz + xyMyz) + r.xz * (xzMyz - sMxy)) + r.yz * (sMs + yzMyz - xyMxy - xzMxz)),
    )

  infix def sandwich(r: Pga3dProjectiveTranslator): Pga3dProjectiveTranslator =
    val sMs = s * s
    val sMxy = s * xy
    val sMxz = s * xz
    val sMyz = s * yz
    val xyMxy = xy * xy
    val xyMxz = xy * xz
    val xyMyz = xy * yz
    val xzMxz = xz * xz
    val xzMyz = xz * yz
    val yzMyz = yz * yz
    Pga3dProjectiveTranslator(
      s = r.s * (sMs + xyMxy + xzMxz + yzMyz),
      wx = (2.0 * (r.wy * (sMxy - xzMyz) + r.wz * (sMxz + xyMyz)) + r.wx * (sMs + yzMyz - xyMxy - xzMxz)),
      wy = (2.0 * (r.wx * (-sMxy - xzMyz) + r.wz * (sMyz - xyMxz)) + r.wy * (sMs + xzMxz - xyMxy - yzMyz)),
      wz = (2.0 * (r.wx * (xyMyz - sMxz) + r.wy * (-sMyz - xyMxz)) + r.wz * (sMs + xyMxy - xzMxz - yzMyz)),
    )

  infix def sandwich(r: Pga3dTranslator): Pga3dProjectiveTranslator =
    val sMs = s * s
    val sMxy = s * xy
    val sMxz = s * xz
    val sMyz = s * yz
    val xyMxy = xy * xy
    val xyMxz = xy * xz
    val xyMyz = xy * yz
    val xzMxz = xz * xz
    val xzMyz = xz * yz
    val yzMyz = yz * yz
    Pga3dProjectiveTranslator(
      s = (sMs + xyMxy + xzMxz + yzMyz),
      wx = (2.0 * (r.wy * (sMxy - xzMyz) + r.wz * (sMxz + xyMyz)) + r.wx * (sMs + yzMyz - xyMxy - xzMxz)),
      wy = (2.0 * (r.wx * (-sMxy - xzMyz) + r.wz * (sMyz - xyMxz)) + r.wy * (sMs + xzMxz - xyMxy - yzMyz)),
      wz = (2.0 * (r.wx * (xyMyz - sMxz) + r.wy * (-sMyz - xyMxz)) + r.wz * (sMs + xyMxy - xzMxz - yzMyz)),
    )

  infix def sandwich(r: Pga3dVector): Pga3dVector =
    val sMs = s * s
    val sMxy = s * xy
    val sMxz = s * xz
    val sMyz = s * yz
    val xyMxy = xy * xy
    val xyMxz = xy * xz
    val xyMyz = xy * yz
    val xzMxz = xz * xz
    val xzMyz = xz * yz
    val yzMyz = yz * yz
    Pga3dVector(
      x = (2.0 * (r.y * (sMxy - xzMyz) + r.z * (sMxz + xyMyz)) + r.x * (sMs + yzMyz - xyMxy - xzMxz)),
      y = (2.0 * (r.x * (-sMxy - xzMyz) + r.z * (sMyz - xyMxz)) + r.y * (sMs + xzMxz - xyMxy - yzMyz)),
      z = (2.0 * (r.x * (xyMyz - sMxz) + r.y * (-sMyz - xyMxz)) + r.z * (sMs + xyMxy - xzMxz - yzMyz)),
    )

  infix def sandwich(r: Pga3dPoint): Pga3dProjectivePoint =
    val sMs = s * s
    val sMxy = s * xy
    val sMxz = s * xz
    val sMyz = s * yz
    val xyMxy = xy * xy
    val xyMxz = xy * xz
    val xyMyz = xy * yz
    val xzMxz = xz * xz
    val xzMyz = xz * yz
    val yzMyz = yz * yz
    Pga3dProjectivePoint(
      x = (2.0 * (r.y * (sMxy - xzMyz) + r.z * (sMxz + xyMyz)) + r.x * (sMs + yzMyz - xyMxy - xzMxz)),
      y = (2.0 * (r.x * (-sMxy - xzMyz) + r.z * (sMyz - xyMxz)) + r.y * (sMs + xzMxz - xyMxy - yzMyz)),
      z = (2.0 * (r.x * (xyMyz - sMxz) + r.y * (-sMyz - xyMxz)) + r.z * (sMs + xyMxy - xzMxz - yzMyz)),
      w = (sMs + xyMxy + xzMxz + yzMyz),
    )

  infix def sandwich(r: Pga3dPlaneCentral): Pga3dPlaneCentral =
    val sMs = s * s
    val sMxy = s * xy
    val sMxz = s * xz
    val sMyz = s * yz
    val xyMxy = xy * xy
    val xyMxz = xy * xz
    val xyMyz = xy * yz
    val xzMxz = xz * xz
    val xzMyz = xz * yz
    val yzMyz = yz * yz
    Pga3dPlaneCentral(
      x = (2.0 * (r.y * (sMxy - xzMyz) + r.z * (sMxz + xyMyz)) + r.x * (sMs + yzMyz - xyMxy - xzMxz)),
      y = (2.0 * (r.x * (-sMxy - xzMyz) + r.z * (sMyz - xyMxz)) + r.y * (sMs + xzMxz - xyMxy - yzMyz)),
      z = (2.0 * (r.x * (xyMyz - sMxz) + r.y * (-sMyz - xyMxz)) + r.z * (sMs + xyMxy - xzMxz - yzMyz)),
    )

  infix def sandwich(r: Pga3dBivectorBulk): Pga3dBivectorBulk =
    val sMs = s * s
    val sMxy = s * xy
    val sMxz = s * xz
    val sMyz = s * yz
    val xyMxy = xy * xy
    val xyMxz = xy * xz
    val xyMyz = xy * yz
    val xzMxz = xz * xz
    val xzMyz = xz * yz
    val yzMyz = yz * yz
    Pga3dBivectorBulk(
      xy = (2.0 * (r.xz * (sMyz + xyMxz) + r.yz * (xyMyz - sMxz)) + r.xy * (sMs + xyMxy - xzMxz - yzMyz)),
      xz = (2.0 * (r.xy * (xyMxz - sMyz) + r.yz * (sMxy + xzMyz)) + r.xz * (sMs + xzMxz - xyMxy - yzMyz)),
      yz = (2.0 * (r.xy * (sMxz + xyMyz) + r.xz * (xzMyz - sMxy)) + r.yz * (sMs + yzMyz - xyMxy - xzMxz)),
    )

  infix def sandwich(r: Pga3dBivectorWeight): Pga3dBivectorWeight =
    val sMs = s * s
    val sMxy = s * xy
    val sMxz = s * xz
    val sMyz = s * yz
    val xyMxy = xy * xy
    val xyMxz = xy * xz
    val xyMyz = xy * yz
    val xzMxz = xz * xz
    val xzMyz = xz * yz
    val yzMyz = yz * yz
    Pga3dBivectorWeight(
      wx = (2.0 * (r.wy * (sMxy - xzMyz) + r.wz * (sMxz + xyMyz)) + r.wx * (sMs + yzMyz - xyMxy - xzMxz)),
      wy = (2.0 * (r.wx * (-sMxy - xzMyz) + r.wz * (sMyz - xyMxz)) + r.wy * (sMs + xzMxz - xyMxy - yzMyz)),
      wz = (2.0 * (r.wx * (xyMyz - sMxz) + r.wy * (-sMyz - xyMxz)) + r.wz * (sMs + xyMxy - xzMxz - yzMyz)),
    )

  infix def sandwich(r: Pga3dPseudoScalar): Pga3dPseudoScalar =
    Pga3dPseudoScalar(
      i = r.i * (s * s + xy * xy + xz * xz + yz * yz),
    )

  infix def sandwich(r: Pga3dPointCenter.type): Pga3dProjectivePoint =
    Pga3dProjectivePoint(
      x = 0.0,
      y = 0.0,
      z = 0.0,
      w = (s * s + xy * xy + xz * xz + yz * yz),
    )

  infix def reverseSandwich(r: Pga3dMotor): Pga3dMotor =
    val sMs = s * s
    val sMxy = s * xy
    val sMxz = s * xz
    val sMyz = s * yz
    val xyMxy = xy * xy
    val xyMxz = xy * xz
    val xyMyz = xy * yz
    val xzMxz = xz * xz
    val xzMyz = xz * yz
    val yzMyz = yz * yz
    Pga3dMotor(
      s = r.s * (sMs + xyMxy + xzMxz + yzMyz),
      wx = (2.0 * (r.wy * (-sMxy - xzMyz) + r.wz * (xyMyz - sMxz)) + r.wx * (sMs + yzMyz - xyMxy - xzMxz)),
      wy = (2.0 * (r.wx * (sMxy - xzMyz) + r.wz * (-sMyz - xyMxz)) + r.wy * (sMs + xzMxz - xyMxy - yzMyz)),
      wz = (2.0 * (r.wx * (sMxz + xyMyz) + r.wy * (sMyz - xyMxz)) + r.wz * (sMs + xyMxy - xzMxz - yzMyz)),
      xy = (2.0 * (r.xz * (xyMxz - sMyz) + r.yz * (sMxz + xyMyz)) + r.xy * (sMs + xyMxy - xzMxz - yzMyz)),
      xz = (2.0 * (r.xy * (sMyz + xyMxz) + r.yz * (xzMyz - sMxy)) + r.xz * (sMs + xzMxz - xyMxy - yzMyz)),
      yz = (2.0 * (r.xy * (xyMyz - sMxz) + r.xz * (sMxy + xzMyz)) + r.yz * (sMs + yzMyz - xyMxy - xzMxz)),
      i = r.i * (sMs + xyMxy + xzMxz + yzMyz),
    )

  infix def reverseSandwich(r: Pga3dPlane): Pga3dPlane =
    val sMs = s * s
    val sMxy = s * xy
    val sMxz = s * xz
    val sMyz = s * yz
    val xyMxy = xy * xy
    val xyMxz = xy * xz
    val xyMyz = xy * yz
    val xzMxz = xz * xz
    val xzMyz = xz * yz
    val yzMyz = yz * yz
    Pga3dPlane(
      x = (2.0 * (r.y * (-sMxy - xzMyz) + r.z * (xyMyz - sMxz)) + r.x * (sMs + yzMyz - xyMxy - xzMxz)),
      y = (2.0 * (r.x * (sMxy - xzMyz) + r.z * (-sMyz - xyMxz)) + r.y * (sMs + xzMxz - xyMxy - yzMyz)),
      z = (2.0 * (r.x * (sMxz + xyMyz) + r.y * (sMyz - xyMxz)) + r.z * (sMs + xyMxy - xzMxz - yzMyz)),
      w = r.w * (sMs + xyMxy + xzMxz + yzMyz),
    )

  infix def reverseSandwich(r: Pga3dBivector): Pga3dBivector =
    val sMs = s * s
    val sMxy = s * xy
    val sMxz = s * xz
    val sMyz = s * yz
    val xyMxy = xy * xy
    val xyMxz = xy * xz
    val xyMyz = xy * yz
    val xzMxz = xz * xz
    val xzMyz = xz * yz
    val yzMyz = yz * yz
    Pga3dBivector(
      wx = (2.0 * (r.wy * (-sMxy - xzMyz) + r.wz * (xyMyz - sMxz)) + r.wx * (sMs + yzMyz - xyMxy - xzMxz)),
      wy = (2.0 * (r.wx * (sMxy - xzMyz) + r.wz * (-sMyz - xyMxz)) + r.wy * (sMs + xzMxz - xyMxy - yzMyz)),
      wz = (2.0 * (r.wx * (sMxz + xyMyz) + r.wy * (sMyz - xyMxz)) + r.wz * (sMs + xyMxy - xzMxz - yzMyz)),
      xy = (2.0 * (r.xz * (xyMxz - sMyz) + r.yz * (sMxz + xyMyz)) + r.xy * (sMs + xyMxy - xzMxz - yzMyz)),
      xz = (2.0 * (r.xy * (sMyz + xyMxz) + r.yz * (xzMyz - sMxy)) + r.xz * (sMs + xzMxz - xyMxy - yzMyz)),
      yz = (2.0 * (r.xy * (xyMyz - sMxz) + r.xz * (sMxy + xzMyz)) + r.yz * (sMs + yzMyz - xyMxy - xzMxz)),
    )

  infix def reverseSandwich(r: Pga3dProjectivePoint): Pga3dProjectivePoint =
    val sMs = s * s
    val sMxy = s * xy
    val sMxz = s * xz
    val sMyz = s * yz
    val xyMxy = xy * xy
    val xyMxz = xy * xz
    val xyMyz = xy * yz
    val xzMxz = xz * xz
    val xzMyz = xz * yz
    val yzMyz = yz * yz
    Pga3dProjectivePoint(
      x = (2.0 * (r.y * (-sMxy - xzMyz) + r.z * (xyMyz - sMxz)) + r.x * (sMs + yzMyz - xyMxy - xzMxz)),
      y = (2.0 * (r.x * (sMxy - xzMyz) + r.z * (-sMyz - xyMxz)) + r.y * (sMs + xzMxz - xyMxy - yzMyz)),
      z = (2.0 * (r.x * (sMxz + xyMyz) + r.y * (sMyz - xyMxz)) + r.z * (sMs + xyMxy - xzMxz - yzMyz)),
      w = r.w * (sMs + xyMxy + xzMxz + yzMyz),
    )

  infix def reverseSandwich(r: Pga3dRotor): Pga3dRotor =
    val sMs = s * s
    val sMxy = s * xy
    val sMxz = s * xz
    val sMyz = s * yz
    val xyMxy = xy * xy
    val xyMxz = xy * xz
    val xyMyz = xy * yz
    val xzMxz = xz * xz
    val xzMyz = xz * yz
    val yzMyz = yz * yz
    Pga3dRotor(
      s = r.s * (sMs + xyMxy + xzMxz + yzMyz),
      xy = (2.0 * (r.xz * (xyMxz - sMyz) + r.yz * (sMxz + xyMyz)) + r.xy * (sMs + xyMxy - xzMxz - yzMyz)),
      xz = (2.0 * (r.xy * (sMyz + xyMxz) + r.yz * (xzMyz - sMxy)) + r.xz * (sMs + xzMxz - xyMxy - yzMyz)),
      yz = (2.0 * (r.xy * (xyMyz - sMxz) + r.xz * (sMxy + xzMyz)) + r.yz * (sMs + yzMyz - xyMxy - xzMxz)),
    )

  infix def reverseSandwich(r: Pga3dProjectiveTranslator): Pga3dProjectiveTranslator =
    val sMs = s * s
    val sMxy = s * xy
    val sMxz = s * xz
    val sMyz = s * yz
    val xyMxy = xy * xy
    val xyMxz = xy * xz
    val xyMyz = xy * yz
    val xzMxz = xz * xz
    val xzMyz = xz * yz
    val yzMyz = yz * yz
    Pga3dProjectiveTranslator(
      s = r.s * (sMs + xyMxy + xzMxz + yzMyz),
      wx = (2.0 * (r.wy * (-sMxy - xzMyz) + r.wz * (xyMyz - sMxz)) + r.wx * (sMs + yzMyz - xyMxy - xzMxz)),
      wy = (2.0 * (r.wx * (sMxy - xzMyz) + r.wz * (-sMyz - xyMxz)) + r.wy * (sMs + xzMxz - xyMxy - yzMyz)),
      wz = (2.0 * (r.wx * (sMxz + xyMyz) + r.wy * (sMyz - xyMxz)) + r.wz * (sMs + xyMxy - xzMxz - yzMyz)),
    )

  infix def reverseSandwich(r: Pga3dTranslator): Pga3dProjectiveTranslator =
    val sMs = s * s
    val sMxy = s * xy
    val sMxz = s * xz
    val sMyz = s * yz
    val xyMxy = xy * xy
    val xyMxz = xy * xz
    val xyMyz = xy * yz
    val xzMxz = xz * xz
    val xzMyz = xz * yz
    val yzMyz = yz * yz
    Pga3dProjectiveTranslator(
      s = (sMs + xyMxy + xzMxz + yzMyz),
      wx = (2.0 * (r.wy * (-sMxy - xzMyz) + r.wz * (xyMyz - sMxz)) + r.wx * (sMs + yzMyz - xyMxy - xzMxz)),
      wy = (2.0 * (r.wx * (sMxy - xzMyz) + r.wz * (-sMyz - xyMxz)) + r.wy * (sMs + xzMxz - xyMxy - yzMyz)),
      wz = (2.0 * (r.wx * (sMxz + xyMyz) + r.wy * (sMyz - xyMxz)) + r.wz * (sMs + xyMxy - xzMxz - yzMyz)),
    )

  infix def reverseSandwich(r: Pga3dVector): Pga3dVector =
    val sMs = s * s
    val sMxy = s * xy
    val sMxz = s * xz
    val sMyz = s * yz
    val xyMxy = xy * xy
    val xyMxz = xy * xz
    val xyMyz = xy * yz
    val xzMxz = xz * xz
    val xzMyz = xz * yz
    val yzMyz = yz * yz
    Pga3dVector(
      x = (2.0 * (r.y * (-sMxy - xzMyz) + r.z * (xyMyz - sMxz)) + r.x * (sMs + yzMyz - xyMxy - xzMxz)),
      y = (2.0 * (r.x * (sMxy - xzMyz) + r.z * (-sMyz - xyMxz)) + r.y * (sMs + xzMxz - xyMxy - yzMyz)),
      z = (2.0 * (r.x * (sMxz + xyMyz) + r.y * (sMyz - xyMxz)) + r.z * (sMs + xyMxy - xzMxz - yzMyz)),
    )

  infix def reverseSandwich(r: Pga3dPoint): Pga3dProjectivePoint =
    val sMs = s * s
    val sMxy = s * xy
    val sMxz = s * xz
    val sMyz = s * yz
    val xyMxy = xy * xy
    val xyMxz = xy * xz
    val xyMyz = xy * yz
    val xzMxz = xz * xz
    val xzMyz = xz * yz
    val yzMyz = yz * yz
    Pga3dProjectivePoint(
      x = (2.0 * (r.y * (-sMxy - xzMyz) + r.z * (xyMyz - sMxz)) + r.x * (sMs + yzMyz - xyMxy - xzMxz)),
      y = (2.0 * (r.x * (sMxy - xzMyz) + r.z * (-sMyz - xyMxz)) + r.y * (sMs + xzMxz - xyMxy - yzMyz)),
      z = (2.0 * (r.x * (sMxz + xyMyz) + r.y * (sMyz - xyMxz)) + r.z * (sMs + xyMxy - xzMxz - yzMyz)),
      w = (sMs + xyMxy + xzMxz + yzMyz),
    )

  infix def reverseSandwich(r: Pga3dPlaneCentral): Pga3dPlaneCentral =
    val sMs = s * s
    val sMxy = s * xy
    val sMxz = s * xz
    val sMyz = s * yz
    val xyMxy = xy * xy
    val xyMxz = xy * xz
    val xyMyz = xy * yz
    val xzMxz = xz * xz
    val xzMyz = xz * yz
    val yzMyz = yz * yz
    Pga3dPlaneCentral(
      x = (2.0 * (r.y * (-sMxy - xzMyz) + r.z * (xyMyz - sMxz)) + r.x * (sMs + yzMyz - xyMxy - xzMxz)),
      y = (2.0 * (r.x * (sMxy - xzMyz) + r.z * (-sMyz - xyMxz)) + r.y * (sMs + xzMxz - xyMxy - yzMyz)),
      z = (2.0 * (r.x * (sMxz + xyMyz) + r.y * (sMyz - xyMxz)) + r.z * (sMs + xyMxy - xzMxz - yzMyz)),
    )

  infix def reverseSandwich(r: Pga3dBivectorBulk): Pga3dBivectorBulk =
    val sMs = s * s
    val sMxy = s * xy
    val sMxz = s * xz
    val sMyz = s * yz
    val xyMxy = xy * xy
    val xyMxz = xy * xz
    val xyMyz = xy * yz
    val xzMxz = xz * xz
    val xzMyz = xz * yz
    val yzMyz = yz * yz
    Pga3dBivectorBulk(
      xy = (2.0 * (r.xz * (xyMxz - sMyz) + r.yz * (sMxz + xyMyz)) + r.xy * (sMs + xyMxy - xzMxz - yzMyz)),
      xz = (2.0 * (r.xy * (sMyz + xyMxz) + r.yz * (xzMyz - sMxy)) + r.xz * (sMs + xzMxz - xyMxy - yzMyz)),
      yz = (2.0 * (r.xy * (xyMyz - sMxz) + r.xz * (sMxy + xzMyz)) + r.yz * (sMs + yzMyz - xyMxy - xzMxz)),
    )

  infix def reverseSandwich(r: Pga3dBivectorWeight): Pga3dBivectorWeight =
    val sMs = s * s
    val sMxy = s * xy
    val sMxz = s * xz
    val sMyz = s * yz
    val xyMxy = xy * xy
    val xyMxz = xy * xz
    val xyMyz = xy * yz
    val xzMxz = xz * xz
    val xzMyz = xz * yz
    val yzMyz = yz * yz
    Pga3dBivectorWeight(
      wx = (2.0 * (r.wy * (-sMxy - xzMyz) + r.wz * (xyMyz - sMxz)) + r.wx * (sMs + yzMyz - xyMxy - xzMxz)),
      wy = (2.0 * (r.wx * (sMxy - xzMyz) + r.wz * (-sMyz - xyMxz)) + r.wy * (sMs + xzMxz - xyMxy - yzMyz)),
      wz = (2.0 * (r.wx * (sMxz + xyMyz) + r.wy * (sMyz - xyMxz)) + r.wz * (sMs + xyMxy - xzMxz - yzMyz)),
    )

  infix def reverseSandwich(r: Pga3dPseudoScalar): Pga3dPseudoScalar =
    Pga3dPseudoScalar(
      i = r.i * (s * s + xy * xy + xz * xz + yz * yz),
    )

  infix def reverseSandwich(r: Pga3dPointCenter.type): Pga3dProjectivePoint =
    Pga3dProjectivePoint(
      x = 0.0,
      y = 0.0,
      z = 0.0,
      w = (s * s + xy * xy + xz * xz + yz * yz),
    )

  infix def cross(r: Pga3dMotor): Pga3dBivector =
    Pga3dBivector(
      wx = (r.wy * xy + r.wz * xz),
      wy = (r.wz * yz - r.wx * xy),
      wz = (-r.wx * xz - r.wy * yz),
      xy = (r.xz * yz - r.yz * xz),
      xz = (r.yz * xy - r.xy * yz),
      yz = (r.xy * xz - r.xz * xy),
    )

  infix def cross(r: Pga3dPlane): Pga3dPlaneCentral =
    Pga3dPlaneCentral(
      x = (r.y * xy + r.z * xz),
      y = (r.z * yz - r.x * xy),
      z = (-r.x * xz - r.y * yz),
    )

  infix def cross(r: Pga3dBivector): Pga3dBivector =
    Pga3dBivector(
      wx = (r.wy * xy + r.wz * xz),
      wy = (r.wz * yz - r.wx * xy),
      wz = (-r.wx * xz - r.wy * yz),
      xy = (r.xz * yz - r.yz * xz),
      xz = (r.yz * xy - r.xy * yz),
      yz = (r.xy * xz - r.xz * xy),
    )

  infix def cross(r: Pga3dProjectivePoint): Pga3dVector =
    Pga3dVector(
      x = (r.y * xy + r.z * xz),
      y = (r.z * yz - r.x * xy),
      z = (-r.x * xz - r.y * yz),
    )

  infix def cross(r: Pga3dRotor): Pga3dBivectorBulk =
    Pga3dBivectorBulk(
      xy = (r.xz * yz - r.yz * xz),
      xz = (r.yz * xy - r.xy * yz),
      yz = (r.xy * xz - r.xz * xy),
    )

  infix def cross(r: Pga3dProjectiveTranslator): Pga3dBivectorWeight =
    Pga3dBivectorWeight(
      wx = (r.wy * xy + r.wz * xz),
      wy = (r.wz * yz - r.wx * xy),
      wz = (-r.wx * xz - r.wy * yz),
    )

  infix def cross(r: Pga3dTranslator): Pga3dBivectorWeight =
    Pga3dBivectorWeight(
      wx = (r.wy * xy + r.wz * xz),
      wy = (r.wz * yz - r.wx * xy),
      wz = (-r.wx * xz - r.wy * yz),
    )

  infix def cross(r: Pga3dVector): Pga3dVector =
    Pga3dVector(
      x = (r.y * xy + r.z * xz),
      y = (r.z * yz - r.x * xy),
      z = (-r.x * xz - r.y * yz),
    )

  infix def cross(r: Pga3dPoint): Pga3dVector =
    Pga3dVector(
      x = (r.y * xy + r.z * xz),
      y = (r.z * yz - r.x * xy),
      z = (-r.x * xz - r.y * yz),
    )

  infix def cross(r: Pga3dPlaneCentral): Pga3dPlaneCentral =
    Pga3dPlaneCentral(
      x = (r.y * xy + r.z * xz),
      y = (r.z * yz - r.x * xy),
      z = (-r.x * xz - r.y * yz),
    )

  infix def cross(r: Pga3dBivectorBulk): Pga3dBivectorBulk =
    Pga3dBivectorBulk(
      xy = (r.xz * yz - r.yz * xz),
      xz = (r.yz * xy - r.xy * yz),
      yz = (r.xy * xz - r.xz * xy),
    )

  infix def cross(r: Pga3dBivectorWeight): Pga3dBivectorWeight =
    Pga3dBivectorWeight(
      wx = (r.wy * xy + r.wz * xz),
      wy = (r.wz * yz - r.wx * xy),
      wz = (-r.wx * xz - r.wy * yz),
    )


object Pga3dRotor:

  inline val componentsCount = 4

  val zero: Pga3dRotor = Pga3dRotor(0.0, 0.0, 0.0, 0.0)

  val id: Pga3dRotor = Pga3dRotor(1.0, 0.0, 0.0, 0.0)

  def rotation(from: Pga3dPlaneCentral, to: Pga3dPlaneCentral): Pga3dRotor = {
    import me.kright.gametools.mathutil.ExactArith.diffOfProducts

    // not sqrt(from.normSquare * to.normSquare): the product overflows/underflows
    // for extreme magnitudes (~1e100 or ~1e-100) where each norm alone is still fine
    val norm = from.norm * to.norm
    val q2a = to.geometric(from) / norm
    val dot = q2a.s

    // the -0.9 threshold keeps (1.0 + dot) >= 0.1, so the half-angle branch loses
    // at most ~2e-15 relative to the dot rounding; angles closer to pi take the
    // exact-wedge branch below, which stays ~1e-15 all the way to pi
    if (dot > -0.9) {
      val newCos = Math.sqrt((1.0 + dot) / 2)
      val newSinDivSin2 = 0.5 / newCos
      return Pga3dRotor(newCos, q2a.xy * newSinDivSin2, q2a.xz * newSinDivSin2, q2a.yz * newSinDivSin2)
    }

    // near pi the wedge components of q2a cancel catastrophically (~1e-17 absolute
    // noise, which would tilt the axis by ~1e-17/sin2a), so the axis is recomputed
    // with error-free products
    val invNorm = 1.0 / norm
    val bxy = diffOfProducts(from.y, to.x, from.x, to.y) * invNorm
    val bxz = diffOfProducts(from.z, to.x, from.x, to.z) * invNorm
    val byz = diffOfProducts(from.z, to.y, from.y, to.z) * invNorm
    val sin2a = Math.sqrt(bxy * bxy + bxz * bxz + byz * byz)

    if (sin2a > 0.0) {
      // rotation by (pi - eps): the dot guard bounds sin2a <= sin(acos(0.9)) ~ 0.44,
      // where asin is well-conditioned - unlike atan2 near pi, whose ~ulp(pi)
      // absolute error would be ~1e-16/eps relative in s
      val eps = Math.asin(sin2a)
      val axisMult = Math.cos(eps * 0.5) / sin2a
      return Pga3dRotor(Math.sin(eps * 0.5), bxy * axisMult, bxz * axisMult, byz * axisMult)
    }

    // exactly antipodal inputs: the axis is any direction orthogonal to from
    if (Math.abs(from.x) > Math.abs(from.z)) {
      return Pga3dRotor(0.0, 0.0, -from.x, -from.y).normalizedByNorm
    }
    return Pga3dRotor(0.0, from.y, from.z, 0.0).normalizedByNorm
  }

  def rotation(from: Pga3dVector, to: Pga3dVector): Pga3dRotor =
    rotation(from.dual, to.dual)

  def fromAxes(axisX: Pga3dVector, axisY: Pga3dVector, axisZ: Pga3dVector): Pga3dRotor = {
    val m00 = axisX.x
    val m10 = axisX.y
    val m20 = axisX.z
    val m01 = axisY.x
    val m11 = axisY.y
    val m21 = axisY.z
    val m02 = axisZ.x
    val m12 = axisZ.y
    val m22 = axisZ.z

    val tr = m00 + m11 + m22
    val max = Math.max(tr, Math.max(m00, Math.max(m11, m22)))

    if (tr == max) {
      val s = Math.sqrt(1.0 + tr)
      val invS = 0.5 / s
      Pga3dRotor(
        s = 0.5 * s,
        xy = (m01 - m10) * invS,
        xz = (m02 - m20) * invS,
        yz = (m12 - m21) * invS
      )
    } else if (m00 == max) {
      val yz = Math.sqrt(1.0 + m00 - m11 - m22)
      val invYZ = 0.5 / yz
      Pga3dRotor(
        s = (m12 - m21) * invYZ,
        xy = (m20 + m02) * invYZ,
        xz = -(m10 + m01) * invYZ,
        yz = 0.5 * yz
      )
    } else if (m11 == max) {
      val xz = Math.sqrt(1.0 - m00 + m11 - m22)
      val invXZ = 0.5 / xz
      Pga3dRotor(
        s = (m02 - m20) * invXZ,
        xy = -(m12 + m21) * invXZ,
        xz = 0.5 * xz,
        yz = -(m10 + m01) * invXZ
      )
    } else {
      val xy = Math.sqrt(1.0 - m00 - m11 + m22)
      val invXY = 0.5 / xy
      Pga3dRotor(
        s = (m01 - m10) * invXY,
        xy = 0.5 * xy,
        xz = -(m12 + m21) * invXY,
        yz = (m20 + m02) * invXY
      )
    }
  }