package me.kright.gametools.pga3d

import scala.annotation.targetName
import me.kright.gametools.flatarray.FlatDoubleSerializer
import me.kright.gametools.mathutil.CanEqualWithEps


/**
 * A motor: a rigid transformation of 3d space (combined rotation and translation),
 * the even-graded (0, 2, 4) element of 3d PGA. Applied with motor.sandwich(obj).
 * A motor is the exponent of a Pga3dBivector (bivector.exp), and motor.log returns that bivector back.
 *
 * Variable fields: s, wx, wy, wz, xy, xz, yz, i.
 *
 * Generated by pgaNdCodeGen (me.kright.gametools.pga.codegen.scalagen.pga3d.runScalaCodeGen).
 * Do not edit by hand: change the generator and re-run it.
 */
final case class Pga3dMotor(s: Double = 0.0,
                            wx: Double = 0.0,
                            wy: Double = 0.0,
                            wz: Double = 0.0,
                            xy: Double = 0.0,
                            xz: Double = 0.0,
                            yz: Double = 0.0,
                            i: Double = 0.0) derives CanEqual, CanEqualWithEps, FlatDoubleSerializer:

  override def toString: String =
    s"Pga3dMotor(s = $s, wx = $wx, wy = $wy, wz = $wz, xy = $xy, xz = $xz, yz = $yz, i = $i)"

  def dual: Pga3dMotor =
    Pga3dMotor(
      s = i,
      wx = yz,
      wy = -xz,
      wz = xy,
      xy = wz,
      xz = -wy,
      yz = wx,
      i = s,
    )

  def weight: Pga3dMotor =
    Pga3dMotor(
      s = 0.0,
      wx = wx,
      wy = wy,
      wz = wz,
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      i = i,
    )

  def bulk: Pga3dRotor =
    Pga3dRotor(
      s = s,
      xy = xy,
      xz = xz,
      yz = yz,
    )

  @targetName("unaryMinus")
  def unary_- : Pga3dMotor =
    Pga3dMotor(
      s = -s,
      wx = -wx,
      wy = -wy,
      wz = -wz,
      xy = -xy,
      xz = -xz,
      yz = -yz,
      i = -i,
    )

  def reverse: Pga3dMotor =
    Pga3dMotor(
      s = s,
      wx = -wx,
      wy = -wy,
      wz = -wz,
      xy = -xy,
      xz = -xz,
      yz = -yz,
      i = i,
    )

  def antiReverse: Pga3dMotor =
    Pga3dMotor(
      s = s,
      wx = -wx,
      wy = -wy,
      wz = -wz,
      xy = -xy,
      xz = -xz,
      yz = -yz,
      i = i,
    )

  /**
   * see [[https://arxiv.org/abs/2206.07496]], page 14
   * and [[https://bivector.net/PGAdyn.pdf]], page 42
   */
  def renormalized: Pga3dMotor =
    val a2 = 1.0 / (s * s + xy * xy + xz * xz + yz * yz)
    val a = Math.sqrt(a2)
    val b = (s * i - wx * yz + wy * xz - wz * xy) * a * a2
    Pga3dMotor(
      s = a * s,
      wx = (a * wx + b * yz),
      wy = (a * wy - b * xz),
      wz = (a * wz + b * xy),
      xy = a * xy,
      xz = a * xz,
      yz = a * yz,
      i = (a * i - b * s),
    )

  /** motor has to be normalized */
  def toRotorAndTranslator: (Pga3dRotor, Pga3dTranslator) = {
    val q = this.toRotorUnsafe
    val t = q.reverse.geometric(this)
    (q, t.toTranslatorUnsafe)
  }

  /** motor has to be normalized */
  def toTranslatorAndRotor: (Pga3dTranslator, Pga3dRotor) = {
    val q = this.toRotorUnsafe
    val t = this.geometric(q.reverse)
    (t.toTranslatorUnsafe, q)
  }

  def bulkNormSquare: Double =
    (s * s + xy * xy + xz * xz + yz * yz)

  def bulkNorm: Double =
    Math.sqrt(bulkNormSquare)

  def normalizedByBulk =
    this / bulkNorm

  def weightNormSquare: Double =
    (i * i + wx * wx + wy * wy + wz * wz)

  def weightNorm: Double =
    Math.sqrt(weightNormSquare)

  def normalizedByWeight =
    this / weightNorm

  def normSquare: Double =
    (i * i + s * s + wx * wx + wy * wy + wz * wz + xy * xy + xz * xz + yz * yz)

  def norm: Double =
    Math.sqrt(normSquare)

  def normalizedByNorm =
    this / norm

  @targetName("times")
  def *(r: Double): Pga3dMotor =
    Pga3dMotor(
      s = r * s,
      wx = r * wx,
      wy = r * wy,
      wz = r * wz,
      xy = r * xy,
      xz = r * xz,
      yz = r * yz,
      i = i * r,
    )

  /** multiplies by the reciprocal: one division instead of one per component, at the cost of one extra rounding (~0.5 ulp) */
  @targetName("div")
  def /(r: Double): Pga3dMotor =
    this * (1.0 / r)

  @targetName("plus")
  def +(r: Pga3dMotor): Pga3dMotor =
    Pga3dMotor(
      s = (r.s + s),
      wx = (r.wx + wx),
      wy = (r.wy + wy),
      wz = (r.wz + wz),
      xy = (r.xy + xy),
      xz = (r.xz + xz),
      yz = (r.yz + yz),
      i = (i + r.i),
    )

  @targetName("minus")
  def -(r: Pga3dMotor): Pga3dMotor =
    Pga3dMotor(
      s = (s - r.s),
      wx = (wx - r.wx),
      wy = (wy - r.wy),
      wz = (wz - r.wz),
      xy = (xy - r.xy),
      xz = (xz - r.xz),
      yz = (yz - r.yz),
      i = (i - r.i),
    )

  def madd(r: Pga3dMotor, mult: Double): Pga3dMotor =
    Pga3dMotor(
      s = (s + mult * r.s),
      wx = (wx + mult * r.wx),
      wy = (wy + mult * r.wy),
      wz = (wz + mult * r.wz),
      xy = (xy + mult * r.xy),
      xz = (xz + mult * r.xz),
      yz = (yz + mult * r.yz),
      i = (i + mult * r.i),
    )

  /** componentwise product on the raw fields; NOT a geometric-algebra operation (basis-dependent) */
  def scale(r: Pga3dMotor): Pga3dMotor =
    Pga3dMotor(
      s = s * r.s,
      wx = wx * r.wx,
      wy = wy * r.wy,
      wz = wz * r.wz,
      xy = xy * r.xy,
      xz = xz * r.xz,
      yz = yz * r.yz,
      i = i * r.i,
    )

  /** componentwise 1/x on the raw fields (a zero field yields Infinity); NOT the multiplicative inverse */
  def reciprocal: Pga3dMotor =
    Pga3dMotor(
      s = 1.0 / s,
      wx = 1.0 / wx,
      wy = 1.0 / wy,
      wz = 1.0 / wz,
      xy = 1.0 / xy,
      xz = 1.0 / xz,
      yz = 1.0 / yz,
      i = 1.0 / i,
    )

  def log: Pga3dBivector =
    val scalar = s
    if (s < 0.0) {
      return (-this).log
    }

    val lenXYZ2 = xy * xy + xz * xz + yz * yz
    val lenXYZ = Math.sqrt(lenXYZ2)
    val angle = Math.atan2(lenXYZ, scalar)

    // 1 / sin^2 for a normalized motor; (1.0 - scalar * scalar) is the same value,
    // but cancels catastrophically for small angles (relative error ~eps / angle^2)
    val a = 1.0 / lenXYZ2

    // for a normalized motor sin(angle) = lenXYZ, so this is angle / sin(angle); the series branch:
    // x/sin(x) = 1 / (sin(x)/x) = 1 / (1 - x^2/6 + x^4/120 - ...);
    // substitute v = x^2/6 - x^4/120 + ... into 1/(1 - v) = 1 + v + v^2 + ...:
    //   x/sin(x) = 1 + x^2/6 + (1/36 - 1/120)*x^4 + ...
    //            = 1 + x^2/6 + 7*x^4/360 + ...
    // at x <= 1e-5 the dropped 7*x^4/360 <= 2e-22 relative term is far below 1e-17,
    // so the second-order form is exact in double
    val b = if (Math.abs(angle) > 1e-5) {
      angle / lenXYZ
    } else {
      1.0 + angle * angle / 6.0
    }

    // c = a * i * (1 - scalar * b); for a normalized motor scalar = cos(x), lenXYZ = sin(x),
    // a = 1/sin(x)^2 and b = x/sin(x), so c = i * (1 - cos(x)*b) / sin(x)^2. Step by step:
    //   cos(x)*b = (1 - x^2/2 + x^4/24 - ...) * (1 + x^2/6 + 7*x^4/360 + ...)
    //            = 1 + (1/6 - 1/2)*x^2 + (7/360 - 1/12 + 1/24)*x^4 + ...
    //            = 1 - x^2/3 - x^4/45 - ...
    //   1 - cos(x)*b = x^2/3 + x^4/45 + ...
    //   sin(x)^2 = (x - x^3/6 + ...)^2 = x^2 - x^4/3 + ... = x^2 * (1 - x^2/3 + ...)
    //   1/sin(x)^2 = (1 + x^2/3 + ...) / x^2   (again via 1/(1 - v) = 1 + v + ...)
    //   c/i = (x^2/3 + x^4/45 + ...) * (1 + x^2/3 + ...) / x^2
    //       = 1/3 + (1/9 + 1/45)*x^2 + ... = 1/3 + 2*x^2/15 + ...
    // carrying the x^4 terms through the same steps gives the dropped term 2*x^4/63;
    // at x <= 1e-5 it is <= 3.2e-22, relatively far below 1e-17, so the second-order
    // form is exact in double
    val c = if (Math.abs(angle) > 1e-5) {
      a * i * (1.0 - scalar * b)
    } else {
      (1.0 / 3.0 + angle * angle * (2.0 / 15.0)) * i
    }

    Pga3dBivector(
      wx = (b * wx + c * yz),
      wy = (b * wy - c * xz),
      wz = (b * wz + c * xy),
      xy = b * xy,
      xz = b * xz,
      yz = b * yz,
    )


  /** the fractional power of the motion: pow(0.5) is the half motion, pow(2.0) applies it twice */
  def pow(t: Double): Pga3dMotor =
    log.exp(t)

  def toMultivector: Pga3dMultivector =
    Pga3dMultivector(
      s = s,
      w = 0.0,
      x = 0.0,
      y = 0.0,
      z = 0.0,
      wx = wx,
      wy = wy,
      wz = wz,
      xy = xy,
      xz = xz,
      yz = yz,
      wxy = 0.0,
      wxz = 0.0,
      wyz = 0.0,
      xyz = 0.0,
      i = i,
    )

  def toBivectorUnsafe: Pga3dBivector =
    Pga3dBivector(
      wx = wx,
      wy = wy,
      wz = wz,
      xy = xy,
      xz = xz,
      yz = yz,
    )

  def toRotorUnsafe: Pga3dRotor =
    Pga3dRotor(
      s = s,
      xy = xy,
      xz = xz,
      yz = yz,
    )

  def toProjectiveTranslatorUnsafe: Pga3dProjectiveTranslator =
    Pga3dProjectiveTranslator(
      s = s,
      wx = wx,
      wy = wy,
      wz = wz,
    )

  def toTranslatorUnsafe: Pga3dTranslator =
    Pga3dTranslator(
      wx = wx,
      wy = wy,
      wz = wz,
    )

  def toBivectorBulkUnsafe: Pga3dBivectorBulk =
    Pga3dBivectorBulk(
      xy = xy,
      xz = xz,
      yz = yz,
    )

  def toBivectorWeightUnsafe: Pga3dBivectorWeight =
    Pga3dBivectorWeight(
      wx = wx,
      wy = wy,
      wz = wz,
    )

  def axisX: Pga3dVector =
    toRotorUnsafe.axisX

  def axisY: Pga3dVector =
    toRotorUnsafe.axisY

  def axisZ: Pga3dVector =
    toRotorUnsafe.axisZ

  /**
   * Spherical linear interpolation along the geodesic from this (t = 0) to b (t = 1),
   * with constant angular velocity. Computes this * (this.reverse.geometric(b))^t via log/exp.
   * Assumes both this and b are normalized; the result is normalized.
   * Near-antipodal inputs (b close to -this) are ill-conditioned: the geodesic is undefined
   * there and the interpolation direction becomes numerically unstable.
   */
  def slerp(b: Pga3dMotor, t: Double): Pga3dMotor =
    this.geometric(this.reverse.geometric(b).log.exp(t))

  /**
   * Normalized linear interpolation: the componentwise lerp this * (1 - t) + b * t, renormalized.
   * A fast APPROXIMATION of slerp: the angular velocity is not constant, so intermediate values
   * deviate from the true geodesic. The error is negligible for small angles between this and b
   * and grows toward the midpoint of large rotations. Assumes both inputs are normalized.
   */
  def nlerp(b: Pga3dMotor, t: Double): Pga3dMotor =
    (this * (1.0 - t) + b * t).renormalized

  infix def geometric(r: Pga3dMotor): Pga3dMotor =
    Pga3dMotor(
      s = (r.s * s - r.xy * xy - r.xz * xz - r.yz * yz),
      wx = (r.s * wx + r.wx * s + r.wy * xy + r.wz * xz - i * r.yz - r.i * yz - r.xy * wy - r.xz * wz),
      wy = (i * r.xz + r.i * xz + r.s * wy + r.wy * s + r.wz * yz + r.xy * wx - r.wx * xy - r.yz * wz),
      wz = (r.s * wz + r.wz * s + r.xz * wx + r.yz * wy - i * r.xy - r.i * xy - r.wx * xz - r.wy * yz),
      xy = (r.s * xy + r.xy * s + r.xz * yz - r.yz * xz),
      xz = (r.s * xz + r.xz * s + r.yz * xy - r.xy * yz),
      yz = (r.s * yz + r.xy * xz + r.yz * s - r.xz * xy),
      i = (i * r.s + r.i * s + r.wx * yz + r.wz * xy + r.xy * wz + r.yz * wx - r.wy * xz - r.xz * wy),
    )

  infix def geometric(r: Pga3dPlane): Pga3dMultivector =
    Pga3dMultivector(
      s = 0.0,
      w = (r.w * s + r.x * wx + r.y * wy + r.z * wz),
      x = (r.x * s + r.y * xy + r.z * xz),
      y = (r.y * s + r.z * yz - r.x * xy),
      z = (r.z * s - r.x * xz - r.y * yz),
      wx = 0.0,
      wy = 0.0,
      wz = 0.0,
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      wxy = (i * r.z + r.w * xy + r.y * wx - r.x * wy),
      wxz = (r.w * xz + r.z * wx - i * r.y - r.x * wz),
      wyz = (i * r.x + r.w * yz + r.z * wy - r.y * wz),
      xyz = (r.x * yz + r.z * xy - r.y * xz),
      i = 0.0,
    )

  infix def geometric(r: Pga3dBivector): Pga3dMotor =
    Pga3dMotor(
      s = (-r.xy * xy - r.xz * xz - r.yz * yz),
      wx = (r.wx * s + r.wy * xy + r.wz * xz - i * r.yz - r.xy * wy - r.xz * wz),
      wy = (i * r.xz + r.wy * s + r.wz * yz + r.xy * wx - r.wx * xy - r.yz * wz),
      wz = (r.wz * s + r.xz * wx + r.yz * wy - i * r.xy - r.wx * xz - r.wy * yz),
      xy = (r.xy * s + r.xz * yz - r.yz * xz),
      xz = (r.xz * s + r.yz * xy - r.xy * yz),
      yz = (r.xy * xz + r.yz * s - r.xz * xy),
      i = (r.wx * yz + r.wz * xy + r.xy * wz + r.yz * wx - r.wy * xz - r.xz * wy),
    )

  infix def geometric(r: Pga3dProjectivePoint): Pga3dMultivector =
    Pga3dMultivector(
      s = 0.0,
      w = (r.x * yz + r.z * xy - i * r.w - r.y * xz),
      x = -r.w * yz,
      y = r.w * xz,
      z = -r.w * xy,
      wx = 0.0,
      wy = 0.0,
      wz = 0.0,
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      wxy = (r.w * wz + r.x * xz + r.y * yz - r.z * s),
      wxz = (r.y * s + r.z * yz - r.w * wy - r.x * xy),
      wyz = (r.w * wx - r.x * s - r.y * xy - r.z * xz),
      xyz = r.w * s,
      i = 0.0,
    )

  infix def geometric(r: Pga3dRotor): Pga3dMotor =
    Pga3dMotor(
      s = (r.s * s - r.xy * xy - r.xz * xz - r.yz * yz),
      wx = (r.s * wx - i * r.yz - r.xy * wy - r.xz * wz),
      wy = (i * r.xz + r.s * wy + r.xy * wx - r.yz * wz),
      wz = (r.s * wz + r.xz * wx + r.yz * wy - i * r.xy),
      xy = (r.s * xy + r.xy * s + r.xz * yz - r.yz * xz),
      xz = (r.s * xz + r.xz * s + r.yz * xy - r.xy * yz),
      yz = (r.s * yz + r.xy * xz + r.yz * s - r.xz * xy),
      i = (i * r.s + r.xy * wz + r.yz * wx - r.xz * wy),
    )

  infix def geometric(r: Pga3dProjectiveTranslator): Pga3dMotor =
    Pga3dMotor(
      s = r.s * s,
      wx = (r.s * wx + r.wx * s + r.wy * xy + r.wz * xz),
      wy = (r.s * wy + r.wy * s + r.wz * yz - r.wx * xy),
      wz = (r.s * wz + r.wz * s - r.wx * xz - r.wy * yz),
      xy = r.s * xy,
      xz = r.s * xz,
      yz = r.s * yz,
      i = (i * r.s + r.wx * yz + r.wz * xy - r.wy * xz),
    )

  infix def geometric(r: Pga3dTranslator): Pga3dMotor =
    Pga3dMotor(
      s = s,
      wx = (wx + r.wx * s + r.wy * xy + r.wz * xz),
      wy = (wy + r.wy * s + r.wz * yz - r.wx * xy),
      wz = (wz + r.wz * s - r.wx * xz - r.wy * yz),
      xy = xy,
      xz = xz,
      yz = yz,
      i = (i + r.wx * yz + r.wz * xy - r.wy * xz),
    )

  infix def geometric(r: Pga3dVector): Pga3dMultivector =
    Pga3dMultivector(
      s = 0.0,
      w = (r.x * yz + r.z * xy - r.y * xz),
      x = 0.0,
      y = 0.0,
      z = 0.0,
      wx = 0.0,
      wy = 0.0,
      wz = 0.0,
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      wxy = (r.x * xz + r.y * yz - r.z * s),
      wxz = (r.y * s + r.z * yz - r.x * xy),
      wyz = (-r.x * s - r.y * xy - r.z * xz),
      xyz = 0.0,
      i = 0.0,
    )

  infix def geometric(r: Pga3dPoint): Pga3dMultivector =
    Pga3dMultivector(
      s = 0.0,
      w = (-i + r.x * yz + r.z * xy - r.y * xz),
      x = -yz,
      y = xz,
      z = -xy,
      wx = 0.0,
      wy = 0.0,
      wz = 0.0,
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      wxy = (wz + r.x * xz + r.y * yz - r.z * s),
      wxz = (-wy + r.y * s + r.z * yz - r.x * xy),
      wyz = (wx - r.x * s - r.y * xy - r.z * xz),
      xyz = s,
      i = 0.0,
    )

  infix def geometric(r: Pga3dPlaneCentral): Pga3dMultivector =
    Pga3dMultivector(
      s = 0.0,
      w = (r.x * wx + r.y * wy + r.z * wz),
      x = (r.x * s + r.y * xy + r.z * xz),
      y = (r.y * s + r.z * yz - r.x * xy),
      z = (r.z * s - r.x * xz - r.y * yz),
      wx = 0.0,
      wy = 0.0,
      wz = 0.0,
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      wxy = (i * r.z + r.y * wx - r.x * wy),
      wxz = (r.z * wx - i * r.y - r.x * wz),
      wyz = (i * r.x + r.z * wy - r.y * wz),
      xyz = (r.x * yz + r.z * xy - r.y * xz),
      i = 0.0,
    )

  infix def geometric(r: Pga3dBivectorBulk): Pga3dMotor =
    Pga3dMotor(
      s = (-r.xy * xy - r.xz * xz - r.yz * yz),
      wx = (-i * r.yz - r.xy * wy - r.xz * wz),
      wy = (i * r.xz + r.xy * wx - r.yz * wz),
      wz = (r.xz * wx + r.yz * wy - i * r.xy),
      xy = (r.xy * s + r.xz * yz - r.yz * xz),
      xz = (r.xz * s + r.yz * xy - r.xy * yz),
      yz = (r.xy * xz + r.yz * s - r.xz * xy),
      i = (r.xy * wz + r.yz * wx - r.xz * wy),
    )

  infix def geometric(r: Pga3dBivectorWeight): Pga3dMotor =
    Pga3dMotor(
      s = 0.0,
      wx = (r.wx * s + r.wy * xy + r.wz * xz),
      wy = (r.wy * s + r.wz * yz - r.wx * xy),
      wz = (r.wz * s - r.wx * xz - r.wy * yz),
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      i = (r.wx * yz + r.wz * xy - r.wy * xz),
    )

  infix def geometric(r: Pga3dPseudoScalar): Pga3dMotor =
    Pga3dMotor(
      s = 0.0,
      wx = -r.i * yz,
      wy = r.i * xz,
      wz = -r.i * xy,
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      i = r.i * s,
    )

  infix def geometric(r: Pga3dPointCenter.type): Pga3dMultivector =
    Pga3dMultivector(
      s = 0.0,
      w = -i,
      x = -yz,
      y = xz,
      z = -xy,
      wx = 0.0,
      wy = 0.0,
      wz = 0.0,
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      wxy = wz,
      wxz = -wy,
      wyz = wx,
      xyz = s,
      i = 0.0,
    )

  infix def dot(r: Pga3dMotor): Pga3dMotor =
    Pga3dMotor(
      s = (r.s * s - r.xy * xy - r.xz * xz - r.yz * yz),
      wx = (r.s * wx + r.wx * s - i * r.yz - r.i * yz),
      wy = (i * r.xz + r.i * xz + r.s * wy + r.wy * s),
      wz = (r.s * wz + r.wz * s - i * r.xy - r.i * xy),
      xy = (r.s * xy + r.xy * s),
      xz = (r.s * xz + r.xz * s),
      yz = (r.s * yz + r.yz * s),
      i = (i * r.s + r.i * s),
    )

  infix def dot(r: Pga3dPlane): Pga3dMultivector =
    Pga3dMultivector(
      s = 0.0,
      w = (r.w * s + r.x * wx + r.y * wy + r.z * wz),
      x = (r.x * s + r.y * xy + r.z * xz),
      y = (r.y * s + r.z * yz - r.x * xy),
      z = (r.z * s - r.x * xz - r.y * yz),
      wx = 0.0,
      wy = 0.0,
      wz = 0.0,
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      wxy = i * r.z,
      wxz = -i * r.y,
      wyz = i * r.x,
      xyz = 0.0,
      i = 0.0,
    )

  infix def dot(r: Pga3dBivector): Pga3dMotor =
    Pga3dMotor(
      s = (-r.xy * xy - r.xz * xz - r.yz * yz),
      wx = (r.wx * s - i * r.yz),
      wy = (i * r.xz + r.wy * s),
      wz = (r.wz * s - i * r.xy),
      xy = r.xy * s,
      xz = r.xz * s,
      yz = r.yz * s,
      i = 0.0,
    )

  infix def dot(r: Pga3dProjectivePoint): Pga3dMultivector =
    Pga3dMultivector(
      s = 0.0,
      w = (r.x * yz + r.z * xy - i * r.w - r.y * xz),
      x = -r.w * yz,
      y = r.w * xz,
      z = -r.w * xy,
      wx = 0.0,
      wy = 0.0,
      wz = 0.0,
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      wxy = -r.z * s,
      wxz = r.y * s,
      wyz = -r.x * s,
      xyz = r.w * s,
      i = 0.0,
    )

  infix def dot(r: Pga3dRotor): Pga3dMotor =
    Pga3dMotor(
      s = (r.s * s - r.xy * xy - r.xz * xz - r.yz * yz),
      wx = (r.s * wx - i * r.yz),
      wy = (i * r.xz + r.s * wy),
      wz = (r.s * wz - i * r.xy),
      xy = (r.s * xy + r.xy * s),
      xz = (r.s * xz + r.xz * s),
      yz = (r.s * yz + r.yz * s),
      i = i * r.s,
    )

  infix def dot(r: Pga3dProjectiveTranslator): Pga3dMotor =
    Pga3dMotor(
      s = r.s * s,
      wx = (r.s * wx + r.wx * s),
      wy = (r.s * wy + r.wy * s),
      wz = (r.s * wz + r.wz * s),
      xy = r.s * xy,
      xz = r.s * xz,
      yz = r.s * yz,
      i = i * r.s,
    )

  infix def dot(r: Pga3dTranslator): Pga3dMotor =
    Pga3dMotor(
      s = s,
      wx = (wx + r.wx * s),
      wy = (wy + r.wy * s),
      wz = (wz + r.wz * s),
      xy = xy,
      xz = xz,
      yz = yz,
      i = i,
    )

  infix def dot(r: Pga3dVector): Pga3dMultivector =
    Pga3dMultivector(
      s = 0.0,
      w = (r.x * yz + r.z * xy - r.y * xz),
      x = 0.0,
      y = 0.0,
      z = 0.0,
      wx = 0.0,
      wy = 0.0,
      wz = 0.0,
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      wxy = -r.z * s,
      wxz = r.y * s,
      wyz = -r.x * s,
      xyz = 0.0,
      i = 0.0,
    )

  infix def dot(r: Pga3dPoint): Pga3dMultivector =
    Pga3dMultivector(
      s = 0.0,
      w = (-i + r.x * yz + r.z * xy - r.y * xz),
      x = -yz,
      y = xz,
      z = -xy,
      wx = 0.0,
      wy = 0.0,
      wz = 0.0,
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      wxy = -r.z * s,
      wxz = r.y * s,
      wyz = -r.x * s,
      xyz = s,
      i = 0.0,
    )

  infix def dot(r: Pga3dPlaneCentral): Pga3dMultivector =
    Pga3dMultivector(
      s = 0.0,
      w = (r.x * wx + r.y * wy + r.z * wz),
      x = (r.x * s + r.y * xy + r.z * xz),
      y = (r.y * s + r.z * yz - r.x * xy),
      z = (r.z * s - r.x * xz - r.y * yz),
      wx = 0.0,
      wy = 0.0,
      wz = 0.0,
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      wxy = i * r.z,
      wxz = -i * r.y,
      wyz = i * r.x,
      xyz = 0.0,
      i = 0.0,
    )

  infix def dot(r: Pga3dBivectorBulk): Pga3dMotor =
    Pga3dMotor(
      s = (-r.xy * xy - r.xz * xz - r.yz * yz),
      wx = -i * r.yz,
      wy = i * r.xz,
      wz = -i * r.xy,
      xy = r.xy * s,
      xz = r.xz * s,
      yz = r.yz * s,
      i = 0.0,
    )

  infix def dot(r: Pga3dBivectorWeight): Pga3dBivectorWeight =
    Pga3dBivectorWeight(
      wx = r.wx * s,
      wy = r.wy * s,
      wz = r.wz * s,
    )

  infix def dot(r: Pga3dPseudoScalar): Pga3dMotor =
    Pga3dMotor(
      s = 0.0,
      wx = -r.i * yz,
      wy = r.i * xz,
      wz = -r.i * xy,
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      i = r.i * s,
    )

  infix def dot(r: Pga3dPointCenter.type): Pga3dMultivector =
    Pga3dMultivector(
      s = 0.0,
      w = -i,
      x = -yz,
      y = xz,
      z = -xy,
      wx = 0.0,
      wy = 0.0,
      wz = 0.0,
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      wxy = 0.0,
      wxz = 0.0,
      wyz = 0.0,
      xyz = s,
      i = 0.0,
    )

  infix def wedge(r: Pga3dMotor): Pga3dMotor =
    Pga3dMotor(
      s = r.s * s,
      wx = (r.s * wx + r.wx * s),
      wy = (r.s * wy + r.wy * s),
      wz = (r.s * wz + r.wz * s),
      xy = (r.s * xy + r.xy * s),
      xz = (r.s * xz + r.xz * s),
      yz = (r.s * yz + r.yz * s),
      i = (i * r.s + r.i * s + r.wx * yz + r.wz * xy + r.xy * wz + r.yz * wx - r.wy * xz - r.xz * wy),
    )

  inline infix def ^(r: Pga3dMotor): Pga3dMotor = wedge(r)

  inline infix def meet(r: Pga3dMotor): Pga3dMotor = wedge(r)

  infix def wedge(r: Pga3dPlane): Pga3dMultivector =
    Pga3dMultivector(
      s = 0.0,
      w = r.w * s,
      x = r.x * s,
      y = r.y * s,
      z = r.z * s,
      wx = 0.0,
      wy = 0.0,
      wz = 0.0,
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      wxy = (r.w * xy + r.y * wx - r.x * wy),
      wxz = (r.w * xz + r.z * wx - r.x * wz),
      wyz = (r.w * yz + r.z * wy - r.y * wz),
      xyz = (r.x * yz + r.z * xy - r.y * xz),
      i = 0.0,
    )

  inline infix def ^(r: Pga3dPlane): Pga3dMultivector = wedge(r)

  inline infix def meet(r: Pga3dPlane): Pga3dMultivector = wedge(r)

  infix def wedge(r: Pga3dBivector): Pga3dMotor =
    Pga3dMotor(
      s = 0.0,
      wx = r.wx * s,
      wy = r.wy * s,
      wz = r.wz * s,
      xy = r.xy * s,
      xz = r.xz * s,
      yz = r.yz * s,
      i = (r.wx * yz + r.wz * xy + r.xy * wz + r.yz * wx - r.wy * xz - r.xz * wy),
    )

  inline infix def ^(r: Pga3dBivector): Pga3dMotor = wedge(r)

  inline infix def meet(r: Pga3dBivector): Pga3dMotor = wedge(r)

  infix def wedge(r: Pga3dProjectivePoint): Pga3dProjectivePoint =
    Pga3dProjectivePoint(
      x = r.x * s,
      y = r.y * s,
      z = r.z * s,
      w = r.w * s,
    )

  inline infix def ^(r: Pga3dProjectivePoint): Pga3dProjectivePoint = wedge(r)

  inline infix def meet(r: Pga3dProjectivePoint): Pga3dProjectivePoint = wedge(r)

  infix def wedge(r: Pga3dRotor): Pga3dMotor =
    Pga3dMotor(
      s = r.s * s,
      wx = r.s * wx,
      wy = r.s * wy,
      wz = r.s * wz,
      xy = (r.s * xy + r.xy * s),
      xz = (r.s * xz + r.xz * s),
      yz = (r.s * yz + r.yz * s),
      i = (i * r.s + r.xy * wz + r.yz * wx - r.xz * wy),
    )

  inline infix def ^(r: Pga3dRotor): Pga3dMotor = wedge(r)

  inline infix def meet(r: Pga3dRotor): Pga3dMotor = wedge(r)

  infix def wedge(r: Pga3dProjectiveTranslator): Pga3dMotor =
    Pga3dMotor(
      s = r.s * s,
      wx = (r.s * wx + r.wx * s),
      wy = (r.s * wy + r.wy * s),
      wz = (r.s * wz + r.wz * s),
      xy = r.s * xy,
      xz = r.s * xz,
      yz = r.s * yz,
      i = (i * r.s + r.wx * yz + r.wz * xy - r.wy * xz),
    )

  inline infix def ^(r: Pga3dProjectiveTranslator): Pga3dMotor = wedge(r)

  inline infix def meet(r: Pga3dProjectiveTranslator): Pga3dMotor = wedge(r)

  infix def wedge(r: Pga3dTranslator): Pga3dMotor =
    Pga3dMotor(
      s = s,
      wx = (wx + r.wx * s),
      wy = (wy + r.wy * s),
      wz = (wz + r.wz * s),
      xy = xy,
      xz = xz,
      yz = yz,
      i = (i + r.wx * yz + r.wz * xy - r.wy * xz),
    )

  inline infix def ^(r: Pga3dTranslator): Pga3dMotor = wedge(r)

  inline infix def meet(r: Pga3dTranslator): Pga3dMotor = wedge(r)

  infix def wedge(r: Pga3dVector): Pga3dVector =
    Pga3dVector(
      x = r.x * s,
      y = r.y * s,
      z = r.z * s,
    )

  inline infix def ^(r: Pga3dVector): Pga3dVector = wedge(r)

  inline infix def meet(r: Pga3dVector): Pga3dVector = wedge(r)

  infix def wedge(r: Pga3dPoint): Pga3dProjectivePoint =
    Pga3dProjectivePoint(
      x = r.x * s,
      y = r.y * s,
      z = r.z * s,
      w = s,
    )

  inline infix def ^(r: Pga3dPoint): Pga3dProjectivePoint = wedge(r)

  inline infix def meet(r: Pga3dPoint): Pga3dProjectivePoint = wedge(r)

  infix def wedge(r: Pga3dPlaneCentral): Pga3dMultivector =
    Pga3dMultivector(
      s = 0.0,
      w = 0.0,
      x = r.x * s,
      y = r.y * s,
      z = r.z * s,
      wx = 0.0,
      wy = 0.0,
      wz = 0.0,
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      wxy = (r.y * wx - r.x * wy),
      wxz = (r.z * wx - r.x * wz),
      wyz = (r.z * wy - r.y * wz),
      xyz = (r.x * yz + r.z * xy - r.y * xz),
      i = 0.0,
    )

  inline infix def ^(r: Pga3dPlaneCentral): Pga3dMultivector = wedge(r)

  inline infix def meet(r: Pga3dPlaneCentral): Pga3dMultivector = wedge(r)

  infix def wedge(r: Pga3dBivectorBulk): Pga3dMotor =
    Pga3dMotor(
      s = 0.0,
      wx = 0.0,
      wy = 0.0,
      wz = 0.0,
      xy = r.xy * s,
      xz = r.xz * s,
      yz = r.yz * s,
      i = (r.xy * wz + r.yz * wx - r.xz * wy),
    )

  inline infix def ^(r: Pga3dBivectorBulk): Pga3dMotor = wedge(r)

  inline infix def meet(r: Pga3dBivectorBulk): Pga3dMotor = wedge(r)

  infix def wedge(r: Pga3dBivectorWeight): Pga3dMotor =
    Pga3dMotor(
      s = 0.0,
      wx = r.wx * s,
      wy = r.wy * s,
      wz = r.wz * s,
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      i = (r.wx * yz + r.wz * xy - r.wy * xz),
    )

  inline infix def ^(r: Pga3dBivectorWeight): Pga3dMotor = wedge(r)

  inline infix def meet(r: Pga3dBivectorWeight): Pga3dMotor = wedge(r)

  infix def wedge(r: Pga3dPseudoScalar): Pga3dPseudoScalar =
    Pga3dPseudoScalar(
      i = r.i * s,
    )

  inline infix def ^(r: Pga3dPseudoScalar): Pga3dPseudoScalar = wedge(r)

  inline infix def meet(r: Pga3dPseudoScalar): Pga3dPseudoScalar = wedge(r)

  infix def wedge(r: Pga3dPointCenter.type): Pga3dProjectivePoint =
    Pga3dProjectivePoint(
      x = 0.0,
      y = 0.0,
      z = 0.0,
      w = s,
    )

  inline infix def ^(r: Pga3dPointCenter.type): Pga3dProjectivePoint = wedge(r)

  inline infix def meet(r: Pga3dPointCenter.type): Pga3dProjectivePoint = wedge(r)

  infix def antiGeometric(r: Pga3dMotor): Pga3dMotor =
    Pga3dMotor(
      s = (i * r.s + r.i * s + r.wx * yz + r.wz * xy + r.xy * wz + r.yz * wx - r.wy * xz - r.xz * wy),
      wx = (i * r.wx + r.i * wx + r.wy * wz - r.wz * wy),
      wy = (i * r.wy + r.i * wy + r.wz * wx - r.wx * wz),
      wz = (i * r.wz + r.i * wz + r.wx * wy - r.wy * wx),
      xy = (i * r.xy + r.i * xy + r.xz * wx + r.yz * wy - r.s * wz - r.wx * xz - r.wy * yz - r.wz * s),
      xz = (i * r.xz + r.i * xz + r.s * wy + r.wx * xy + r.wy * s + r.yz * wz - r.wz * yz - r.xy * wx),
      yz = (i * r.yz + r.i * yz + r.wy * xy + r.wz * xz - r.s * wx - r.wx * s - r.xy * wy - r.xz * wz),
      i = (i * r.i - r.wx * wx - r.wy * wy - r.wz * wz),
    )

  infix def antiGeometric(r: Pga3dPlane): Pga3dMultivector =
    Pga3dMultivector(
      s = 0.0,
      w = i * r.w,
      x = (i * r.x + r.y * wz - r.w * yz - r.z * wy),
      y = (i * r.y + r.w * xz + r.z * wx - r.x * wz),
      z = (i * r.z + r.x * wy - r.w * xy - r.y * wx),
      wx = 0.0,
      wy = 0.0,
      wz = 0.0,
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      wxy = r.w * wz,
      wxz = -r.w * wy,
      wyz = r.w * wx,
      xyz = (r.x * wx + r.y * wy + r.z * wz - r.w * s),
      i = 0.0,
    )

  infix def antiGeometric(r: Pga3dBivector): Pga3dMotor =
    Pga3dMotor(
      s = (r.wx * yz + r.wz * xy + r.xy * wz + r.yz * wx - r.wy * xz - r.xz * wy),
      wx = (i * r.wx + r.wy * wz - r.wz * wy),
      wy = (i * r.wy + r.wz * wx - r.wx * wz),
      wz = (i * r.wz + r.wx * wy - r.wy * wx),
      xy = (i * r.xy + r.xz * wx + r.yz * wy - r.wx * xz - r.wy * yz - r.wz * s),
      xz = (i * r.xz + r.wx * xy + r.wy * s + r.yz * wz - r.wz * yz - r.xy * wx),
      yz = (i * r.yz + r.wy * xy + r.wz * xz - r.wx * s - r.xy * wy - r.xz * wz),
      i = (-r.wx * wx - r.wy * wy - r.wz * wz),
    )

  infix def antiGeometric(r: Pga3dProjectivePoint): Pga3dMultivector =
    Pga3dMultivector(
      s = 0.0,
      w = (r.x * wx + r.y * wy + r.z * wz),
      x = (r.y * xy + r.z * xz - r.w * wx - r.x * s),
      y = (r.z * yz - r.w * wy - r.x * xy - r.y * s),
      z = (-r.w * wz - r.x * xz - r.y * yz - r.z * s),
      wx = 0.0,
      wy = 0.0,
      wz = 0.0,
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      wxy = (r.y * wx - i * r.z - r.x * wy),
      wxz = (i * r.y + r.z * wx - r.x * wz),
      wyz = (r.z * wy - i * r.x - r.y * wz),
      xyz = (i * r.w + r.x * yz + r.z * xy - r.y * xz),
      i = 0.0,
    )

  infix def antiGeometric(r: Pga3dRotor): Pga3dRotor =
    Pga3dRotor(
      s = (i * r.s + r.xy * wz + r.yz * wx - r.xz * wy),
      xy = (i * r.xy + r.xz * wx + r.yz * wy - r.s * wz),
      xz = (i * r.xz + r.s * wy + r.yz * wz - r.xy * wx),
      yz = (i * r.yz - r.s * wx - r.xy * wy - r.xz * wz),
    )

  infix def antiGeometric(r: Pga3dProjectiveTranslator): Pga3dMotor =
    Pga3dMotor(
      s = (i * r.s + r.wx * yz + r.wz * xy - r.wy * xz),
      wx = (i * r.wx + r.wy * wz - r.wz * wy),
      wy = (i * r.wy + r.wz * wx - r.wx * wz),
      wz = (i * r.wz + r.wx * wy - r.wy * wx),
      xy = (-r.s * wz - r.wx * xz - r.wy * yz - r.wz * s),
      xz = (r.s * wy + r.wx * xy + r.wy * s - r.wz * yz),
      yz = (r.wy * xy + r.wz * xz - r.s * wx - r.wx * s),
      i = (-r.wx * wx - r.wy * wy - r.wz * wz),
    )

  infix def antiGeometric(r: Pga3dTranslator): Pga3dMotor =
    Pga3dMotor(
      s = (i + r.wx * yz + r.wz * xy - r.wy * xz),
      wx = (i * r.wx + r.wy * wz - r.wz * wy),
      wy = (i * r.wy + r.wz * wx - r.wx * wz),
      wz = (i * r.wz + r.wx * wy - r.wy * wx),
      xy = (-wz - r.wx * xz - r.wy * yz - r.wz * s),
      xz = (wy + r.wx * xy + r.wy * s - r.wz * yz),
      yz = (-wx + r.wy * xy + r.wz * xz - r.wx * s),
      i = (-r.wx * wx - r.wy * wy - r.wz * wz),
    )

  infix def antiGeometric(r: Pga3dVector): Pga3dMultivector =
    Pga3dMultivector(
      s = 0.0,
      w = (r.x * wx + r.y * wy + r.z * wz),
      x = (r.y * xy + r.z * xz - r.x * s),
      y = (r.z * yz - r.x * xy - r.y * s),
      z = (-r.x * xz - r.y * yz - r.z * s),
      wx = 0.0,
      wy = 0.0,
      wz = 0.0,
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      wxy = (r.y * wx - i * r.z - r.x * wy),
      wxz = (i * r.y + r.z * wx - r.x * wz),
      wyz = (r.z * wy - i * r.x - r.y * wz),
      xyz = (r.x * yz + r.z * xy - r.y * xz),
      i = 0.0,
    )

  infix def antiGeometric(r: Pga3dPoint): Pga3dMultivector =
    Pga3dMultivector(
      s = 0.0,
      w = (r.x * wx + r.y * wy + r.z * wz),
      x = (-wx + r.y * xy + r.z * xz - r.x * s),
      y = (-wy + r.z * yz - r.x * xy - r.y * s),
      z = (-wz - r.x * xz - r.y * yz - r.z * s),
      wx = 0.0,
      wy = 0.0,
      wz = 0.0,
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      wxy = (r.y * wx - i * r.z - r.x * wy),
      wxz = (i * r.y + r.z * wx - r.x * wz),
      wyz = (r.z * wy - i * r.x - r.y * wz),
      xyz = (i + r.x * yz + r.z * xy - r.y * xz),
      i = 0.0,
    )

  infix def antiGeometric(r: Pga3dPlaneCentral): Pga3dMultivector =
    Pga3dMultivector(
      s = 0.0,
      w = 0.0,
      x = (i * r.x + r.y * wz - r.z * wy),
      y = (i * r.y + r.z * wx - r.x * wz),
      z = (i * r.z + r.x * wy - r.y * wx),
      wx = 0.0,
      wy = 0.0,
      wz = 0.0,
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      wxy = 0.0,
      wxz = 0.0,
      wyz = 0.0,
      xyz = (r.x * wx + r.y * wy + r.z * wz),
      i = 0.0,
    )

  infix def antiGeometric(r: Pga3dBivectorBulk): Pga3dRotor =
    Pga3dRotor(
      s = (r.xy * wz + r.yz * wx - r.xz * wy),
      xy = (i * r.xy + r.xz * wx + r.yz * wy),
      xz = (i * r.xz + r.yz * wz - r.xy * wx),
      yz = (i * r.yz - r.xy * wy - r.xz * wz),
    )

  infix def antiGeometric(r: Pga3dBivectorWeight): Pga3dMotor =
    Pga3dMotor(
      s = (r.wx * yz + r.wz * xy - r.wy * xz),
      wx = (i * r.wx + r.wy * wz - r.wz * wy),
      wy = (i * r.wy + r.wz * wx - r.wx * wz),
      wz = (i * r.wz + r.wx * wy - r.wy * wx),
      xy = (-r.wx * xz - r.wy * yz - r.wz * s),
      xz = (r.wx * xy + r.wy * s - r.wz * yz),
      yz = (r.wy * xy + r.wz * xz - r.wx * s),
      i = (-r.wx * wx - r.wy * wy - r.wz * wz),
    )

  infix def antiGeometric(r: Pga3dPseudoScalar): Pga3dMotor =
    Pga3dMotor(
      s = r.i * s,
      wx = r.i * wx,
      wy = r.i * wy,
      wz = r.i * wz,
      xy = r.i * xy,
      xz = r.i * xz,
      yz = r.i * yz,
      i = i * r.i,
    )

  infix def antiGeometric(r: Pga3dPointCenter.type): Pga3dMultivector =
    Pga3dMultivector(
      s = 0.0,
      w = 0.0,
      x = -wx,
      y = -wy,
      z = -wz,
      wx = 0.0,
      wy = 0.0,
      wz = 0.0,
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      wxy = 0.0,
      wxz = 0.0,
      wyz = 0.0,
      xyz = i,
      i = 0.0,
    )

  infix def antiDot(r: Pga3dMotor): Pga3dMotor =
    Pga3dMotor(
      s = (i * r.s + r.i * s),
      wx = (i * r.wx + r.i * wx),
      wy = (i * r.wy + r.i * wy),
      wz = (i * r.wz + r.i * wz),
      xy = (i * r.xy + r.i * xy - r.s * wz - r.wz * s),
      xz = (i * r.xz + r.i * xz + r.s * wy + r.wy * s),
      yz = (i * r.yz + r.i * yz - r.s * wx - r.wx * s),
      i = (i * r.i - r.wx * wx - r.wy * wy - r.wz * wz),
    )

  infix def antiDot(r: Pga3dPlane): Pga3dMultivector =
    Pga3dMultivector(
      s = 0.0,
      w = i * r.w,
      x = i * r.x,
      y = i * r.y,
      z = i * r.z,
      wx = 0.0,
      wy = 0.0,
      wz = 0.0,
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      wxy = r.w * wz,
      wxz = -r.w * wy,
      wyz = r.w * wx,
      xyz = (r.x * wx + r.y * wy + r.z * wz - r.w * s),
      i = 0.0,
    )

  infix def antiDot(r: Pga3dBivector): Pga3dMotor =
    Pga3dMotor(
      s = 0.0,
      wx = i * r.wx,
      wy = i * r.wy,
      wz = i * r.wz,
      xy = (i * r.xy - r.wz * s),
      xz = (i * r.xz + r.wy * s),
      yz = (i * r.yz - r.wx * s),
      i = (-r.wx * wx - r.wy * wy - r.wz * wz),
    )

  infix def antiDot(r: Pga3dProjectivePoint): Pga3dMultivector =
    Pga3dMultivector(
      s = 0.0,
      w = 0.0,
      x = -r.x * s,
      y = -r.y * s,
      z = -r.z * s,
      wx = 0.0,
      wy = 0.0,
      wz = 0.0,
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      wxy = (r.y * wx - i * r.z - r.x * wy),
      wxz = (i * r.y + r.z * wx - r.x * wz),
      wyz = (r.z * wy - i * r.x - r.y * wz),
      xyz = (i * r.w + r.x * yz + r.z * xy - r.y * xz),
      i = 0.0,
    )

  infix def antiDot(r: Pga3dRotor): Pga3dRotor =
    Pga3dRotor(
      s = i * r.s,
      xy = (i * r.xy - r.s * wz),
      xz = (i * r.xz + r.s * wy),
      yz = (i * r.yz - r.s * wx),
    )

  infix def antiDot(r: Pga3dProjectiveTranslator): Pga3dMotor =
    Pga3dMotor(
      s = i * r.s,
      wx = i * r.wx,
      wy = i * r.wy,
      wz = i * r.wz,
      xy = (-r.s * wz - r.wz * s),
      xz = (r.s * wy + r.wy * s),
      yz = (-r.s * wx - r.wx * s),
      i = (-r.wx * wx - r.wy * wy - r.wz * wz),
    )

  infix def antiDot(r: Pga3dTranslator): Pga3dMotor =
    Pga3dMotor(
      s = i,
      wx = i * r.wx,
      wy = i * r.wy,
      wz = i * r.wz,
      xy = (-wz - r.wz * s),
      xz = (wy + r.wy * s),
      yz = (-wx - r.wx * s),
      i = (-r.wx * wx - r.wy * wy - r.wz * wz),
    )

  infix def antiDot(r: Pga3dVector): Pga3dMultivector =
    Pga3dMultivector(
      s = 0.0,
      w = 0.0,
      x = -r.x * s,
      y = -r.y * s,
      z = -r.z * s,
      wx = 0.0,
      wy = 0.0,
      wz = 0.0,
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      wxy = (r.y * wx - i * r.z - r.x * wy),
      wxz = (i * r.y + r.z * wx - r.x * wz),
      wyz = (r.z * wy - i * r.x - r.y * wz),
      xyz = (r.x * yz + r.z * xy - r.y * xz),
      i = 0.0,
    )

  infix def antiDot(r: Pga3dPoint): Pga3dMultivector =
    Pga3dMultivector(
      s = 0.0,
      w = 0.0,
      x = -r.x * s,
      y = -r.y * s,
      z = -r.z * s,
      wx = 0.0,
      wy = 0.0,
      wz = 0.0,
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      wxy = (r.y * wx - i * r.z - r.x * wy),
      wxz = (i * r.y + r.z * wx - r.x * wz),
      wyz = (r.z * wy - i * r.x - r.y * wz),
      xyz = (i + r.x * yz + r.z * xy - r.y * xz),
      i = 0.0,
    )

  infix def antiDot(r: Pga3dPlaneCentral): Pga3dMultivector =
    Pga3dMultivector(
      s = 0.0,
      w = 0.0,
      x = i * r.x,
      y = i * r.y,
      z = i * r.z,
      wx = 0.0,
      wy = 0.0,
      wz = 0.0,
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      wxy = 0.0,
      wxz = 0.0,
      wyz = 0.0,
      xyz = (r.x * wx + r.y * wy + r.z * wz),
      i = 0.0,
    )

  infix def antiDot(r: Pga3dBivectorBulk): Pga3dBivectorBulk =
    Pga3dBivectorBulk(
      xy = i * r.xy,
      xz = i * r.xz,
      yz = i * r.yz,
    )

  infix def antiDot(r: Pga3dBivectorWeight): Pga3dMotor =
    Pga3dMotor(
      s = 0.0,
      wx = i * r.wx,
      wy = i * r.wy,
      wz = i * r.wz,
      xy = -r.wz * s,
      xz = r.wy * s,
      yz = -r.wx * s,
      i = (-r.wx * wx - r.wy * wy - r.wz * wz),
    )

  infix def antiDot(r: Pga3dPseudoScalar): Pga3dMotor =
    Pga3dMotor(
      s = r.i * s,
      wx = r.i * wx,
      wy = r.i * wy,
      wz = r.i * wz,
      xy = r.i * xy,
      xz = r.i * xz,
      yz = r.i * yz,
      i = i * r.i,
    )

  infix def antiDot(r: Pga3dPointCenter.type): Pga3dProjectivePoint =
    Pga3dProjectivePoint(
      x = 0.0,
      y = 0.0,
      z = 0.0,
      w = i,
    )

  infix def antiWedge(r: Pga3dMotor): Pga3dMotor =
    Pga3dMotor(
      s = (i * r.s + r.i * s + r.wx * yz + r.wz * xy + r.xy * wz + r.yz * wx - r.wy * xz - r.xz * wy),
      wx = (i * r.wx + r.i * wx),
      wy = (i * r.wy + r.i * wy),
      wz = (i * r.wz + r.i * wz),
      xy = (i * r.xy + r.i * xy),
      xz = (i * r.xz + r.i * xz),
      yz = (i * r.yz + r.i * yz),
      i = i * r.i,
    )

  inline infix def v(r: Pga3dMotor): Pga3dMotor = antiWedge(r)

  inline infix def join(r: Pga3dMotor): Pga3dMotor = antiWedge(r)

  infix def antiWedge(r: Pga3dPlane): Pga3dPlane =
    Pga3dPlane(
      x = i * r.x,
      y = i * r.y,
      z = i * r.z,
      w = i * r.w,
    )

  inline infix def v(r: Pga3dPlane): Pga3dPlane = antiWedge(r)

  inline infix def join(r: Pga3dPlane): Pga3dPlane = antiWedge(r)

  infix def antiWedge(r: Pga3dBivector): Pga3dMotor =
    Pga3dMotor(
      s = (r.wx * yz + r.wz * xy + r.xy * wz + r.yz * wx - r.wy * xz - r.xz * wy),
      wx = i * r.wx,
      wy = i * r.wy,
      wz = i * r.wz,
      xy = i * r.xy,
      xz = i * r.xz,
      yz = i * r.yz,
      i = 0.0,
    )

  inline infix def v(r: Pga3dBivector): Pga3dMotor = antiWedge(r)

  inline infix def join(r: Pga3dBivector): Pga3dMotor = antiWedge(r)

  infix def antiWedge(r: Pga3dProjectivePoint): Pga3dMultivector =
    Pga3dMultivector(
      s = 0.0,
      w = (r.x * wx + r.y * wy + r.z * wz),
      x = (r.y * xy + r.z * xz - r.w * wx),
      y = (r.z * yz - r.w * wy - r.x * xy),
      z = (-r.w * wz - r.x * xz - r.y * yz),
      wx = 0.0,
      wy = 0.0,
      wz = 0.0,
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      wxy = -i * r.z,
      wxz = i * r.y,
      wyz = -i * r.x,
      xyz = i * r.w,
      i = 0.0,
    )

  inline infix def v(r: Pga3dProjectivePoint): Pga3dMultivector = antiWedge(r)

  inline infix def join(r: Pga3dProjectivePoint): Pga3dMultivector = antiWedge(r)

  infix def antiWedge(r: Pga3dRotor): Pga3dRotor =
    Pga3dRotor(
      s = (i * r.s + r.xy * wz + r.yz * wx - r.xz * wy),
      xy = i * r.xy,
      xz = i * r.xz,
      yz = i * r.yz,
    )

  inline infix def v(r: Pga3dRotor): Pga3dRotor = antiWedge(r)

  inline infix def join(r: Pga3dRotor): Pga3dRotor = antiWedge(r)

  infix def antiWedge(r: Pga3dProjectiveTranslator): Pga3dProjectiveTranslator =
    Pga3dProjectiveTranslator(
      s = (i * r.s + r.wx * yz + r.wz * xy - r.wy * xz),
      wx = i * r.wx,
      wy = i * r.wy,
      wz = i * r.wz,
    )

  inline infix def v(r: Pga3dProjectiveTranslator): Pga3dProjectiveTranslator = antiWedge(r)

  inline infix def join(r: Pga3dProjectiveTranslator): Pga3dProjectiveTranslator = antiWedge(r)

  infix def antiWedge(r: Pga3dTranslator): Pga3dProjectiveTranslator =
    Pga3dProjectiveTranslator(
      s = (i + r.wx * yz + r.wz * xy - r.wy * xz),
      wx = i * r.wx,
      wy = i * r.wy,
      wz = i * r.wz,
    )

  inline infix def v(r: Pga3dTranslator): Pga3dProjectiveTranslator = antiWedge(r)

  inline infix def join(r: Pga3dTranslator): Pga3dProjectiveTranslator = antiWedge(r)

  infix def antiWedge(r: Pga3dVector): Pga3dMultivector =
    Pga3dMultivector(
      s = 0.0,
      w = (r.x * wx + r.y * wy + r.z * wz),
      x = (r.y * xy + r.z * xz),
      y = (r.z * yz - r.x * xy),
      z = (-r.x * xz - r.y * yz),
      wx = 0.0,
      wy = 0.0,
      wz = 0.0,
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      wxy = -i * r.z,
      wxz = i * r.y,
      wyz = -i * r.x,
      xyz = 0.0,
      i = 0.0,
    )

  inline infix def v(r: Pga3dVector): Pga3dMultivector = antiWedge(r)

  inline infix def join(r: Pga3dVector): Pga3dMultivector = antiWedge(r)

  infix def antiWedge(r: Pga3dPoint): Pga3dMultivector =
    Pga3dMultivector(
      s = 0.0,
      w = (r.x * wx + r.y * wy + r.z * wz),
      x = (-wx + r.y * xy + r.z * xz),
      y = (-wy + r.z * yz - r.x * xy),
      z = (-wz - r.x * xz - r.y * yz),
      wx = 0.0,
      wy = 0.0,
      wz = 0.0,
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      wxy = -i * r.z,
      wxz = i * r.y,
      wyz = -i * r.x,
      xyz = i,
      i = 0.0,
    )

  inline infix def v(r: Pga3dPoint): Pga3dMultivector = antiWedge(r)

  inline infix def join(r: Pga3dPoint): Pga3dMultivector = antiWedge(r)

  infix def antiWedge(r: Pga3dPlaneCentral): Pga3dPlaneCentral =
    Pga3dPlaneCentral(
      x = i * r.x,
      y = i * r.y,
      z = i * r.z,
    )

  inline infix def v(r: Pga3dPlaneCentral): Pga3dPlaneCentral = antiWedge(r)

  inline infix def join(r: Pga3dPlaneCentral): Pga3dPlaneCentral = antiWedge(r)

  infix def antiWedge(r: Pga3dBivectorBulk): Pga3dRotor =
    Pga3dRotor(
      s = (r.xy * wz + r.yz * wx - r.xz * wy),
      xy = i * r.xy,
      xz = i * r.xz,
      yz = i * r.yz,
    )

  inline infix def v(r: Pga3dBivectorBulk): Pga3dRotor = antiWedge(r)

  inline infix def join(r: Pga3dBivectorBulk): Pga3dRotor = antiWedge(r)

  infix def antiWedge(r: Pga3dBivectorWeight): Pga3dProjectiveTranslator =
    Pga3dProjectiveTranslator(
      s = (r.wx * yz + r.wz * xy - r.wy * xz),
      wx = i * r.wx,
      wy = i * r.wy,
      wz = i * r.wz,
    )

  inline infix def v(r: Pga3dBivectorWeight): Pga3dProjectiveTranslator = antiWedge(r)

  inline infix def join(r: Pga3dBivectorWeight): Pga3dProjectiveTranslator = antiWedge(r)

  infix def antiWedge(r: Pga3dPseudoScalar): Pga3dMotor =
    Pga3dMotor(
      s = r.i * s,
      wx = r.i * wx,
      wy = r.i * wy,
      wz = r.i * wz,
      xy = r.i * xy,
      xz = r.i * xz,
      yz = r.i * yz,
      i = i * r.i,
    )

  inline infix def v(r: Pga3dPseudoScalar): Pga3dMotor = antiWedge(r)

  inline infix def join(r: Pga3dPseudoScalar): Pga3dMotor = antiWedge(r)

  infix def antiWedge(r: Pga3dPointCenter.type): Pga3dMultivector =
    Pga3dMultivector(
      s = 0.0,
      w = 0.0,
      x = -wx,
      y = -wy,
      z = -wz,
      wx = 0.0,
      wy = 0.0,
      wz = 0.0,
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      wxy = 0.0,
      wxz = 0.0,
      wyz = 0.0,
      xyz = i,
      i = 0.0,
    )

  inline infix def v(r: Pga3dPointCenter.type): Pga3dMultivector = antiWedge(r)

  inline infix def join(r: Pga3dPointCenter.type): Pga3dMultivector = antiWedge(r)

  infix def sandwich(r: Pga3dMotor): Pga3dMotor =
    val sMs = s * s
    val sMwx = s * wx
    val sMwy = s * wy
    val sMwz = s * wz
    val sMxy = s * xy
    val sMxz = s * xz
    val sMyz = s * yz
    val sMi = i * s
    val wxMxy = wx * xy
    val wxMxz = wx * xz
    val wxMyz = wx * yz
    val wyMxy = wy * xy
    val wyMxz = wy * xz
    val wyMyz = wy * yz
    val wzMxy = wz * xy
    val wzMxz = wz * xz
    val wzMyz = wz * yz
    val xyMxy = xy * xy
    val xyMxz = xy * xz
    val xyMyz = xy * yz
    val xyMi = i * xy
    val xzMxz = xz * xz
    val xzMyz = xz * yz
    val xzMi = i * xz
    val yzMyz = yz * yz
    val yzMi = i * yz
    Pga3dMotor(
      s = r.s * (sMs + xyMxy + xzMxz + yzMyz),
      wx = (2.0 * (r.wy * (sMxy - xzMyz) + r.wz * (sMxz + xyMyz) + r.xy * (wxMxy + wzMyz - sMwy - xzMi) + r.xz * (wxMxz + xyMi - sMwz - wyMyz) + r.yz * (wxMyz + wyMxz - sMi - wzMxy)) + r.wx * (sMs + yzMyz - xyMxy - xzMxz)),
      wy = (2.0 * (r.wx * (-sMxy - xzMyz) + r.wz * (sMyz - xyMxz) + r.xy * (sMwx + wyMxy - wzMxz - yzMi) + r.xz * (sMi + wxMyz + wyMxz + wzMxy) + r.yz * (wyMyz + xyMi - sMwz - wxMxz)) + r.wy * (sMs + xzMxz - xyMxy - yzMyz)),
      wz = (2.0 * (r.wx * (xyMyz - sMxz) + r.wy * (-sMyz - xyMxz) + r.xy * (wyMxz + wzMxy - sMi - wxMyz) + r.xz * (sMwx + wzMxz - wyMxy - yzMi) + r.yz * (sMwy + wxMxy + wzMyz + xzMi)) + r.wz * (sMs + xyMxy - xzMxz - yzMyz)),
      xy = (2.0 * (r.xz * (sMyz + xyMxz) + r.yz * (xyMyz - sMxz)) + r.xy * (sMs + xyMxy - xzMxz - yzMyz)),
      xz = (2.0 * (r.xy * (xyMxz - sMyz) + r.yz * (sMxy + xzMyz)) + r.xz * (sMs + xzMxz - xyMxy - yzMyz)),
      yz = (2.0 * (r.xy * (sMxz + xyMyz) + r.xz * (xzMyz - sMxy)) + r.yz * (sMs + yzMyz - xyMxy - xzMxz)),
      i = (r.i * (sMs + xyMxy + xzMxz + yzMyz) + 2.0 * r.s * (sMi + wyMxz - wxMyz - wzMxy)),
    )

  infix def sandwich(r: Pga3dPlane): Pga3dPlane =
    val sMs = s * s
    val sMxy = s * xy
    val sMxz = s * xz
    val sMyz = s * yz
    val xyMxy = xy * xy
    val xyMxz = xy * xz
    val xyMyz = xy * yz
    val xzMxz = xz * xz
    val xzMyz = xz * yz
    val yzMyz = yz * yz
    Pga3dPlane(
      x = (2.0 * (r.y * (sMxy - xzMyz) + r.z * (sMxz + xyMyz)) + r.x * (sMs + yzMyz - xyMxy - xzMxz)),
      y = (2.0 * (r.x * (-sMxy - xzMyz) + r.z * (sMyz - xyMxz)) + r.y * (sMs + xzMxz - xyMxy - yzMyz)),
      z = (2.0 * (r.x * (xyMyz - sMxz) + r.y * (-sMyz - xyMxz)) + r.z * (sMs + xyMxy - xzMxz - yzMyz)),
      w = (2.0 * (r.x * (i * yz + s * wx - wy * xy - wz * xz) + r.y * (s * wy + wx * xy - i * xz - wz * yz) + r.z * (i * xy + s * wz + wx * xz + wy * yz)) + r.w * (sMs + xyMxy + xzMxz + yzMyz)),
    )

  infix def sandwich(r: Pga3dBivector): Pga3dBivector =
    val sMs = s * s
    val sMwx = s * wx
    val sMwy = s * wy
    val sMwz = s * wz
    val sMxy = s * xy
    val sMxz = s * xz
    val sMyz = s * yz
    val sMi = i * s
    val wxMxy = wx * xy
    val wxMxz = wx * xz
    val wxMyz = wx * yz
    val wyMxy = wy * xy
    val wyMxz = wy * xz
    val wyMyz = wy * yz
    val wzMxy = wz * xy
    val wzMxz = wz * xz
    val wzMyz = wz * yz
    val xyMxy = xy * xy
    val xyMxz = xy * xz
    val xyMyz = xy * yz
    val xyMi = i * xy
    val xzMxz = xz * xz
    val xzMyz = xz * yz
    val xzMi = i * xz
    val yzMyz = yz * yz
    val yzMi = i * yz
    Pga3dBivector(
      wx = (2.0 * (r.wy * (sMxy - xzMyz) + r.wz * (sMxz + xyMyz) + r.xy * (wxMxy + wzMyz - sMwy - xzMi) + r.xz * (wxMxz + xyMi - sMwz - wyMyz) + r.yz * (wxMyz + wyMxz - sMi - wzMxy)) + r.wx * (sMs + yzMyz - xyMxy - xzMxz)),
      wy = (2.0 * (r.wx * (-sMxy - xzMyz) + r.wz * (sMyz - xyMxz) + r.xy * (sMwx + wyMxy - wzMxz - yzMi) + r.xz * (sMi + wxMyz + wyMxz + wzMxy) + r.yz * (wyMyz + xyMi - sMwz - wxMxz)) + r.wy * (sMs + xzMxz - xyMxy - yzMyz)),
      wz = (2.0 * (r.wx * (xyMyz - sMxz) + r.wy * (-sMyz - xyMxz) + r.xy * (wyMxz + wzMxy - sMi - wxMyz) + r.xz * (sMwx + wzMxz - wyMxy - yzMi) + r.yz * (sMwy + wxMxy + wzMyz + xzMi)) + r.wz * (sMs + xyMxy - xzMxz - yzMyz)),
      xy = (2.0 * (r.xz * (sMyz + xyMxz) + r.yz * (xyMyz - sMxz)) + r.xy * (sMs + xyMxy - xzMxz - yzMyz)),
      xz = (2.0 * (r.xy * (xyMxz - sMyz) + r.yz * (sMxy + xzMyz)) + r.xz * (sMs + xzMxz - xyMxy - yzMyz)),
      yz = (2.0 * (r.xy * (sMxz + xyMyz) + r.xz * (xzMyz - sMxy)) + r.yz * (sMs + yzMyz - xyMxy - xzMxz)),
    )

  infix def sandwich(r: Pga3dProjectivePoint): Pga3dProjectivePoint =
    val sMs = s * s
    val sMxy = s * xy
    val sMxz = s * xz
    val sMyz = s * yz
    val xyMxy = xy * xy
    val xyMxz = xy * xz
    val xyMyz = xy * yz
    val xzMxz = xz * xz
    val xzMyz = xz * yz
    val yzMyz = yz * yz
    Pga3dProjectivePoint(
      x = (2.0 * (r.w * (-i * yz - s * wx - wy * xy - wz * xz) + r.y * (sMxy - xzMyz) + r.z * (sMxz + xyMyz)) + r.x * (sMs + yzMyz - xyMxy - xzMxz)),
      y = (2.0 * (r.w * (i * xz + wx * xy - s * wy - wz * yz) + r.x * (-sMxy - xzMyz) + r.z * (sMyz - xyMxz)) + r.y * (sMs + xzMxz - xyMxy - yzMyz)),
      z = (2.0 * (r.w * (wx * xz + wy * yz - i * xy - s * wz) + r.x * (xyMyz - sMxz) + r.y * (-sMyz - xyMxz)) + r.z * (sMs + xyMxy - xzMxz - yzMyz)),
      w = r.w * (sMs + xyMxy + xzMxz + yzMyz),
    )

  infix def sandwich(r: Pga3dRotor): Pga3dMotor =
    val sMs = s * s
    val sMwx = s * wx
    val sMwy = s * wy
    val sMwz = s * wz
    val sMxy = s * xy
    val sMxz = s * xz
    val sMyz = s * yz
    val sMi = i * s
    val wxMxy = wx * xy
    val wxMxz = wx * xz
    val wxMyz = wx * yz
    val wyMxy = wy * xy
    val wyMxz = wy * xz
    val wyMyz = wy * yz
    val wzMxy = wz * xy
    val wzMxz = wz * xz
    val wzMyz = wz * yz
    val xyMxy = xy * xy
    val xyMxz = xy * xz
    val xyMyz = xy * yz
    val xyMi = i * xy
    val xzMxz = xz * xz
    val xzMyz = xz * yz
    val xzMi = i * xz
    val yzMyz = yz * yz
    val yzMi = i * yz
    Pga3dMotor(
      s = r.s * (sMs + xyMxy + xzMxz + yzMyz),
      wx = 2.0 * (r.xy * (wxMxy + wzMyz - sMwy - xzMi) + r.xz * (wxMxz + xyMi - sMwz - wyMyz) + r.yz * (wxMyz + wyMxz - sMi - wzMxy)),
      wy = 2.0 * (r.xy * (sMwx + wyMxy - wzMxz - yzMi) + r.xz * (sMi + wxMyz + wyMxz + wzMxy) + r.yz * (wyMyz + xyMi - sMwz - wxMxz)),
      wz = 2.0 * (r.xy * (wyMxz + wzMxy - sMi - wxMyz) + r.xz * (sMwx + wzMxz - wyMxy - yzMi) + r.yz * (sMwy + wxMxy + wzMyz + xzMi)),
      xy = (2.0 * (r.xz * (sMyz + xyMxz) + r.yz * (xyMyz - sMxz)) + r.xy * (sMs + xyMxy - xzMxz - yzMyz)),
      xz = (2.0 * (r.xy * (xyMxz - sMyz) + r.yz * (sMxy + xzMyz)) + r.xz * (sMs + xzMxz - xyMxy - yzMyz)),
      yz = (2.0 * (r.xy * (sMxz + xyMyz) + r.xz * (xzMyz - sMxy)) + r.yz * (sMs + yzMyz - xyMxy - xzMxz)),
      i = 2.0 * r.s * (sMi + wyMxz - wxMyz - wzMxy),
    )

  infix def sandwich(r: Pga3dProjectiveTranslator): Pga3dMotor =
    val sMs = s * s
    val sMxy = s * xy
    val sMxz = s * xz
    val sMyz = s * yz
    val xyMxy = xy * xy
    val xyMxz = xy * xz
    val xyMyz = xy * yz
    val xzMxz = xz * xz
    val xzMyz = xz * yz
    val yzMyz = yz * yz
    Pga3dMotor(
      s = r.s * (sMs + xyMxy + xzMxz + yzMyz),
      wx = (2.0 * (r.wy * (sMxy - xzMyz) + r.wz * (sMxz + xyMyz)) + r.wx * (sMs + yzMyz - xyMxy - xzMxz)),
      wy = (2.0 * (r.wx * (-sMxy - xzMyz) + r.wz * (sMyz - xyMxz)) + r.wy * (sMs + xzMxz - xyMxy - yzMyz)),
      wz = (2.0 * (r.wx * (xyMyz - sMxz) + r.wy * (-sMyz - xyMxz)) + r.wz * (sMs + xyMxy - xzMxz - yzMyz)),
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      i = 2.0 * r.s * (i * s + wy * xz - wx * yz - wz * xy),
    )

  infix def sandwich(r: Pga3dTranslator): Pga3dMotor =
    val sMs = s * s
    val sMxy = s * xy
    val sMxz = s * xz
    val sMyz = s * yz
    val xyMxy = xy * xy
    val xyMxz = xy * xz
    val xyMyz = xy * yz
    val xzMxz = xz * xz
    val xzMyz = xz * yz
    val yzMyz = yz * yz
    Pga3dMotor(
      s = (sMs + xyMxy + xzMxz + yzMyz),
      wx = (2.0 * (r.wy * (sMxy - xzMyz) + r.wz * (sMxz + xyMyz)) + r.wx * (sMs + yzMyz - xyMxy - xzMxz)),
      wy = (2.0 * (r.wx * (-sMxy - xzMyz) + r.wz * (sMyz - xyMxz)) + r.wy * (sMs + xzMxz - xyMxy - yzMyz)),
      wz = (2.0 * (r.wx * (xyMyz - sMxz) + r.wy * (-sMyz - xyMxz)) + r.wz * (sMs + xyMxy - xzMxz - yzMyz)),
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      i = 2.0 * (i * s + wy * xz - wx * yz - wz * xy),
    )

  infix def sandwich(r: Pga3dVector): Pga3dVector =
    val sMs = s * s
    val sMxy = s * xy
    val sMxz = s * xz
    val sMyz = s * yz
    val xyMxy = xy * xy
    val xyMxz = xy * xz
    val xyMyz = xy * yz
    val xzMxz = xz * xz
    val xzMyz = xz * yz
    val yzMyz = yz * yz
    Pga3dVector(
      x = (2.0 * (r.y * (sMxy - xzMyz) + r.z * (sMxz + xyMyz)) + r.x * (sMs + yzMyz - xyMxy - xzMxz)),
      y = (2.0 * (r.x * (-sMxy - xzMyz) + r.z * (sMyz - xyMxz)) + r.y * (sMs + xzMxz - xyMxy - yzMyz)),
      z = (2.0 * (r.x * (xyMyz - sMxz) + r.y * (-sMyz - xyMxz)) + r.z * (sMs + xyMxy - xzMxz - yzMyz)),
    )

  infix def sandwich(r: Pga3dPoint): Pga3dProjectivePoint =
    val sMs = s * s
    val sMxy = s * xy
    val sMxz = s * xz
    val sMyz = s * yz
    val xyMxy = xy * xy
    val xyMxz = xy * xz
    val xyMyz = xy * yz
    val xzMxz = xz * xz
    val xzMyz = xz * yz
    val yzMyz = yz * yz
    Pga3dProjectivePoint(
      x = (2.0 * (r.y * (sMxy - xzMyz) + r.z * (sMxz + xyMyz) - i * yz - s * wx - wy * xy - wz * xz) + r.x * (sMs + yzMyz - xyMxy - xzMxz)),
      y = (2.0 * (i * xz + r.x * (-sMxy - xzMyz) + r.z * (sMyz - xyMxz) + wx * xy - s * wy - wz * yz) + r.y * (sMs + xzMxz - xyMxy - yzMyz)),
      z = (2.0 * (r.x * (xyMyz - sMxz) + r.y * (-sMyz - xyMxz) + wx * xz + wy * yz - i * xy - s * wz) + r.z * (sMs + xyMxy - xzMxz - yzMyz)),
      w = (sMs + xyMxy + xzMxz + yzMyz),
    )

  infix def sandwich(r: Pga3dPlaneCentral): Pga3dPlane =
    val sMs = s * s
    val sMxy = s * xy
    val sMxz = s * xz
    val sMyz = s * yz
    val xyMxy = xy * xy
    val xyMxz = xy * xz
    val xyMyz = xy * yz
    val xzMxz = xz * xz
    val xzMyz = xz * yz
    val yzMyz = yz * yz
    Pga3dPlane(
      x = (2.0 * (r.y * (sMxy - xzMyz) + r.z * (sMxz + xyMyz)) + r.x * (sMs + yzMyz - xyMxy - xzMxz)),
      y = (2.0 * (r.x * (-sMxy - xzMyz) + r.z * (sMyz - xyMxz)) + r.y * (sMs + xzMxz - xyMxy - yzMyz)),
      z = (2.0 * (r.x * (xyMyz - sMxz) + r.y * (-sMyz - xyMxz)) + r.z * (sMs + xyMxy - xzMxz - yzMyz)),
      w = 2.0 * (r.x * (i * yz + s * wx - wy * xy - wz * xz) + r.y * (s * wy + wx * xy - i * xz - wz * yz) + r.z * (i * xy + s * wz + wx * xz + wy * yz)),
    )

  infix def sandwich(r: Pga3dBivectorBulk): Pga3dBivector =
    val sMs = s * s
    val sMwx = s * wx
    val sMwy = s * wy
    val sMwz = s * wz
    val sMxy = s * xy
    val sMxz = s * xz
    val sMyz = s * yz
    val sMi = i * s
    val wxMxy = wx * xy
    val wxMxz = wx * xz
    val wxMyz = wx * yz
    val wyMxy = wy * xy
    val wyMxz = wy * xz
    val wyMyz = wy * yz
    val wzMxy = wz * xy
    val wzMxz = wz * xz
    val wzMyz = wz * yz
    val xyMxy = xy * xy
    val xyMxz = xy * xz
    val xyMyz = xy * yz
    val xyMi = i * xy
    val xzMxz = xz * xz
    val xzMyz = xz * yz
    val xzMi = i * xz
    val yzMyz = yz * yz
    val yzMi = i * yz
    Pga3dBivector(
      wx = 2.0 * (r.xy * (wxMxy + wzMyz - sMwy - xzMi) + r.xz * (wxMxz + xyMi - sMwz - wyMyz) + r.yz * (wxMyz + wyMxz - sMi - wzMxy)),
      wy = 2.0 * (r.xy * (sMwx + wyMxy - wzMxz - yzMi) + r.xz * (sMi + wxMyz + wyMxz + wzMxy) + r.yz * (wyMyz + xyMi - sMwz - wxMxz)),
      wz = 2.0 * (r.xy * (wyMxz + wzMxy - sMi - wxMyz) + r.xz * (sMwx + wzMxz - wyMxy - yzMi) + r.yz * (sMwy + wxMxy + wzMyz + xzMi)),
      xy = (2.0 * (r.xz * (sMyz + xyMxz) + r.yz * (xyMyz - sMxz)) + r.xy * (sMs + xyMxy - xzMxz - yzMyz)),
      xz = (2.0 * (r.xy * (xyMxz - sMyz) + r.yz * (sMxy + xzMyz)) + r.xz * (sMs + xzMxz - xyMxy - yzMyz)),
      yz = (2.0 * (r.xy * (sMxz + xyMyz) + r.xz * (xzMyz - sMxy)) + r.yz * (sMs + yzMyz - xyMxy - xzMxz)),
    )

  infix def sandwich(r: Pga3dBivectorWeight): Pga3dBivectorWeight =
    val sMs = s * s
    val sMxy = s * xy
    val sMxz = s * xz
    val sMyz = s * yz
    val xyMxy = xy * xy
    val xyMxz = xy * xz
    val xyMyz = xy * yz
    val xzMxz = xz * xz
    val xzMyz = xz * yz
    val yzMyz = yz * yz
    Pga3dBivectorWeight(
      wx = (2.0 * (r.wy * (sMxy - xzMyz) + r.wz * (sMxz + xyMyz)) + r.wx * (sMs + yzMyz - xyMxy - xzMxz)),
      wy = (2.0 * (r.wx * (-sMxy - xzMyz) + r.wz * (sMyz - xyMxz)) + r.wy * (sMs + xzMxz - xyMxy - yzMyz)),
      wz = (2.0 * (r.wx * (xyMyz - sMxz) + r.wy * (-sMyz - xyMxz)) + r.wz * (sMs + xyMxy - xzMxz - yzMyz)),
    )

  infix def sandwich(r: Pga3dPseudoScalar): Pga3dPseudoScalar =
    Pga3dPseudoScalar(
      i = r.i * (s * s + xy * xy + xz * xz + yz * yz),
    )

  infix def sandwich(r: Pga3dPointCenter.type): Pga3dProjectivePoint =
    Pga3dProjectivePoint(
      x = 2.0 * (-i * yz - s * wx - wy * xy - wz * xz),
      y = 2.0 * (i * xz + wx * xy - s * wy - wz * yz),
      z = 2.0 * (wx * xz + wy * yz - i * xy - s * wz),
      w = (s * s + xy * xy + xz * xz + yz * yz),
    )

  infix def reverseSandwich(r: Pga3dMotor): Pga3dMotor =
    val sMs = s * s
    val sMwx = s * wx
    val sMwy = s * wy
    val sMwz = s * wz
    val sMxy = s * xy
    val sMxz = s * xz
    val sMyz = s * yz
    val sMi = i * s
    val wxMxy = wx * xy
    val wxMxz = wx * xz
    val wxMyz = wx * yz
    val wyMxy = wy * xy
    val wyMxz = wy * xz
    val wyMyz = wy * yz
    val wzMxy = wz * xy
    val wzMxz = wz * xz
    val wzMyz = wz * yz
    val xyMxy = xy * xy
    val xyMxz = xy * xz
    val xyMyz = xy * yz
    val xyMi = i * xy
    val xzMxz = xz * xz
    val xzMyz = xz * yz
    val xzMi = i * xz
    val yzMyz = yz * yz
    val yzMi = i * yz
    Pga3dMotor(
      s = r.s * (sMs + xyMxy + xzMxz + yzMyz),
      wx = (2.0 * (r.wy * (-sMxy - xzMyz) + r.wz * (xyMyz - sMxz) + r.xy * (sMwy + wxMxy + wzMyz + xzMi) + r.xz * (sMwz + wxMxz - wyMyz - xyMi) + r.yz * (wxMyz + wyMxz - sMi - wzMxy)) + r.wx * (sMs + yzMyz - xyMxy - xzMxz)),
      wy = (2.0 * (r.wx * (sMxy - xzMyz) + r.wz * (-sMyz - xyMxz) + r.xy * (wyMxy + yzMi - sMwx - wzMxz) + r.xz * (sMi + wxMyz + wyMxz + wzMxy) + r.yz * (sMwz + wyMyz - wxMxz - xyMi)) + r.wy * (sMs + xzMxz - xyMxy - yzMyz)),
      wz = (2.0 * (r.wx * (sMxz + xyMyz) + r.wy * (sMyz - xyMxz) + r.xy * (wyMxz + wzMxy - sMi - wxMyz) + r.xz * (wzMxz + yzMi - sMwx - wyMxy) + r.yz * (wxMxy + wzMyz - sMwy - xzMi)) + r.wz * (sMs + xyMxy - xzMxz - yzMyz)),
      xy = (2.0 * (r.xz * (xyMxz - sMyz) + r.yz * (sMxz + xyMyz)) + r.xy * (sMs + xyMxy - xzMxz - yzMyz)),
      xz = (2.0 * (r.xy * (sMyz + xyMxz) + r.yz * (xzMyz - sMxy)) + r.xz * (sMs + xzMxz - xyMxy - yzMyz)),
      yz = (2.0 * (r.xy * (xyMyz - sMxz) + r.xz * (sMxy + xzMyz)) + r.yz * (sMs + yzMyz - xyMxy - xzMxz)),
      i = (r.i * (sMs + xyMxy + xzMxz + yzMyz) + 2.0 * r.s * (sMi + wyMxz - wxMyz - wzMxy)),
    )

  infix def reverseSandwich(r: Pga3dPlane): Pga3dPlane =
    val sMs = s * s
    val sMxy = s * xy
    val sMxz = s * xz
    val sMyz = s * yz
    val xyMxy = xy * xy
    val xyMxz = xy * xz
    val xyMyz = xy * yz
    val xzMxz = xz * xz
    val xzMyz = xz * yz
    val yzMyz = yz * yz
    Pga3dPlane(
      x = (2.0 * (r.y * (-sMxy - xzMyz) + r.z * (xyMyz - sMxz)) + r.x * (sMs + yzMyz - xyMxy - xzMxz)),
      y = (2.0 * (r.x * (sMxy - xzMyz) + r.z * (-sMyz - xyMxz)) + r.y * (sMs + xzMxz - xyMxy - yzMyz)),
      z = (2.0 * (r.x * (sMxz + xyMyz) + r.y * (sMyz - xyMxz)) + r.z * (sMs + xyMxy - xzMxz - yzMyz)),
      w = (2.0 * (r.x * (-i * yz - s * wx - wy * xy - wz * xz) + r.y * (i * xz + wx * xy - s * wy - wz * yz) + r.z * (wx * xz + wy * yz - i * xy - s * wz)) + r.w * (sMs + xyMxy + xzMxz + yzMyz)),
    )

  infix def reverseSandwich(r: Pga3dBivector): Pga3dBivector =
    val sMs = s * s
    val sMwx = s * wx
    val sMwy = s * wy
    val sMwz = s * wz
    val sMxy = s * xy
    val sMxz = s * xz
    val sMyz = s * yz
    val sMi = i * s
    val wxMxy = wx * xy
    val wxMxz = wx * xz
    val wxMyz = wx * yz
    val wyMxy = wy * xy
    val wyMxz = wy * xz
    val wyMyz = wy * yz
    val wzMxy = wz * xy
    val wzMxz = wz * xz
    val wzMyz = wz * yz
    val xyMxy = xy * xy
    val xyMxz = xy * xz
    val xyMyz = xy * yz
    val xyMi = i * xy
    val xzMxz = xz * xz
    val xzMyz = xz * yz
    val xzMi = i * xz
    val yzMyz = yz * yz
    val yzMi = i * yz
    Pga3dBivector(
      wx = (2.0 * (r.wy * (-sMxy - xzMyz) + r.wz * (xyMyz - sMxz) + r.xy * (sMwy + wxMxy + wzMyz + xzMi) + r.xz * (sMwz + wxMxz - wyMyz - xyMi) + r.yz * (wxMyz + wyMxz - sMi - wzMxy)) + r.wx * (sMs + yzMyz - xyMxy - xzMxz)),
      wy = (2.0 * (r.wx * (sMxy - xzMyz) + r.wz * (-sMyz - xyMxz) + r.xy * (wyMxy + yzMi - sMwx - wzMxz) + r.xz * (sMi + wxMyz + wyMxz + wzMxy) + r.yz * (sMwz + wyMyz - wxMxz - xyMi)) + r.wy * (sMs + xzMxz - xyMxy - yzMyz)),
      wz = (2.0 * (r.wx * (sMxz + xyMyz) + r.wy * (sMyz - xyMxz) + r.xy * (wyMxz + wzMxy - sMi - wxMyz) + r.xz * (wzMxz + yzMi - sMwx - wyMxy) + r.yz * (wxMxy + wzMyz - sMwy - xzMi)) + r.wz * (sMs + xyMxy - xzMxz - yzMyz)),
      xy = (2.0 * (r.xz * (xyMxz - sMyz) + r.yz * (sMxz + xyMyz)) + r.xy * (sMs + xyMxy - xzMxz - yzMyz)),
      xz = (2.0 * (r.xy * (sMyz + xyMxz) + r.yz * (xzMyz - sMxy)) + r.xz * (sMs + xzMxz - xyMxy - yzMyz)),
      yz = (2.0 * (r.xy * (xyMyz - sMxz) + r.xz * (sMxy + xzMyz)) + r.yz * (sMs + yzMyz - xyMxy - xzMxz)),
    )

  infix def reverseSandwich(r: Pga3dProjectivePoint): Pga3dProjectivePoint =
    val sMs = s * s
    val sMxy = s * xy
    val sMxz = s * xz
    val sMyz = s * yz
    val xyMxy = xy * xy
    val xyMxz = xy * xz
    val xyMyz = xy * yz
    val xzMxz = xz * xz
    val xzMyz = xz * yz
    val yzMyz = yz * yz
    Pga3dProjectivePoint(
      x = (2.0 * (r.w * (i * yz + s * wx - wy * xy - wz * xz) + r.y * (-sMxy - xzMyz) + r.z * (xyMyz - sMxz)) + r.x * (sMs + yzMyz - xyMxy - xzMxz)),
      y = (2.0 * (r.w * (s * wy + wx * xy - i * xz - wz * yz) + r.x * (sMxy - xzMyz) + r.z * (-sMyz - xyMxz)) + r.y * (sMs + xzMxz - xyMxy - yzMyz)),
      z = (2.0 * (r.w * (i * xy + s * wz + wx * xz + wy * yz) + r.x * (sMxz + xyMyz) + r.y * (sMyz - xyMxz)) + r.z * (sMs + xyMxy - xzMxz - yzMyz)),
      w = r.w * (sMs + xyMxy + xzMxz + yzMyz),
    )

  infix def reverseSandwich(r: Pga3dRotor): Pga3dMotor =
    val sMs = s * s
    val sMwx = s * wx
    val sMwy = s * wy
    val sMwz = s * wz
    val sMxy = s * xy
    val sMxz = s * xz
    val sMyz = s * yz
    val sMi = i * s
    val wxMxy = wx * xy
    val wxMxz = wx * xz
    val wxMyz = wx * yz
    val wyMxy = wy * xy
    val wyMxz = wy * xz
    val wyMyz = wy * yz
    val wzMxy = wz * xy
    val wzMxz = wz * xz
    val wzMyz = wz * yz
    val xyMxy = xy * xy
    val xyMxz = xy * xz
    val xyMyz = xy * yz
    val xyMi = i * xy
    val xzMxz = xz * xz
    val xzMyz = xz * yz
    val xzMi = i * xz
    val yzMyz = yz * yz
    val yzMi = i * yz
    Pga3dMotor(
      s = r.s * (sMs + xyMxy + xzMxz + yzMyz),
      wx = 2.0 * (r.xy * (sMwy + wxMxy + wzMyz + xzMi) + r.xz * (sMwz + wxMxz - wyMyz - xyMi) + r.yz * (wxMyz + wyMxz - sMi - wzMxy)),
      wy = 2.0 * (r.xy * (wyMxy + yzMi - sMwx - wzMxz) + r.xz * (sMi + wxMyz + wyMxz + wzMxy) + r.yz * (sMwz + wyMyz - wxMxz - xyMi)),
      wz = 2.0 * (r.xy * (wyMxz + wzMxy - sMi - wxMyz) + r.xz * (wzMxz + yzMi - sMwx - wyMxy) + r.yz * (wxMxy + wzMyz - sMwy - xzMi)),
      xy = (2.0 * (r.xz * (xyMxz - sMyz) + r.yz * (sMxz + xyMyz)) + r.xy * (sMs + xyMxy - xzMxz - yzMyz)),
      xz = (2.0 * (r.xy * (sMyz + xyMxz) + r.yz * (xzMyz - sMxy)) + r.xz * (sMs + xzMxz - xyMxy - yzMyz)),
      yz = (2.0 * (r.xy * (xyMyz - sMxz) + r.xz * (sMxy + xzMyz)) + r.yz * (sMs + yzMyz - xyMxy - xzMxz)),
      i = 2.0 * r.s * (sMi + wyMxz - wxMyz - wzMxy),
    )

  infix def reverseSandwich(r: Pga3dProjectiveTranslator): Pga3dMotor =
    val sMs = s * s
    val sMxy = s * xy
    val sMxz = s * xz
    val sMyz = s * yz
    val xyMxy = xy * xy
    val xyMxz = xy * xz
    val xyMyz = xy * yz
    val xzMxz = xz * xz
    val xzMyz = xz * yz
    val yzMyz = yz * yz
    Pga3dMotor(
      s = r.s * (sMs + xyMxy + xzMxz + yzMyz),
      wx = (2.0 * (r.wy * (-sMxy - xzMyz) + r.wz * (xyMyz - sMxz)) + r.wx * (sMs + yzMyz - xyMxy - xzMxz)),
      wy = (2.0 * (r.wx * (sMxy - xzMyz) + r.wz * (-sMyz - xyMxz)) + r.wy * (sMs + xzMxz - xyMxy - yzMyz)),
      wz = (2.0 * (r.wx * (sMxz + xyMyz) + r.wy * (sMyz - xyMxz)) + r.wz * (sMs + xyMxy - xzMxz - yzMyz)),
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      i = 2.0 * r.s * (i * s + wy * xz - wx * yz - wz * xy),
    )

  infix def reverseSandwich(r: Pga3dTranslator): Pga3dMotor =
    val sMs = s * s
    val sMxy = s * xy
    val sMxz = s * xz
    val sMyz = s * yz
    val xyMxy = xy * xy
    val xyMxz = xy * xz
    val xyMyz = xy * yz
    val xzMxz = xz * xz
    val xzMyz = xz * yz
    val yzMyz = yz * yz
    Pga3dMotor(
      s = (sMs + xyMxy + xzMxz + yzMyz),
      wx = (2.0 * (r.wy * (-sMxy - xzMyz) + r.wz * (xyMyz - sMxz)) + r.wx * (sMs + yzMyz - xyMxy - xzMxz)),
      wy = (2.0 * (r.wx * (sMxy - xzMyz) + r.wz * (-sMyz - xyMxz)) + r.wy * (sMs + xzMxz - xyMxy - yzMyz)),
      wz = (2.0 * (r.wx * (sMxz + xyMyz) + r.wy * (sMyz - xyMxz)) + r.wz * (sMs + xyMxy - xzMxz - yzMyz)),
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      i = 2.0 * (i * s + wy * xz - wx * yz - wz * xy),
    )

  infix def reverseSandwich(r: Pga3dVector): Pga3dVector =
    val sMs = s * s
    val sMxy = s * xy
    val sMxz = s * xz
    val sMyz = s * yz
    val xyMxy = xy * xy
    val xyMxz = xy * xz
    val xyMyz = xy * yz
    val xzMxz = xz * xz
    val xzMyz = xz * yz
    val yzMyz = yz * yz
    Pga3dVector(
      x = (2.0 * (r.y * (-sMxy - xzMyz) + r.z * (xyMyz - sMxz)) + r.x * (sMs + yzMyz - xyMxy - xzMxz)),
      y = (2.0 * (r.x * (sMxy - xzMyz) + r.z * (-sMyz - xyMxz)) + r.y * (sMs + xzMxz - xyMxy - yzMyz)),
      z = (2.0 * (r.x * (sMxz + xyMyz) + r.y * (sMyz - xyMxz)) + r.z * (sMs + xyMxy - xzMxz - yzMyz)),
    )

  infix def reverseSandwich(r: Pga3dPoint): Pga3dProjectivePoint =
    val sMs = s * s
    val sMxy = s * xy
    val sMxz = s * xz
    val sMyz = s * yz
    val xyMxy = xy * xy
    val xyMxz = xy * xz
    val xyMyz = xy * yz
    val xzMxz = xz * xz
    val xzMyz = xz * yz
    val yzMyz = yz * yz
    Pga3dProjectivePoint(
      x = (2.0 * (i * yz + r.y * (-sMxy - xzMyz) + r.z * (xyMyz - sMxz) + s * wx - wy * xy - wz * xz) + r.x * (sMs + yzMyz - xyMxy - xzMxz)),
      y = (2.0 * (r.x * (sMxy - xzMyz) + r.z * (-sMyz - xyMxz) + s * wy + wx * xy - i * xz - wz * yz) + r.y * (sMs + xzMxz - xyMxy - yzMyz)),
      z = (2.0 * (i * xy + r.x * (sMxz + xyMyz) + r.y * (sMyz - xyMxz) + s * wz + wx * xz + wy * yz) + r.z * (sMs + xyMxy - xzMxz - yzMyz)),
      w = (sMs + xyMxy + xzMxz + yzMyz),
    )

  infix def reverseSandwich(r: Pga3dPlaneCentral): Pga3dPlane =
    val sMs = s * s
    val sMxy = s * xy
    val sMxz = s * xz
    val sMyz = s * yz
    val xyMxy = xy * xy
    val xyMxz = xy * xz
    val xyMyz = xy * yz
    val xzMxz = xz * xz
    val xzMyz = xz * yz
    val yzMyz = yz * yz
    Pga3dPlane(
      x = (2.0 * (r.y * (-sMxy - xzMyz) + r.z * (xyMyz - sMxz)) + r.x * (sMs + yzMyz - xyMxy - xzMxz)),
      y = (2.0 * (r.x * (sMxy - xzMyz) + r.z * (-sMyz - xyMxz)) + r.y * (sMs + xzMxz - xyMxy - yzMyz)),
      z = (2.0 * (r.x * (sMxz + xyMyz) + r.y * (sMyz - xyMxz)) + r.z * (sMs + xyMxy - xzMxz - yzMyz)),
      w = 2.0 * (r.x * (-i * yz - s * wx - wy * xy - wz * xz) + r.y * (i * xz + wx * xy - s * wy - wz * yz) + r.z * (wx * xz + wy * yz - i * xy - s * wz)),
    )

  infix def reverseSandwich(r: Pga3dBivectorBulk): Pga3dBivector =
    val sMs = s * s
    val sMwx = s * wx
    val sMwy = s * wy
    val sMwz = s * wz
    val sMxy = s * xy
    val sMxz = s * xz
    val sMyz = s * yz
    val sMi = i * s
    val wxMxy = wx * xy
    val wxMxz = wx * xz
    val wxMyz = wx * yz
    val wyMxy = wy * xy
    val wyMxz = wy * xz
    val wyMyz = wy * yz
    val wzMxy = wz * xy
    val wzMxz = wz * xz
    val wzMyz = wz * yz
    val xyMxy = xy * xy
    val xyMxz = xy * xz
    val xyMyz = xy * yz
    val xyMi = i * xy
    val xzMxz = xz * xz
    val xzMyz = xz * yz
    val xzMi = i * xz
    val yzMyz = yz * yz
    val yzMi = i * yz
    Pga3dBivector(
      wx = 2.0 * (r.xy * (sMwy + wxMxy + wzMyz + xzMi) + r.xz * (sMwz + wxMxz - wyMyz - xyMi) + r.yz * (wxMyz + wyMxz - sMi - wzMxy)),
      wy = 2.0 * (r.xy * (wyMxy + yzMi - sMwx - wzMxz) + r.xz * (sMi + wxMyz + wyMxz + wzMxy) + r.yz * (sMwz + wyMyz - wxMxz - xyMi)),
      wz = 2.0 * (r.xy * (wyMxz + wzMxy - sMi - wxMyz) + r.xz * (wzMxz + yzMi - sMwx - wyMxy) + r.yz * (wxMxy + wzMyz - sMwy - xzMi)),
      xy = (2.0 * (r.xz * (xyMxz - sMyz) + r.yz * (sMxz + xyMyz)) + r.xy * (sMs + xyMxy - xzMxz - yzMyz)),
      xz = (2.0 * (r.xy * (sMyz + xyMxz) + r.yz * (xzMyz - sMxy)) + r.xz * (sMs + xzMxz - xyMxy - yzMyz)),
      yz = (2.0 * (r.xy * (xyMyz - sMxz) + r.xz * (sMxy + xzMyz)) + r.yz * (sMs + yzMyz - xyMxy - xzMxz)),
    )

  infix def reverseSandwich(r: Pga3dBivectorWeight): Pga3dBivectorWeight =
    val sMs = s * s
    val sMxy = s * xy
    val sMxz = s * xz
    val sMyz = s * yz
    val xyMxy = xy * xy
    val xyMxz = xy * xz
    val xyMyz = xy * yz
    val xzMxz = xz * xz
    val xzMyz = xz * yz
    val yzMyz = yz * yz
    Pga3dBivectorWeight(
      wx = (2.0 * (r.wy * (-sMxy - xzMyz) + r.wz * (xyMyz - sMxz)) + r.wx * (sMs + yzMyz - xyMxy - xzMxz)),
      wy = (2.0 * (r.wx * (sMxy - xzMyz) + r.wz * (-sMyz - xyMxz)) + r.wy * (sMs + xzMxz - xyMxy - yzMyz)),
      wz = (2.0 * (r.wx * (sMxz + xyMyz) + r.wy * (sMyz - xyMxz)) + r.wz * (sMs + xyMxy - xzMxz - yzMyz)),
    )

  infix def reverseSandwich(r: Pga3dPseudoScalar): Pga3dPseudoScalar =
    Pga3dPseudoScalar(
      i = r.i * (s * s + xy * xy + xz * xz + yz * yz),
    )

  infix def reverseSandwich(r: Pga3dPointCenter.type): Pga3dProjectivePoint =
    Pga3dProjectivePoint(
      x = 2.0 * (i * yz + s * wx - wy * xy - wz * xz),
      y = 2.0 * (s * wy + wx * xy - i * xz - wz * yz),
      z = 2.0 * (i * xy + s * wz + wx * xz + wy * yz),
      w = (s * s + xy * xy + xz * xz + yz * yz),
    )

  infix def cross(r: Pga3dMotor): Pga3dBivector =
    Pga3dBivector(
      wx = ((r.wy * xy - r.xy * wy) + (r.wz * xz - r.xz * wz)),
      wy = ((r.wz * yz - r.yz * wz) + (r.xy * wx - r.wx * xy)),
      wz = ((r.xz * wx - r.wx * xz) + (r.yz * wy - r.wy * yz)),
      xy = (r.xz * yz - r.yz * xz),
      xz = (r.yz * xy - r.xy * yz),
      yz = (r.xy * xz - r.xz * xy),
    )

  infix def cross(r: Pga3dPlane): Pga3dMultivector =
    Pga3dMultivector(
      s = 0.0,
      w = (r.x * wx + r.y * wy + r.z * wz),
      x = (r.y * xy + r.z * xz),
      y = (r.z * yz - r.x * xy),
      z = (-r.x * xz - r.y * yz),
      wx = 0.0,
      wy = 0.0,
      wz = 0.0,
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      wxy = i * r.z,
      wxz = -i * r.y,
      wyz = i * r.x,
      xyz = 0.0,
      i = 0.0,
    )

  infix def cross(r: Pga3dBivector): Pga3dBivector =
    Pga3dBivector(
      wx = ((r.wy * xy - r.xy * wy) + (r.wz * xz - r.xz * wz)),
      wy = ((r.wz * yz - r.yz * wz) + (r.xy * wx - r.wx * xy)),
      wz = ((r.xz * wx - r.wx * xz) + (r.yz * wy - r.wy * yz)),
      xy = (r.xz * yz - r.yz * xz),
      xz = (r.yz * xy - r.xy * yz),
      yz = (r.xy * xz - r.xz * xy),
    )

  infix def cross(r: Pga3dProjectivePoint): Pga3dMultivector =
    Pga3dMultivector(
      s = 0.0,
      w = -i * r.w,
      x = 0.0,
      y = 0.0,
      z = 0.0,
      wx = 0.0,
      wy = 0.0,
      wz = 0.0,
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      wxy = (r.w * wz + r.x * xz + r.y * yz),
      wxz = (r.z * yz - r.w * wy - r.x * xy),
      wyz = (r.w * wx - r.y * xy - r.z * xz),
      xyz = 0.0,
      i = 0.0,
    )

  infix def cross(r: Pga3dRotor): Pga3dBivector =
    Pga3dBivector(
      wx = (-r.xy * wy - r.xz * wz),
      wy = (r.xy * wx - r.yz * wz),
      wz = (r.xz * wx + r.yz * wy),
      xy = (r.xz * yz - r.yz * xz),
      xz = (r.yz * xy - r.xy * yz),
      yz = (r.xy * xz - r.xz * xy),
    )

  infix def cross(r: Pga3dProjectiveTranslator): Pga3dBivectorWeight =
    Pga3dBivectorWeight(
      wx = (r.wy * xy + r.wz * xz),
      wy = (r.wz * yz - r.wx * xy),
      wz = (-r.wx * xz - r.wy * yz),
    )

  infix def cross(r: Pga3dTranslator): Pga3dBivectorWeight =
    Pga3dBivectorWeight(
      wx = (r.wy * xy + r.wz * xz),
      wy = (r.wz * yz - r.wx * xy),
      wz = (-r.wx * xz - r.wy * yz),
    )

  infix def cross(r: Pga3dVector): Pga3dVector =
    Pga3dVector(
      x = (r.y * xy + r.z * xz),
      y = (r.z * yz - r.x * xy),
      z = (-r.x * xz - r.y * yz),
    )

  infix def cross(r: Pga3dPoint): Pga3dMultivector =
    Pga3dMultivector(
      s = 0.0,
      w = -i,
      x = 0.0,
      y = 0.0,
      z = 0.0,
      wx = 0.0,
      wy = 0.0,
      wz = 0.0,
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      wxy = (wz + r.x * xz + r.y * yz),
      wxz = (-wy + r.z * yz - r.x * xy),
      wyz = (wx - r.y * xy - r.z * xz),
      xyz = 0.0,
      i = 0.0,
    )

  infix def cross(r: Pga3dPlaneCentral): Pga3dMultivector =
    Pga3dMultivector(
      s = 0.0,
      w = (r.x * wx + r.y * wy + r.z * wz),
      x = (r.y * xy + r.z * xz),
      y = (r.z * yz - r.x * xy),
      z = (-r.x * xz - r.y * yz),
      wx = 0.0,
      wy = 0.0,
      wz = 0.0,
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      wxy = i * r.z,
      wxz = -i * r.y,
      wyz = i * r.x,
      xyz = 0.0,
      i = 0.0,
    )

  infix def cross(r: Pga3dBivectorBulk): Pga3dBivector =
    Pga3dBivector(
      wx = (-r.xy * wy - r.xz * wz),
      wy = (r.xy * wx - r.yz * wz),
      wz = (r.xz * wx + r.yz * wy),
      xy = (r.xz * yz - r.yz * xz),
      xz = (r.yz * xy - r.xy * yz),
      yz = (r.xy * xz - r.xz * xy),
    )

  infix def cross(r: Pga3dBivectorWeight): Pga3dBivectorWeight =
    Pga3dBivectorWeight(
      wx = (r.wy * xy + r.wz * xz),
      wy = (r.wz * yz - r.wx * xy),
      wz = (-r.wx * xz - r.wy * yz),
    )

  infix def cross(r: Pga3dPointCenter.type): Pga3dMultivector =
    Pga3dMultivector(
      s = 0.0,
      w = -i,
      x = 0.0,
      y = 0.0,
      z = 0.0,
      wx = 0.0,
      wy = 0.0,
      wz = 0.0,
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      wxy = wz,
      wxz = -wy,
      wyz = wx,
      xyz = 0.0,
      i = 0.0,
    )


object Pga3dMotor:

  inline val componentsCount = 8

  val zero: Pga3dMotor = Pga3dMotor(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0)

  val id: Pga3dMotor = Pga3dMotor(1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0)

  def addVector(v: Pga3dVector): Pga3dMotor = Pga3dTranslator.addVector(v).toMotor