package me.kright.gametools.pga3d

import me.kright.gametools.flatarray.FlatDoubleSerializer
import me.kright.gametools.mathutil.CanEqualWithEps

/**
 * A cached form of a motor: the sandwich and reverseSandwich products expressed as precomputed matrices.
 *
 * Prefer this class over motor.sandwich whenever the same motor is applied to many objects -
 * moving all the points of a body, transforming forces and velocities in a physics solver step, etc.
 * Building the transform costs about as much as a single motor sandwich, and after that every
 * application is a plain matrix multiplication, several times cheaper than motor.sandwich,
 * which recomputes the coefficients on every call.
 *
 * The class is immutable, like the Pga3dMotor it is built around.
 *
 * Cached values:
 *  - r00..r22: the 3x3 rotation matrix of the motor (scaled by motor.normSquare for non-normalized motors),
 *    used for the euclidean part of any object; the reverse transformation uses its transpose.
 *  - d00..d22: the dual (moment) 3x3 block for bivectors, which mixes the bulk part into the weight part;
 *    the reverse block is expressed through the same coefficients.
 *  - tx, ty, tz and txRev, tyRev, tzRev: translation for points, forward and reverse.
 *  - normSquare and normSquareI: the Study number motor * motor.reverse (normSquareI = 0
 *    for normalized motors).
 *
 * The results are equivalent to motor.sandwich(r) / motor.reverseSandwich(r) up to floating point
 * rounding for any motor, normalized or not.
 *
 * Generated by pgaNdCodeGen (me.kright.gametools.pga.codegen.scalagen.pga3d.runScalaCodeGen).
 * Do not edit by hand: change the generator and re-run it.
 */
final case class Pga3dTransform(motor: Pga3dMotor,
                                r00: Double, r01: Double, r02: Double,
                                r10: Double, r11: Double, r12: Double,
                                r20: Double, r21: Double, r22: Double,

                                d00: Double, d01: Double, d02: Double,
                                d10: Double, d11: Double, d12: Double,
                                d20: Double, d21: Double, d22: Double,

                                normSquare: Double,
                                normSquareI: Double,

                                tx: Double, ty: Double, tz: Double,
                                txRev: Double, tyRev: Double, tzRev: Double) derives CanEqual, CanEqualWithEps, FlatDoubleSerializer:

  override def toString: String =
    s"Pga3dTransform($motor)"

  infix def sandwich(r: Pga3dMotor): Pga3dMotor =
    Pga3dMotor(
      s = normSquare * r.s,
      wx = (d00 * r.xy + d01 * r.xz + d02 * r.yz + r.wx * r00 + r.wy * r01 + r.wz * r02),
      wy = (d10 * r.xy + d11 * r.xz + d12 * r.yz + r.wx * r10 + r.wy * r11 + r.wz * r12),
      wz = (d20 * r.xy + d21 * r.xz + d22 * r.yz + r.wx * r20 + r.wy * r21 + r.wz * r22),
      xy = (r.xy * r22 + r.yz * r20 - r.xz * r21),
      xz = (r.xz * r11 - r.xy * r12 - r.yz * r10),
      yz = (r.xy * r02 + r.yz * r00 - r.xz * r01),
      i = (normSquare * r.i + normSquareI * r.s),
    )

  infix def reverseSandwich(r: Pga3dMotor): Pga3dMotor =
    Pga3dMotor(
      s = normSquare * r.s,
      wx = (d02 * r.yz + d22 * r.xy + r.wx * r00 + r.wy * r10 + r.wz * r20 - d12 * r.xz),
      wy = (d11 * r.xz + r.wx * r01 + r.wy * r11 + r.wz * r21 - d01 * r.yz - d21 * r.xy),
      wz = (d00 * r.yz + d20 * r.xy + r.wx * r02 + r.wy * r12 + r.wz * r22 - d10 * r.xz),
      xy = (r.xy * r22 + r.yz * r02 - r.xz * r12),
      xz = (r.xz * r11 - r.xy * r21 - r.yz * r01),
      yz = (r.xy * r20 + r.yz * r00 - r.xz * r10),
      i = (normSquare * r.i + normSquareI * r.s),
    )

  infix def sandwich(r: Pga3dPlane): Pga3dPlane =
    Pga3dPlane(
      x = (r.x * r00 + r.y * r01 + r.z * r02),
      y = (r.x * r10 + r.y * r11 + r.z * r12),
      z = (r.x * r20 + r.y * r21 + r.z * r22),
      w = (normSquare * r.w + r.x * txRev + r.y * tyRev + r.z * tzRev),
    )

  infix def reverseSandwich(r: Pga3dPlane): Pga3dPlane =
    Pga3dPlane(
      x = (r.x * r00 + r.y * r10 + r.z * r20),
      y = (r.x * r01 + r.y * r11 + r.z * r21),
      z = (r.x * r02 + r.y * r12 + r.z * r22),
      w = (normSquare * r.w + r.x * tx + r.y * ty + r.z * tz),
    )

  infix def sandwich(r: Pga3dBivector): Pga3dBivector =
    Pga3dBivector(
      wx = (d00 * r.xy + d01 * r.xz + d02 * r.yz + r.wx * r00 + r.wy * r01 + r.wz * r02),
      wy = (d10 * r.xy + d11 * r.xz + d12 * r.yz + r.wx * r10 + r.wy * r11 + r.wz * r12),
      wz = (d20 * r.xy + d21 * r.xz + d22 * r.yz + r.wx * r20 + r.wy * r21 + r.wz * r22),
      xy = (r.xy * r22 + r.yz * r20 - r.xz * r21),
      xz = (r.xz * r11 - r.xy * r12 - r.yz * r10),
      yz = (r.xy * r02 + r.yz * r00 - r.xz * r01),
    )

  infix def reverseSandwich(r: Pga3dBivector): Pga3dBivector =
    Pga3dBivector(
      wx = (d02 * r.yz + d22 * r.xy + r.wx * r00 + r.wy * r10 + r.wz * r20 - d12 * r.xz),
      wy = (d11 * r.xz + r.wx * r01 + r.wy * r11 + r.wz * r21 - d01 * r.yz - d21 * r.xy),
      wz = (d00 * r.yz + d20 * r.xy + r.wx * r02 + r.wy * r12 + r.wz * r22 - d10 * r.xz),
      xy = (r.xy * r22 + r.yz * r02 - r.xz * r12),
      xz = (r.xz * r11 - r.xy * r21 - r.yz * r01),
      yz = (r.xy * r20 + r.yz * r00 - r.xz * r10),
    )

  infix def sandwich(r: Pga3dProjectivePoint): Pga3dProjectivePoint =
    Pga3dProjectivePoint(
      x = (r.w * tx + r.x * r00 + r.y * r01 + r.z * r02),
      y = (r.w * ty + r.x * r10 + r.y * r11 + r.z * r12),
      z = (r.w * tz + r.x * r20 + r.y * r21 + r.z * r22),
      w = normSquare * r.w,
    )

  infix def reverseSandwich(r: Pga3dProjectivePoint): Pga3dProjectivePoint =
    Pga3dProjectivePoint(
      x = (r.w * txRev + r.x * r00 + r.y * r10 + r.z * r20),
      y = (r.w * tyRev + r.x * r01 + r.y * r11 + r.z * r21),
      z = (r.w * tzRev + r.x * r02 + r.y * r12 + r.z * r22),
      w = normSquare * r.w,
    )

  infix def sandwich(r: Pga3dRotor): Pga3dMotor =
    Pga3dMotor(
      s = normSquare * r.s,
      wx = (d00 * r.xy + d01 * r.xz + d02 * r.yz),
      wy = (d10 * r.xy + d11 * r.xz + d12 * r.yz),
      wz = (d20 * r.xy + d21 * r.xz + d22 * r.yz),
      xy = (r.xy * r22 + r.yz * r20 - r.xz * r21),
      xz = (r.xz * r11 - r.xy * r12 - r.yz * r10),
      yz = (r.xy * r02 + r.yz * r00 - r.xz * r01),
      i = normSquareI * r.s,
    )

  infix def reverseSandwich(r: Pga3dRotor): Pga3dMotor =
    Pga3dMotor(
      s = normSquare * r.s,
      wx = (d02 * r.yz + d22 * r.xy - d12 * r.xz),
      wy = (d11 * r.xz - d01 * r.yz - d21 * r.xy),
      wz = (d00 * r.yz + d20 * r.xy - d10 * r.xz),
      xy = (r.xy * r22 + r.yz * r02 - r.xz * r12),
      xz = (r.xz * r11 - r.xy * r21 - r.yz * r01),
      yz = (r.xy * r20 + r.yz * r00 - r.xz * r10),
      i = normSquareI * r.s,
    )

  infix def sandwich(r: Pga3dProjectiveTranslator): Pga3dMotor =
    Pga3dMotor(
      s = normSquare * r.s,
      wx = (r.wx * r00 + r.wy * r01 + r.wz * r02),
      wy = (r.wx * r10 + r.wy * r11 + r.wz * r12),
      wz = (r.wx * r20 + r.wy * r21 + r.wz * r22),
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      i = normSquareI * r.s,
    )

  infix def reverseSandwich(r: Pga3dProjectiveTranslator): Pga3dMotor =
    Pga3dMotor(
      s = normSquare * r.s,
      wx = (r.wx * r00 + r.wy * r10 + r.wz * r20),
      wy = (r.wx * r01 + r.wy * r11 + r.wz * r21),
      wz = (r.wx * r02 + r.wy * r12 + r.wz * r22),
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      i = normSquareI * r.s,
    )

  infix def sandwich(r: Pga3dTranslator): Pga3dMotor =
    Pga3dMotor(
      s = normSquare,
      wx = (r.wx * r00 + r.wy * r01 + r.wz * r02),
      wy = (r.wx * r10 + r.wy * r11 + r.wz * r12),
      wz = (r.wx * r20 + r.wy * r21 + r.wz * r22),
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      i = normSquareI,
    )

  infix def reverseSandwich(r: Pga3dTranslator): Pga3dMotor =
    Pga3dMotor(
      s = normSquare,
      wx = (r.wx * r00 + r.wy * r10 + r.wz * r20),
      wy = (r.wx * r01 + r.wy * r11 + r.wz * r21),
      wz = (r.wx * r02 + r.wy * r12 + r.wz * r22),
      xy = 0.0,
      xz = 0.0,
      yz = 0.0,
      i = normSquareI,
    )

  infix def sandwich(r: Pga3dVector): Pga3dVector =
    Pga3dVector(
      x = (r.x * r00 + r.y * r01 + r.z * r02),
      y = (r.x * r10 + r.y * r11 + r.z * r12),
      z = (r.x * r20 + r.y * r21 + r.z * r22),
    )

  infix def reverseSandwich(r: Pga3dVector): Pga3dVector =
    Pga3dVector(
      x = (r.x * r00 + r.y * r10 + r.z * r20),
      y = (r.x * r01 + r.y * r11 + r.z * r21),
      z = (r.x * r02 + r.y * r12 + r.z * r22),
    )

  infix def sandwich(r: Pga3dPoint): Pga3dProjectivePoint =
    Pga3dProjectivePoint(
      x = (tx + r.x * r00 + r.y * r01 + r.z * r02),
      y = (ty + r.x * r10 + r.y * r11 + r.z * r12),
      z = (tz + r.x * r20 + r.y * r21 + r.z * r22),
      w = normSquare,
    )

  infix def reverseSandwich(r: Pga3dPoint): Pga3dProjectivePoint =
    Pga3dProjectivePoint(
      x = (txRev + r.x * r00 + r.y * r10 + r.z * r20),
      y = (tyRev + r.x * r01 + r.y * r11 + r.z * r21),
      z = (tzRev + r.x * r02 + r.y * r12 + r.z * r22),
      w = normSquare,
    )

  infix def sandwich(r: Pga3dPlaneCentral): Pga3dPlane =
    Pga3dPlane(
      x = (r.x * r00 + r.y * r01 + r.z * r02),
      y = (r.x * r10 + r.y * r11 + r.z * r12),
      z = (r.x * r20 + r.y * r21 + r.z * r22),
      w = (r.x * txRev + r.y * tyRev + r.z * tzRev),
    )

  infix def reverseSandwich(r: Pga3dPlaneCentral): Pga3dPlane =
    Pga3dPlane(
      x = (r.x * r00 + r.y * r10 + r.z * r20),
      y = (r.x * r01 + r.y * r11 + r.z * r21),
      z = (r.x * r02 + r.y * r12 + r.z * r22),
      w = (r.x * tx + r.y * ty + r.z * tz),
    )

  infix def sandwich(r: Pga3dBivectorBulk): Pga3dBivector =
    Pga3dBivector(
      wx = (d00 * r.xy + d01 * r.xz + d02 * r.yz),
      wy = (d10 * r.xy + d11 * r.xz + d12 * r.yz),
      wz = (d20 * r.xy + d21 * r.xz + d22 * r.yz),
      xy = (r.xy * r22 + r.yz * r20 - r.xz * r21),
      xz = (r.xz * r11 - r.xy * r12 - r.yz * r10),
      yz = (r.xy * r02 + r.yz * r00 - r.xz * r01),
    )

  infix def reverseSandwich(r: Pga3dBivectorBulk): Pga3dBivector =
    Pga3dBivector(
      wx = (d02 * r.yz + d22 * r.xy - d12 * r.xz),
      wy = (d11 * r.xz - d01 * r.yz - d21 * r.xy),
      wz = (d00 * r.yz + d20 * r.xy - d10 * r.xz),
      xy = (r.xy * r22 + r.yz * r02 - r.xz * r12),
      xz = (r.xz * r11 - r.xy * r21 - r.yz * r01),
      yz = (r.xy * r20 + r.yz * r00 - r.xz * r10),
    )

  infix def sandwich(r: Pga3dBivectorWeight): Pga3dBivectorWeight =
    Pga3dBivectorWeight(
      wx = (r.wx * r00 + r.wy * r01 + r.wz * r02),
      wy = (r.wx * r10 + r.wy * r11 + r.wz * r12),
      wz = (r.wx * r20 + r.wy * r21 + r.wz * r22),
    )

  infix def reverseSandwich(r: Pga3dBivectorWeight): Pga3dBivectorWeight =
    Pga3dBivectorWeight(
      wx = (r.wx * r00 + r.wy * r10 + r.wz * r20),
      wy = (r.wx * r01 + r.wy * r11 + r.wz * r21),
      wz = (r.wx * r02 + r.wy * r12 + r.wz * r22),
    )

  infix def sandwich(r: Pga3dPseudoScalar): Pga3dPseudoScalar =
    Pga3dPseudoScalar(
      i = normSquare * r.i,
    )

  infix def reverseSandwich(r: Pga3dPseudoScalar): Pga3dPseudoScalar =
    Pga3dPseudoScalar(
      i = normSquare * r.i,
    )

  infix def sandwich(r: Pga3dPointCenter.type): Pga3dProjectivePoint =
    Pga3dProjectivePoint(
      x = tx,
      y = ty,
      z = tz,
      w = normSquare,
    )

  infix def reverseSandwich(r: Pga3dPointCenter.type): Pga3dProjectivePoint =
    Pga3dProjectivePoint(
      x = txRev,
      y = tyRev,
      z = tzRev,
      w = normSquare,
    )


object Pga3dTransform:
  val id: Pga3dTransform = Pga3dTransform(Pga3dMotor.id)

  def apply(motor: Pga3dMotor): Pga3dTransform =
    val s = motor.s
    val wx = motor.wx
    val wy = motor.wy
    val wz = motor.wz
    val xy = motor.xy
    val xz = motor.xz
    val yz = motor.yz
    val i = motor.i

    val sMs = s * s
    val sMwx = s * wx
    val sMwy = s * wy
    val sMwz = s * wz
    val sMxy = s * xy
    val sMxz = s * xz
    val sMyz = s * yz
    val sMi = i * s
    val wxMxy = wx * xy
    val wxMxz = wx * xz
    val wxMyz = wx * yz
    val wyMxy = wy * xy
    val wyMxz = wy * xz
    val wyMyz = wy * yz
    val wzMxy = wz * xy
    val wzMxz = wz * xz
    val wzMyz = wz * yz
    val xyMxy = xy * xy
    val xyMxz = xy * xz
    val xyMyz = xy * yz
    val xyMi = i * xy
    val xzMxz = xz * xz
    val xzMyz = xz * yz
    val xzMi = i * xz
    val yzMyz = yz * yz
    val yzMi = i * yz

    new Pga3dTransform(
      motor,
      r00 = (sMs + yzMyz - xyMxy - xzMxz),
      r01 = 2.0 * (sMxy - xzMyz),
      r02 = 2.0 * (sMxz + xyMyz),
      r10 = 2.0 * (-sMxy - xzMyz),
      r11 = (sMs + xzMxz - xyMxy - yzMyz),
      r12 = 2.0 * (sMyz - xyMxz),
      r20 = 2.0 * (xyMyz - sMxz),
      r21 = 2.0 * (-sMyz - xyMxz),
      r22 = (sMs + xyMxy - xzMxz - yzMyz),

      d00 = 2.0 * (wxMxy + wzMyz - sMwy - xzMi),
      d01 = 2.0 * (wxMxz + xyMi - sMwz - wyMyz),
      d02 = 2.0 * (wxMyz + wyMxz - sMi - wzMxy),
      d10 = 2.0 * (sMwx + wyMxy - wzMxz - yzMi),
      d11 = 2.0 * (sMi + wxMyz + wyMxz + wzMxy),
      d12 = 2.0 * (wyMyz + xyMi - sMwz - wxMxz),
      d20 = 2.0 * (wyMxz + wzMxy - sMi - wxMyz),
      d21 = 2.0 * (sMwx + wzMxz - wyMxy - yzMi),
      d22 = 2.0 * (sMwy + wxMxy + wzMyz + xzMi),

      normSquare = (sMs + xyMxy + xzMxz + yzMyz),
      normSquareI = 2.0 * (sMi + wyMxz - wxMyz - wzMxy),

      tx = 2.0 * (-sMwx - wyMxy - wzMxz - yzMi),
      ty = 2.0 * (wxMxy + xzMi - sMwy - wzMyz),
      tz = 2.0 * (wxMxz + wyMyz - sMwz - xyMi),
      txRev = 2.0 * (sMwx + yzMi - wyMxy - wzMxz),
      tyRev = 2.0 * (sMwy + wxMxy - wzMyz - xzMi),
      tzRev = 2.0 * (sMwz + wxMxz + wyMyz + xyMi),
    )