package me.kright.gametools.pga.codegen.scala.common

import me.kright.gametools.pga.codegen.common.{FileContent, GeneratedFileSystem}

import java.nio.file.Path

/** generates operations.md: a reference of every generated operation with its argument and result types */
object OperationsReference:

  private def leftClasses(using algebra: ScalaPgaAlgebra): Seq[ScalaMultivectorSubClass] =
    algebra.pgaClasses.filter(_.shouldBeGenerated)

  private def rightClasses(using algebra: ScalaPgaAlgebra): Seq[ScalaMultivectorSubClass] =
    algebra.pgaClasses.filterNot(cls => cls == algebra.zeroCls || cls == algebra.scalar)

  private def binaryOpDescriptions(using algebra: ScalaPgaAlgebra): Map[String, String] = Map(
    "geometric" -> "The geometric product.",
    "dot" -> "The dot (inner) product.",
    "wedge" -> "The wedge (outer) product, also known as `meet`: the intersection of geometric elements.",
    "antiGeometric" -> "The dual of the geometric product.",
    "antiDot" -> "The dual of the dot product.",
    "antiDotI" -> "The pseudoscalar component of `antiDot`, returned as a `Double`.",
    "antiWedge" -> "The dual of the wedge product, also known as `join`: the element spanned by the arguments (e.g. the line through two points).",
    "sandwich" -> s"`a.sandwich(b)` transforms `b` by `a`: rotation for a rotor, translation for a translator, rigid motion for a motor, reflection for a ${algebra.hyperplaneElementName}.",
    "reverseSandwich" -> "`a.reverseSandwich(b)` equals `a.reverse.sandwich(b)`: the inverse transformation of `sandwich`.",
    "cross" -> "The commutator product `(a * b - b * a) / 2`.",
  )

  private def shortName(cls: ScalaMultivectorSubClass)(using algebra: ScalaPgaAlgebra): String =
    if (cls.name.startsWith(algebra.typeNamePrefix)) cls.name.drop(algebra.typeNamePrefix.length) else cls.name

  private def binaryOpTable(op: MultivectorBinaryOp)(using algebra: ScalaPgaAlgebra): String =
    val sb = StringBuilder()
    sb ++= rightClasses.map(shortName).mkString(s"| ${op.name} | ", " | ", " |\n")
    sb ++= rightClasses.map(_ => "---").mkString("|---|", "|", "|\n")
    for (leftCls <- leftClasses) {
      val cells = rightClasses.map { rightCls =>
        if ((leftCls == algebra.multivector) != (rightCls == algebra.multivector)) ""
        else op(leftCls.self, rightCls.makeSymbolic("v")) match
          case None => ""
          case Some(result) =>
            val resultCls = algebra.findMatchingClass(result)
            if (resultCls == algebra.zeroCls) "" else shortName(resultCls)
      }
      sb ++= cells.mkString(s"| **${shortName(leftCls)}** | ", " | ", " |\n")
    }
    sb.toString

  private def methodSignatures(cls: ScalaMultivectorSubClass)(using algebra: ScalaPgaAlgebra): Seq[String] =
    for {
      op <- algebra.unaryOperations
      snippet <- op(cls, cls.self).toSeq
      line <- snippet.linesIterator.toSeq
      if line.startsWith("def ") && line.endsWith(" =")
    } yield line.stripPrefix("def ").stripSuffix(" =")

  def generate()(using algebra: ScalaPgaAlgebra): String =
    val sb = StringBuilder()
    val heading = algebra.targetPackage.split('.').last
    sb ++=
      s"""# $heading operations reference
        |
        |Generated by pgaNdCodeGen (${algebra.generatorMainFqcn}).
        |Do not edit by hand: change the generator and re-run it.
        |
        |Every method returns the narrowest generated type that can represent the result:
        |the code generator evaluates each operation symbolically and picks the smallest class
        |whose fields cover all possibly non-zero components.
        |
        |## Binary operations
        |
        |Row = type of the left operand `a`, column = type of the right operand `b`,
        |cell = result type of `a.<op>(b)`. Class names omit the `${algebra.typeNamePrefix}` prefix.
        |An empty cell means the method is not generated because the result is identically zero.
        |`${algebra.multivector.name}` combines only with `${algebra.multivector.name}`; the specialized classes combine
        |with each other, but not with `${algebra.multivector.name}`.
        |
        |""".stripMargin

    for (op <- algebra.binaryOperations) {
      sb ++= s"### ${op.name}\n\n"
      if (op.names.tail.nonEmpty) {
        sb ++= op.names.tail.map(n => s"`$n`").mkString("Aliases: ", ", ", ".\n\n")
      }
      binaryOpDescriptions.get(op.name).foreach(d => sb ++= s"$d\n\n")
      sb ++= binaryOpTable(op)
      sb ++= "\n"
    }

    sb ++=
      s"""## Per-class methods
        |
        |All other generated methods: unary operations (reverse, dual, bulk, weight, norms),
        |conversions, exponent and logarithm, componentwise `+`, `-` and `madd`, and scaling
        |by a `Double`. Companion-object helpers (e.g. `${algebra.rotor.name}.rotation`) are not listed.
        |
        |""".stripMargin

    for (cls <- leftClasses) {
      sb ++= s"### ${cls.name}\n\n"
      methodSignatures(cls).foreach(sig => sb ++= s"- `$sig`\n")
      sb ++= "\n"
    }

    sb.toString.stripTrailing() + "\n"

  def writeToFile(path: Path, fs: GeneratedFileSystem)(using algebra: ScalaPgaAlgebra): Unit =
    fs.write(FileContent(path, generate()))
