package me.kright.gametools.pga.codegen.scala.common

import me.kright.gametools.ga.*
import me.kright.gametools.pga.codegen.common.{MultivectorField, MultivectorSubClass}
import me.kright.gametools.pga.codegen.scala.common.ops.DefVariablesComponentsCount
import me.kright.gametools.symbolic.Sym
import me.kright.gametools.symbolic.transform.simplifiers.ReplaceSumOrProduct
import me.kright.gametools.mathutil.Sign

import _root_.scala.math.Numeric.Implicits.infixNumericOps
import _root_.scala.util.Try
import _root_.scala.util.chaining.scalaUtilChainingOps

/**
 * The two former per-dimension `ScalaMultivectorSubClass` class bodies (pga3d, pga2d) were byte-identical:
 * every difference between the algebras lived in their companion objects (class lists, op lists, naming).
 * This is therefore a single concrete class, parameterized by an injected [[ScalaPgaAlgebra]], rather than
 * a base class with per-dimension subclasses.
 */
class ScalaMultivectorSubClass(name: String,
                               variableFields: Seq[MultivectorField],
                               constantFields: Seq[(MultivectorField, Double)] = Seq(),
                               shouldBeGenerated: Boolean = true,
                               val description: String = "")(using val algebra: ScalaPgaAlgebra)
  extends MultivectorSubClass(name, variableFields, constantFields, shouldBeGenerated)(using algebra.pga) with ScalaCodeGenClass:

  import algebra.given

  override def isObject: Boolean = variableFields.isEmpty

  override def typeNamePrefix: String = algebra.typeNamePrefix

  override def generatedComment: String = algebra.generatedComment

  override def targetPackage: String = algebra.targetPackage

  override def generateClassDoc(): String =
    val bladeCoefficients: Seq[String] =
      variableFields.map(f => s"${algebra.pga.representation(f.basisBlade)} = ${if (f.sign == Sign.Negative) "-" else ""}${f.name}") ++
        constantFields.map((f, v) => s"${algebra.pga.representation(f.basisBlade)} = ${if (f.sign == Sign.Negative && v != 0.0) -v else v}")

    // when each field simply stores the coefficient of the same-named basis blade, the list adds nothing
    val bladesAreTrivial = constantFields.isEmpty &&
      variableFields.forall(f => f.sign == Sign.Positive && algebra.pga.representation(f.basisBlade) == f.name)

    val lines = Seq.newBuilder[String]
    lines ++= description.linesIterator
    lines += ""
    if (variableFields.nonEmpty) lines += s"Variable fields: ${variableFields.map(_.name).mkString(", ")}."
    if (constantFields.nonEmpty) lines += s"Constant fields: ${constantFields.map((f, v) => s"${f.name} = $v").mkString(", ")}."
    if (!bladesAreTrivial) lines += s"Basis blade coefficients: ${bladeCoefficients.mkString(", ")}."
    lines += ""
    lines += s"Generated by pgaNdCodeGen (${algebra.generatorMainFqcn})."
    lines += "Do not edit by hand: change the generator and re-run it."

    val all = lines.result()
    ("/**" +: all.map(l => if (l.isEmpty) " *" else s" * $l") :+ " */").mkString("\n")

  override def generateImports(): String =
    """import scala.annotation.targetName
      |import me.kright.gametools.flatarray.FlatDoubleSerializer
      |
      |""".stripMargin

  def makeSymbolic(instanceName: String): MultiVector[Sym] =
    if (name == "Double") {
      MultiVector.scalar(Sym(instanceName))
    } else {
      MultiVector[Sym](
        variableFields.map(f => f.basisBlade -> Sym(s"${instanceName}.${f.name}").pipe(e => if (f.sign == Sign.Positive) e else -e)).toMap ++
          constantFields.map((f, v) => f.basisBlade -> Sym(v).pipe(e => if (f.sign == Sign.Positive) e else -e))
      )
    }

  val self: MultiVector[Sym] =
    if (name == "Double") {
      MultiVector.scalar(Sym("this"))
    } else {
      MultiVector[Sym](
        variableFields.map(f => f.basisBlade -> Sym(f.name).pipe(e => if (f.sign == Sign.Positive) e else -e)).toMap ++
          constantFields.map((f, v) => f.basisBlade -> Sym(v).pipe(e => if (f.sign == Sign.Positive) e else -e))
      )
    }

  def makeConstructor(value: MultiVector[Sym]): String =
    val groupedResult = value.mapValues(_.groupMultipliers())
    if (name == "Double") {
      val expr = groupedResult.get(variableFields.head.basisBlade).getOrElse(Sym.zero)
      return expr.toString
    }
    if (isObject) {
      return name
    }

    val code = ScalaCodeBuilder()
    code(name + "(")
    code.block {
      for (f <- variableFields) {
        val expr: Sym = groupedResult.get(f.basisBlade).getOrElse(Sym.zero)

        val exprString: String =
          if (f.sign == Sign.Positive) expr.toString
          else (-expr).groupMultipliers().toString

        require(!exprString.startsWith("--"), s"expString = '${exprString}',\n-expr = ${(-expr).symbol},\nexpr = ${expr.symbol}")

        code(s"${f.name} = ${exprString},")
      }
    }
    code(")")
    code.toString


  override def generateCode(): String =
    generateCode(algebra.unaryOperations, algebra.binaryOperations)

  private def generateConstructorCode(code: ScalaCodeBuilder): Unit = {
    if (isObject) {
      code(s"object ${name}:")
    } else {
      require(variableFields.nonEmpty)

      val start = s"final case class ${name}("
      val pad = " ".repeat(start.length)

      code(variableFields
        .map(f => s"${f.name}: Double = 0.0")
        .zipWithIndex
        .map((s, i) => if (i == 0) s else pad + s)
        .mkString(start, ",\n", ") derives CanEqual, FlatDoubleSerializer:"))
    }
  }

  private def generateCode(unaryOps: Seq[MultivectorUnaryOp],
                           binaryOps: Seq[MultivectorBinaryOp]): String = {
    val code = ScalaCodeBuilder()

    generateConstructorCode(code)

    code.block {
      if (isObject) {
        DefVariablesComponentsCount()(using algebra).apply(this, self).foreach { lines =>
          code(lines)
        }
      }

      for (unaryOp <- unaryOps) {
        unaryOp(this, self).foreach { lines =>
          code(lines)
        }
      }

      for (binaryOp <- binaryOps) {
        for (rightCls <- algebra.pgaClasses
             if (rightCls != algebra.zeroCls)
               && (rightCls != algebra.scalar)
               && ((this == algebra.multivector) == (rightCls == algebra.multivector))) {
          val v = rightCls.makeSymbolic("v")
          binaryOp(self, v) match {
            case None => ()
            case Some(result) => {
              val resultCls = algebra.findMatchingClass(result)
              if (resultCls != algebra.zeroCls) {
                code(s"\ninfix def ${binaryOp.name}(v: ${rightCls.typeName}): ${resultCls.typeName} =")

                code.block {
                  if (resultCls == this && result == self) {
                    code("this")
                  } else if (resultCls == this && result == -self) {
                    code("-this")
                  } else if (resultCls == rightCls && result == v) {
                    code("v")
                  } else if (resultCls == rightCls && result == -v) {
                    code("-v")
                  } else {
                    binaryOp.name match
                      case "sandwich" | "reverseSandwich" => code(makeConstructorOptimized(result, resultCls))
                      case _ => code(resultCls.makeConstructor(result))
                  }
                }

                for (opName <- binaryOp.names.tail) {
                  code(s"\ninline infix def ${opName}(v: ${rightCls.typeName}): ${resultCls.typeName} = ${binaryOp.name}(v)")
                }
              }
            }
          }
        }
      }
    }

    if (!isObject) {
      code(
        s"""
           |
           |object ${typeName}:""".stripMargin)
      code.block {

        for (unaryOp <- algebra.companionObjectOperations) {
          unaryOp(this, self).foreach { lines =>
            code(lines)
          }
        }

      }
    }

    code.toString
  }

  def makeConstructorOptimized(result: MultiVector[Sym], resultCls: ScalaMultivectorSubClass): String = {
    val code = ScalaCodeBuilder()

    val simplifications: Seq[(Sym, Sym)] =
      (for ((fx, i) <- variableFields.zipWithIndex;
            (fy, j) <- variableFields.zipWithIndex if i <= j)
      yield Sym(s"${fx.name}M${fy.name}") -> self(fx.basisBladeWithSign) * self(fy.basisBladeWithSign))

    var rr = result
    for ((simple, expr) <- simplifications) {
      val replacer = ReplaceSumOrProduct(expr.symbol, simple.symbol)
      val newRR = rr.mapValues(v => v.map(replacer))

      if ((getSize(newRR) + 1 < getSize(rr))) {
        rr = newRR
        code(s"val ${simple.toString} = ${expr.toString}")
      }
    }

    val constructorCode = resultCls.makeConstructor(rr)
    code(constructorCode)
    code.toString
  }

  private def getSize(a: MultiVector[Sym]): Int =
    a.values.map((b, s) => s.size).sum


object ScalaMultivectorSubClass:
  // instances are singletons compared by reference identity (no case class / structural equality involved)
  given CanEqual[ScalaMultivectorSubClass, ScalaMultivectorSubClass] = CanEqual.derived
