package me.kright.gametools.pga.codegen.scalagen.common

import scala.collection.immutable.ArraySeq

/**
 * Generates the ${prefix}Matrix object: conversions between linear operators on the given
 * grade-2 class (Pga3dBivector / Pga2dProjectivePoint) and square matrices, derived from
 * the class's variable fields.
 */
class ScalaMatrixCodeGen(cls: ScalaMultivectorSubClass)(using algebra: ScalaPgaAlgebra) extends ScalaCodeGenClass:
  private val fields = cls.variableFields.map(_.name)
  private val n = fields.size

  override def name: String =
    s"${algebra.typeNamePrefix}Matrix"

  override def isObject: Boolean =
    true

  override def typeNamePrefix: String = algebra.typeNamePrefix

  override def targetPackage: String = algebra.targetPackage

  override def generateImports(): String =
    s"""import me.kright.arrayview.{ArrayView2d, ArrayView2dFlat}
       |import me.kright.gametools.matrix.*
       |import me.kright.gametools.flatarray.FlatDoubleSerializer
       |import scala.collection.immutable.ArraySeq
       |""".stripMargin

  override def generateClassDoc(): String =
    s"""/**
       | * Conversions between linear operators on ${cls.name} and ${n}x${n} matrices.
       | *
       | * Generated by pgaNdCodeGen (${algebra.generatorMainFqcn}).
       | * Do not edit by hand: change the generator and re-run it.
       | */""".stripMargin

  override def generateCode(): String =
    val basisElements = fields.indices
      .map(i => fields.indices.map(j => if (i == j) "1" else "0").mkString(s"${cls.name}(", ", ", "),"))
      .mkString("\n    ")

    val dotSum = fields.zipWithIndex
      .map((f, j) => s"b.$f * m(${if (j == 0) "offset" else s"offset + $j"})")
      .mkString(" +\n        ")

    val constructorArgs = fields.zipWithIndex
      .map((f, i) => s"$f = dot(${i * n}),")
      .mkString("\n      ")

    s"""object ${name}:
       |  private val basis = ArraySeq[${cls.name}](
       |    $basisElements
       |  )
       |
       |  def multiply(matrix: ArrayView2d[Double], b: ${cls.name}): ${cls.name} =
       |    // free for the flat matrices linearMapping builds; copies a lazy view once
       |    val m = matrix.withSimpleLayout.data
       |
       |    inline def dot(offset: Int): Double =
       |      $dotSum
       |
       |    ${cls.name}(
       |      $constructorArgs
       |    )
       |
       |  def linearMapping(map: ${cls.name} => ${cls.name}): ArrayView2dFlat[Double] =
       |    val matrix = ArrayView2dFlat[Double]($n, $n)
       |    for ((b, i) <- basis.zipWithIndex) {
       |      val mappedB = map(b)
       |      FlatDoubleSerializer.write(mappedB, matrix.data, i * $n)
       |    }
       |    matrix.transposeInplace()
       |    matrix
       |
       |""".stripMargin
