package me.kright.gametools.pga.codegen.scalagen.common

import me.kright.gametools.ga.MultiVector
import me.kright.gametools.mathutil.Sign
import me.kright.gametools.pga.codegen.common.MultivectorField
import me.kright.gametools.symbolic.{Sym, Symbolic, SymbolicStr}
import me.kright.gametools.symbolic.transform.simplifiers.ReplaceSumOrProduct

import scala.collection.mutable
import scala.math.Numeric.Implicits.infixNumericOps

/**
 * Generates the ${prefix}Transform class: a cached form of a motor where the sandwich and reverseSandwich
 * products are precomputed into flat matrix coefficients, so each application is a plain matrix multiplication.
 *
 * The coefficients are derived symbolically: sandwich is linear in its argument, so applying the symbolic
 * motor sandwich to each basis element of the argument class yields one column of the operator matrix.
 * Every distinct column entry is registered once as a named cached field (rotation r, the dimension-specific
 * blocks of [[registerMomentBlock]], translations t/tRev, normSquare).
 *
 * Each method is then generated by symbol replacement: the cached coefficients (multiplied by the argument
 * fields, in both signs) are substituted into the full symbolic sandwich expression with ReplaceSumOrProduct,
 * so the emitted code is the motor sandwich expression itself with the coefficient groups named. If anything
 * fails to substitute - e.g. a newly added argument class needs a coefficient that is not in the registry -
 * motor fields remain in the expression and generation fails with an error instead of silently caching
 * more fields.
 */
class ScalaTransformCodeGen(using protected val algebra: ScalaPgaAlgebra) extends ScalaCodeGenClass:
  protected val num: Numeric[Sym] = summon[Numeric[Sym]]

  private val motor = algebra.motor
  private val motorSelf = motor.self

  protected case class SandwichOp(name: String, apply: MultiVector[Sym] => MultiVector[Sym])

  protected val forwardOp: SandwichOp = SandwichOp("sandwich", b => motorSelf.sandwich(b))
  protected val reverseOp: SandwichOp = SandwichOp("reverseSandwich", b => motorSelf.reverse.sandwich(b))

  /**
   * argument classes the transform supports, in the order the methods are emitted: everything the motor
   * sandwich supports. A sandwich of a motor-like argument is not a composition but a change of coordinates
   * of the transformation itself (conjugation), so those are supported too.
   */
  private val supportedClasses: Seq[ScalaMultivectorSubClass] =
    algebra.pgaClasses.filter(cls =>
      cls != algebra.multivector && cls != algebra.scalar && cls != algebra.zeroCls)

  // cached coefficient fields of the generated class: name -> symbolic expression over the motor fields,
  // in registration order (= constructor parameter order)
  private val cachedFields = mutable.LinkedHashMap[String, Sym]()
  private val exprToName = mutable.HashMap[Sym, String]()

  // the same field names grouped for rendering: groups are separated by a blank line,
  // each inner Seq is one line of the constructor parameter list (e.g. one row of a matrix)
  private val fieldGroups = mutable.ArrayBuffer[mutable.ArrayBuffer[Seq[String]]]()

  protected def newGroup(): Unit = fieldGroups += mutable.ArrayBuffer()

  protected def addLine(names: Seq[String]): Unit = fieldGroups.last += names

  private val normSquareName = "normSquare"
  private var hasNormSquareI = false
  protected var rotationNames: Seq[String] = Seq.empty
  protected var rotationIsComplete = true
  private var translationLines: Seq[Seq[String]] = Seq.empty

  protected def isZero(e: Sym): Boolean =
    e == Sym.zero || e == num.zero

  protected def register(name: String, expr: Sym): Unit =
    require(!isZero(expr), s"cached field $name is zero")
    require(!cachedFields.contains(name), s"cached field $name is registered twice")
    require(!exprToName.contains(expr), s"cached field $name duplicates ${exprToName(expr)}")
    cachedFields(name) = expr
    exprToName(expr) = name

  /** find the cached field equal to the expression, up to sign; boolean = negated */
  protected def resolve(expr: Sym): Option[(String, Boolean)] =
    exprToName.get(expr).map((_, false))
      .orElse(exprToName.get(num.negate(expr)).map((_, true)))

  /** the value which the constructor argument for the field receives from the multivector */
  protected def outputExpr(mv: MultiVector[Sym], f: MultivectorField): Sym =
    val e = mv(f.basisBlade)
    if (f.sign == Sign.Positive) e else num.negate(e)

  /** the multivector of a single variable field of the class set to 1 */
  protected def basisInput(f: MultivectorField): MultiVector[Sym] =
    MultiVector[Sym](algebra.pga, f.basisBladeWithSign)

  /** the multivector of the constant fields of the class (e.g. w = 1 of a point), if any */
  private def constInput(cls: ScalaMultivectorSubClass): Option[MultiVector[Sym]] =
    Option.when(cls.constantFields.nonEmpty) {
      MultiVector[Sym](algebra.pga, cls.constantFields.map((f, v) =>
        f.basisBlade -> (if (f.sign == Sign.Positive) Sym(v) else num.negate(Sym(v)))).toMap)
    }

  /**
   * hook for dimension-specific cached blocks, registered between the rotation matrix and normSquare
   * (in 3d: the moment block of the bivector sandwich). Runs during base-class construction,
   * so overrides must not read fields of the subclass.
   */
  protected def registerMomentBlock(): Unit = ()

  /** doc-comment lines describing the fields of [[registerMomentBlock]] */
  protected def momentBlockDocLines: Seq[String] = Seq.empty

  /**
   * the name of the cached rotation-matrix entry at (row, column). In 2d the two stored entries
   * are literally the cosine and sine of the rotation angle, and the subclass names them so.
   * Runs during base-class construction, so overrides must not read fields of the subclass.
   */
  protected def rotationFieldName(i: Int, j: Int): String = s"r$i$j"

  /** doc-comment lines describing the rotation fields */
  protected def rotationDocLines: Seq[String] =
    val n = algebra.vector.variableFields.size
    val rNamesText = if (rotationIsComplete) s"${rotationFieldName(0, 0)}..${rotationFieldName(n - 1, n - 1)}" else rotationNames.mkString(", ")
    Seq(
      s" *  - $rNamesText: the ${n}x$n rotation matrix of the motor (scaled by motor.normSquare for non-normalized motors),",
      " *    used for the euclidean part of any object; the reverse transformation uses its transpose.",
    ) ++ Option.when(!rotationIsComplete)(
      " *    The remaining entries equal the stored ones up to sign and are not cached.")

  private def buildRegistry(): Unit =
    // r: the rotation matrix, from the columns of the vector sandwich. In 2d the matrix has only
    // two independent entries (r11 = r00 and r10 = -r01), so entries which already resolve against
    // a registered field (up to sign) are not stored again - the substitution finds them by itself.
    newGroup()
    val vectorColumns = algebra.vector.variableFields.map(f => forwardOp.apply(basisInput(f)))
    for ((outF, i) <- algebra.vector.variableFields.zipWithIndex) {
      val names = vectorColumns.zipWithIndex.flatMap { (column, j) =>
        val e = outputExpr(column, outF)
        Option.when(resolve(e).isEmpty) {
          val name = rotationFieldName(i, j)
          register(name, e)
          name
        }
      }
      if (names.nonEmpty) addLine(names)
    }
    rotationNames = fieldGroups.last.flatten.toSeq
    rotationIsComplete = rotationNames.size == algebra.vector.variableFields.size * algebra.vector.variableFields.size

    registerMomentBlock()

    // normSquare, from the pseudoscalar sandwich, and normSquareI: the pseudoscalar part
    // of motor * motor.reverse (the dual part of the Study number, zero for normalized motors),
    // from the scalar column of the motor sandwich. 2d motors have no pseudoscalar part,
    // so normSquareI exists only in 3d.
    newGroup()
    val psField = algebra.pseudoScalar.variableFields.head
    register(normSquareName, outputExpr(forwardOp.apply(basisInput(psField)), psField))
    addLine(Seq(normSquareName))
    val motorScalarField = motor.variableFields.find(_.basisBlade == algebra.pga.scalarBlade).get
    val normSquareIExpr = outputExpr(forwardOp.apply(basisInput(motorScalarField)), psField)
    if (!isZero(normSquareIExpr)) {
      register(s"${normSquareName}I", normSquareIExpr)
      addLine(Seq(s"${normSquareName}I"))
      hasNormSquareI = true
    }

    // t / tRev: the translations for points, from the two sandwiches of the coordinate center
    newGroup()
    for ((op, suffix) <- Seq(forwardOp -> "", reverseOp -> "Rev")) {
      val result = op.apply(constInput(algebra.pointCenter).get)
      val resultCls = algebra.findMatchingClass(result)
      addLine(resultCls.variableFields.flatMap { outF =>
        val e = outputExpr(result, outF)
        Option.when(!isZero(e) && resolve(e).isEmpty) {
          val name = s"t${outF.name}$suffix"
          register(name, e)
          name
        }
      })
    }
    translationLines = fieldGroups.last.toSeq

  buildRegistry()

  override def name: String = s"${algebra.typeNamePrefix}Transform"

  override def isObject: Boolean = false

  override def typeNamePrefix: String = algebra.typeNamePrefix

  override def targetPackage: String = algebra.targetPackage

  override def generateImports(): String =
    """import me.kright.gametools.flatarray.FlatDoubleSerializer
      |import me.kright.gametools.mathutil.CanEqualWithEps
      |""".stripMargin

  override def generateClassDoc(): String =
    val rLine = rotationDocLines
    val tLine = Seq(
      s" *  - ${translationLines.map(_.mkString(", ")).mkString(" and ")}: translation for points, forward and reverse.")
    val normSquareLines =
      if (hasNormSquareI)
        Seq(
          " *  - normSquare and normSquareI: the Study number motor * motor.reverse (normSquareI = 0",
          " *    for normalized motors).",
        )
      else
        Seq(" *  - normSquare: the squared norm of the motor, the weight of the resulting projective point.")

    val cachedValues = (rLine ++ momentBlockDocLines ++ tLine ++ normSquareLines).mkString("\n")

    s"""/**
       | * A cached form of a motor: the sandwich and reverseSandwich products expressed as precomputed matrices.
       | *
       | * Prefer this class over motor.sandwich whenever the same motor is applied to many objects -
       | * moving all the points of a body, transforming forces and velocities in a physics solver step, etc.
       | * Building the transform costs about as much as a single motor sandwich, and after that every
       | * application is a plain matrix multiplication, several times cheaper than motor.sandwich,
       | * which recomputes the coefficients on every call.
       | *
       | * The class is immutable, like the ${motor.name} it is built around.
       | *
       | * Cached values:
       |$cachedValues
       | *
       | * The results are equivalent to motor.sandwich(r) / motor.reverseSandwich(r) up to floating point
       | * rounding for any motor, normalized or not.
       | *
       | * Generated by pgaNdCodeGen (${algebra.generatorMainFqcn}).
       | * Do not edit by hand: change the generator and re-run it.
       | */""".stripMargin

  private def collectStringSymbols(e: SymbolicStr): Set[String] = e match
    case Symbolic.Symbol(s: String) => Set(s)
    case Symbolic.Symbol(_) => Set.empty
    case Symbolic.Func(_, args) => args.iterator.flatMap(collectStringSymbols).toSet

  private def generateMethod(code: ScalaCodeBuilder, op: SandwichOp, cls: ScalaMultivectorSubClass): Unit =
    val fullResult = op.apply(cls.makeSymbolic("r"))
    val resultCls = algebra.findMatchingClass(fullResult)
    require(resultCls != algebra.zeroCls, s"${op.name}(${cls.name}) is zero")

    // every cached coefficient, standing alone (the constant fields of the argument) and multiplied
    // by each argument field, in both signs
    val substitutions: Seq[(Sym, Sym)] =
      for ((name, expr) <- cachedFields.toSeq;
           (pattern, replacement) <- (expr, Sym(name)) +:
             cls.variableFields.map { f =>
               val rSym = Sym(s"r.${f.name}")
               (rSym * expr, rSym * Sym(name))
             };
           signed <- Seq((pattern, replacement), (num.negate(pattern), num.negate(replacement))))
      yield signed

    val substituted = substitutions.foldLeft(fullResult) { case (mv, (pattern, replacement)) =>
      pattern.symbol match
        case f@Symbolic.Func("+" | "*", _) =>
          val replacer = ReplaceSumOrProduct(f, replacement.symbol)
          mv.mapValues(_.map(replacer))
        case _ => mv
    }

    // everything must have been replaced by the cached coefficients: a remaining motor field means
    // the registry does not cover this class
    val motorFieldNames = motor.variableFields.map(_.name).toSet
    for ((blade, e) <- substituted.values) {
      val leftover = collectStringSymbols(e.symbol).intersect(motorFieldNames)
      require(leftover.isEmpty,
        s"${op.name}(${cls.name}): motor fields $leftover are not covered by the cached coefficients in $e")
    }

    code(s"\ninfix def ${op.name}(r: ${cls.typeName}): ${resultCls.typeName} =")
    code.block {
      code(resultCls.makeConstructor(substituted))
    }

  private def generateApply(code: ScalaCodeBuilder): Unit =
    code(s"\ndef apply(motor: ${motor.name}): ${name} =")
    code.block {
      for (f <- motor.variableFields) {
        code(s"val ${f.name} = motor.${f.name}")
      }
      code("")

      // the same pairwise-product extraction as in ScalaMultivectorSubClass.makeConstructorOptimized
      val simplifications: Seq[(Sym, Sym)] =
        for ((fx, i) <- motor.variableFields.zipWithIndex;
             (fy, j) <- motor.variableFields.zipWithIndex if i <= j)
        yield Sym(s"${fx.name}M${fy.name}") -> motorSelf(fx.basisBladeWithSign) * motorSelf(fy.basisBladeWithSign)

      def totalSize(exprs: Seq[(String, Sym)]): Int = exprs.map((_, e) => e.size).sum

      var exprs: Seq[(String, Sym)] = cachedFields.toSeq
      for ((simple, product) <- simplifications) {
        val replacer = ReplaceSumOrProduct(product.symbol, simple.symbol)
        val newExprs = exprs.map((n, e) => (n, e.map(replacer)))
        if (totalSize(newExprs) + 1 < totalSize(exprs)) {
          exprs = newExprs
          code(s"val ${simple.toString} = ${product.toString}")
        }
      }

      code("")
      code(s"new ${name}(")
      code.block {
        code("motor,")
        val exprByName = exprs.toMap
        for ((group, groupIndex) <- fieldGroups.zipWithIndex) {
          if (groupIndex > 0) code("")
          for (fieldName <- group.flatten) {
            code(s"$fieldName = ${exprByName(fieldName).groupMultipliers()},")
          }
        }
      }
      code(")")
    }

  override def generateCode(): String =
    val code = ScalaCodeBuilder()

    code(s"final case class ${name}(motor: ${motor.name},")
    val pad = " ".repeat(s"final case class ${name}(".length)
    for ((group, groupIndex) <- fieldGroups.zipWithIndex) {
      if (groupIndex > 0) code("")
      for ((line, lineIndex) <- group.zipWithIndex) {
        val isLast = groupIndex == fieldGroups.size - 1 && lineIndex == group.size - 1
        val params = line.map(n => s"$n: Double").mkString(", ")
        val terminator = if (isLast) ") derives CanEqual, CanEqualWithEps, FlatDoubleSerializer:" else ","
        code(s"$pad$params$terminator")
      }
    }

    code.block {
      code("")
      code("override def toString: String =")
      code.block {
        code(s"""s"${name}($$motor)"""")
      }

      for (cls <- supportedClasses; op <- Seq(forwardOp, reverseOp)) {
        generateMethod(code, op, cls)
      }
    }

    code(s"""
            |
            |object ${name}:""".stripMargin)
    code.block {
      code(s"val id: ${name} = ${name}(${motor.name}.id)")
      generateApply(code)
    }

    code.toString
