package me.kright.gametools.pga2d

import scala.annotation.targetName
import me.kright.gametools.flatarray.FlatDoubleSerializer


/**
 * A point on the 2d plane, stored in dual representation with human-friendly fields x, y and constant w = 1.
 *
 * Variable fields: x, y.
 * Constant fields: w = 1.0.
 * Basis blade coefficients: wy = -x, wx = y, xy = 1.0.
 *
 * Generated by pgaNdCodeGen (me.kright.gametools.pga.codegen.scala.pga2d.runScalaCodeGen).
 * Do not edit by hand: change the generator and re-run it.
 */
final case class Pga2dPoint(x: Double = 0.0,
                            y: Double = 0.0) derives CanEqual, FlatDoubleSerializer:
  inline val w = 1.0

  inline def wy: Double = -x

  inline def wx: Double = y

  inline def xy: Double = 1.0

  override def toString: String =
    s"Pga2dPoint(x = $x, y = $y)"

  def dual: Pga2dLine =
    Pga2dLine(
      x = x,
      y = y,
      w = 1.0,
    )

  def weight: Pga2dVector =
    Pga2dVector(
      x = x,
      y = y,
    )

  def bulk: Pga2dPointCenter.type =
    Pga2dPointCenter

  @targetName("unaryMinus")
  def unary_- : Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = -x,
      y = -y,
      w = -1.0,
    )

  def reverse: Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = -x,
      y = -y,
      w = -1.0,
    )

  def antiReverse: Pga2dPoint =
    this

  def bulkNormSquare: Double =
    1.0

  def bulkNorm: Double =
    Math.sqrt(bulkNormSquare)

  def normalizedByBulk =
    this / bulkNorm

  def weightNormSquare: Double =
    (x * x + y * y)

  def weightNorm: Double =
    Math.sqrt(weightNormSquare)

  def normalizedByWeight =
    this / weightNorm

  def normSquare: Double =
    (1.0 + x * x + y * y)

  def norm: Double =
    Math.sqrt(normSquare)

  def normalizedByNorm =
    this / norm

  @targetName("times")
  def *(v: Double): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = v * x,
      y = v * y,
      w = v,
    )

  @targetName("div")
  def /(v: Double): Pga2dProjectivePoint =
    this * (1.0 / v)

  infix def min(other: Pga2dPoint): Pga2dPoint =
    Pga2dPoint(math.min(x, other.x), math.min(y, other.y))

  infix def max(other: Pga2dPoint): Pga2dPoint =
    Pga2dPoint(math.max(x, other.x), math.max(y, other.y))

  def distanceTo(point: Pga2dPoint): Double =
    (this - point).norm

  @targetName("plus")
  def +(v: Pga2dProjectivePoint): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = (v.x + x),
      y = (v.y + y),
      w = (1.0 + v.w),
    )

  @targetName("minus")
  def -(v: Pga2dProjectivePoint): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = (x - v.x),
      y = (y - v.y),
      w = (1.0 - v.w),
    )

  def madd(v: Pga2dProjectivePoint, mult: Double): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = (x + mult * v.x),
      y = (y + mult * v.y),
      w = (1.0 + mult * v.w),
    )

  @targetName("plus")
  def +(v: Pga2dPoint): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = (v.x + x),
      y = (v.y + y),
      w = 2.0,
    )

  @targetName("minus")
  def -(v: Pga2dPoint): Pga2dVector =
    Pga2dVector(
      x = (x - v.x),
      y = (y - v.y),
    )

  def madd(v: Pga2dPoint, mult: Double): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = (x + mult * v.x),
      y = (y + mult * v.y),
      w = (1.0 + mult),
    )

  @targetName("plus")
  def +(v: Pga2dVector): Pga2dPoint =
    Pga2dPoint(
      x = (v.x + x),
      y = (v.y + y),
    )

  @targetName("minus")
  def -(v: Pga2dVector): Pga2dPoint =
    Pga2dPoint(
      x = (x - v.x),
      y = (y - v.y),
    )

  def madd(v: Pga2dVector, mult: Double): Pga2dPoint =
    Pga2dPoint(
      x = (x + mult * v.x),
      y = (y + mult * v.y),
    )

  def scale(v: Pga2dPoint): Pga2dPoint =
    Pga2dPoint(
      x = x * v.x,
      y = y * v.y,
    )

  def reciprocal: Pga2dPoint =
    Pga2dPoint(
      x = 1.0 / x,
      y = 1.0 / y,
    )

  def toMultivector: Pga2dMultivector =
    Pga2dMultivector(
      s = 0.0,
      w = 0.0,
      x = 0.0,
      y = 0.0,
      wx = y,
      wy = -x,
      xy = 1.0,
      i = 0.0,
    )

  def toMotor: Pga2dMotor =
    Pga2dMotor(
      s = 0.0,
      wx = y,
      wy = -x,
      xy = 1.0,
    )

  def toProjectivePoint: Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = x,
      y = y,
      w = 1.0,
    )

  def toRotorUnsafe: Pga2dRotor =
    Pga2dRotor(
      s = 0.0,
      xy = 1.0,
    )

  def toProjectiveTranslatorUnsafe: Pga2dProjectiveTranslator =
    Pga2dProjectiveTranslator(
      s = 0.0,
      wx = y,
      wy = -x,
    )

  def toTranslatorUnsafe: Pga2dTranslator =
    Pga2dTranslator(
      wx = y,
      wy = -x,
    )

  def toVectorUnsafe: Pga2dVector =
    Pga2dVector(
      x = x,
      y = y,
    )

  /** fused line.dot(point).geometric(line) */
  def projectOntoLine(line: Pga2dLine): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = (line.x * (line.w + line.y * y) - line.y * line.y * x),
      y = (line.y * (line.w + line.x * x) - line.x * line.x * y),
      w = (-line.x * line.x - line.y * line.y),
    )

  infix def geometric(v: Pga2dMotor): Pga2dMotor =
    Pga2dMotor(
      s = -v.xy,
      wx = (v.wy + v.s * y + v.xy * x),
      wy = (-v.wx + v.xy * y - v.s * x),
      xy = v.s,
    )

  infix def geometric(v: Pga2dLine): Pga2dMultivector =
    Pga2dMultivector(
      s = 0.0,
      w = (v.x * y - v.y * x),
      x = v.y,
      y = -v.x,
      wx = 0.0,
      wy = 0.0,
      xy = 0.0,
      i = (v.w + v.x * x + v.y * y),
    )

  infix def geometric(v: Pga2dProjectivePoint): Pga2dProjectiveTranslator =
    Pga2dProjectiveTranslator(
      s = -v.w,
      wx = (-v.x + v.w * x),
      wy = (-v.y + v.w * y),
    )

  infix def geometric(v: Pga2dRotor): Pga2dMotor =
    Pga2dMotor(
      s = -v.xy,
      wx = (v.s * y + v.xy * x),
      wy = (v.xy * y - v.s * x),
      xy = v.s,
    )

  infix def geometric(v: Pga2dProjectiveTranslator): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = (v.wx + v.s * x),
      y = (v.wy + v.s * y),
      w = v.s,
    )

  infix def geometric(v: Pga2dTranslator): Pga2dPoint =
    Pga2dPoint(
      x = (v.wx + x),
      y = (v.wy + y),
    )

  infix def geometric(v: Pga2dVector): Pga2dVector =
    Pga2dVector(
      x = v.y,
      y = -v.x,
    )

  infix def geometric(v: Pga2dPoint): Pga2dProjectiveTranslator =
    Pga2dProjectiveTranslator(
      s = -1.0,
      wx = (x - v.x),
      wy = (y - v.y),
    )

  infix def geometric(v: Pga2dLineIdeal): Pga2dMultivector =
    Pga2dMultivector(
      s = 0.0,
      w = (v.x * y - v.y * x),
      x = v.y,
      y = -v.x,
      wx = 0.0,
      wy = 0.0,
      xy = 0.0,
      i = (v.x * x + v.y * y),
    )

  infix def geometric(v: Pga2dPseudoScalar): Pga2dLine =
    Pga2dLine(
      x = 0.0,
      y = 0.0,
      w = -v.i,
    )

  infix def geometric(v: Pga2dPointCenter.type): Pga2dProjectiveTranslator =
    Pga2dProjectiveTranslator(
      s = -1.0,
      wx = x,
      wy = y,
    )

  infix def dot(v: Pga2dMotor): Pga2dMotor =
    Pga2dMotor(
      s = -v.xy,
      wx = v.s * y,
      wy = -v.s * x,
      xy = v.s,
    )

  infix def dot(v: Pga2dLine): Pga2dLine =
    Pga2dLine(
      x = v.y,
      y = -v.x,
      w = (v.x * y - v.y * x),
    )

  infix def dot(v: Pga2dProjectivePoint): Double =
    -v.w

  infix def dot(v: Pga2dRotor): Pga2dMotor =
    Pga2dMotor(
      s = -v.xy,
      wx = v.s * y,
      wy = -v.s * x,
      xy = v.s,
    )

  infix def dot(v: Pga2dProjectiveTranslator): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = v.s * x,
      y = v.s * y,
      w = v.s,
    )

  infix def dot(v: Pga2dTranslator): Pga2dPoint =
    this

  infix def dot(v: Pga2dPoint): Double =
    -1.0

  infix def dot(v: Pga2dLineIdeal): Pga2dLine =
    Pga2dLine(
      x = v.y,
      y = -v.x,
      w = (v.x * y - v.y * x),
    )

  infix def dot(v: Pga2dPseudoScalar): Pga2dLine =
    Pga2dLine(
      x = 0.0,
      y = 0.0,
      w = -v.i,
    )

  infix def dot(v: Pga2dPointCenter.type): Double =
    -1.0

  infix def wedge(v: Pga2dMotor): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = v.s * x,
      y = v.s * y,
      w = v.s,
    )

  inline infix def ^(v: Pga2dMotor): Pga2dProjectivePoint = wedge(v)

  inline infix def meet(v: Pga2dMotor): Pga2dProjectivePoint = wedge(v)

  infix def wedge(v: Pga2dLine): Pga2dPseudoScalar =
    Pga2dPseudoScalar(
      i = (v.w + v.x * x + v.y * y),
    )

  inline infix def ^(v: Pga2dLine): Pga2dPseudoScalar = wedge(v)

  inline infix def meet(v: Pga2dLine): Pga2dPseudoScalar = wedge(v)

  infix def wedge(v: Pga2dRotor): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = v.s * x,
      y = v.s * y,
      w = v.s,
    )

  inline infix def ^(v: Pga2dRotor): Pga2dProjectivePoint = wedge(v)

  inline infix def meet(v: Pga2dRotor): Pga2dProjectivePoint = wedge(v)

  infix def wedge(v: Pga2dProjectiveTranslator): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = v.s * x,
      y = v.s * y,
      w = v.s,
    )

  inline infix def ^(v: Pga2dProjectiveTranslator): Pga2dProjectivePoint = wedge(v)

  inline infix def meet(v: Pga2dProjectiveTranslator): Pga2dProjectivePoint = wedge(v)

  infix def wedge(v: Pga2dTranslator): Pga2dPoint =
    this

  inline infix def ^(v: Pga2dTranslator): Pga2dPoint = wedge(v)

  inline infix def meet(v: Pga2dTranslator): Pga2dPoint = wedge(v)

  infix def wedge(v: Pga2dLineIdeal): Pga2dPseudoScalar =
    Pga2dPseudoScalar(
      i = (v.x * x + v.y * y),
    )

  inline infix def ^(v: Pga2dLineIdeal): Pga2dPseudoScalar = wedge(v)

  inline infix def meet(v: Pga2dLineIdeal): Pga2dPseudoScalar = wedge(v)

  infix def antiGeometric(v: Pga2dMotor): Pga2dMultivector =
    Pga2dMultivector(
      s = 0.0,
      w = (v.wx * x + v.wy * y),
      x = (-v.wx + v.s * x + v.xy * y),
      y = (-v.wy + v.s * y - v.xy * x),
      wx = 0.0,
      wy = 0.0,
      xy = 0.0,
      i = (v.wx * y - v.wy * x),
    )

  infix def antiGeometric(v: Pga2dLine): Pga2dMotor =
    Pga2dMotor(
      s = (v.w + v.x * x + v.y * y),
      wx = v.w * x,
      wy = v.w * y,
      xy = (v.x * y - v.y * x),
    )

  infix def antiGeometric(v: Pga2dProjectivePoint): Pga2dMultivector =
    Pga2dMultivector(
      s = 0.0,
      w = (v.y * x - v.x * y),
      x = (-v.y + v.w * y),
      y = (v.x - v.w * x),
      wx = 0.0,
      wy = 0.0,
      xy = 0.0,
      i = (v.x * x + v.y * y),
    )

  infix def antiGeometric(v: Pga2dRotor): Pga2dLineIdeal =
    Pga2dLineIdeal(
      x = (v.s * x + v.xy * y),
      y = (v.s * y - v.xy * x),
    )

  infix def antiGeometric(v: Pga2dProjectiveTranslator): Pga2dMultivector =
    Pga2dMultivector(
      s = 0.0,
      w = (v.wx * x + v.wy * y),
      x = (-v.wx + v.s * x),
      y = (-v.wy + v.s * y),
      wx = 0.0,
      wy = 0.0,
      xy = 0.0,
      i = (v.wx * y - v.wy * x),
    )

  infix def antiGeometric(v: Pga2dTranslator): Pga2dMultivector =
    Pga2dMultivector(
      s = 0.0,
      w = (v.wx * x + v.wy * y),
      x = (x - v.wx),
      y = (y - v.wy),
      wx = 0.0,
      wy = 0.0,
      xy = 0.0,
      i = (v.wx * y - v.wy * x),
    )

  infix def antiGeometric(v: Pga2dVector): Pga2dMultivector =
    Pga2dMultivector(
      s = 0.0,
      w = (v.y * x - v.x * y),
      x = -v.y,
      y = v.x,
      wx = 0.0,
      wy = 0.0,
      xy = 0.0,
      i = (v.x * x + v.y * y),
    )

  infix def antiGeometric(v: Pga2dPoint): Pga2dMultivector =
    Pga2dMultivector(
      s = 0.0,
      w = (v.y * x - v.x * y),
      x = (y - v.y),
      y = (v.x - x),
      wx = 0.0,
      wy = 0.0,
      xy = 0.0,
      i = (v.x * x + v.y * y),
    )

  infix def antiGeometric(v: Pga2dLineIdeal): Pga2dRotor =
    Pga2dRotor(
      s = (v.x * x + v.y * y),
      xy = (v.x * y - v.y * x),
    )

  infix def antiGeometric(v: Pga2dPseudoScalar): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = v.i * x,
      y = v.i * y,
      w = v.i,
    )

  infix def antiGeometric(v: Pga2dPointCenter.type): Pga2dLineIdeal =
    Pga2dLineIdeal(
      x = y,
      y = -x,
    )

  infix def antiDot(v: Pga2dMotor): Pga2dMultivector =
    Pga2dMultivector(
      s = 0.0,
      w = 0.0,
      x = v.s * x,
      y = v.s * y,
      wx = 0.0,
      wy = 0.0,
      xy = 0.0,
      i = (v.wx * y - v.wy * x),
    )

  infix def antiDot(v: Pga2dLine): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = -v.w * y,
      y = v.w * x,
      w = (v.x * y - v.y * x),
    )

  infix def antiDot(v: Pga2dProjectivePoint): Pga2dPseudoScalar =
    Pga2dPseudoScalar(
      i = (v.x * x + v.y * y),
    )

  infix def antiDot(v: Pga2dRotor): Pga2dLineIdeal =
    Pga2dLineIdeal(
      x = v.s * x,
      y = v.s * y,
    )

  infix def antiDot(v: Pga2dProjectiveTranslator): Pga2dMultivector =
    Pga2dMultivector(
      s = 0.0,
      w = 0.0,
      x = v.s * x,
      y = v.s * y,
      wx = 0.0,
      wy = 0.0,
      xy = 0.0,
      i = (v.wx * y - v.wy * x),
    )

  infix def antiDot(v: Pga2dTranslator): Pga2dMultivector =
    Pga2dMultivector(
      s = 0.0,
      w = 0.0,
      x = x,
      y = y,
      wx = 0.0,
      wy = 0.0,
      xy = 0.0,
      i = (v.wx * y - v.wy * x),
    )

  infix def antiDot(v: Pga2dVector): Pga2dPseudoScalar =
    Pga2dPseudoScalar(
      i = (v.x * x + v.y * y),
    )

  infix def antiDot(v: Pga2dPoint): Pga2dPseudoScalar =
    Pga2dPseudoScalar(
      i = (v.x * x + v.y * y),
    )

  infix def antiDot(v: Pga2dLineIdeal): Pga2dRotor =
    Pga2dRotor(
      s = 0.0,
      xy = (v.x * y - v.y * x),
    )

  infix def antiDot(v: Pga2dPseudoScalar): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = v.i * x,
      y = v.i * y,
      w = v.i,
    )

  infix def antiDotI(v: Pga2dProjectivePoint): Double =
    (v.x * x + v.y * y)

  infix def antiDotI(v: Pga2dVector): Double =
    (v.x * x + v.y * y)

  infix def antiDotI(v: Pga2dPoint): Double =
    (v.x * x + v.y * y)

  infix def antiWedge(v: Pga2dMotor): Pga2dLine =
    Pga2dLine(
      x = (-v.wx + v.xy * y),
      y = (-v.wy - v.xy * x),
      w = (v.wx * x + v.wy * y),
    )

  inline infix def v(v: Pga2dMotor): Pga2dLine = antiWedge(v)

  inline infix def join(v: Pga2dMotor): Pga2dLine = antiWedge(v)

  infix def antiWedge(v: Pga2dLine): Double =
    (v.w + v.x * x + v.y * y)

  inline infix def v(v: Pga2dLine): Double = antiWedge(v)

  inline infix def join(v: Pga2dLine): Double = antiWedge(v)

  infix def antiWedge(v: Pga2dProjectivePoint): Pga2dLine =
    Pga2dLine(
      x = (-v.y + v.w * y),
      y = (v.x - v.w * x),
      w = (v.y * x - v.x * y),
    )

  inline infix def v(v: Pga2dProjectivePoint): Pga2dLine = antiWedge(v)

  inline infix def join(v: Pga2dProjectivePoint): Pga2dLine = antiWedge(v)

  infix def antiWedge(v: Pga2dRotor): Pga2dLineIdeal =
    Pga2dLineIdeal(
      x = v.xy * y,
      y = -v.xy * x,
    )

  inline infix def v(v: Pga2dRotor): Pga2dLineIdeal = antiWedge(v)

  inline infix def join(v: Pga2dRotor): Pga2dLineIdeal = antiWedge(v)

  infix def antiWedge(v: Pga2dProjectiveTranslator): Pga2dLine =
    Pga2dLine(
      x = -v.wx,
      y = -v.wy,
      w = (v.wx * x + v.wy * y),
    )

  inline infix def v(v: Pga2dProjectiveTranslator): Pga2dLine = antiWedge(v)

  inline infix def join(v: Pga2dProjectiveTranslator): Pga2dLine = antiWedge(v)

  infix def antiWedge(v: Pga2dTranslator): Pga2dLine =
    Pga2dLine(
      x = -v.wx,
      y = -v.wy,
      w = (v.wx * x + v.wy * y),
    )

  inline infix def v(v: Pga2dTranslator): Pga2dLine = antiWedge(v)

  inline infix def join(v: Pga2dTranslator): Pga2dLine = antiWedge(v)

  infix def antiWedge(v: Pga2dVector): Pga2dLine =
    Pga2dLine(
      x = -v.y,
      y = v.x,
      w = (v.y * x - v.x * y),
    )

  inline infix def v(v: Pga2dVector): Pga2dLine = antiWedge(v)

  inline infix def join(v: Pga2dVector): Pga2dLine = antiWedge(v)

  infix def antiWedge(v: Pga2dPoint): Pga2dLine =
    Pga2dLine(
      x = (y - v.y),
      y = (v.x - x),
      w = (v.y * x - v.x * y),
    )

  inline infix def v(v: Pga2dPoint): Pga2dLine = antiWedge(v)

  inline infix def join(v: Pga2dPoint): Pga2dLine = antiWedge(v)

  infix def antiWedge(v: Pga2dLineIdeal): Double =
    (v.x * x + v.y * y)

  inline infix def v(v: Pga2dLineIdeal): Double = antiWedge(v)

  inline infix def join(v: Pga2dLineIdeal): Double = antiWedge(v)

  infix def antiWedge(v: Pga2dPseudoScalar): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = v.i * x,
      y = v.i * y,
      w = v.i,
    )

  inline infix def v(v: Pga2dPseudoScalar): Pga2dProjectivePoint = antiWedge(v)

  inline infix def join(v: Pga2dPseudoScalar): Pga2dProjectivePoint = antiWedge(v)

  infix def antiWedge(v: Pga2dPointCenter.type): Pga2dLineIdeal =
    Pga2dLineIdeal(
      x = y,
      y = -x,
    )

  inline infix def v(v: Pga2dPointCenter.type): Pga2dLineIdeal = antiWedge(v)

  inline infix def join(v: Pga2dPointCenter.type): Pga2dLineIdeal = antiWedge(v)

  infix def sandwich(v: Pga2dMotor): Pga2dMotor =
    Pga2dMotor(
      s = v.s,
      wx = (-v.wx + 2.0 * v.xy * y),
      wy = (-v.wy - 2.0 * v.xy * x),
      xy = v.xy,
    )

  infix def sandwich(v: Pga2dLine): Pga2dLine =
    Pga2dLine(
      x = -v.x,
      y = -v.y,
      w = (v.w + 2.0 * v.x * x + 2.0 * v.y * y),
    )

  infix def sandwich(v: Pga2dProjectivePoint): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = (-v.x + 2.0 * v.w * x),
      y = (-v.y + 2.0 * v.w * y),
      w = v.w,
    )

  infix def sandwich(v: Pga2dRotor): Pga2dMotor =
    Pga2dMotor(
      s = v.s,
      wx = 2.0 * v.xy * y,
      wy = -2.0 * v.xy * x,
      xy = v.xy,
    )

  infix def sandwich(v: Pga2dProjectiveTranslator): Pga2dProjectiveTranslator =
    Pga2dProjectiveTranslator(
      s = v.s,
      wx = -v.wx,
      wy = -v.wy,
    )

  infix def sandwich(v: Pga2dTranslator): Pga2dTranslator =
    Pga2dTranslator(
      wx = -v.wx,
      wy = -v.wy,
    )

  infix def sandwich(v: Pga2dVector): Pga2dVector =
    -v

  infix def sandwich(v: Pga2dPoint): Pga2dPoint =
    Pga2dPoint(
      x = (-v.x + 2.0 * x),
      y = (-v.y + 2.0 * y),
    )

  infix def sandwich(v: Pga2dLineIdeal): Pga2dLine =
    Pga2dLine(
      x = -v.x,
      y = -v.y,
      w = 2.0 * (v.x * x + v.y * y),
    )

  infix def sandwich(v: Pga2dPseudoScalar): Pga2dPseudoScalar =
    v

  infix def sandwich(v: Pga2dPointCenter.type): Pga2dPoint =
    Pga2dPoint(
      x = 2.0 * x,
      y = 2.0 * y,
    )

  infix def reverseSandwich(v: Pga2dMotor): Pga2dMotor =
    Pga2dMotor(
      s = v.s,
      wx = (-v.wx + 2.0 * v.xy * y),
      wy = (-v.wy - 2.0 * v.xy * x),
      xy = v.xy,
    )

  infix def reverseSandwich(v: Pga2dLine): Pga2dLine =
    Pga2dLine(
      x = -v.x,
      y = -v.y,
      w = (v.w + 2.0 * v.x * x + 2.0 * v.y * y),
    )

  infix def reverseSandwich(v: Pga2dProjectivePoint): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = (-v.x + 2.0 * v.w * x),
      y = (-v.y + 2.0 * v.w * y),
      w = v.w,
    )

  infix def reverseSandwich(v: Pga2dRotor): Pga2dMotor =
    Pga2dMotor(
      s = v.s,
      wx = 2.0 * v.xy * y,
      wy = -2.0 * v.xy * x,
      xy = v.xy,
    )

  infix def reverseSandwich(v: Pga2dProjectiveTranslator): Pga2dProjectiveTranslator =
    Pga2dProjectiveTranslator(
      s = v.s,
      wx = -v.wx,
      wy = -v.wy,
    )

  infix def reverseSandwich(v: Pga2dTranslator): Pga2dTranslator =
    Pga2dTranslator(
      wx = -v.wx,
      wy = -v.wy,
    )

  infix def reverseSandwich(v: Pga2dVector): Pga2dVector =
    -v

  infix def reverseSandwich(v: Pga2dPoint): Pga2dPoint =
    Pga2dPoint(
      x = (-v.x + 2.0 * x),
      y = (-v.y + 2.0 * y),
    )

  infix def reverseSandwich(v: Pga2dLineIdeal): Pga2dLine =
    Pga2dLine(
      x = -v.x,
      y = -v.y,
      w = 2.0 * (v.x * x + v.y * y),
    )

  infix def reverseSandwich(v: Pga2dPseudoScalar): Pga2dPseudoScalar =
    v

  infix def reverseSandwich(v: Pga2dPointCenter.type): Pga2dPoint =
    Pga2dPoint(
      x = 2.0 * x,
      y = 2.0 * y,
    )

  infix def cross(v: Pga2dMotor): Pga2dVector =
    Pga2dVector(
      x = (v.wx - v.xy * y),
      y = (v.wy + v.xy * x),
    )

  infix def cross(v: Pga2dLine): Pga2dLine =
    Pga2dLine(
      x = v.y,
      y = -v.x,
      w = (v.x * y - v.y * x),
    )

  infix def cross(v: Pga2dProjectivePoint): Pga2dVector =
    Pga2dVector(
      x = (v.y - v.w * y),
      y = (-v.x + v.w * x),
    )

  infix def cross(v: Pga2dRotor): Pga2dVector =
    Pga2dVector(
      x = -v.xy * y,
      y = v.xy * x,
    )

  infix def cross(v: Pga2dProjectiveTranslator): Pga2dVector =
    Pga2dVector(
      x = v.wx,
      y = v.wy,
    )

  infix def cross(v: Pga2dTranslator): Pga2dVector =
    Pga2dVector(
      x = v.wx,
      y = v.wy,
    )

  infix def cross(v: Pga2dVector): Pga2dVector =
    Pga2dVector(
      x = v.y,
      y = -v.x,
    )

  infix def cross(v: Pga2dPoint): Pga2dVector =
    Pga2dVector(
      x = (v.y - y),
      y = (x - v.x),
    )

  infix def cross(v: Pga2dLineIdeal): Pga2dLine =
    Pga2dLine(
      x = v.y,
      y = -v.x,
      w = (v.x * y - v.y * x),
    )

  infix def cross(v: Pga2dPointCenter.type): Pga2dVector =
    Pga2dVector(
      x = -y,
      y = x,
    )


object Pga2dPoint:

  inline val componentsCount = 2

  val center: Pga2dPoint =
    Pga2dPoint(0.0, 0.0)

  def blade2(wx: Double, wy: Double): Pga2dPoint =
    Pga2dPoint(
      x = -wy,
      y = wx,
    )

  def interpolate(a: Pga2dPoint, b: Pga2dPoint, t: Double): Pga2dPoint =
    (a.toVectorUnsafe * (1.0 - t) + b.toVectorUnsafe * t).toPointUnsafe

  def mid(a: Pga2dPoint, b: Pga2dPoint): Pga2dPoint =
    Pga2dPoint(
      x = (a.x + b.x) * 0.5,
      y = (a.y + b.y) * 0.5,
    )

  def mid(a: Pga2dPoint, b: Pga2dPoint, c: Pga2dPoint): Pga2dPoint =
    val m = 1.0 / 3.0
    Pga2dPoint(
      x = (a.x + b.x + c.x) * m,
      y = (a.y + b.y + c.y) * m,
    )