package me.kright.gametools.pga2d

import scala.annotation.targetName
import me.kright.gametools.flatarray.FlatDoubleSerializer


/**
 * The center of coordinates as a singleton object: a Pga2dPoint with x = y = 0 and w = 1.
 *
 * Constant fields: x = 0.0, y = 0.0, w = 1.0.
 * Basis blade coefficients: wy = 0.0, wx = 0.0, xy = 1.0.
 *
 * Generated by pgaNdCodeGen (me.kright.gametools.pga.codegen.scala.pga2d.runScalaCodeGen).
 * Do not edit by hand: change the generator and re-run it.
 */
object Pga2dPointCenter:

  inline val componentsCount = 0
  inline val x = 0.0
  inline val y = 0.0
  inline val w = 1.0

  inline def wy: Double = 0.0

  inline def wx: Double = 0.0

  inline def xy: Double = 1.0

  override def toString: String =
    "Pga2dPointCenter"

  def dual: Pga2dLine =
    Pga2dLine(
      x = 0.0,
      y = 0.0,
      w = 1.0,
    )

  def bulk: Pga2dPointCenter.type =
    Pga2dPointCenter

  @targetName("unaryMinus")
  def unary_- : Pga2dRotor =
    Pga2dRotor(
      s = 0.0,
      xy = -1.0,
    )

  def reverse: Pga2dRotor =
    Pga2dRotor(
      s = 0.0,
      xy = -1.0,
    )

  def antiReverse: Pga2dPointCenter.type =
    this

  def bulkNormSquare: Double =
    1.0

  def bulkNorm: Double =
    Math.sqrt(bulkNormSquare)

  def normalizedByBulk =
    this / bulkNorm

  def normSquare: Double =
    1.0

  def norm: Double =
    Math.sqrt(normSquare)

  def normalizedByNorm =
    this / norm

  @targetName("times")
  def *(v: Double): Pga2dRotor =
    Pga2dRotor(
      s = 0.0,
      xy = v,
    )

  @targetName("div")
  def /(v: Double): Pga2dRotor =
    this * (1.0 / v)

  @targetName("plus")
  def +(v: Pga2dPointCenter.type): Pga2dRotor =
    Pga2dRotor(
      s = 0.0,
      xy = 2.0,
    )

  def madd(v: Pga2dPointCenter.type, mult: Double): Pga2dRotor =
    Pga2dRotor(
      s = 0.0,
      xy = (1.0 + mult),
    )

  def multiplyElementwise(v: Pga2dPointCenter.type): Pga2dPointCenter.type =
    Pga2dPointCenter

  def toMultivector: Pga2dMultivector =
    Pga2dMultivector(
      s = 0.0,
      w = 0.0,
      x = 0.0,
      y = 0.0,
      wx = 0.0,
      wy = 0.0,
      xy = 1.0,
      i = 0.0,
    )

  def toMotor: Pga2dMotor =
    Pga2dMotor(
      s = 0.0,
      wx = 0.0,
      wy = 0.0,
      xy = 1.0,
    )

  def toProjectivePoint: Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = 0.0,
      y = 0.0,
      w = 1.0,
    )

  def toRotor: Pga2dRotor =
    Pga2dRotor(
      s = 0.0,
      xy = 1.0,
    )

  def toProjectiveTranslatorUnsafe: Pga2dProjectiveTranslator =
    Pga2dProjectiveTranslator(
      s = 0.0,
      wx = 0.0,
      wy = 0.0,
    )

  def toTranslatorUnsafe: Pga2dTranslator =
    Pga2dTranslator(
      wx = 0.0,
      wy = 0.0,
    )

  def toVectorUnsafe: Pga2dVector =
    Pga2dVector(
      x = 0.0,
      y = 0.0,
    )

  def toPoint: Pga2dPoint =
    Pga2dPoint(
      x = 0.0,
      y = 0.0,
    )

  /** fused line.dot(point).geometric(line) */
  def projectOntoLine(line: Pga2dLine): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = line.w * line.x,
      y = line.w * line.y,
      w = (-line.x * line.x - line.y * line.y),
    )

  infix def geometric(v: Pga2dMotor): Pga2dMotor =
    Pga2dMotor(
      s = -v.xy,
      wx = v.wy,
      wy = -v.wx,
      xy = v.s,
    )

  infix def geometric(v: Pga2dLine): Pga2dMultivector =
    Pga2dMultivector(
      s = 0.0,
      w = 0.0,
      x = v.y,
      y = -v.x,
      wx = 0.0,
      wy = 0.0,
      xy = 0.0,
      i = v.w,
    )

  infix def geometric(v: Pga2dProjectivePoint): Pga2dProjectiveTranslator =
    Pga2dProjectiveTranslator(
      s = -v.w,
      wx = -v.x,
      wy = -v.y,
    )

  infix def geometric(v: Pga2dRotor): Pga2dRotor =
    Pga2dRotor(
      s = -v.xy,
      xy = v.s,
    )

  infix def geometric(v: Pga2dProjectiveTranslator): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = v.wx,
      y = v.wy,
      w = v.s,
    )

  infix def geometric(v: Pga2dTranslator): Pga2dPoint =
    Pga2dPoint(
      x = v.wx,
      y = v.wy,
    )

  infix def geometric(v: Pga2dVector): Pga2dVector =
    Pga2dVector(
      x = v.y,
      y = -v.x,
    )

  infix def geometric(v: Pga2dPoint): Pga2dProjectiveTranslator =
    Pga2dProjectiveTranslator(
      s = -1.0,
      wx = -v.x,
      wy = -v.y,
    )

  infix def geometric(v: Pga2dLineIdeal): Pga2dLineIdeal =
    Pga2dLineIdeal(
      x = v.y,
      y = -v.x,
    )

  infix def geometric(v: Pga2dPseudoScalar): Pga2dLine =
    Pga2dLine(
      x = 0.0,
      y = 0.0,
      w = -v.i,
    )

  infix def geometric(v: Pga2dPointCenter.type): Double =
    -1.0

  infix def dot(v: Pga2dMotor): Pga2dRotor =
    Pga2dRotor(
      s = -v.xy,
      xy = v.s,
    )

  infix def dot(v: Pga2dLine): Pga2dLineIdeal =
    Pga2dLineIdeal(
      x = v.y,
      y = -v.x,
    )

  infix def dot(v: Pga2dProjectivePoint): Double =
    -v.w

  infix def dot(v: Pga2dRotor): Pga2dRotor =
    Pga2dRotor(
      s = -v.xy,
      xy = v.s,
    )

  infix def dot(v: Pga2dProjectiveTranslator): Pga2dRotor =
    Pga2dRotor(
      s = 0.0,
      xy = v.s,
    )

  infix def dot(v: Pga2dTranslator): Pga2dPointCenter.type =
    this

  infix def dot(v: Pga2dPoint): Double =
    -1.0

  infix def dot(v: Pga2dLineIdeal): Pga2dLineIdeal =
    Pga2dLineIdeal(
      x = v.y,
      y = -v.x,
    )

  infix def dot(v: Pga2dPseudoScalar): Pga2dLine =
    Pga2dLine(
      x = 0.0,
      y = 0.0,
      w = -v.i,
    )

  infix def dot(v: Pga2dPointCenter.type): Double =
    -1.0

  infix def wedge(v: Pga2dMotor): Pga2dRotor =
    Pga2dRotor(
      s = 0.0,
      xy = v.s,
    )

  inline infix def ^(v: Pga2dMotor): Pga2dRotor = wedge(v)

  inline infix def meet(v: Pga2dMotor): Pga2dRotor = wedge(v)

  infix def wedge(v: Pga2dLine): Pga2dPseudoScalar =
    Pga2dPseudoScalar(
      i = v.w,
    )

  inline infix def ^(v: Pga2dLine): Pga2dPseudoScalar = wedge(v)

  inline infix def meet(v: Pga2dLine): Pga2dPseudoScalar = wedge(v)

  infix def wedge(v: Pga2dRotor): Pga2dRotor =
    Pga2dRotor(
      s = 0.0,
      xy = v.s,
    )

  inline infix def ^(v: Pga2dRotor): Pga2dRotor = wedge(v)

  inline infix def meet(v: Pga2dRotor): Pga2dRotor = wedge(v)

  infix def wedge(v: Pga2dProjectiveTranslator): Pga2dRotor =
    Pga2dRotor(
      s = 0.0,
      xy = v.s,
    )

  inline infix def ^(v: Pga2dProjectiveTranslator): Pga2dRotor = wedge(v)

  inline infix def meet(v: Pga2dProjectiveTranslator): Pga2dRotor = wedge(v)

  infix def wedge(v: Pga2dTranslator): Pga2dPointCenter.type =
    this

  inline infix def ^(v: Pga2dTranslator): Pga2dPointCenter.type = wedge(v)

  inline infix def meet(v: Pga2dTranslator): Pga2dPointCenter.type = wedge(v)

  infix def antiGeometric(v: Pga2dMotor): Pga2dLineIdeal =
    Pga2dLineIdeal(
      x = -v.wx,
      y = -v.wy,
    )

  infix def antiGeometric(v: Pga2dLine): Double =
    v.w

  infix def antiGeometric(v: Pga2dProjectivePoint): Pga2dLineIdeal =
    Pga2dLineIdeal(
      x = -v.y,
      y = v.x,
    )

  infix def antiGeometric(v: Pga2dProjectiveTranslator): Pga2dLineIdeal =
    Pga2dLineIdeal(
      x = -v.wx,
      y = -v.wy,
    )

  infix def antiGeometric(v: Pga2dTranslator): Pga2dLineIdeal =
    Pga2dLineIdeal(
      x = -v.wx,
      y = -v.wy,
    )

  infix def antiGeometric(v: Pga2dVector): Pga2dLineIdeal =
    Pga2dLineIdeal(
      x = -v.y,
      y = v.x,
    )

  infix def antiGeometric(v: Pga2dPoint): Pga2dLineIdeal =
    Pga2dLineIdeal(
      x = -v.y,
      y = v.x,
    )

  infix def antiGeometric(v: Pga2dPseudoScalar): Pga2dRotor =
    Pga2dRotor(
      s = 0.0,
      xy = v.i,
    )

  infix def antiDot(v: Pga2dPseudoScalar): Pga2dRotor =
    Pga2dRotor(
      s = 0.0,
      xy = v.i,
    )

  infix def antiWedge(v: Pga2dMotor): Pga2dLineIdeal =
    Pga2dLineIdeal(
      x = -v.wx,
      y = -v.wy,
    )

  inline infix def v(v: Pga2dMotor): Pga2dLineIdeal = antiWedge(v)

  inline infix def join(v: Pga2dMotor): Pga2dLineIdeal = antiWedge(v)

  infix def antiWedge(v: Pga2dLine): Double =
    v.w

  inline infix def v(v: Pga2dLine): Double = antiWedge(v)

  inline infix def join(v: Pga2dLine): Double = antiWedge(v)

  infix def antiWedge(v: Pga2dProjectivePoint): Pga2dLineIdeal =
    Pga2dLineIdeal(
      x = -v.y,
      y = v.x,
    )

  inline infix def v(v: Pga2dProjectivePoint): Pga2dLineIdeal = antiWedge(v)

  inline infix def join(v: Pga2dProjectivePoint): Pga2dLineIdeal = antiWedge(v)

  infix def antiWedge(v: Pga2dProjectiveTranslator): Pga2dLineIdeal =
    Pga2dLineIdeal(
      x = -v.wx,
      y = -v.wy,
    )

  inline infix def v(v: Pga2dProjectiveTranslator): Pga2dLineIdeal = antiWedge(v)

  inline infix def join(v: Pga2dProjectiveTranslator): Pga2dLineIdeal = antiWedge(v)

  infix def antiWedge(v: Pga2dTranslator): Pga2dLineIdeal =
    Pga2dLineIdeal(
      x = -v.wx,
      y = -v.wy,
    )

  inline infix def v(v: Pga2dTranslator): Pga2dLineIdeal = antiWedge(v)

  inline infix def join(v: Pga2dTranslator): Pga2dLineIdeal = antiWedge(v)

  infix def antiWedge(v: Pga2dVector): Pga2dLineIdeal =
    Pga2dLineIdeal(
      x = -v.y,
      y = v.x,
    )

  inline infix def v(v: Pga2dVector): Pga2dLineIdeal = antiWedge(v)

  inline infix def join(v: Pga2dVector): Pga2dLineIdeal = antiWedge(v)

  infix def antiWedge(v: Pga2dPoint): Pga2dLineIdeal =
    Pga2dLineIdeal(
      x = -v.y,
      y = v.x,
    )

  inline infix def v(v: Pga2dPoint): Pga2dLineIdeal = antiWedge(v)

  inline infix def join(v: Pga2dPoint): Pga2dLineIdeal = antiWedge(v)

  infix def antiWedge(v: Pga2dPseudoScalar): Pga2dRotor =
    Pga2dRotor(
      s = 0.0,
      xy = v.i,
    )

  inline infix def v(v: Pga2dPseudoScalar): Pga2dRotor = antiWedge(v)

  inline infix def join(v: Pga2dPseudoScalar): Pga2dRotor = antiWedge(v)

  infix def sandwich(v: Pga2dMotor): Pga2dMotor =
    Pga2dMotor(
      s = v.s,
      wx = -v.wx,
      wy = -v.wy,
      xy = v.xy,
    )

  infix def sandwich(v: Pga2dLine): Pga2dLine =
    Pga2dLine(
      x = -v.x,
      y = -v.y,
      w = v.w,
    )

  infix def sandwich(v: Pga2dProjectivePoint): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = -v.x,
      y = -v.y,
      w = v.w,
    )

  infix def sandwich(v: Pga2dRotor): Pga2dRotor =
    Pga2dRotor(
      s = v.s,
      xy = v.xy,
    )

  infix def sandwich(v: Pga2dProjectiveTranslator): Pga2dProjectiveTranslator =
    Pga2dProjectiveTranslator(
      s = v.s,
      wx = -v.wx,
      wy = -v.wy,
    )

  infix def sandwich(v: Pga2dTranslator): Pga2dTranslator =
    Pga2dTranslator(
      wx = -v.wx,
      wy = -v.wy,
    )

  infix def sandwich(v: Pga2dVector): Pga2dVector =
    -v

  infix def sandwich(v: Pga2dPoint): Pga2dPoint =
    Pga2dPoint(
      x = -v.x,
      y = -v.y,
    )

  infix def sandwich(v: Pga2dLineIdeal): Pga2dLineIdeal =
    Pga2dLineIdeal(
      x = -v.x,
      y = -v.y,
    )

  infix def sandwich(v: Pga2dPseudoScalar): Pga2dPseudoScalar =
    v

  infix def sandwich(v: Pga2dPointCenter.type): Pga2dPointCenter.type =
    this

  infix def reverseSandwich(v: Pga2dMotor): Pga2dMotor =
    Pga2dMotor(
      s = v.s,
      wx = -v.wx,
      wy = -v.wy,
      xy = v.xy,
    )

  infix def reverseSandwich(v: Pga2dLine): Pga2dLine =
    Pga2dLine(
      x = -v.x,
      y = -v.y,
      w = v.w,
    )

  infix def reverseSandwich(v: Pga2dProjectivePoint): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = -v.x,
      y = -v.y,
      w = v.w,
    )

  infix def reverseSandwich(v: Pga2dRotor): Pga2dRotor =
    Pga2dRotor(
      s = v.s,
      xy = v.xy,
    )

  infix def reverseSandwich(v: Pga2dProjectiveTranslator): Pga2dProjectiveTranslator =
    Pga2dProjectiveTranslator(
      s = v.s,
      wx = -v.wx,
      wy = -v.wy,
    )

  infix def reverseSandwich(v: Pga2dTranslator): Pga2dTranslator =
    Pga2dTranslator(
      wx = -v.wx,
      wy = -v.wy,
    )

  infix def reverseSandwich(v: Pga2dVector): Pga2dVector =
    -v

  infix def reverseSandwich(v: Pga2dPoint): Pga2dPoint =
    Pga2dPoint(
      x = -v.x,
      y = -v.y,
    )

  infix def reverseSandwich(v: Pga2dLineIdeal): Pga2dLineIdeal =
    Pga2dLineIdeal(
      x = -v.x,
      y = -v.y,
    )

  infix def reverseSandwich(v: Pga2dPseudoScalar): Pga2dPseudoScalar =
    v

  infix def reverseSandwich(v: Pga2dPointCenter.type): Pga2dPointCenter.type =
    this

  infix def cross(v: Pga2dMotor): Pga2dVector =
    Pga2dVector(
      x = v.wx,
      y = v.wy,
    )

  infix def cross(v: Pga2dLine): Pga2dLineIdeal =
    Pga2dLineIdeal(
      x = v.y,
      y = -v.x,
    )

  infix def cross(v: Pga2dProjectivePoint): Pga2dVector =
    Pga2dVector(
      x = v.y,
      y = -v.x,
    )

  infix def cross(v: Pga2dProjectiveTranslator): Pga2dVector =
    Pga2dVector(
      x = v.wx,
      y = v.wy,
    )

  infix def cross(v: Pga2dTranslator): Pga2dVector =
    Pga2dVector(
      x = v.wx,
      y = v.wy,
    )

  infix def cross(v: Pga2dVector): Pga2dVector =
    Pga2dVector(
      x = v.y,
      y = -v.x,
    )

  infix def cross(v: Pga2dPoint): Pga2dVector =
    Pga2dVector(
      x = v.y,
      y = -v.x,
    )

  infix def cross(v: Pga2dLineIdeal): Pga2dLineIdeal =
    Pga2dLineIdeal(
      x = v.y,
      y = -v.x,
    )