package me.kright.gametools.pga2d

import scala.annotation.targetName
import me.kright.gametools.mathutil.FlatDoubleSerializer


/**
 * A point with three homogeneous coordinates: (x/w, y/w) when w != 0, or an ideal point (a direction) when w == 0.
 * The grade-2 element of 2d PGA, stored in dual representation.
 * projectivePoint.exp() is a Pga2dMotor (rotation around the point), and motor.log() is a Pga2dProjectivePoint.
 *
 * Variable fields: x, y, w.
 * Basis blade coefficients: wy = -x, wx = y, xy = w.
 *
 * Generated by pgaNdCodeGen (me.kright.gametools.pga.codegen.scala.pga2d.runScalaCodeGen).
 * Do not edit by hand: change the generator and re-run it.
 */
final case class Pga2dProjectivePoint(x: Double = 0.0,
                                      y: Double = 0.0,
                                      w: Double = 0.0) derives CanEqual, FlatDoubleSerializer:

  inline def wy: Double = -x

  inline def wx: Double = y

  inline def xy: Double = w

  override def toString: String =
    s"Pga2dProjectivePoint(x = $x, y = $y, w = $w)"

  def dual: Pga2dLine =
    Pga2dLine(
      x = x,
      y = y,
      w = w,
    )

  def weight: Pga2dVector =
    Pga2dVector(
      x = x,
      y = y,
    )

  def bulk: Pga2dRotor =
    Pga2dRotor(
      s = 0.0,
      xy = w,
    )

  @targetName("unaryMinus")
  def unary_- : Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = -x,
      y = -y,
      w = -w,
    )

  def reverse: Pga2dProjectivePoint =
    -this

  def antiReverse: Pga2dProjectivePoint =
    this

  def bulkNormSquare: Double =
    w * w

  def bulkNorm: Double =
    Math.sqrt(bulkNormSquare)

  def normalizedByBulk =
    this / bulkNorm

  def weightNormSquare: Double =
    (x * x + y * y)

  def weightNorm: Double =
    Math.sqrt(weightNormSquare)

  def normalizedByWeight =
    this / weightNorm

  def normSquare: Double =
    (w * w + x * x + y * y)

  def norm: Double =
    Math.sqrt(normSquare)

  def normalizedByNorm =
    this / norm

  @targetName("times")
  def *(v: Double): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = v * x,
      y = v * y,
      w = v * w,
    )

  @targetName("div")
  def /(v: Double): Pga2dProjectivePoint =
    this * (1.0 / v)

  @targetName("plus")
  def +(v: Pga2dProjectivePoint): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = (v.x + x),
      y = (v.y + y),
      w = (v.w + w),
    )

  @targetName("minus")
  def -(v: Pga2dProjectivePoint): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = (x - v.x),
      y = (y - v.y),
      w = (w - v.w),
    )

  def madd(v: Pga2dProjectivePoint, mult: Double): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = (x + mult * v.x),
      y = (y + mult * v.y),
      w = (w + mult * v.w),
    )

  @targetName("plus")
  def +(v: Pga2dPoint): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = (v.x + x),
      y = (v.y + y),
      w = (1.0 + w),
    )

  @targetName("minus")
  def -(v: Pga2dPoint): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = (x - v.x),
      y = (y - v.y),
      w = (-1.0 + w),
    )

  def madd(v: Pga2dPoint, mult: Double): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = (x + mult * v.x),
      y = (y + mult * v.y),
      w = (mult + w),
    )

  @targetName("plus")
  def +(v: Pga2dVector): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = (v.x + x),
      y = (v.y + y),
      w = w,
    )

  @targetName("minus")
  def -(v: Pga2dVector): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = (x - v.x),
      y = (y - v.y),
      w = w,
    )

  def madd(v: Pga2dVector, mult: Double): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = (x + mult * v.x),
      y = (y + mult * v.y),
      w = w,
    )

  def multiplyElementwise(v: Pga2dProjectivePoint): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = -v.x * x,
      y = v.y * y,
      w = v.w * w,
    )

  def exp(): Pga2dMotor =
    val len = bulkNorm
    val cos = Math.cos(len)

    // sin(x)/x = 1 - x^2/6 + x^4/120 - ...; at x <= 1e-5 the dropped x^4/120 <= 8.4e-23
    // relative term is far below 2^-53, so the second-order form is exact in double
    val sinDivLen = if (len > 1e-5) {
      Math.sin(len) / len
    } else 1.0 - (len * len) / 6.0

    Pga2dMotor(
      s = cos,
      wx = sinDivLen * y,
      wy = -sinDivLen * x,
      xy = sinDivLen * w,
    )

  def exp(t: Double): Pga2dMotor =
    val len = bulkNorm * Math.abs(t)
    val cos = Math.cos(len)

    // sin(x)/x = 1 - x^2/6 + x^4/120 - ...; at x <= 1e-5 the dropped x^4/120 <= 8.4e-23
    // relative term is far below 2^-53, so the second-order form is exact in double
    val sinDivLen = if (len > 1e-5) {
      Math.sin(len) / len
    } else 1.0 - (len * len) / 6.0

    Pga2dMotor(
      s = cos,
      wx = sinDivLen * t * y,
      wy = -sinDivLen * t * x,
      xy = sinDivLen * t * w,
    )

  def toMultivector: Pga2dMultivector =
    Pga2dMultivector(
      s = 0.0,
      w = 0.0,
      x = 0.0,
      y = 0.0,
      wx = y,
      wy = -x,
      xy = w,
      i = 0.0,
    )

  def toMotor: Pga2dMotor =
    Pga2dMotor(
      s = 0.0,
      wx = y,
      wy = -x,
      xy = w,
    )

  def toRotorUnsafe: Pga2dRotor =
    Pga2dRotor(
      s = 0.0,
      xy = w,
    )

  def toProjectiveTranslatorUnsafe: Pga2dProjectiveTranslator =
    Pga2dProjectiveTranslator(
      s = 0.0,
      wx = y,
      wy = -x,
    )

  def toTranslatorUnsafe: Pga2dTranslator =
    Pga2dTranslator(
      wx = y,
      wy = -x,
    )

  def toVectorUnsafe: Pga2dVector =
    Pga2dVector(
      x = x,
      y = y,
    )

  def toPointUnsafe: Pga2dPoint =
    Pga2dPoint(
      x = x,
      y = y,
    )

  def toPoint: Pga2dPoint =
    val mult = (1.0 / w)
    Pga2dPoint(
      x = mult * x,
      y = mult * y,
    )

  /** fused line.dot(point).geometric(line) */
  def projectOntoLine(line: Pga2dLine): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = (line.x * (line.w * w + line.y * y) - line.y * line.y * x),
      y = (line.y * (line.w * w + line.x * x) - line.x * line.x * y),
      w = w * (-line.x * line.x - line.y * line.y),
    )

  infix def geometric(v: Pga2dMotor): Pga2dMotor =
    Pga2dMotor(
      s = -v.xy * w,
      wx = (v.s * y + v.wy * w + v.xy * x),
      wy = (v.xy * y - v.s * x - v.wx * w),
      xy = v.s * w,
    )

  infix def geometric(v: Pga2dLine): Pga2dMultivector =
    Pga2dMultivector(
      s = 0.0,
      w = (v.x * y - v.y * x),
      x = v.y * w,
      y = -v.x * w,
      wx = 0.0,
      wy = 0.0,
      xy = 0.0,
      i = (v.w * w + v.x * x + v.y * y),
    )

  infix def geometric(v: Pga2dProjectivePoint): Pga2dProjectiveTranslator =
    Pga2dProjectiveTranslator(
      s = -v.w * w,
      wx = (v.w * x - v.x * w),
      wy = (v.w * y - v.y * w),
    )

  infix def geometric(v: Pga2dRotor): Pga2dMotor =
    Pga2dMotor(
      s = -v.xy * w,
      wx = (v.s * y + v.xy * x),
      wy = (v.xy * y - v.s * x),
      xy = v.s * w,
    )

  infix def geometric(v: Pga2dProjectiveTranslator): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = (v.s * x + v.wx * w),
      y = (v.s * y + v.wy * w),
      w = v.s * w,
    )

  infix def geometric(v: Pga2dTranslator): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = (x + v.wx * w),
      y = (y + v.wy * w),
      w = w,
    )

  infix def geometric(v: Pga2dVector): Pga2dVector =
    Pga2dVector(
      x = v.y * w,
      y = -v.x * w,
    )

  infix def geometric(v: Pga2dPoint): Pga2dProjectiveTranslator =
    Pga2dProjectiveTranslator(
      s = -w,
      wx = (x - v.x * w),
      wy = (y - v.y * w),
    )

  infix def geometric(v: Pga2dLineIdeal): Pga2dMultivector =
    Pga2dMultivector(
      s = 0.0,
      w = (v.x * y - v.y * x),
      x = v.y * w,
      y = -v.x * w,
      wx = 0.0,
      wy = 0.0,
      xy = 0.0,
      i = (v.x * x + v.y * y),
    )

  infix def geometric(v: Pga2dPseudoScalar): Pga2dLine =
    Pga2dLine(
      x = 0.0,
      y = 0.0,
      w = -v.i * w,
    )

  infix def geometric(v: Pga2dPointCenter.type): Pga2dProjectiveTranslator =
    Pga2dProjectiveTranslator(
      s = -w,
      wx = x,
      wy = y,
    )

  infix def dot(v: Pga2dMotor): Pga2dMotor =
    Pga2dMotor(
      s = -v.xy * w,
      wx = v.s * y,
      wy = -v.s * x,
      xy = v.s * w,
    )

  infix def dot(v: Pga2dLine): Pga2dLine =
    Pga2dLine(
      x = v.y * w,
      y = -v.x * w,
      w = (v.x * y - v.y * x),
    )

  infix def dot(v: Pga2dProjectivePoint): Double =
    -v.w * w

  infix def dot(v: Pga2dRotor): Pga2dMotor =
    Pga2dMotor(
      s = -v.xy * w,
      wx = v.s * y,
      wy = -v.s * x,
      xy = v.s * w,
    )

  infix def dot(v: Pga2dProjectiveTranslator): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = v.s * x,
      y = v.s * y,
      w = v.s * w,
    )

  infix def dot(v: Pga2dTranslator): Pga2dProjectivePoint =
    this

  infix def dot(v: Pga2dPoint): Double =
    -w

  infix def dot(v: Pga2dLineIdeal): Pga2dLine =
    Pga2dLine(
      x = v.y * w,
      y = -v.x * w,
      w = (v.x * y - v.y * x),
    )

  infix def dot(v: Pga2dPseudoScalar): Pga2dLine =
    Pga2dLine(
      x = 0.0,
      y = 0.0,
      w = -v.i * w,
    )

  infix def dot(v: Pga2dPointCenter.type): Double =
    -w

  infix def wedge(v: Pga2dMotor): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = v.s * x,
      y = v.s * y,
      w = v.s * w,
    )

  inline infix def ^(v: Pga2dMotor): Pga2dProjectivePoint = wedge(v)

  inline infix def meet(v: Pga2dMotor): Pga2dProjectivePoint = wedge(v)

  infix def wedge(v: Pga2dLine): Pga2dPseudoScalar =
    Pga2dPseudoScalar(
      i = (v.w * w + v.x * x + v.y * y),
    )

  inline infix def ^(v: Pga2dLine): Pga2dPseudoScalar = wedge(v)

  inline infix def meet(v: Pga2dLine): Pga2dPseudoScalar = wedge(v)

  infix def wedge(v: Pga2dRotor): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = v.s * x,
      y = v.s * y,
      w = v.s * w,
    )

  inline infix def ^(v: Pga2dRotor): Pga2dProjectivePoint = wedge(v)

  inline infix def meet(v: Pga2dRotor): Pga2dProjectivePoint = wedge(v)

  infix def wedge(v: Pga2dProjectiveTranslator): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = v.s * x,
      y = v.s * y,
      w = v.s * w,
    )

  inline infix def ^(v: Pga2dProjectiveTranslator): Pga2dProjectivePoint = wedge(v)

  inline infix def meet(v: Pga2dProjectiveTranslator): Pga2dProjectivePoint = wedge(v)

  infix def wedge(v: Pga2dTranslator): Pga2dProjectivePoint =
    this

  inline infix def ^(v: Pga2dTranslator): Pga2dProjectivePoint = wedge(v)

  inline infix def meet(v: Pga2dTranslator): Pga2dProjectivePoint = wedge(v)

  infix def wedge(v: Pga2dLineIdeal): Pga2dPseudoScalar =
    Pga2dPseudoScalar(
      i = (v.x * x + v.y * y),
    )

  inline infix def ^(v: Pga2dLineIdeal): Pga2dPseudoScalar = wedge(v)

  inline infix def meet(v: Pga2dLineIdeal): Pga2dPseudoScalar = wedge(v)

  infix def antiGeometric(v: Pga2dMotor): Pga2dMultivector =
    Pga2dMultivector(
      s = 0.0,
      w = (v.wx * x + v.wy * y),
      x = (v.s * x + v.xy * y - v.wx * w),
      y = (v.s * y - v.wy * w - v.xy * x),
      wx = 0.0,
      wy = 0.0,
      xy = 0.0,
      i = (v.wx * y - v.wy * x),
    )

  infix def antiGeometric(v: Pga2dLine): Pga2dMotor =
    Pga2dMotor(
      s = (v.w * w + v.x * x + v.y * y),
      wx = v.w * x,
      wy = v.w * y,
      xy = (v.x * y - v.y * x),
    )

  infix def antiGeometric(v: Pga2dProjectivePoint): Pga2dMultivector =
    Pga2dMultivector(
      s = 0.0,
      w = (v.y * x - v.x * y),
      x = (v.w * y - v.y * w),
      y = (v.x * w - v.w * x),
      wx = 0.0,
      wy = 0.0,
      xy = 0.0,
      i = (v.x * x + v.y * y),
    )

  infix def antiGeometric(v: Pga2dRotor): Pga2dLineIdeal =
    Pga2dLineIdeal(
      x = (v.s * x + v.xy * y),
      y = (v.s * y - v.xy * x),
    )

  infix def antiGeometric(v: Pga2dProjectiveTranslator): Pga2dMultivector =
    Pga2dMultivector(
      s = 0.0,
      w = (v.wx * x + v.wy * y),
      x = (v.s * x - v.wx * w),
      y = (v.s * y - v.wy * w),
      wx = 0.0,
      wy = 0.0,
      xy = 0.0,
      i = (v.wx * y - v.wy * x),
    )

  infix def antiGeometric(v: Pga2dTranslator): Pga2dMultivector =
    Pga2dMultivector(
      s = 0.0,
      w = (v.wx * x + v.wy * y),
      x = (x - v.wx * w),
      y = (y - v.wy * w),
      wx = 0.0,
      wy = 0.0,
      xy = 0.0,
      i = (v.wx * y - v.wy * x),
    )

  infix def antiGeometric(v: Pga2dVector): Pga2dMultivector =
    Pga2dMultivector(
      s = 0.0,
      w = (v.y * x - v.x * y),
      x = -v.y * w,
      y = v.x * w,
      wx = 0.0,
      wy = 0.0,
      xy = 0.0,
      i = (v.x * x + v.y * y),
    )

  infix def antiGeometric(v: Pga2dPoint): Pga2dMultivector =
    Pga2dMultivector(
      s = 0.0,
      w = (v.y * x - v.x * y),
      x = (y - v.y * w),
      y = (-x + v.x * w),
      wx = 0.0,
      wy = 0.0,
      xy = 0.0,
      i = (v.x * x + v.y * y),
    )

  infix def antiGeometric(v: Pga2dLineIdeal): Pga2dRotor =
    Pga2dRotor(
      s = (v.x * x + v.y * y),
      xy = (v.x * y - v.y * x),
    )

  infix def antiGeometric(v: Pga2dPseudoScalar): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = v.i * x,
      y = v.i * y,
      w = v.i * w,
    )

  infix def antiGeometric(v: Pga2dPointCenter.type): Pga2dLineIdeal =
    Pga2dLineIdeal(
      x = y,
      y = -x,
    )

  infix def antiDot(v: Pga2dMotor): Pga2dMultivector =
    Pga2dMultivector(
      s = 0.0,
      w = 0.0,
      x = v.s * x,
      y = v.s * y,
      wx = 0.0,
      wy = 0.0,
      xy = 0.0,
      i = (v.wx * y - v.wy * x),
    )

  infix def antiDot(v: Pga2dLine): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = -v.w * y,
      y = v.w * x,
      w = (v.x * y - v.y * x),
    )

  infix def antiDot(v: Pga2dProjectivePoint): Pga2dPseudoScalar =
    Pga2dPseudoScalar(
      i = (v.x * x + v.y * y),
    )

  infix def antiDot(v: Pga2dRotor): Pga2dLineIdeal =
    Pga2dLineIdeal(
      x = v.s * x,
      y = v.s * y,
    )

  infix def antiDot(v: Pga2dProjectiveTranslator): Pga2dMultivector =
    Pga2dMultivector(
      s = 0.0,
      w = 0.0,
      x = v.s * x,
      y = v.s * y,
      wx = 0.0,
      wy = 0.0,
      xy = 0.0,
      i = (v.wx * y - v.wy * x),
    )

  infix def antiDot(v: Pga2dTranslator): Pga2dMultivector =
    Pga2dMultivector(
      s = 0.0,
      w = 0.0,
      x = x,
      y = y,
      wx = 0.0,
      wy = 0.0,
      xy = 0.0,
      i = (v.wx * y - v.wy * x),
    )

  infix def antiDot(v: Pga2dVector): Pga2dPseudoScalar =
    Pga2dPseudoScalar(
      i = (v.x * x + v.y * y),
    )

  infix def antiDot(v: Pga2dPoint): Pga2dPseudoScalar =
    Pga2dPseudoScalar(
      i = (v.x * x + v.y * y),
    )

  infix def antiDot(v: Pga2dLineIdeal): Pga2dRotor =
    Pga2dRotor(
      s = 0.0,
      xy = (v.x * y - v.y * x),
    )

  infix def antiDot(v: Pga2dPseudoScalar): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = v.i * x,
      y = v.i * y,
      w = v.i * w,
    )

  infix def antiDotI(v: Pga2dProjectivePoint): Double =
    (v.x * x + v.y * y)

  infix def antiDotI(v: Pga2dVector): Double =
    (v.x * x + v.y * y)

  infix def antiDotI(v: Pga2dPoint): Double =
    (v.x * x + v.y * y)

  infix def antiWedge(v: Pga2dMotor): Pga2dLine =
    Pga2dLine(
      x = (v.xy * y - v.wx * w),
      y = (-v.wy * w - v.xy * x),
      w = (v.wx * x + v.wy * y),
    )

  inline infix def v(v: Pga2dMotor): Pga2dLine = antiWedge(v)

  inline infix def join(v: Pga2dMotor): Pga2dLine = antiWedge(v)

  infix def antiWedge(v: Pga2dLine): Double =
    (v.w * w + v.x * x + v.y * y)

  inline infix def v(v: Pga2dLine): Double = antiWedge(v)

  inline infix def join(v: Pga2dLine): Double = antiWedge(v)

  infix def antiWedge(v: Pga2dProjectivePoint): Pga2dLine =
    Pga2dLine(
      x = (v.w * y - v.y * w),
      y = (v.x * w - v.w * x),
      w = (v.y * x - v.x * y),
    )

  inline infix def v(v: Pga2dProjectivePoint): Pga2dLine = antiWedge(v)

  inline infix def join(v: Pga2dProjectivePoint): Pga2dLine = antiWedge(v)

  infix def antiWedge(v: Pga2dRotor): Pga2dLineIdeal =
    Pga2dLineIdeal(
      x = v.xy * y,
      y = -v.xy * x,
    )

  inline infix def v(v: Pga2dRotor): Pga2dLineIdeal = antiWedge(v)

  inline infix def join(v: Pga2dRotor): Pga2dLineIdeal = antiWedge(v)

  infix def antiWedge(v: Pga2dProjectiveTranslator): Pga2dLine =
    Pga2dLine(
      x = -v.wx * w,
      y = -v.wy * w,
      w = (v.wx * x + v.wy * y),
    )

  inline infix def v(v: Pga2dProjectiveTranslator): Pga2dLine = antiWedge(v)

  inline infix def join(v: Pga2dProjectiveTranslator): Pga2dLine = antiWedge(v)

  infix def antiWedge(v: Pga2dTranslator): Pga2dLine =
    Pga2dLine(
      x = -v.wx * w,
      y = -v.wy * w,
      w = (v.wx * x + v.wy * y),
    )

  inline infix def v(v: Pga2dTranslator): Pga2dLine = antiWedge(v)

  inline infix def join(v: Pga2dTranslator): Pga2dLine = antiWedge(v)

  infix def antiWedge(v: Pga2dVector): Pga2dLine =
    Pga2dLine(
      x = -v.y * w,
      y = v.x * w,
      w = (v.y * x - v.x * y),
    )

  inline infix def v(v: Pga2dVector): Pga2dLine = antiWedge(v)

  inline infix def join(v: Pga2dVector): Pga2dLine = antiWedge(v)

  infix def antiWedge(v: Pga2dPoint): Pga2dLine =
    Pga2dLine(
      x = (y - v.y * w),
      y = (-x + v.x * w),
      w = (v.y * x - v.x * y),
    )

  inline infix def v(v: Pga2dPoint): Pga2dLine = antiWedge(v)

  inline infix def join(v: Pga2dPoint): Pga2dLine = antiWedge(v)

  infix def antiWedge(v: Pga2dLineIdeal): Double =
    (v.x * x + v.y * y)

  inline infix def v(v: Pga2dLineIdeal): Double = antiWedge(v)

  inline infix def join(v: Pga2dLineIdeal): Double = antiWedge(v)

  infix def antiWedge(v: Pga2dPseudoScalar): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = v.i * x,
      y = v.i * y,
      w = v.i * w,
    )

  inline infix def v(v: Pga2dPseudoScalar): Pga2dProjectivePoint = antiWedge(v)

  inline infix def join(v: Pga2dPseudoScalar): Pga2dProjectivePoint = antiWedge(v)

  infix def antiWedge(v: Pga2dPointCenter.type): Pga2dLineIdeal =
    Pga2dLineIdeal(
      x = y,
      y = -x,
    )

  inline infix def v(v: Pga2dPointCenter.type): Pga2dLineIdeal = antiWedge(v)

  inline infix def join(v: Pga2dPointCenter.type): Pga2dLineIdeal = antiWedge(v)

  infix def sandwich(v: Pga2dMotor): Pga2dMotor =
    val wMw = w * w
    Pga2dMotor(
      s = v.s * wMw,
      wx = (-v.wx * wMw + 2.0 * v.xy * w * y),
      wy = (-v.wy * wMw - 2.0 * v.xy * w * x),
      xy = v.xy * wMw,
    )

  infix def sandwich(v: Pga2dLine): Pga2dLine =
    val wMw = w * w
    Pga2dLine(
      x = -v.x * wMw,
      y = -v.y * wMw,
      w = (v.w * wMw + 2.0 * w * (v.x * x + v.y * y)),
    )

  infix def sandwich(v: Pga2dProjectivePoint): Pga2dProjectivePoint =
    val wMw = w * w
    Pga2dProjectivePoint(
      x = (-v.x * wMw + 2.0 * v.w * w * x),
      y = (-v.y * wMw + 2.0 * v.w * w * y),
      w = v.w * wMw,
    )

  infix def sandwich(v: Pga2dRotor): Pga2dMotor =
    val wMw = w * w
    Pga2dMotor(
      s = v.s * wMw,
      wx = 2.0 * v.xy * w * y,
      wy = -2.0 * v.xy * w * x,
      xy = v.xy * wMw,
    )

  infix def sandwich(v: Pga2dProjectiveTranslator): Pga2dProjectiveTranslator =
    val wMw = w * w
    Pga2dProjectiveTranslator(
      s = v.s * wMw,
      wx = -v.wx * wMw,
      wy = -v.wy * wMw,
    )

  infix def sandwich(v: Pga2dTranslator): Pga2dProjectiveTranslator =
    val wMw = w * w
    Pga2dProjectiveTranslator(
      s = wMw,
      wx = -v.wx * wMw,
      wy = -v.wy * wMw,
    )

  infix def sandwich(v: Pga2dVector): Pga2dVector =
    val wMw = w * w
    Pga2dVector(
      x = -v.x * wMw,
      y = -v.y * wMw,
    )

  infix def sandwich(v: Pga2dPoint): Pga2dProjectivePoint =
    val wMw = w * w
    Pga2dProjectivePoint(
      x = (-v.x * wMw + 2.0 * w * x),
      y = (-v.y * wMw + 2.0 * w * y),
      w = wMw,
    )

  infix def sandwich(v: Pga2dLineIdeal): Pga2dLine =
    val wMw = w * w
    Pga2dLine(
      x = -v.x * wMw,
      y = -v.y * wMw,
      w = 2.0 * w * (v.x * x + v.y * y),
    )

  infix def sandwich(v: Pga2dPseudoScalar): Pga2dPseudoScalar =
    Pga2dPseudoScalar(
      i = v.i * w * w,
    )

  infix def sandwich(v: Pga2dPointCenter.type): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = 2.0 * w * x,
      y = 2.0 * w * y,
      w = w * w,
    )

  infix def reverseSandwich(v: Pga2dMotor): Pga2dMotor =
    val wMw = w * w
    Pga2dMotor(
      s = v.s * wMw,
      wx = (-v.wx * wMw + 2.0 * v.xy * w * y),
      wy = (-v.wy * wMw - 2.0 * v.xy * w * x),
      xy = v.xy * wMw,
    )

  infix def reverseSandwich(v: Pga2dLine): Pga2dLine =
    val wMw = w * w
    Pga2dLine(
      x = -v.x * wMw,
      y = -v.y * wMw,
      w = (v.w * wMw + 2.0 * w * (v.x * x + v.y * y)),
    )

  infix def reverseSandwich(v: Pga2dProjectivePoint): Pga2dProjectivePoint =
    val wMw = w * w
    Pga2dProjectivePoint(
      x = (-v.x * wMw + 2.0 * v.w * w * x),
      y = (-v.y * wMw + 2.0 * v.w * w * y),
      w = v.w * wMw,
    )

  infix def reverseSandwich(v: Pga2dRotor): Pga2dMotor =
    val wMw = w * w
    Pga2dMotor(
      s = v.s * wMw,
      wx = 2.0 * v.xy * w * y,
      wy = -2.0 * v.xy * w * x,
      xy = v.xy * wMw,
    )

  infix def reverseSandwich(v: Pga2dProjectiveTranslator): Pga2dProjectiveTranslator =
    val wMw = w * w
    Pga2dProjectiveTranslator(
      s = v.s * wMw,
      wx = -v.wx * wMw,
      wy = -v.wy * wMw,
    )

  infix def reverseSandwich(v: Pga2dTranslator): Pga2dProjectiveTranslator =
    val wMw = w * w
    Pga2dProjectiveTranslator(
      s = wMw,
      wx = -v.wx * wMw,
      wy = -v.wy * wMw,
    )

  infix def reverseSandwich(v: Pga2dVector): Pga2dVector =
    val wMw = w * w
    Pga2dVector(
      x = -v.x * wMw,
      y = -v.y * wMw,
    )

  infix def reverseSandwich(v: Pga2dPoint): Pga2dProjectivePoint =
    val wMw = w * w
    Pga2dProjectivePoint(
      x = (-v.x * wMw + 2.0 * w * x),
      y = (-v.y * wMw + 2.0 * w * y),
      w = wMw,
    )

  infix def reverseSandwich(v: Pga2dLineIdeal): Pga2dLine =
    val wMw = w * w
    Pga2dLine(
      x = -v.x * wMw,
      y = -v.y * wMw,
      w = 2.0 * w * (v.x * x + v.y * y),
    )

  infix def reverseSandwich(v: Pga2dPseudoScalar): Pga2dPseudoScalar =
    Pga2dPseudoScalar(
      i = v.i * w * w,
    )

  infix def reverseSandwich(v: Pga2dPointCenter.type): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = 2.0 * w * x,
      y = 2.0 * w * y,
      w = w * w,
    )

  infix def cross(v: Pga2dMotor): Pga2dVector =
    Pga2dVector(
      x = (v.wx * w - v.xy * y),
      y = (v.wy * w + v.xy * x),
    )

  infix def cross(v: Pga2dLine): Pga2dLine =
    Pga2dLine(
      x = v.y * w,
      y = -v.x * w,
      w = (v.x * y - v.y * x),
    )

  infix def cross(v: Pga2dProjectivePoint): Pga2dVector =
    Pga2dVector(
      x = (v.y * w - v.w * y),
      y = (v.w * x - v.x * w),
    )

  infix def cross(v: Pga2dRotor): Pga2dVector =
    Pga2dVector(
      x = -v.xy * y,
      y = v.xy * x,
    )

  infix def cross(v: Pga2dProjectiveTranslator): Pga2dVector =
    Pga2dVector(
      x = v.wx * w,
      y = v.wy * w,
    )

  infix def cross(v: Pga2dTranslator): Pga2dVector =
    Pga2dVector(
      x = v.wx * w,
      y = v.wy * w,
    )

  infix def cross(v: Pga2dVector): Pga2dVector =
    Pga2dVector(
      x = v.y * w,
      y = -v.x * w,
    )

  infix def cross(v: Pga2dPoint): Pga2dVector =
    Pga2dVector(
      x = (-y + v.y * w),
      y = (x - v.x * w),
    )

  infix def cross(v: Pga2dLineIdeal): Pga2dLine =
    Pga2dLine(
      x = v.y * w,
      y = -v.x * w,
      w = (v.x * y - v.y * x),
    )

  infix def cross(v: Pga2dPointCenter.type): Pga2dVector =
    Pga2dVector(
      x = -y,
      y = x,
    )


object Pga2dProjectivePoint:

  inline val componentsCount = 3

  val zero: Pga2dProjectivePoint = Pga2dProjectivePoint(0.0, 0.0, 0.0)

  def blade2(wx: Double, wy: Double, xy: Double): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = -wy,
      y = wx,
      w = xy,
    )

  def interpolate(a: Pga2dProjectivePoint, b: Pga2dProjectivePoint, t: Double): Pga2dProjectivePoint =
    a * (1.0 - t) + b * t