package me.kright.gametools.pga2d

import scala.annotation.targetName
import me.kright.gametools.flatarray.FlatDoubleSerializer


/**
 * A vector: the difference between two points, a direction with magnitude; an ideal point with w = 0.
 * Stored in dual representation with fields x, y. Translators move points but do not change vectors.
 *
 * Variable fields: x, y.
 * Basis blade coefficients: wy = -x, wx = y.
 *
 * Generated by pgaNdCodeGen (me.kright.gametools.pga.codegen.scalagen.pga2d.runScalaCodeGen).
 * Do not edit by hand: change the generator and re-run it.
 */
final case class Pga2dVector(x: Double = 0.0,
                             y: Double = 0.0) derives CanEqual, FlatDoubleSerializer:

  inline def wy: Double = -x

  inline def wx: Double = y

  override def toString: String =
    s"Pga2dVector(x = $x, y = $y)"

  def dual: Pga2dLineCentral =
    Pga2dLineCentral(
      x = x,
      y = y,
    )

  def weight: Pga2dVector =
    this

  @targetName("unaryMinus")
  def unary_- : Pga2dVector =
    Pga2dVector(
      x = -x,
      y = -y,
    )

  def reverse: Pga2dVector =
    -this

  def antiReverse: Pga2dVector =
    this

  def weightNormSquare: Double =
    (x * x + y * y)

  def weightNorm: Double =
    Math.sqrt(weightNormSquare)

  def normalizedByWeight =
    this / weightNorm

  def normSquare: Double =
    (x * x + y * y)

  def norm: Double =
    Math.sqrt(normSquare)

  def normalizedByNorm =
    this / norm

  @targetName("times")
  def *(r: Double): Pga2dVector =
    Pga2dVector(
      x = r * x,
      y = r * y,
    )

  /** multiplies by the reciprocal: one division instead of one per component, at the cost of one extra rounding (~0.5 ulp) */
  @targetName("div")
  def /(r: Double): Pga2dVector =
    this * (1.0 / r)

  infix def min(other: Pga2dVector): Pga2dVector =
    Pga2dVector(math.min(x, other.x), math.min(y, other.y))

  infix def max(other: Pga2dVector): Pga2dVector =
    Pga2dVector(math.max(x, other.x), math.max(y, other.y))

  @targetName("plus")
  def +(r: Pga2dProjectivePoint): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = (r.x + x),
      y = (r.y + y),
      w = r.w,
    )

  @targetName("minus")
  def -(r: Pga2dProjectivePoint): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = (x - r.x),
      y = (y - r.y),
      w = -r.w,
    )

  def madd(r: Pga2dProjectivePoint, mult: Double): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = (x + mult * r.x),
      y = (y + mult * r.y),
      w = mult * r.w,
    )

  @targetName("plus")
  def +(r: Pga2dPoint): Pga2dPoint =
    Pga2dPoint(
      x = (r.x + x),
      y = (r.y + y),
    )

  @targetName("minus")
  def -(r: Pga2dPoint): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = (x - r.x),
      y = (y - r.y),
      w = -1.0,
    )

  def madd(r: Pga2dPoint, mult: Double): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = (x + mult * r.x),
      y = (y + mult * r.y),
      w = mult,
    )

  @targetName("plus")
  def +(r: Pga2dVector): Pga2dVector =
    Pga2dVector(
      x = (r.x + x),
      y = (r.y + y),
    )

  @targetName("minus")
  def -(r: Pga2dVector): Pga2dVector =
    Pga2dVector(
      x = (x - r.x),
      y = (y - r.y),
    )

  def madd(r: Pga2dVector, mult: Double): Pga2dVector =
    Pga2dVector(
      x = (x + mult * r.x),
      y = (y + mult * r.y),
    )

  /** componentwise product on the raw fields; NOT a geometric-algebra operation (basis-dependent) */
  def scale(r: Pga2dVector): Pga2dVector =
    Pga2dVector(
      x = x * r.x,
      y = y * r.y,
    )

  /** componentwise 1/x on the raw fields (a zero field yields Infinity); NOT the multiplicative inverse */
  def reciprocal: Pga2dVector =
    Pga2dVector(
      x = 1.0 / x,
      y = 1.0 / y,
    )

  def exp(): Pga2dTranslator =
    Pga2dTranslator(
      wx = y,
      wy = -x,
    )

  def exp(t: Double): Pga2dTranslator =
    Pga2dTranslator(
      wx = t * y,
      wy = -t * x,
    )

  def toMultivector: Pga2dMultivector =
    Pga2dMultivector(
      s = 0.0,
      w = 0.0,
      x = 0.0,
      y = 0.0,
      wx = y,
      wy = -x,
      xy = 0.0,
      i = 0.0,
    )

  def toMotor: Pga2dMotor =
    Pga2dMotor(
      s = 0.0,
      wx = y,
      wy = -x,
      xy = 0.0,
    )

  def toProjectivePoint: Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = x,
      y = y,
      w = 0.0,
    )

  def toProjectiveTranslator: Pga2dProjectiveTranslator =
    Pga2dProjectiveTranslator(
      s = 0.0,
      wx = y,
      wy = -x,
    )

  def toTranslatorUnsafe: Pga2dTranslator =
    Pga2dTranslator(
      wx = y,
      wy = -x,
    )

  def toPointUnsafe: Pga2dPoint =
    Pga2dPoint(
      x = x,
      y = y,
    )

  infix def geometric(r: Pga2dMotor): Pga2dVector =
    Pga2dVector(
      x = (r.s * x - r.xy * y),
      y = (r.s * y + r.xy * x),
    )

  infix def geometric(r: Pga2dLine): Pga2dMultivector =
    Pga2dMultivector(
      s = 0.0,
      w = (r.x * y - r.y * x),
      x = 0.0,
      y = 0.0,
      wx = 0.0,
      wy = 0.0,
      xy = 0.0,
      i = (r.x * x + r.y * y),
    )

  infix def geometric(r: Pga2dProjectivePoint): Pga2dVector =
    Pga2dVector(
      x = -r.w * y,
      y = r.w * x,
    )

  infix def geometric(r: Pga2dRotor): Pga2dVector =
    Pga2dVector(
      x = (r.s * x - r.xy * y),
      y = (r.s * y + r.xy * x),
    )

  infix def geometric(r: Pga2dProjectiveTranslator): Pga2dVector =
    Pga2dVector(
      x = r.s * x,
      y = r.s * y,
    )

  infix def geometric(r: Pga2dTranslator): Pga2dVector =
    this

  infix def geometric(r: Pga2dPoint): Pga2dVector =
    Pga2dVector(
      x = -y,
      y = x,
    )

  infix def geometric(r: Pga2dLineCentral): Pga2dMultivector =
    Pga2dMultivector(
      s = 0.0,
      w = (r.x * y - r.y * x),
      x = 0.0,
      y = 0.0,
      wx = 0.0,
      wy = 0.0,
      xy = 0.0,
      i = (r.x * x + r.y * y),
    )

  infix def geometric(r: Pga2dPointCenter.type): Pga2dVector =
    Pga2dVector(
      x = -y,
      y = x,
    )

  infix def dot(r: Pga2dMotor): Pga2dVector =
    Pga2dVector(
      x = r.s * x,
      y = r.s * y,
    )

  infix def dot(r: Pga2dLine): Pga2dLine =
    Pga2dLine(
      x = 0.0,
      y = 0.0,
      w = (r.x * y - r.y * x),
    )

  infix def dot(r: Pga2dRotor): Pga2dVector =
    Pga2dVector(
      x = r.s * x,
      y = r.s * y,
    )

  infix def dot(r: Pga2dProjectiveTranslator): Pga2dVector =
    Pga2dVector(
      x = r.s * x,
      y = r.s * y,
    )

  infix def dot(r: Pga2dTranslator): Pga2dVector =
    this

  infix def dot(r: Pga2dLineCentral): Pga2dLine =
    Pga2dLine(
      x = 0.0,
      y = 0.0,
      w = (r.x * y - r.y * x),
    )

  infix def wedge(r: Pga2dMotor): Pga2dVector =
    Pga2dVector(
      x = r.s * x,
      y = r.s * y,
    )

  inline infix def ^(r: Pga2dMotor): Pga2dVector = wedge(r)

  inline infix def meet(r: Pga2dMotor): Pga2dVector = wedge(r)

  infix def wedge(r: Pga2dLine): Pga2dPseudoScalar =
    Pga2dPseudoScalar(
      i = (r.x * x + r.y * y),
    )

  inline infix def ^(r: Pga2dLine): Pga2dPseudoScalar = wedge(r)

  inline infix def meet(r: Pga2dLine): Pga2dPseudoScalar = wedge(r)

  infix def wedge(r: Pga2dRotor): Pga2dVector =
    Pga2dVector(
      x = r.s * x,
      y = r.s * y,
    )

  inline infix def ^(r: Pga2dRotor): Pga2dVector = wedge(r)

  inline infix def meet(r: Pga2dRotor): Pga2dVector = wedge(r)

  infix def wedge(r: Pga2dProjectiveTranslator): Pga2dVector =
    Pga2dVector(
      x = r.s * x,
      y = r.s * y,
    )

  inline infix def ^(r: Pga2dProjectiveTranslator): Pga2dVector = wedge(r)

  inline infix def meet(r: Pga2dProjectiveTranslator): Pga2dVector = wedge(r)

  infix def wedge(r: Pga2dTranslator): Pga2dVector =
    this

  inline infix def ^(r: Pga2dTranslator): Pga2dVector = wedge(r)

  inline infix def meet(r: Pga2dTranslator): Pga2dVector = wedge(r)

  infix def wedge(r: Pga2dLineCentral): Pga2dPseudoScalar =
    Pga2dPseudoScalar(
      i = (r.x * x + r.y * y),
    )

  inline infix def ^(r: Pga2dLineCentral): Pga2dPseudoScalar = wedge(r)

  inline infix def meet(r: Pga2dLineCentral): Pga2dPseudoScalar = wedge(r)

  infix def antiGeometric(r: Pga2dMotor): Pga2dMultivector =
    Pga2dMultivector(
      s = 0.0,
      w = (r.wx * x + r.wy * y),
      x = (r.s * x + r.xy * y),
      y = (r.s * y - r.xy * x),
      wx = 0.0,
      wy = 0.0,
      xy = 0.0,
      i = (r.wx * y - r.wy * x),
    )

  infix def antiGeometric(r: Pga2dLine): Pga2dMotor =
    Pga2dMotor(
      s = (r.x * x + r.y * y),
      wx = r.w * x,
      wy = r.w * y,
      xy = (r.x * y - r.y * x),
    )

  infix def antiGeometric(r: Pga2dProjectivePoint): Pga2dMultivector =
    Pga2dMultivector(
      s = 0.0,
      w = (r.y * x - r.x * y),
      x = r.w * y,
      y = -r.w * x,
      wx = 0.0,
      wy = 0.0,
      xy = 0.0,
      i = (r.x * x + r.y * y),
    )

  infix def antiGeometric(r: Pga2dRotor): Pga2dLineCentral =
    Pga2dLineCentral(
      x = (r.s * x + r.xy * y),
      y = (r.s * y - r.xy * x),
    )

  infix def antiGeometric(r: Pga2dProjectiveTranslator): Pga2dMultivector =
    Pga2dMultivector(
      s = 0.0,
      w = (r.wx * x + r.wy * y),
      x = r.s * x,
      y = r.s * y,
      wx = 0.0,
      wy = 0.0,
      xy = 0.0,
      i = (r.wx * y - r.wy * x),
    )

  infix def antiGeometric(r: Pga2dTranslator): Pga2dMultivector =
    Pga2dMultivector(
      s = 0.0,
      w = (r.wx * x + r.wy * y),
      x = x,
      y = y,
      wx = 0.0,
      wy = 0.0,
      xy = 0.0,
      i = (r.wx * y - r.wy * x),
    )

  infix def antiGeometric(r: Pga2dVector): Pga2dMultivector =
    Pga2dMultivector(
      s = 0.0,
      w = (r.y * x - r.x * y),
      x = 0.0,
      y = 0.0,
      wx = 0.0,
      wy = 0.0,
      xy = 0.0,
      i = (r.x * x + r.y * y),
    )

  infix def antiGeometric(r: Pga2dPoint): Pga2dMultivector =
    Pga2dMultivector(
      s = 0.0,
      w = (r.y * x - r.x * y),
      x = y,
      y = -x,
      wx = 0.0,
      wy = 0.0,
      xy = 0.0,
      i = (r.x * x + r.y * y),
    )

  infix def antiGeometric(r: Pga2dLineCentral): Pga2dRotor =
    Pga2dRotor(
      s = (r.x * x + r.y * y),
      xy = (r.x * y - r.y * x),
    )

  infix def antiGeometric(r: Pga2dPseudoScalar): Pga2dVector =
    Pga2dVector(
      x = r.i * x,
      y = r.i * y,
    )

  infix def antiGeometric(r: Pga2dPointCenter.type): Pga2dLineCentral =
    Pga2dLineCentral(
      x = y,
      y = -x,
    )

  infix def antiDot(r: Pga2dMotor): Pga2dMultivector =
    Pga2dMultivector(
      s = 0.0,
      w = 0.0,
      x = r.s * x,
      y = r.s * y,
      wx = 0.0,
      wy = 0.0,
      xy = 0.0,
      i = (r.wx * y - r.wy * x),
    )

  infix def antiDot(r: Pga2dLine): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = -r.w * y,
      y = r.w * x,
      w = (r.x * y - r.y * x),
    )

  infix def antiDot(r: Pga2dProjectivePoint): Pga2dPseudoScalar =
    Pga2dPseudoScalar(
      i = (r.x * x + r.y * y),
    )

  infix def antiDot(r: Pga2dRotor): Pga2dLineCentral =
    Pga2dLineCentral(
      x = r.s * x,
      y = r.s * y,
    )

  infix def antiDot(r: Pga2dProjectiveTranslator): Pga2dMultivector =
    Pga2dMultivector(
      s = 0.0,
      w = 0.0,
      x = r.s * x,
      y = r.s * y,
      wx = 0.0,
      wy = 0.0,
      xy = 0.0,
      i = (r.wx * y - r.wy * x),
    )

  infix def antiDot(r: Pga2dTranslator): Pga2dMultivector =
    Pga2dMultivector(
      s = 0.0,
      w = 0.0,
      x = x,
      y = y,
      wx = 0.0,
      wy = 0.0,
      xy = 0.0,
      i = (r.wx * y - r.wy * x),
    )

  infix def antiDot(r: Pga2dVector): Pga2dPseudoScalar =
    Pga2dPseudoScalar(
      i = (r.x * x + r.y * y),
    )

  infix def antiDot(r: Pga2dPoint): Pga2dPseudoScalar =
    Pga2dPseudoScalar(
      i = (r.x * x + r.y * y),
    )

  infix def antiDot(r: Pga2dLineCentral): Pga2dRotor =
    Pga2dRotor(
      s = 0.0,
      xy = (r.x * y - r.y * x),
    )

  infix def antiDot(r: Pga2dPseudoScalar): Pga2dVector =
    Pga2dVector(
      x = r.i * x,
      y = r.i * y,
    )

  infix def antiDotI(r: Pga2dProjectivePoint): Double =
    (r.x * x + r.y * y)

  infix def antiDotI(r: Pga2dVector): Double =
    (r.x * x + r.y * y)

  infix def antiDotI(r: Pga2dPoint): Double =
    (r.x * x + r.y * y)

  infix def antiWedge(r: Pga2dMotor): Pga2dLine =
    Pga2dLine(
      x = r.xy * y,
      y = -r.xy * x,
      w = (r.wx * x + r.wy * y),
    )

  inline infix def v(r: Pga2dMotor): Pga2dLine = antiWedge(r)

  inline infix def join(r: Pga2dMotor): Pga2dLine = antiWedge(r)

  infix def antiWedge(r: Pga2dLine): Double =
    (r.x * x + r.y * y)

  inline infix def v(r: Pga2dLine): Double = antiWedge(r)

  inline infix def join(r: Pga2dLine): Double = antiWedge(r)

  infix def antiWedge(r: Pga2dProjectivePoint): Pga2dLine =
    Pga2dLine(
      x = r.w * y,
      y = -r.w * x,
      w = (r.y * x - r.x * y),
    )

  inline infix def v(r: Pga2dProjectivePoint): Pga2dLine = antiWedge(r)

  inline infix def join(r: Pga2dProjectivePoint): Pga2dLine = antiWedge(r)

  infix def antiWedge(r: Pga2dRotor): Pga2dLineCentral =
    Pga2dLineCentral(
      x = r.xy * y,
      y = -r.xy * x,
    )

  inline infix def v(r: Pga2dRotor): Pga2dLineCentral = antiWedge(r)

  inline infix def join(r: Pga2dRotor): Pga2dLineCentral = antiWedge(r)

  infix def antiWedge(r: Pga2dProjectiveTranslator): Pga2dLine =
    Pga2dLine(
      x = 0.0,
      y = 0.0,
      w = (r.wx * x + r.wy * y),
    )

  inline infix def v(r: Pga2dProjectiveTranslator): Pga2dLine = antiWedge(r)

  inline infix def join(r: Pga2dProjectiveTranslator): Pga2dLine = antiWedge(r)

  infix def antiWedge(r: Pga2dTranslator): Pga2dLine =
    Pga2dLine(
      x = 0.0,
      y = 0.0,
      w = (r.wx * x + r.wy * y),
    )

  inline infix def v(r: Pga2dTranslator): Pga2dLine = antiWedge(r)

  inline infix def join(r: Pga2dTranslator): Pga2dLine = antiWedge(r)

  infix def antiWedge(r: Pga2dVector): Pga2dLine =
    Pga2dLine(
      x = 0.0,
      y = 0.0,
      w = (r.y * x - r.x * y),
    )

  inline infix def v(r: Pga2dVector): Pga2dLine = antiWedge(r)

  inline infix def join(r: Pga2dVector): Pga2dLine = antiWedge(r)

  infix def antiWedge(r: Pga2dPoint): Pga2dLine =
    Pga2dLine(
      x = y,
      y = -x,
      w = (r.y * x - r.x * y),
    )

  inline infix def v(r: Pga2dPoint): Pga2dLine = antiWedge(r)

  inline infix def join(r: Pga2dPoint): Pga2dLine = antiWedge(r)

  infix def antiWedge(r: Pga2dLineCentral): Double =
    (r.x * x + r.y * y)

  inline infix def v(r: Pga2dLineCentral): Double = antiWedge(r)

  inline infix def join(r: Pga2dLineCentral): Double = antiWedge(r)

  infix def antiWedge(r: Pga2dPseudoScalar): Pga2dVector =
    Pga2dVector(
      x = r.i * x,
      y = r.i * y,
    )

  inline infix def v(r: Pga2dPseudoScalar): Pga2dVector = antiWedge(r)

  inline infix def join(r: Pga2dPseudoScalar): Pga2dVector = antiWedge(r)

  infix def antiWedge(r: Pga2dPointCenter.type): Pga2dLineCentral =
    Pga2dLineCentral(
      x = y,
      y = -x,
    )

  inline infix def v(r: Pga2dPointCenter.type): Pga2dLineCentral = antiWedge(r)

  inline infix def join(r: Pga2dPointCenter.type): Pga2dLineCentral = antiWedge(r)

  infix def cross(r: Pga2dMotor): Pga2dVector =
    Pga2dVector(
      x = -r.xy * y,
      y = r.xy * x,
    )

  infix def cross(r: Pga2dLine): Pga2dLine =
    Pga2dLine(
      x = 0.0,
      y = 0.0,
      w = (r.x * y - r.y * x),
    )

  infix def cross(r: Pga2dProjectivePoint): Pga2dVector =
    Pga2dVector(
      x = -r.w * y,
      y = r.w * x,
    )

  infix def cross(r: Pga2dRotor): Pga2dVector =
    Pga2dVector(
      x = -r.xy * y,
      y = r.xy * x,
    )

  infix def cross(r: Pga2dPoint): Pga2dVector =
    Pga2dVector(
      x = -y,
      y = x,
    )

  infix def cross(r: Pga2dLineCentral): Pga2dLine =
    Pga2dLine(
      x = 0.0,
      y = 0.0,
      w = (r.x * y - r.y * x),
    )

  infix def cross(r: Pga2dPointCenter.type): Pga2dVector =
    Pga2dVector(
      x = -y,
      y = x,
    )


object Pga2dVector:

  inline val componentsCount = 2

  val zero: Pga2dVector = Pga2dVector(0.0, 0.0)

  def blade2(wx: Double, wy: Double): Pga2dVector =
    Pga2dVector(
      x = -wy,
      y = wx,
    )

  def interpolate(a: Pga2dVector, b: Pga2dVector, t: Double): Pga2dVector =
    a * (1.0 - t) + b * t