package me.kright.gametools.pga2d

import me.kright.gametools.flatarray.FlatDoubleSerializer
import me.kright.gametools.mathutil.CanEqualWithEps

/**
 * A cached form of a normalized motor: the sandwich and reverseSandwich products expressed as precomputed matrices.
 *
 * Prefer this class over motor.sandwich whenever the same motor is applied to many objects -
 * moving all the points of a body, transforming forces and velocities in a physics solver step, etc.
 * Building the transform costs about as much as a single motor sandwich, and after that every
 * application is a plain matrix multiplication, several times cheaper than motor.sandwich,
 * which recomputes the coefficients on every call.
 *
 * The class is immutable, like the Pga2dMotor it is built around.
 *
 * Cached values:
 *  - cos, sin: the cosine and sine of the rotation angle;
 *    the full 2x2 rotation matrix is [[cos, sin], [-sin, cos]], and the reverse transformation
 *    uses its transpose.
 *  - tx, ty and txRev, tyRev: translation for points, forward and reverse.
 *
 * The motor must be normalized (motor.normSquare == 1): build the transform with Pga2dTransform(motor),
 * which renormalizes its argument, or with Pga2dTransform.fromNormalized(motor), which trusts the caller
 * and skips the renormalization. The assumption pays off in the result types: the sandwich of a
 * point is a point (not a projective point), of a translator - a translator, and the Study-number
 * corrections disappear from the formulas. For a transform over an arbitrary motor see
 * [[Pga2dProjectiveTransform]].
 *
 * For a normalized motor the results are equivalent to motor.sandwich(r) / motor.reverseSandwich(r)
 * up to floating point rounding.
 *
 * Generated by pgaNdCodeGen (me.kright.gametools.pga.codegen.scalagen.pga2d.runScalaCodeGen).
 * Do not edit by hand: change the generator and re-run it.
 */
final case class Pga2dTransform(motor: Pga2dMotor,

                                cos: Double, sin: Double,

                                tx: Double, ty: Double,
                                txRev: Double, tyRev: Double) derives CanEqual, CanEqualWithEps, FlatDoubleSerializer:

  override def toString: String =
    s"Pga2dTransform($motor)"

  infix def sandwich(r: Pga2dMotor): Pga2dMotor =
    Pga2dMotor(
      s = r.s,
      wx = (cos * r.wx + r.wy * sin + r.xy * ty),
      wy = (cos * r.wy - r.wx * sin - r.xy * tx),
      xy = r.xy,
    )

  infix def reverseSandwich(r: Pga2dMotor): Pga2dMotor =
    Pga2dMotor(
      s = r.s,
      wx = (cos * r.wx + r.xy * tyRev - r.wy * sin),
      wy = (cos * r.wy + r.wx * sin - r.xy * txRev),
      xy = r.xy,
    )

  infix def sandwich(r: Pga2dLine): Pga2dLine =
    Pga2dLine(
      x = (cos * r.x + r.y * sin),
      y = (cos * r.y - r.x * sin),
      w = (r.w + r.x * txRev + r.y * tyRev),
    )

  infix def reverseSandwich(r: Pga2dLine): Pga2dLine =
    Pga2dLine(
      x = (cos * r.x - r.y * sin),
      y = (cos * r.y + r.x * sin),
      w = (r.w + r.x * tx + r.y * ty),
    )

  infix def sandwich(r: Pga2dRotor): Pga2dMotor =
    Pga2dMotor(
      s = r.s,
      wx = r.xy * ty,
      wy = -r.xy * tx,
      xy = r.xy,
    )

  infix def reverseSandwich(r: Pga2dRotor): Pga2dMotor =
    Pga2dMotor(
      s = r.s,
      wx = r.xy * tyRev,
      wy = -r.xy * txRev,
      xy = r.xy,
    )

  infix def sandwich(r: Pga2dProjectivePoint): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = (cos * r.x + r.w * tx + r.y * sin),
      y = (cos * r.y + r.w * ty - r.x * sin),
      w = r.w,
    )

  infix def reverseSandwich(r: Pga2dProjectivePoint): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = (cos * r.x + r.w * txRev - r.y * sin),
      y = (cos * r.y + r.w * tyRev + r.x * sin),
      w = r.w,
    )

  infix def sandwich(r: Pga2dProjectiveTranslator): Pga2dProjectiveTranslator =
    Pga2dProjectiveTranslator(
      s = r.s,
      wx = (cos * r.wx + r.wy * sin),
      wy = (cos * r.wy - r.wx * sin),
    )

  infix def reverseSandwich(r: Pga2dProjectiveTranslator): Pga2dProjectiveTranslator =
    Pga2dProjectiveTranslator(
      s = r.s,
      wx = (cos * r.wx - r.wy * sin),
      wy = (cos * r.wy + r.wx * sin),
    )

  infix def sandwich(r: Pga2dTranslator): Pga2dTranslator =
    Pga2dTranslator(
      wx = (cos * r.wx + r.wy * sin),
      wy = (cos * r.wy - r.wx * sin),
    )

  infix def reverseSandwich(r: Pga2dTranslator): Pga2dTranslator =
    Pga2dTranslator(
      wx = (cos * r.wx - r.wy * sin),
      wy = (cos * r.wy + r.wx * sin),
    )

  infix def sandwich(r: Pga2dVector): Pga2dVector =
    Pga2dVector(
      x = (cos * r.x + r.y * sin),
      y = (cos * r.y - r.x * sin),
    )

  infix def reverseSandwich(r: Pga2dVector): Pga2dVector =
    Pga2dVector(
      x = (cos * r.x - r.y * sin),
      y = (cos * r.y + r.x * sin),
    )

  infix def sandwich(r: Pga2dPoint): Pga2dPoint =
    Pga2dPoint(
      x = (tx + cos * r.x + r.y * sin),
      y = (ty + cos * r.y - r.x * sin),
    )

  infix def reverseSandwich(r: Pga2dPoint): Pga2dPoint =
    Pga2dPoint(
      x = (txRev + cos * r.x - r.y * sin),
      y = (tyRev + cos * r.y + r.x * sin),
    )

  infix def sandwich(r: Pga2dLineCentral): Pga2dLine =
    Pga2dLine(
      x = (cos * r.x + r.y * sin),
      y = (cos * r.y - r.x * sin),
      w = (r.x * txRev + r.y * tyRev),
    )

  infix def reverseSandwich(r: Pga2dLineCentral): Pga2dLine =
    Pga2dLine(
      x = (cos * r.x - r.y * sin),
      y = (cos * r.y + r.x * sin),
      w = (r.x * tx + r.y * ty),
    )

  infix def sandwich(r: Pga2dPseudoScalar): Pga2dPseudoScalar =
    Pga2dPseudoScalar(
      i = r.i,
    )

  infix def reverseSandwich(r: Pga2dPseudoScalar): Pga2dPseudoScalar =
    Pga2dPseudoScalar(
      i = r.i,
    )

  infix def sandwich(r: Pga2dPointCenter.type): Pga2dPoint =
    Pga2dPoint(
      x = tx,
      y = ty,
    )

  infix def reverseSandwich(r: Pga2dPointCenter.type): Pga2dPoint =
    Pga2dPoint(
      x = txRev,
      y = tyRev,
    )


object Pga2dTransform:
  val id: Pga2dTransform = fromNormalized(Pga2dMotor.id)

  /** the transform of motor.renormalized - safe for any input;
   * see [[fromNormalized]] to skip the renormalization when the motor is known to be normalized */
  def apply(motor: Pga2dMotor): Pga2dTransform =
    fromNormalized(motor.renormalized)

  /** trusts the caller that motor.normSquare == 1 and skips the renormalization;
   * for a non-normalized motor the results are silently scaled - prefer [[apply]] when unsure */
  def fromNormalized(motor: Pga2dMotor): Pga2dTransform =
    val s = motor.s
    val wx = motor.wx
    val wy = motor.wy
    val xy = motor.xy

    val sMwx = s * wx
    val sMwy = s * wy
    val wxMxy = wx * xy
    val wyMxy = wy * xy

    new Pga2dTransform(
      motor,

      cos = (s * s - xy * xy),
      sin = 2.0 * s * xy,

      tx = 2.0 * (-sMwx - wyMxy),
      ty = 2.0 * (wxMxy - sMwy),
      txRev = 2.0 * (sMwx - wyMxy),
      tyRev = 2.0 * (sMwy + wxMxy),
    )