package me.kright.gametools.pga2d

import scala.annotation.targetName
import me.kright.gametools.flatarray.FlatDoubleSerializer


/**
 * A generic multivector of 2d PGA with all 8 components, used when no specialized class fits the value.
 *
 * Variable fields: s, w, x, y, wx, wy, xy, i.
 *
 * Generated by pgaNdCodeGen (me.kright.gametools.pga.codegen.scala.pga2d.runScalaCodeGen).
 * Do not edit by hand: change the generator and re-run it.
 */
final case class Pga2dMultivector(s: Double = 0.0,
                                  w: Double = 0.0,
                                  x: Double = 0.0,
                                  y: Double = 0.0,
                                  wx: Double = 0.0,
                                  wy: Double = 0.0,
                                  xy: Double = 0.0,
                                  i: Double = 0.0) derives CanEqual, FlatDoubleSerializer:

  override def toString: String =
    s"Pga2dMultivector(s = $s, w = $w, x = $x, y = $y, wx = $wx, wy = $wy, xy = $xy, i = $i)"

  def dual: Pga2dMultivector =
    Pga2dMultivector(
      s = i,
      w = xy,
      x = -wy,
      y = wx,
      wx = y,
      wy = -x,
      xy = w,
      i = s,
    )

  def weight: Pga2dMultivector =
    Pga2dMultivector(
      s = 0.0,
      w = w,
      x = 0.0,
      y = 0.0,
      wx = wx,
      wy = wy,
      xy = 0.0,
      i = i,
    )

  def bulk: Pga2dMultivector =
    Pga2dMultivector(
      s = s,
      w = 0.0,
      x = x,
      y = y,
      wx = 0.0,
      wy = 0.0,
      xy = xy,
      i = 0.0,
    )

  @targetName("unaryMinus")
  def unary_- : Pga2dMultivector =
    Pga2dMultivector(
      s = -s,
      w = -w,
      x = -x,
      y = -y,
      wx = -wx,
      wy = -wy,
      xy = -xy,
      i = -i,
    )

  def reverse: Pga2dMultivector =
    Pga2dMultivector(
      s = s,
      w = w,
      x = x,
      y = y,
      wx = -wx,
      wy = -wy,
      xy = -xy,
      i = -i,
    )

  def antiReverse: Pga2dMultivector =
    Pga2dMultivector(
      s = -s,
      w = -w,
      x = -x,
      y = -y,
      wx = wx,
      wy = wy,
      xy = xy,
      i = i,
    )

  def bulkNormSquare: Double =
    (s * s + x * x + xy * xy + y * y)

  def bulkNorm: Double =
    Math.sqrt(bulkNormSquare)

  def normalizedByBulk =
    this / bulkNorm

  def weightNormSquare: Double =
    (i * i + w * w + wx * wx + wy * wy)

  def weightNorm: Double =
    Math.sqrt(weightNormSquare)

  def normalizedByWeight =
    this / weightNorm

  def normSquare: Double =
    (i * i + s * s + w * w + wx * wx + wy * wy + x * x + xy * xy + y * y)

  def norm: Double =
    Math.sqrt(normSquare)

  def normalizedByNorm =
    this / norm

  @targetName("times")
  def *(v: Double): Pga2dMultivector =
    Pga2dMultivector(
      s = s * v,
      w = v * w,
      x = v * x,
      y = v * y,
      wx = v * wx,
      wy = v * wy,
      xy = v * xy,
      i = i * v,
    )

  @targetName("div")
  def /(v: Double): Pga2dMultivector =
    this * (1.0 / v)

  @targetName("plus")
  def +(v: Pga2dMultivector): Pga2dMultivector =
    Pga2dMultivector(
      s = (s + v.s),
      w = (v.w + w),
      x = (v.x + x),
      y = (v.y + y),
      wx = (v.wx + wx),
      wy = (v.wy + wy),
      xy = (v.xy + xy),
      i = (i + v.i),
    )

  @targetName("minus")
  def -(v: Pga2dMultivector): Pga2dMultivector =
    Pga2dMultivector(
      s = (s - v.s),
      w = (w - v.w),
      x = (x - v.x),
      y = (y - v.y),
      wx = (wx - v.wx),
      wy = (wy - v.wy),
      xy = (xy - v.xy),
      i = (i - v.i),
    )

  def madd(v: Pga2dMultivector, mult: Double): Pga2dMultivector =
    Pga2dMultivector(
      s = (s + mult * v.s),
      w = (w + mult * v.w),
      x = (x + mult * v.x),
      y = (y + mult * v.y),
      wx = (wx + mult * v.wx),
      wy = (wy + mult * v.wy),
      xy = (xy + mult * v.xy),
      i = (i + mult * v.i),
    )

  def scale(v: Pga2dMultivector): Pga2dMultivector =
    Pga2dMultivector(
      s = s * v.s,
      w = w * v.w,
      x = x * v.x,
      y = y * v.y,
      wx = wx * v.wx,
      wy = wy * v.wy,
      xy = xy * v.xy,
      i = i * v.i,
    )

  def reciprocal: Pga2dMultivector =
    Pga2dMultivector(
      s = 1.0 / s,
      w = 1.0 / w,
      x = 1.0 / x,
      y = 1.0 / y,
      wx = 1.0 / wx,
      wy = 1.0 / wy,
      xy = 1.0 / xy,
      i = 1.0 / i,
    )

  def toMotorUnsafe: Pga2dMotor =
    Pga2dMotor(
      s = s,
      wx = wx,
      wy = wy,
      xy = xy,
    )

  def toLineUnsafe: Pga2dLine =
    Pga2dLine(
      x = x,
      y = y,
      w = w,
    )

  def toProjectivePointUnsafe: Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = -wy,
      y = wx,
      w = xy,
    )

  def toRotorUnsafe: Pga2dRotor =
    Pga2dRotor(
      s = s,
      xy = xy,
    )

  def toProjectiveTranslatorUnsafe: Pga2dProjectiveTranslator =
    Pga2dProjectiveTranslator(
      s = s,
      wx = wx,
      wy = wy,
    )

  def toTranslatorUnsafe: Pga2dTranslator =
    Pga2dTranslator(
      wx = wx,
      wy = wy,
    )

  def toVectorUnsafe: Pga2dVector =
    Pga2dVector(
      x = -wy,
      y = wx,
    )

  def toPointUnsafe: Pga2dPoint =
    Pga2dPoint(
      x = -wy,
      y = wx,
    )

  def toLineIdealUnsafe: Pga2dLineIdeal =
    Pga2dLineIdeal(
      x = x,
      y = y,
    )

  infix def geometric(v: Pga2dMultivector): Pga2dMultivector =
    Pga2dMultivector(
      s = (s * v.s + v.x * x + v.y * y - v.xy * xy),
      w = (s * v.w + v.s * w + v.x * wx + v.y * wy - i * v.xy - v.i * xy - v.wx * x - v.wy * y),
      x = (s * v.x + v.s * x + v.y * xy - v.xy * y),
      y = (s * v.y + v.s * y + v.xy * x - v.x * xy),
      wx = (i * v.y + s * v.wx + v.i * y + v.s * wx + v.wy * xy + v.x * w - v.w * x - v.xy * wy),
      wy = (s * v.wy + v.s * wy + v.xy * wx + v.y * w - i * v.x - v.i * x - v.w * y - v.wx * xy),
      xy = (s * v.xy + v.s * xy + v.y * x - v.x * y),
      i = (i * v.s + s * v.i + v.w * xy + v.wx * y + v.xy * w + v.y * wx - v.wy * x - v.x * wy),
    )

  infix def dot(v: Pga2dMultivector): Pga2dMultivector =
    Pga2dMultivector(
      s = (s * v.s + v.x * x + v.y * y - v.xy * xy),
      w = (s * v.w + v.s * w + v.x * wx + v.y * wy - i * v.xy - v.i * xy - v.wx * x - v.wy * y),
      x = (s * v.x + v.s * x + v.y * xy - v.xy * y),
      y = (s * v.y + v.s * y + v.xy * x - v.x * xy),
      wx = (i * v.y + s * v.wx + v.i * y + v.s * wx),
      wy = (s * v.wy + v.s * wy - i * v.x - v.i * x),
      xy = (s * v.xy + v.s * xy),
      i = (i * v.s + s * v.i),
    )

  infix def wedge(v: Pga2dMultivector): Pga2dMultivector =
    Pga2dMultivector(
      s = s * v.s,
      w = (s * v.w + v.s * w),
      x = (s * v.x + v.s * x),
      y = (s * v.y + v.s * y),
      wx = (s * v.wx + v.s * wx + v.x * w - v.w * x),
      wy = (s * v.wy + v.s * wy + v.y * w - v.w * y),
      xy = (s * v.xy + v.s * xy + v.y * x - v.x * y),
      i = (i * v.s + s * v.i + v.w * xy + v.wx * y + v.xy * w + v.y * wx - v.wy * x - v.x * wy),
    )

  inline infix def ^(v: Pga2dMultivector): Pga2dMultivector = wedge(v)

  inline infix def meet(v: Pga2dMultivector): Pga2dMultivector = wedge(v)

  infix def antiGeometric(v: Pga2dMultivector): Pga2dMultivector =
    Pga2dMultivector(
      s = (i * v.s + s * v.i + v.w * xy + v.wx * y + v.xy * w + v.y * wx - v.wy * x - v.x * wy),
      w = (i * v.w + v.i * w + v.wy * wx - v.wx * wy),
      x = (i * v.x + v.i * x + v.xy * wx + v.y * w - s * v.wy - v.s * wy - v.w * y - v.wx * xy),
      y = (i * v.y + s * v.wx + v.i * y + v.s * wx + v.w * x + v.xy * wy - v.wy * xy - v.x * w),
      wx = (i * v.wx + v.i * wx + v.wy * w - v.w * wy),
      wy = (i * v.wy + v.i * wy + v.w * wx - v.wx * w),
      xy = (i * v.xy + v.i * xy + v.x * wx + v.y * wy - s * v.w - v.s * w - v.wx * x - v.wy * y),
      i = (i * v.i + v.wx * wx + v.wy * wy - v.w * w),
    )

  infix def antiDot(v: Pga2dMultivector): Pga2dMultivector =
    Pga2dMultivector(
      s = (i * v.s + s * v.i),
      w = (i * v.w + v.i * w),
      x = (i * v.x + v.i * x - s * v.wy - v.s * wy),
      y = (i * v.y + s * v.wx + v.i * y + v.s * wx),
      wx = (i * v.wx + v.i * wx + v.wy * w - v.w * wy),
      wy = (i * v.wy + v.i * wy + v.w * wx - v.wx * w),
      xy = (i * v.xy + v.i * xy + v.x * wx + v.y * wy - s * v.w - v.s * w - v.wx * x - v.wy * y),
      i = (i * v.i + v.wx * wx + v.wy * wy - v.w * w),
    )

  infix def antiWedge(v: Pga2dMultivector): Pga2dMultivector =
    Pga2dMultivector(
      s = (i * v.s + s * v.i + v.w * xy + v.wx * y + v.xy * w + v.y * wx - v.wy * x - v.x * wy),
      w = (i * v.w + v.i * w + v.wy * wx - v.wx * wy),
      x = (i * v.x + v.i * x + v.xy * wx - v.wx * xy),
      y = (i * v.y + v.i * y + v.xy * wy - v.wy * xy),
      wx = (i * v.wx + v.i * wx),
      wy = (i * v.wy + v.i * wy),
      xy = (i * v.xy + v.i * xy),
      i = i * v.i,
    )

  inline infix def v(v: Pga2dMultivector): Pga2dMultivector = antiWedge(v)

  inline infix def join(v: Pga2dMultivector): Pga2dMultivector = antiWedge(v)

  infix def sandwich(v: Pga2dMultivector): Pga2dMultivector =
    val sMs = s * s
    val sMw = s * w
    val sMx = s * x
    val sMy = s * y
    val sMwx = s * wx
    val sMwy = s * wy
    val sMxy = s * xy
    val wMx = w * x
    val wMy = w * y
    val xMx = x * x
    val xMy = x * y
    val xMwx = wx * x
    val xMxy = x * xy
    val xMi = i * x
    val yMy = y * y
    val yMwy = wy * y
    val yMxy = xy * y
    val yMi = i * y
    val wxMxy = wx * xy
    val wyMxy = wy * xy
    val xyMxy = xy * xy
    val xyMi = i * xy
    Pga2dMultivector(
      s = (2.0 * (v.x * (sMx - yMxy) + v.y * (sMy + xMxy)) + v.s * (sMs + xMx + xyMxy + yMy)),
      w = (2.0 * (v.s * (sMw + xMwx + xyMi + yMwy) + v.x * (sMwx + wMx - wyMxy - yMi) + v.y * (sMwy + wMy + wxMxy + xMi)) + v.w * (sMs + xyMxy - xMx - yMy)),
      x = (2.0 * (v.s * (sMx + yMxy) + v.y * (sMxy + xMy)) + v.x * (sMs + xMx - xyMxy - yMy)),
      y = (2.0 * (v.s * (sMy - xMxy) + v.x * (xMy - sMxy)) + v.y * (sMs + yMy - xMx - xyMxy)),
      wx = (2.0 * (v.i * (sMy - xMxy) + v.wy * (sMxy - xMy) + v.xy * (wMy + wxMxy - sMwy - xMi)) + v.wx * (sMs + yMy - xMx - xyMxy)),
      wy = (2.0 * (v.i * (-sMx - yMxy) + v.wx * (-sMxy - xMy) + v.xy * (sMwx + wyMxy - wMx - yMi)) + v.wy * (sMs + xMx - xyMxy - yMy)),
      xy = v.xy * (sMs + xyMxy - xMx - yMy),
      i = (2.0 * (v.wx * (sMy + xMxy) + v.wy * (yMxy - sMx) + v.xy * (sMw + xyMi - xMwx - yMwy)) + v.i * (sMs + xMx + xyMxy + yMy)),
    )

  infix def reverseSandwich(v: Pga2dMultivector): Pga2dMultivector =
    val sMs = s * s
    val sMw = s * w
    val sMx = s * x
    val sMy = s * y
    val sMwx = s * wx
    val sMwy = s * wy
    val sMxy = s * xy
    val wMx = w * x
    val wMy = w * y
    val xMx = x * x
    val xMy = x * y
    val xMwx = wx * x
    val xMxy = x * xy
    val xMi = i * x
    val yMy = y * y
    val yMwy = wy * y
    val yMxy = xy * y
    val yMi = i * y
    val wxMxy = wx * xy
    val wyMxy = wy * xy
    val xyMxy = xy * xy
    val xyMi = i * xy
    Pga2dMultivector(
      s = (2.0 * (v.x * (sMx + yMxy) + v.y * (sMy - xMxy)) + v.s * (sMs + xMx + xyMxy + yMy)),
      w = (2.0 * (v.s * (sMw + xyMi - xMwx - yMwy) + v.x * (wMx + yMi - sMwx - wyMxy) + v.y * (wMy + wxMxy - sMwy - xMi)) + v.w * (sMs + xyMxy - xMx - yMy)),
      x = (2.0 * (v.s * (sMx - yMxy) + v.y * (xMy - sMxy)) + v.x * (sMs + xMx - xyMxy - yMy)),
      y = (2.0 * (v.s * (sMy + xMxy) + v.x * (sMxy + xMy)) + v.y * (sMs + yMy - xMx - xyMxy)),
      wx = (2.0 * (v.i * (sMy + xMxy) + v.wy * (-sMxy - xMy) + v.xy * (sMwy + wMy + wxMxy + xMi)) + v.wx * (sMs + yMy - xMx - xyMxy)),
      wy = (2.0 * (v.i * (yMxy - sMx) + v.wx * (sMxy - xMy) + v.xy * (wyMxy + yMi - sMwx - wMx)) + v.wy * (sMs + xMx - xyMxy - yMy)),
      xy = v.xy * (sMs + xyMxy - xMx - yMy),
      i = (2.0 * (v.wx * (sMy - xMxy) + v.wy * (-sMx - yMxy) + v.xy * (sMw + xMwx + xyMi + yMwy)) + v.i * (sMs + xMx + xyMxy + yMy)),
    )

  infix def cross(v: Pga2dMultivector): Pga2dMultivector =
    Pga2dMultivector(
      s = 0.0,
      w = (v.x * wx + v.y * wy - v.wx * x - v.wy * y),
      x = (v.y * xy - v.xy * y),
      y = (v.xy * x - v.x * xy),
      wx = (v.wy * xy + v.x * w - v.w * x - v.xy * wy),
      wy = (v.xy * wx + v.y * w - v.w * y - v.wx * xy),
      xy = (v.y * x - v.x * y),
      i = 0.0,
    )


object Pga2dMultivector:

  inline val componentsCount = 8

  val zero: Pga2dMultivector = Pga2dMultivector(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0)