package me.kright.gametools.pga2d

import me.kright.arrayview.{ArrayView2d, ArrayView2dFlat}
import me.kright.gametools.matrix.*
import me.kright.gametools.flatarray.FlatDoubleSerializer
import scala.collection.immutable.ArraySeq

/**
 * Conversions between linear operators on Pga2dProjectivePoint and 3x3 matrices.
 *
 * Generated by pgaNdCodeGen (me.kright.gametools.pga.codegen.scalagen.pga2d.runScalaCodeGen).
 * Do not edit by hand: change the generator and re-run it.
 */
object Pga2dMatrix:
  private val basis = ArraySeq[Pga2dProjectivePoint](
    Pga2dProjectivePoint(1, 0, 0),
    Pga2dProjectivePoint(0, 1, 0),
    Pga2dProjectivePoint(0, 0, 1),
  )

  def multiply(matrix: ArrayView2d[Double], b: Pga2dProjectivePoint): Pga2dProjectivePoint =
    // free for the flat matrices linearMapping builds; copies a lazy view once
    val m = matrix.withSimpleLayout.data

    inline def dot(offset: Int): Double =
      b.x * m(offset) +
        b.y * m(offset + 1) +
        b.w * m(offset + 2)

    Pga2dProjectivePoint(
      x = dot(0),
      y = dot(3),
      w = dot(6),
    )

  def linearMapping(map: Pga2dProjectivePoint => Pga2dProjectivePoint): ArrayView2dFlat[Double] =
    val matrix = ArrayView2dFlat[Double](3, 3)
    for ((b, i) <- basis.zipWithIndex) {
      val mappedB = map(b)
      FlatDoubleSerializer.write(mappedB, matrix.data, i * 3)
    }
    matrix.transposeInplace()
    matrix

