package me.kright.gametools.pga2d

import scala.annotation.targetName
import me.kright.gametools.flatarray.FlatDoubleSerializer


/**
 * A translator: translation of the 2d plane, applied with translator.sandwich(obj). Moves points but not vectors.
 * A translator is the exponent of a Pga2dVector (vector.exp()), and translator.log() returns that vector back.
 *
 * Variable fields: wx, wy.
 * Constant fields: s = 1.0.
 * Basis blade coefficients: wx = wx, wy = wy, s = 1.0.
 *
 * Generated by pgaNdCodeGen (me.kright.gametools.pga.codegen.scala.pga2d.runScalaCodeGen).
 * Do not edit by hand: change the generator and re-run it.
 */
final case class Pga2dTranslator(wx: Double = 0.0,
                                 wy: Double = 0.0) derives CanEqual, FlatDoubleSerializer:
  inline val s = 1.0

  override def toString: String =
    s"Pga2dTranslator(wx = $wx, wy = $wy)"

  def dual: Pga2dMultivector =
    Pga2dMultivector(
      s = 0.0,
      w = 0.0,
      x = -wy,
      y = wx,
      wx = 0.0,
      wy = 0.0,
      xy = 0.0,
      i = 1.0,
    )

  def weight: Pga2dVector =
    Pga2dVector(
      x = -wy,
      y = wx,
    )

  def bulk: Double =
    1.0

  @targetName("unaryMinus")
  def unary_- : Pga2dProjectiveTranslator =
    Pga2dProjectiveTranslator(
      s = -1.0,
      wx = -wx,
      wy = -wy,
    )

  def reverse: Pga2dTranslator =
    Pga2dTranslator(
      wx = -wx,
      wy = -wy,
    )

  def antiReverse: Pga2dProjectiveTranslator =
    Pga2dProjectiveTranslator(
      s = -1.0,
      wx = wx,
      wy = wy,
    )

  def bulkNormSquare: Double =
    1.0

  def bulkNorm: Double =
    Math.sqrt(bulkNormSquare)

  def normalizedByBulk =
    this / bulkNorm

  def weightNormSquare: Double =
    (wx * wx + wy * wy)

  def weightNorm: Double =
    Math.sqrt(weightNormSquare)

  def normalizedByWeight =
    this / weightNorm

  def normSquare: Double =
    (1.0 + wx * wx + wy * wy)

  def norm: Double =
    Math.sqrt(normSquare)

  def normalizedByNorm =
    this / norm

  @targetName("times")
  def *(v: Double): Pga2dProjectiveTranslator =
    Pga2dProjectiveTranslator(
      s = v,
      wx = v * wx,
      wy = v * wy,
    )

  @targetName("div")
  def /(v: Double): Pga2dProjectiveTranslator =
    this * (1.0 / v)

  @targetName("plus")
  def +(v: Pga2dTranslator): Pga2dProjectiveTranslator =
    Pga2dProjectiveTranslator(
      s = 2.0,
      wx = (v.wx + wx),
      wy = (v.wy + wy),
    )

  @targetName("minus")
  def -(v: Pga2dTranslator): Pga2dVector =
    Pga2dVector(
      x = (v.wy - wy),
      y = (wx - v.wx),
    )

  def madd(v: Pga2dTranslator, mult: Double): Pga2dProjectiveTranslator =
    Pga2dProjectiveTranslator(
      s = (1.0 + mult),
      wx = (wx + mult * v.wx),
      wy = (wy + mult * v.wy),
    )

  def multiplyElementwise(v: Pga2dTranslator): Pga2dTranslator =
    Pga2dTranslator(
      wx = v.wx * wx,
      wy = v.wy * wy,
    )

  def log(): Pga2dVector =
    Pga2dVector(
      x = -wy,
      y = wx,
    )

  def toMultivector: Pga2dMultivector =
    Pga2dMultivector(
      s = 1.0,
      w = 0.0,
      x = 0.0,
      y = 0.0,
      wx = wx,
      wy = wy,
      xy = 0.0,
      i = 0.0,
    )

  def toMotor: Pga2dMotor =
    Pga2dMotor(
      s = 1.0,
      wx = wx,
      wy = wy,
      xy = 0.0,
    )

  def toProjectivePointUnsafe: Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = -wy,
      y = wx,
      w = 0.0,
    )

  def toRotorUnsafe: Pga2dRotor =
    Pga2dRotor(
      s = 1.0,
      xy = 0.0,
    )

  def toProjectiveTranslator: Pga2dProjectiveTranslator =
    Pga2dProjectiveTranslator(
      s = 1.0,
      wx = wx,
      wy = wy,
    )

  def toVectorUnsafe: Pga2dVector =
    Pga2dVector(
      x = -wy,
      y = wx,
    )

  def toPointUnsafe: Pga2dPoint =
    Pga2dPoint(
      x = -wy,
      y = wx,
    )

  infix def geometric(v: Pga2dMotor): Pga2dMotor =
    Pga2dMotor(
      s = v.s,
      wx = (v.wx + v.s * wx - v.xy * wy),
      wy = (v.wy + v.s * wy + v.xy * wx),
      xy = v.xy,
    )

  infix def geometric(v: Pga2dLine): Pga2dMultivector =
    Pga2dMultivector(
      s = 0.0,
      w = (v.w + v.x * wx + v.y * wy),
      x = v.x,
      y = v.y,
      wx = 0.0,
      wy = 0.0,
      xy = 0.0,
      i = (v.y * wx - v.x * wy),
    )

  infix def geometric(v: Pga2dProjectivePoint): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = (v.x - v.w * wx),
      y = (v.y - v.w * wy),
      w = v.w,
    )

  infix def geometric(v: Pga2dRotor): Pga2dMotor =
    Pga2dMotor(
      s = v.s,
      wx = (v.s * wx - v.xy * wy),
      wy = (v.s * wy + v.xy * wx),
      xy = v.xy,
    )

  infix def geometric(v: Pga2dProjectiveTranslator): Pga2dProjectiveTranslator =
    Pga2dProjectiveTranslator(
      s = v.s,
      wx = (v.wx + v.s * wx),
      wy = (v.wy + v.s * wy),
    )

  infix def geometric(v: Pga2dTranslator): Pga2dTranslator =
    Pga2dTranslator(
      wx = (v.wx + wx),
      wy = (v.wy + wy),
    )

  infix def geometric(v: Pga2dVector): Pga2dVector =
    v

  infix def geometric(v: Pga2dPoint): Pga2dPoint =
    Pga2dPoint(
      x = (v.x - wx),
      y = (v.y - wy),
    )

  infix def geometric(v: Pga2dLineIdeal): Pga2dMultivector =
    Pga2dMultivector(
      s = 0.0,
      w = (v.x * wx + v.y * wy),
      x = v.x,
      y = v.y,
      wx = 0.0,
      wy = 0.0,
      xy = 0.0,
      i = (v.y * wx - v.x * wy),
    )

  infix def geometric(v: Pga2dPseudoScalar): Pga2dPseudoScalar =
    v

  infix def geometric(v: Pga2dPointCenter.type): Pga2dPoint =
    Pga2dPoint(
      x = -wx,
      y = -wy,
    )

  infix def dot(v: Pga2dMotor): Pga2dMotor =
    Pga2dMotor(
      s = v.s,
      wx = (v.wx + v.s * wx),
      wy = (v.wy + v.s * wy),
      xy = v.xy,
    )

  infix def dot(v: Pga2dLine): Pga2dLine =
    Pga2dLine(
      x = v.x,
      y = v.y,
      w = (v.w + v.x * wx + v.y * wy),
    )

  infix def dot(v: Pga2dProjectivePoint): Pga2dProjectivePoint =
    v

  infix def dot(v: Pga2dRotor): Pga2dMotor =
    Pga2dMotor(
      s = v.s,
      wx = v.s * wx,
      wy = v.s * wy,
      xy = v.xy,
    )

  infix def dot(v: Pga2dProjectiveTranslator): Pga2dProjectiveTranslator =
    Pga2dProjectiveTranslator(
      s = v.s,
      wx = (v.wx + v.s * wx),
      wy = (v.wy + v.s * wy),
    )

  infix def dot(v: Pga2dTranslator): Pga2dTranslator =
    Pga2dTranslator(
      wx = (v.wx + wx),
      wy = (v.wy + wy),
    )

  infix def dot(v: Pga2dVector): Pga2dVector =
    v

  infix def dot(v: Pga2dPoint): Pga2dPoint =
    v

  infix def dot(v: Pga2dLineIdeal): Pga2dLine =
    Pga2dLine(
      x = v.x,
      y = v.y,
      w = (v.x * wx + v.y * wy),
    )

  infix def dot(v: Pga2dPseudoScalar): Pga2dPseudoScalar =
    v

  infix def dot(v: Pga2dPointCenter.type): Pga2dPointCenter.type =
    v

  infix def wedge(v: Pga2dMotor): Pga2dMotor =
    Pga2dMotor(
      s = v.s,
      wx = (v.wx + v.s * wx),
      wy = (v.wy + v.s * wy),
      xy = v.xy,
    )

  inline infix def ^(v: Pga2dMotor): Pga2dMotor = wedge(v)

  inline infix def meet(v: Pga2dMotor): Pga2dMotor = wedge(v)

  infix def wedge(v: Pga2dLine): Pga2dMultivector =
    Pga2dMultivector(
      s = 0.0,
      w = v.w,
      x = v.x,
      y = v.y,
      wx = 0.0,
      wy = 0.0,
      xy = 0.0,
      i = (v.y * wx - v.x * wy),
    )

  inline infix def ^(v: Pga2dLine): Pga2dMultivector = wedge(v)

  inline infix def meet(v: Pga2dLine): Pga2dMultivector = wedge(v)

  infix def wedge(v: Pga2dProjectivePoint): Pga2dProjectivePoint =
    v

  inline infix def ^(v: Pga2dProjectivePoint): Pga2dProjectivePoint = wedge(v)

  inline infix def meet(v: Pga2dProjectivePoint): Pga2dProjectivePoint = wedge(v)

  infix def wedge(v: Pga2dRotor): Pga2dMotor =
    Pga2dMotor(
      s = v.s,
      wx = v.s * wx,
      wy = v.s * wy,
      xy = v.xy,
    )

  inline infix def ^(v: Pga2dRotor): Pga2dMotor = wedge(v)

  inline infix def meet(v: Pga2dRotor): Pga2dMotor = wedge(v)

  infix def wedge(v: Pga2dProjectiveTranslator): Pga2dProjectiveTranslator =
    Pga2dProjectiveTranslator(
      s = v.s,
      wx = (v.wx + v.s * wx),
      wy = (v.wy + v.s * wy),
    )

  inline infix def ^(v: Pga2dProjectiveTranslator): Pga2dProjectiveTranslator = wedge(v)

  inline infix def meet(v: Pga2dProjectiveTranslator): Pga2dProjectiveTranslator = wedge(v)

  infix def wedge(v: Pga2dTranslator): Pga2dTranslator =
    Pga2dTranslator(
      wx = (v.wx + wx),
      wy = (v.wy + wy),
    )

  inline infix def ^(v: Pga2dTranslator): Pga2dTranslator = wedge(v)

  inline infix def meet(v: Pga2dTranslator): Pga2dTranslator = wedge(v)

  infix def wedge(v: Pga2dVector): Pga2dVector =
    v

  inline infix def ^(v: Pga2dVector): Pga2dVector = wedge(v)

  inline infix def meet(v: Pga2dVector): Pga2dVector = wedge(v)

  infix def wedge(v: Pga2dPoint): Pga2dPoint =
    v

  inline infix def ^(v: Pga2dPoint): Pga2dPoint = wedge(v)

  inline infix def meet(v: Pga2dPoint): Pga2dPoint = wedge(v)

  infix def wedge(v: Pga2dLineIdeal): Pga2dMultivector =
    Pga2dMultivector(
      s = 0.0,
      w = 0.0,
      x = v.x,
      y = v.y,
      wx = 0.0,
      wy = 0.0,
      xy = 0.0,
      i = (v.y * wx - v.x * wy),
    )

  inline infix def ^(v: Pga2dLineIdeal): Pga2dMultivector = wedge(v)

  inline infix def meet(v: Pga2dLineIdeal): Pga2dMultivector = wedge(v)

  infix def wedge(v: Pga2dPseudoScalar): Pga2dPseudoScalar =
    v

  inline infix def ^(v: Pga2dPseudoScalar): Pga2dPseudoScalar = wedge(v)

  inline infix def meet(v: Pga2dPseudoScalar): Pga2dPseudoScalar = wedge(v)

  infix def wedge(v: Pga2dPointCenter.type): Pga2dPointCenter.type =
    v

  inline infix def ^(v: Pga2dPointCenter.type): Pga2dPointCenter.type = wedge(v)

  inline infix def meet(v: Pga2dPointCenter.type): Pga2dPointCenter.type = wedge(v)

  infix def antiGeometric(v: Pga2dMotor): Pga2dMultivector =
    Pga2dMultivector(
      s = 0.0,
      w = (v.wy * wx - v.wx * wy),
      x = (-v.wy + v.xy * wx - v.s * wy),
      y = (v.wx + v.s * wx + v.xy * wy),
      wx = 0.0,
      wy = 0.0,
      xy = 0.0,
      i = (v.wx * wx + v.wy * wy),
    )

  infix def antiGeometric(v: Pga2dLine): Pga2dMotor =
    Pga2dMotor(
      s = (v.y * wx - v.x * wy),
      wx = -v.w * wy,
      wy = v.w * wx,
      xy = (-v.w + v.x * wx + v.y * wy),
    )

  infix def antiGeometric(v: Pga2dProjectivePoint): Pga2dMultivector =
    Pga2dMultivector(
      s = 0.0,
      w = (-v.x * wx - v.y * wy),
      x = (v.x + v.w * wx),
      y = (v.y + v.w * wy),
      wx = 0.0,
      wy = 0.0,
      xy = 0.0,
      i = (v.y * wx - v.x * wy),
    )

  infix def antiGeometric(v: Pga2dRotor): Pga2dLineIdeal =
    Pga2dLineIdeal(
      x = (v.xy * wx - v.s * wy),
      y = (v.s * wx + v.xy * wy),
    )

  infix def antiGeometric(v: Pga2dProjectiveTranslator): Pga2dMultivector =
    Pga2dMultivector(
      s = 0.0,
      w = (v.wy * wx - v.wx * wy),
      x = (-v.wy - v.s * wy),
      y = (v.wx + v.s * wx),
      wx = 0.0,
      wy = 0.0,
      xy = 0.0,
      i = (v.wx * wx + v.wy * wy),
    )

  infix def antiGeometric(v: Pga2dTranslator): Pga2dMultivector =
    Pga2dMultivector(
      s = 0.0,
      w = (v.wy * wx - v.wx * wy),
      x = (-v.wy - wy),
      y = (v.wx + wx),
      wx = 0.0,
      wy = 0.0,
      xy = 0.0,
      i = (v.wx * wx + v.wy * wy),
    )

  infix def antiGeometric(v: Pga2dVector): Pga2dMultivector =
    Pga2dMultivector(
      s = 0.0,
      w = (-v.x * wx - v.y * wy),
      x = v.x,
      y = v.y,
      wx = 0.0,
      wy = 0.0,
      xy = 0.0,
      i = (v.y * wx - v.x * wy),
    )

  infix def antiGeometric(v: Pga2dPoint): Pga2dMultivector =
    Pga2dMultivector(
      s = 0.0,
      w = (-v.x * wx - v.y * wy),
      x = (v.x + wx),
      y = (v.y + wy),
      wx = 0.0,
      wy = 0.0,
      xy = 0.0,
      i = (v.y * wx - v.x * wy),
    )

  infix def antiGeometric(v: Pga2dLineIdeal): Pga2dRotor =
    Pga2dRotor(
      s = (v.y * wx - v.x * wy),
      xy = (v.x * wx + v.y * wy),
    )

  infix def antiGeometric(v: Pga2dPseudoScalar): Pga2dProjectiveTranslator =
    Pga2dProjectiveTranslator(
      s = v.i,
      wx = v.i * wx,
      wy = v.i * wy,
    )

  infix def antiGeometric(v: Pga2dPointCenter.type): Pga2dLineIdeal =
    Pga2dLineIdeal(
      x = wx,
      y = wy,
    )

  infix def antiDot(v: Pga2dMotor): Pga2dMultivector =
    Pga2dMultivector(
      s = 0.0,
      w = 0.0,
      x = (-v.wy - v.s * wy),
      y = (v.wx + v.s * wx),
      wx = 0.0,
      wy = 0.0,
      xy = 0.0,
      i = (v.wx * wx + v.wy * wy),
    )

  infix def antiDot(v: Pga2dLine): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = -v.w * wx,
      y = -v.w * wy,
      w = (-v.w + v.x * wx + v.y * wy),
    )

  infix def antiDot(v: Pga2dProjectivePoint): Pga2dMultivector =
    Pga2dMultivector(
      s = 0.0,
      w = 0.0,
      x = v.x,
      y = v.y,
      wx = 0.0,
      wy = 0.0,
      xy = 0.0,
      i = (v.y * wx - v.x * wy),
    )

  infix def antiDot(v: Pga2dRotor): Pga2dLineIdeal =
    Pga2dLineIdeal(
      x = -v.s * wy,
      y = v.s * wx,
    )

  infix def antiDot(v: Pga2dProjectiveTranslator): Pga2dMultivector =
    Pga2dMultivector(
      s = 0.0,
      w = 0.0,
      x = (-v.wy - v.s * wy),
      y = (v.wx + v.s * wx),
      wx = 0.0,
      wy = 0.0,
      xy = 0.0,
      i = (v.wx * wx + v.wy * wy),
    )

  infix def antiDot(v: Pga2dTranslator): Pga2dMultivector =
    Pga2dMultivector(
      s = 0.0,
      w = 0.0,
      x = (-v.wy - wy),
      y = (v.wx + wx),
      wx = 0.0,
      wy = 0.0,
      xy = 0.0,
      i = (v.wx * wx + v.wy * wy),
    )

  infix def antiDot(v: Pga2dVector): Pga2dMultivector =
    Pga2dMultivector(
      s = 0.0,
      w = 0.0,
      x = v.x,
      y = v.y,
      wx = 0.0,
      wy = 0.0,
      xy = 0.0,
      i = (v.y * wx - v.x * wy),
    )

  infix def antiDot(v: Pga2dPoint): Pga2dMultivector =
    Pga2dMultivector(
      s = 0.0,
      w = 0.0,
      x = v.x,
      y = v.y,
      wx = 0.0,
      wy = 0.0,
      xy = 0.0,
      i = (v.y * wx - v.x * wy),
    )

  infix def antiDot(v: Pga2dLineIdeal): Pga2dRotor =
    Pga2dRotor(
      s = 0.0,
      xy = (v.x * wx + v.y * wy),
    )

  infix def antiDot(v: Pga2dPseudoScalar): Pga2dProjectiveTranslator =
    Pga2dProjectiveTranslator(
      s = v.i,
      wx = v.i * wx,
      wy = v.i * wy,
    )

  infix def antiWedge(v: Pga2dMotor): Pga2dLine =
    Pga2dLine(
      x = v.xy * wx,
      y = v.xy * wy,
      w = (v.wy * wx - v.wx * wy),
    )

  inline infix def v(v: Pga2dMotor): Pga2dLine = antiWedge(v)

  inline infix def join(v: Pga2dMotor): Pga2dLine = antiWedge(v)

  infix def antiWedge(v: Pga2dLine): Double =
    (v.y * wx - v.x * wy)

  inline infix def v(v: Pga2dLine): Double = antiWedge(v)

  inline infix def join(v: Pga2dLine): Double = antiWedge(v)

  infix def antiWedge(v: Pga2dProjectivePoint): Pga2dLine =
    Pga2dLine(
      x = v.w * wx,
      y = v.w * wy,
      w = (-v.x * wx - v.y * wy),
    )

  inline infix def v(v: Pga2dProjectivePoint): Pga2dLine = antiWedge(v)

  inline infix def join(v: Pga2dProjectivePoint): Pga2dLine = antiWedge(v)

  infix def antiWedge(v: Pga2dRotor): Pga2dLineIdeal =
    Pga2dLineIdeal(
      x = v.xy * wx,
      y = v.xy * wy,
    )

  inline infix def v(v: Pga2dRotor): Pga2dLineIdeal = antiWedge(v)

  inline infix def join(v: Pga2dRotor): Pga2dLineIdeal = antiWedge(v)

  infix def antiWedge(v: Pga2dProjectiveTranslator): Pga2dLine =
    Pga2dLine(
      x = 0.0,
      y = 0.0,
      w = (v.wy * wx - v.wx * wy),
    )

  inline infix def v(v: Pga2dProjectiveTranslator): Pga2dLine = antiWedge(v)

  inline infix def join(v: Pga2dProjectiveTranslator): Pga2dLine = antiWedge(v)

  infix def antiWedge(v: Pga2dTranslator): Pga2dLine =
    Pga2dLine(
      x = 0.0,
      y = 0.0,
      w = (v.wy * wx - v.wx * wy),
    )

  inline infix def v(v: Pga2dTranslator): Pga2dLine = antiWedge(v)

  inline infix def join(v: Pga2dTranslator): Pga2dLine = antiWedge(v)

  infix def antiWedge(v: Pga2dVector): Pga2dLine =
    Pga2dLine(
      x = 0.0,
      y = 0.0,
      w = (-v.x * wx - v.y * wy),
    )

  inline infix def v(v: Pga2dVector): Pga2dLine = antiWedge(v)

  inline infix def join(v: Pga2dVector): Pga2dLine = antiWedge(v)

  infix def antiWedge(v: Pga2dPoint): Pga2dLine =
    Pga2dLine(
      x = wx,
      y = wy,
      w = (-v.x * wx - v.y * wy),
    )

  inline infix def v(v: Pga2dPoint): Pga2dLine = antiWedge(v)

  inline infix def join(v: Pga2dPoint): Pga2dLine = antiWedge(v)

  infix def antiWedge(v: Pga2dLineIdeal): Double =
    (v.y * wx - v.x * wy)

  inline infix def v(v: Pga2dLineIdeal): Double = antiWedge(v)

  inline infix def join(v: Pga2dLineIdeal): Double = antiWedge(v)

  infix def antiWedge(v: Pga2dPseudoScalar): Pga2dProjectiveTranslator =
    Pga2dProjectiveTranslator(
      s = v.i,
      wx = v.i * wx,
      wy = v.i * wy,
    )

  inline infix def v(v: Pga2dPseudoScalar): Pga2dProjectiveTranslator = antiWedge(v)

  inline infix def join(v: Pga2dPseudoScalar): Pga2dProjectiveTranslator = antiWedge(v)

  infix def antiWedge(v: Pga2dPointCenter.type): Pga2dLineIdeal =
    Pga2dLineIdeal(
      x = wx,
      y = wy,
    )

  inline infix def v(v: Pga2dPointCenter.type): Pga2dLineIdeal = antiWedge(v)

  inline infix def join(v: Pga2dPointCenter.type): Pga2dLineIdeal = antiWedge(v)

  infix def sandwich(v: Pga2dMotor): Pga2dMotor =
    Pga2dMotor(
      s = v.s,
      wx = (v.wx - 2.0 * v.xy * wy),
      wy = (v.wy + 2.0 * v.xy * wx),
      xy = v.xy,
    )

  infix def sandwich(v: Pga2dLine): Pga2dLine =
    Pga2dLine(
      x = v.x,
      y = v.y,
      w = (v.w + 2.0 * v.x * wx + 2.0 * v.y * wy),
    )

  infix def sandwich(v: Pga2dProjectivePoint): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = (v.x - 2.0 * v.w * wx),
      y = (v.y - 2.0 * v.w * wy),
      w = v.w,
    )

  infix def sandwich(v: Pga2dRotor): Pga2dMotor =
    Pga2dMotor(
      s = v.s,
      wx = -2.0 * v.xy * wy,
      wy = 2.0 * v.xy * wx,
      xy = v.xy,
    )

  infix def sandwich(v: Pga2dProjectiveTranslator): Pga2dProjectiveTranslator =
    v

  infix def sandwich(v: Pga2dTranslator): Pga2dTranslator =
    v

  infix def sandwich(v: Pga2dVector): Pga2dVector =
    v

  infix def sandwich(v: Pga2dPoint): Pga2dPoint =
    Pga2dPoint(
      x = (v.x - 2.0 * wx),
      y = (v.y - 2.0 * wy),
    )

  infix def sandwich(v: Pga2dLineIdeal): Pga2dLine =
    Pga2dLine(
      x = v.x,
      y = v.y,
      w = 2.0 * (v.x * wx + v.y * wy),
    )

  infix def sandwich(v: Pga2dPseudoScalar): Pga2dPseudoScalar =
    v

  infix def sandwich(v: Pga2dPointCenter.type): Pga2dPoint =
    Pga2dPoint(
      x = -2.0 * wx,
      y = -2.0 * wy,
    )

  infix def reverseSandwich(v: Pga2dMotor): Pga2dMotor =
    Pga2dMotor(
      s = v.s,
      wx = (v.wx + 2.0 * v.xy * wy),
      wy = (v.wy - 2.0 * v.xy * wx),
      xy = v.xy,
    )

  infix def reverseSandwich(v: Pga2dLine): Pga2dLine =
    Pga2dLine(
      x = v.x,
      y = v.y,
      w = (v.w - 2.0 * v.x * wx - 2.0 * v.y * wy),
    )

  infix def reverseSandwich(v: Pga2dProjectivePoint): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = (v.x + 2.0 * v.w * wx),
      y = (v.y + 2.0 * v.w * wy),
      w = v.w,
    )

  infix def reverseSandwich(v: Pga2dRotor): Pga2dMotor =
    Pga2dMotor(
      s = v.s,
      wx = 2.0 * v.xy * wy,
      wy = -2.0 * v.xy * wx,
      xy = v.xy,
    )

  infix def reverseSandwich(v: Pga2dProjectiveTranslator): Pga2dProjectiveTranslator =
    v

  infix def reverseSandwich(v: Pga2dTranslator): Pga2dTranslator =
    v

  infix def reverseSandwich(v: Pga2dVector): Pga2dVector =
    v

  infix def reverseSandwich(v: Pga2dPoint): Pga2dPoint =
    Pga2dPoint(
      x = (v.x + 2.0 * wx),
      y = (v.y + 2.0 * wy),
    )

  infix def reverseSandwich(v: Pga2dLineIdeal): Pga2dLine =
    Pga2dLine(
      x = v.x,
      y = v.y,
      w = 2.0 * (-v.x * wx - v.y * wy),
    )

  infix def reverseSandwich(v: Pga2dPseudoScalar): Pga2dPseudoScalar =
    v

  infix def reverseSandwich(v: Pga2dPointCenter.type): Pga2dPoint =
    Pga2dPoint(
      x = 2.0 * wx,
      y = 2.0 * wy,
    )

  infix def cross(v: Pga2dMotor): Pga2dVector =
    Pga2dVector(
      x = -v.xy * wx,
      y = -v.xy * wy,
    )

  infix def cross(v: Pga2dLine): Pga2dLine =
    Pga2dLine(
      x = 0.0,
      y = 0.0,
      w = (v.x * wx + v.y * wy),
    )

  infix def cross(v: Pga2dProjectivePoint): Pga2dVector =
    Pga2dVector(
      x = -v.w * wx,
      y = -v.w * wy,
    )

  infix def cross(v: Pga2dRotor): Pga2dVector =
    Pga2dVector(
      x = -v.xy * wx,
      y = -v.xy * wy,
    )

  infix def cross(v: Pga2dPoint): Pga2dVector =
    Pga2dVector(
      x = -wx,
      y = -wy,
    )

  infix def cross(v: Pga2dLineIdeal): Pga2dLine =
    Pga2dLine(
      x = 0.0,
      y = 0.0,
      w = (v.x * wx + v.y * wy),
    )

  infix def cross(v: Pga2dPointCenter.type): Pga2dVector =
    Pga2dVector(
      x = -wx,
      y = -wy,
    )


object Pga2dTranslator:

  inline val componentsCount = 2

  val id: Pga2dTranslator = Pga2dTranslator(0.0, 0.0)

  def addVector(v: Pga2dVector): Pga2dTranslator =
    Pga2dTranslator(
      wx = -0.5 * v.x,
      wy = -0.5 * v.y,
    )