package me.kright.gametools.pga2d

import scala.annotation.targetName
import me.kright.gametools.flatarray.FlatDoubleSerializer
import me.kright.gametools.mathutil.CanEqualWithEps


/**
 * A point with three homogeneous coordinates: (x/w, y/w) when w != 0, or an ideal point (a direction) when w == 0.
 * The grade-2 element of 2d PGA, stored in dual representation.
 * projectivePoint.exp is a Pga2dMotor (rotation around the point), and motor.log is a Pga2dProjectivePoint.
 *
 * Variable fields: x, y, w.
 * Basis blade coefficients: wy = -x, wx = y, xy = w.
 *
 * Generated by pgaNdCodeGen (me.kright.gametools.pga.codegen.scalagen.pga2d.runScalaCodeGen).
 * Do not edit by hand: change the generator and re-run it.
 */
final case class Pga2dProjectivePoint(x: Double = 0.0,
                                      y: Double = 0.0,
                                      w: Double = 0.0) derives CanEqual, CanEqualWithEps, FlatDoubleSerializer:

  inline def wy: Double = -x

  inline def wx: Double = y

  inline def xy: Double = w

  override def toString: String =
    s"Pga2dProjectivePoint(x = $x, y = $y, w = $w)"

  def dual: Pga2dLine =
    Pga2dLine(
      x = x,
      y = y,
      w = w,
    )

  def weight: Pga2dVector =
    Pga2dVector(
      x = x,
      y = y,
    )

  def bulk: Pga2dRotor =
    Pga2dRotor(
      s = 0.0,
      xy = w,
    )

  @targetName("unaryMinus")
  def unary_- : Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = -x,
      y = -y,
      w = -w,
    )

  def reverse: Pga2dProjectivePoint =
    -this

  def antiReverse: Pga2dProjectivePoint =
    this

  def bulkNormSquare: Double =
    w * w

  def bulkNorm: Double =
    Math.sqrt(bulkNormSquare)

  def normalizedByBulk =
    this / bulkNorm

  def weightNormSquare: Double =
    (x * x + y * y)

  def weightNorm: Double =
    Math.sqrt(weightNormSquare)

  def normalizedByWeight =
    this / weightNorm

  def normSquare: Double =
    (w * w + x * x + y * y)

  def norm: Double =
    Math.sqrt(normSquare)

  def normalizedByNorm =
    this / norm

  @targetName("times")
  def *(r: Double): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = r * x,
      y = r * y,
      w = r * w,
    )

  /** multiplies by the reciprocal: one division instead of one per component, at the cost of one extra rounding (~0.5 ulp) */
  @targetName("div")
  def /(r: Double): Pga2dProjectivePoint =
    this * (1.0 / r)

  @targetName("plus")
  def +(r: Pga2dProjectivePoint): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = (r.x + x),
      y = (r.y + y),
      w = (r.w + w),
    )

  @targetName("minus")
  def -(r: Pga2dProjectivePoint): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = (x - r.x),
      y = (y - r.y),
      w = (w - r.w),
    )

  def madd(r: Pga2dProjectivePoint, mult: Double): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = (x + mult * r.x),
      y = (y + mult * r.y),
      w = (w + mult * r.w),
    )

  @targetName("plus")
  def +(r: Pga2dPoint): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = (r.x + x),
      y = (r.y + y),
      w = (1.0 + w),
    )

  @targetName("minus")
  def -(r: Pga2dPoint): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = (x - r.x),
      y = (y - r.y),
      w = (-1.0 + w),
    )

  def madd(r: Pga2dPoint, mult: Double): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = (x + mult * r.x),
      y = (y + mult * r.y),
      w = (mult + w),
    )

  @targetName("plus")
  def +(r: Pga2dVector): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = (r.x + x),
      y = (r.y + y),
      w = w,
    )

  @targetName("minus")
  def -(r: Pga2dVector): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = (x - r.x),
      y = (y - r.y),
      w = w,
    )

  def madd(r: Pga2dVector, mult: Double): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = (x + mult * r.x),
      y = (y + mult * r.y),
      w = w,
    )

  /** componentwise product on the raw fields; NOT a geometric-algebra operation (basis-dependent) */
  def scale(r: Pga2dProjectivePoint): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = x * r.x,
      y = y * r.y,
      w = w * r.w,
    )

  /** componentwise 1/x on the raw fields (a zero field yields Infinity); NOT the multiplicative inverse */
  def reciprocal: Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = 1.0 / x,
      y = 1.0 / y,
      w = 1.0 / w,
    )

  def exp: Pga2dMotor =
    val len = bulkNorm
    val cos = Math.cos(len)

    // sin(x)/x = 1 - x^2/6 + x^4/120 - ...; at x <= 1e-5 the dropped x^4/120 <= 8.4e-23
    // relative term is far below 1e-17, so the second-order form is exact in double
    val sinDivLen = if (len > 1e-5) {
      Math.sin(len) / len
    } else {
      1.0 - (len * len) / 6.0
    }

    Pga2dMotor(
      s = cos,
      wx = sinDivLen * y,
      wy = -sinDivLen * x,
      xy = sinDivLen * w,
    )

  def exp(t: Double): Pga2dMotor =
    val len = bulkNorm * Math.abs(t)
    val cos = Math.cos(len)

    // sin(x)/x = 1 - x^2/6 + x^4/120 - ...; at x <= 1e-5 the dropped x^4/120 <= 8.4e-23
    // relative term is far below 1e-17, so the second-order form is exact in double
    val sinDivLen = if (len > 1e-5) {
      Math.sin(len) / len
    } else {
      1.0 - (len * len) / 6.0
    }

    Pga2dMotor(
      s = cos,
      wx = sinDivLen * t * y,
      wy = -sinDivLen * t * x,
      xy = sinDivLen * t * w,
    )

  /**
   * The differential of exp: maps the direction b of change of this grade-2 element u to the
   * resulting velocity of u.exp, expressed as a grade-2 element (the left trivialization):
   *   (u + b * h).exp == (u.dexp(b) * h).exp.geometric(u.exp) + O(h^2)
   * In SE(2)/robotics terms this is the left Jacobian of exp applied to b;
   * the right Jacobian (for the motor.geometric(u.exp) update convention) is (-u).dexp(b).
   * The closed form (x is `cross`, the angle c = bulkNorm is real in 2d: u * u = -c^2 exactly):
   *   dexp(u, b) = b + (sin(c)^2/c^2) * (u x b) + ((2c - sin(2c))/(2c^3)) * (u x (u x b))
   * Degenerate cases are exact and NaN-free: Pga2dProjectivePoint.zero.dexp(b) == b,
   * and for an ideal u (w == 0) the series terminates at b + u.cross(b).
   * The inverse is dexpInv: u.dexpInv(u.dexp(b)) == b.
   */
  def dexp(b: Pga2dProjectivePoint): Pga2dProjectivePoint =
    val len = bulkNorm
    val len2 = len * len
    val cos = Math.cos(len)

    // sin(x)/x = 1 - x^2/6 + x^4/120 - ...; at x <= 1e-5 the dropped x^4/120 <= 8.4e-23
    // relative term is far below 1e-17, so the second-order form is exact in double
    val sinDivLen = if (len > 1e-5) {
      Math.sin(len) / len
    } else {
      1.0 - len2 / 6.0
    }

    // k1 = sin(c)^2 / c^2 = (sin(c)/c)^2
    val k1 = sinDivLen * sinDivLen

    // k2 = (2c - sin(2c)) / (2c^3) = (1 - sinDivLen * cos) / c^2, since sin(2c)/(2c) = sinDivLen * cos;
    // as a series: sum_{k>=1} (-1)^(k+1) * 4^k * m^(k-1) / (2k+1)! = 2/3 - (2/15)*m + (4/315)*m^2 - ..., m = c^2.
    // The polynomial window is wide because the 1 - sinDivLen * cos cancellation costs
    // ~eps/c^2 of relative error, which the single compensating power of c in the term k2
    // multiplies would turn into ~eps/c of absolute error in the result. Up to c = 0.5 the
    // degree-8 polynomial in m is accurate to 1 ulp (the dropped 4^10*m^9/21! term is
    // ~1e-19 relative); at c > 0.5 the trigonometric form is accurate to ~2 ulp
    val k2 = if (len > 0.5) {
      (1.0 - sinDivLen * cos) / len2
    } else {
      2.0 / 3.0 - len2 * (2.0 / 15.0 - len2 * (4.0 / 315.0 - len2 * (2.0 / 2835.0 - len2 * (4.0 / 155925.0 - len2 * (4.0 / 6081075.0 - len2 * (8.0 / 638512875.0 - len2 * (2.0 / 10854718875.0 - len2 * (4.0 / 1856156927625.0))))))))
    }

    val ub = this.cross(b)
    val uub = this.cross(ub)

    Pga2dProjectivePoint(
      x = (b.x + k1 * ub.x + k2 * uub.x),
      y = (b.y + k1 * ub.y + k2 * uub.y),
      w = b.w,
    )

  /**
   * The inverse of the differential of exp: u.dexpInv(u.dexp(b)) == b. Maps the velocity of
   * u.exp (as a grade-2 element, left trivialization) back to the rate of change of u itself -
   * the workhorse of Lie-group ODE integrators, which integrate in the flat grade-2 space and
   * return to the group with one exp, keeping the motor normalized by construction.
   * The closed form (x is `cross`, the angle c = bulkNorm is real in 2d):
   *   dexpInv(u, b) = b - (u x b) + ((1 - c*cot(c))/c^2) * (u x (u x b))
   * The coefficient of (u x b) is exactly -1: the odd Bernoulli numbers beyond B1 vanish.
   * Singular at bulkNorm == pi, where exp stops being injective. Degenerate cases are exact
   * and NaN-free: Pga2dProjectivePoint.zero.dexpInv(b) == b, an ideal u (w == 0)
   * gives b - u.cross(b).
   */
  def dexpInv(b: Pga2dProjectivePoint): Pga2dProjectivePoint =
    val len = bulkNorm
    val len2 = len * len
    val cos = Math.cos(len)

    // sin(x)/x = 1 - x^2/6 + x^4/120 - ...; at x <= 1e-5 the dropped x^4/120 <= 8.4e-23
    // relative term is far below 1e-17, so the second-order form is exact in double
    val sinDivLen = if (len > 1e-5) {
      Math.sin(len) / len
    } else {
      1.0 - len2 / 6.0
    }

    // (sin(c)/c - cos(c)) / c^2 = sum (-1)^k * (2k+2) * m^k / (2k+3)! = 1/3 - m/30 + m^2/840 - ..., m = c^2.
    // The polynomial window is much wider than in exp: here the coefficient multiplies terms
    // with only one compensating power of c, so the ~eps/c^2 relative error of the
    // trigonometric form near small c (the sinDivLen - cos cancellation) would surface as
    // ~eps/c of absolute error in the result (in exp the terms carry c^2 and hide it).
    // Up to c = 0.5 the degree-7 polynomial in m is accurate to 1 ulp (the dropped
    // 18*m^8/19! term is ~7e-21 relative); at c > 0.5 the trigonometric form is accurate
    // to ~2 ulp (its cancellation costs eps/c^2 <= 4*eps of relative error there)
    val sinMinusCosDivLen2 = if (len > 0.5) {
      (sinDivLen - cos) / len2
    } else {
      1.0 / 3.0 - len2 * (1.0 / 30.0 - len2 * (1.0 / 840.0 - len2 * (1.0 / 45360.0 - len2 * (1.0 / 3991680.0 - len2 * (1.0 / 518918400.0 - len2 * (1.0 / 93405312000.0 - len2 / 22230464256000.0))))))
    }

    // k3 = (1 - c*cot(c)) / c^2 = ((sin(c)/c - cos(c)) / (sin(c)/c)) / c^2 = sinMinusCosDivLen2 / sinDivLen;
    // with the wide-window sinMinusCosDivLen2 the quotient is accurate to a few ulps for any c;
    // the series: k3 = 1/3 + m/45 + (2/945)*m^2 + ..., m = c^2; diverges at c = pi where exp
    // stops being injective
    val k3 = sinMinusCosDivLen2 / sinDivLen

    val ub = this.cross(b)
    val uub = this.cross(ub)

    Pga2dProjectivePoint(
      x = (b.x - ub.x + k3 * uub.x),
      y = (b.y - ub.y + k3 * uub.y),
      w = b.w,
    )

  def toMultivector: Pga2dMultivector =
    Pga2dMultivector(
      s = 0.0,
      w = 0.0,
      x = 0.0,
      y = 0.0,
      wx = y,
      wy = -x,
      xy = w,
      i = 0.0,
    )

  def toMotor: Pga2dMotor =
    Pga2dMotor(
      s = 0.0,
      wx = y,
      wy = -x,
      xy = w,
    )

  def toRotorUnsafe: Pga2dRotor =
    Pga2dRotor(
      s = 0.0,
      xy = w,
    )

  def toProjectiveTranslatorUnsafe: Pga2dProjectiveTranslator =
    Pga2dProjectiveTranslator(
      s = 0.0,
      wx = y,
      wy = -x,
    )

  def toTranslatorUnsafe: Pga2dTranslator =
    Pga2dTranslator(
      wx = y,
      wy = -x,
    )

  def toVectorUnsafe: Pga2dVector =
    Pga2dVector(
      x = x,
      y = y,
    )

  def toPointUnsafe: Pga2dPoint =
    Pga2dPoint(
      x = x,
      y = y,
    )

  /** divides by the weight; an ideal point (weight == 0) yields infinite or NaN coordinates */
  def toPoint: Pga2dPoint =
    val mult = (1.0 / w)
    Pga2dPoint(
      x = mult * x,
      y = mult * y,
    )

  /** fused -line.dot(point).geometric(line); w of the result is line.normSquare > 0, so w = 1 for a normalized line */
  def projectOntoLine(line: Pga2dLine): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = (line.y * (line.y * x - line.x * y) - line.w * line.x * w),
      y = (line.x * (line.x * y - line.y * x) - line.w * line.y * w),
      w = w * (line.x * line.x + line.y * line.y),
    )

  /** fused -line.dot(point).geometric(line); w of the result is line.normSquare > 0, so w = 1 for a normalized line */
  def projectOntoLine(line: Pga2dLineCentral): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = line.y * (line.y * x - line.x * y),
      y = line.x * (line.x * y - line.y * x),
      w = w * (line.x * line.x + line.y * line.y),
    )

  infix def geometric(r: Pga2dMotor): Pga2dMotor =
    Pga2dMotor(
      s = -r.xy * w,
      wx = (r.s * y + r.wy * w + r.xy * x),
      wy = (r.xy * y - r.s * x - r.wx * w),
      xy = r.s * w,
    )

  infix def geometric(r: Pga2dLine): Pga2dMultivector =
    Pga2dMultivector(
      s = 0.0,
      w = (r.x * y - r.y * x),
      x = r.y * w,
      y = -r.x * w,
      wx = 0.0,
      wy = 0.0,
      xy = 0.0,
      i = (r.w * w + r.x * x + r.y * y),
    )

  infix def geometric(r: Pga2dProjectivePoint): Pga2dProjectiveTranslator =
    Pga2dProjectiveTranslator(
      s = -r.w * w,
      wx = (r.w * x - r.x * w),
      wy = (r.w * y - r.y * w),
    )

  infix def geometric(r: Pga2dRotor): Pga2dMotor =
    Pga2dMotor(
      s = -r.xy * w,
      wx = (r.s * y + r.xy * x),
      wy = (r.xy * y - r.s * x),
      xy = r.s * w,
    )

  infix def geometric(r: Pga2dProjectiveTranslator): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = (r.s * x + r.wx * w),
      y = (r.s * y + r.wy * w),
      w = r.s * w,
    )

  infix def geometric(r: Pga2dTranslator): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = (x + r.wx * w),
      y = (y + r.wy * w),
      w = w,
    )

  infix def geometric(r: Pga2dVector): Pga2dVector =
    Pga2dVector(
      x = r.y * w,
      y = -r.x * w,
    )

  infix def geometric(r: Pga2dPoint): Pga2dProjectiveTranslator =
    Pga2dProjectiveTranslator(
      s = -w,
      wx = (x - r.x * w),
      wy = (y - r.y * w),
    )

  infix def geometric(r: Pga2dLineCentral): Pga2dMultivector =
    Pga2dMultivector(
      s = 0.0,
      w = (r.x * y - r.y * x),
      x = r.y * w,
      y = -r.x * w,
      wx = 0.0,
      wy = 0.0,
      xy = 0.0,
      i = (r.x * x + r.y * y),
    )

  infix def geometric(r: Pga2dPseudoScalar): Pga2dLine =
    Pga2dLine(
      x = 0.0,
      y = 0.0,
      w = -r.i * w,
    )

  infix def geometric(r: Pga2dPointCenter.type): Pga2dProjectiveTranslator =
    Pga2dProjectiveTranslator(
      s = -w,
      wx = x,
      wy = y,
    )

  infix def dot(r: Pga2dMotor): Pga2dMotor =
    Pga2dMotor(
      s = -r.xy * w,
      wx = r.s * y,
      wy = -r.s * x,
      xy = r.s * w,
    )

  infix def dot(r: Pga2dLine): Pga2dLine =
    Pga2dLine(
      x = r.y * w,
      y = -r.x * w,
      w = (r.x * y - r.y * x),
    )

  infix def dot(r: Pga2dProjectivePoint): Double =
    -r.w * w

  infix def dot(r: Pga2dRotor): Pga2dMotor =
    Pga2dMotor(
      s = -r.xy * w,
      wx = r.s * y,
      wy = -r.s * x,
      xy = r.s * w,
    )

  infix def dot(r: Pga2dProjectiveTranslator): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = r.s * x,
      y = r.s * y,
      w = r.s * w,
    )

  infix def dot(r: Pga2dTranslator): Pga2dProjectivePoint =
    this

  infix def dot(r: Pga2dPoint): Double =
    -w

  infix def dot(r: Pga2dLineCentral): Pga2dLine =
    Pga2dLine(
      x = r.y * w,
      y = -r.x * w,
      w = (r.x * y - r.y * x),
    )

  infix def dot(r: Pga2dPseudoScalar): Pga2dLine =
    Pga2dLine(
      x = 0.0,
      y = 0.0,
      w = -r.i * w,
    )

  infix def dot(r: Pga2dPointCenter.type): Double =
    -w

  infix def wedge(r: Pga2dMotor): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = r.s * x,
      y = r.s * y,
      w = r.s * w,
    )

  inline infix def ^(r: Pga2dMotor): Pga2dProjectivePoint = wedge(r)

  inline infix def meet(r: Pga2dMotor): Pga2dProjectivePoint = wedge(r)

  infix def wedge(r: Pga2dLine): Pga2dPseudoScalar =
    Pga2dPseudoScalar(
      i = (r.w * w + r.x * x + r.y * y),
    )

  inline infix def ^(r: Pga2dLine): Pga2dPseudoScalar = wedge(r)

  inline infix def meet(r: Pga2dLine): Pga2dPseudoScalar = wedge(r)

  infix def wedge(r: Pga2dRotor): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = r.s * x,
      y = r.s * y,
      w = r.s * w,
    )

  inline infix def ^(r: Pga2dRotor): Pga2dProjectivePoint = wedge(r)

  inline infix def meet(r: Pga2dRotor): Pga2dProjectivePoint = wedge(r)

  infix def wedge(r: Pga2dProjectiveTranslator): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = r.s * x,
      y = r.s * y,
      w = r.s * w,
    )

  inline infix def ^(r: Pga2dProjectiveTranslator): Pga2dProjectivePoint = wedge(r)

  inline infix def meet(r: Pga2dProjectiveTranslator): Pga2dProjectivePoint = wedge(r)

  infix def wedge(r: Pga2dTranslator): Pga2dProjectivePoint =
    this

  inline infix def ^(r: Pga2dTranslator): Pga2dProjectivePoint = wedge(r)

  inline infix def meet(r: Pga2dTranslator): Pga2dProjectivePoint = wedge(r)

  infix def wedge(r: Pga2dLineCentral): Pga2dPseudoScalar =
    Pga2dPseudoScalar(
      i = (r.x * x + r.y * y),
    )

  inline infix def ^(r: Pga2dLineCentral): Pga2dPseudoScalar = wedge(r)

  inline infix def meet(r: Pga2dLineCentral): Pga2dPseudoScalar = wedge(r)

  infix def antiGeometric(r: Pga2dMotor): Pga2dMultivector =
    Pga2dMultivector(
      s = 0.0,
      w = (r.wx * x + r.wy * y),
      x = (r.s * x + r.xy * y - r.wx * w),
      y = (r.s * y - r.wy * w - r.xy * x),
      wx = 0.0,
      wy = 0.0,
      xy = 0.0,
      i = (r.wx * y - r.wy * x),
    )

  infix def antiGeometric(r: Pga2dLine): Pga2dMotor =
    Pga2dMotor(
      s = (r.w * w + r.x * x + r.y * y),
      wx = r.w * x,
      wy = r.w * y,
      xy = (r.x * y - r.y * x),
    )

  infix def antiGeometric(r: Pga2dProjectivePoint): Pga2dMultivector =
    Pga2dMultivector(
      s = 0.0,
      w = (r.y * x - r.x * y),
      x = (r.w * y - r.y * w),
      y = (r.x * w - r.w * x),
      wx = 0.0,
      wy = 0.0,
      xy = 0.0,
      i = (r.x * x + r.y * y),
    )

  infix def antiGeometric(r: Pga2dRotor): Pga2dLineCentral =
    Pga2dLineCentral(
      x = (r.s * x + r.xy * y),
      y = (r.s * y - r.xy * x),
    )

  infix def antiGeometric(r: Pga2dProjectiveTranslator): Pga2dMultivector =
    Pga2dMultivector(
      s = 0.0,
      w = (r.wx * x + r.wy * y),
      x = (r.s * x - r.wx * w),
      y = (r.s * y - r.wy * w),
      wx = 0.0,
      wy = 0.0,
      xy = 0.0,
      i = (r.wx * y - r.wy * x),
    )

  infix def antiGeometric(r: Pga2dTranslator): Pga2dMultivector =
    Pga2dMultivector(
      s = 0.0,
      w = (r.wx * x + r.wy * y),
      x = (x - r.wx * w),
      y = (y - r.wy * w),
      wx = 0.0,
      wy = 0.0,
      xy = 0.0,
      i = (r.wx * y - r.wy * x),
    )

  infix def antiGeometric(r: Pga2dVector): Pga2dMultivector =
    Pga2dMultivector(
      s = 0.0,
      w = (r.y * x - r.x * y),
      x = -r.y * w,
      y = r.x * w,
      wx = 0.0,
      wy = 0.0,
      xy = 0.0,
      i = (r.x * x + r.y * y),
    )

  infix def antiGeometric(r: Pga2dPoint): Pga2dMultivector =
    Pga2dMultivector(
      s = 0.0,
      w = (r.y * x - r.x * y),
      x = (y - r.y * w),
      y = (-x + r.x * w),
      wx = 0.0,
      wy = 0.0,
      xy = 0.0,
      i = (r.x * x + r.y * y),
    )

  infix def antiGeometric(r: Pga2dLineCentral): Pga2dRotor =
    Pga2dRotor(
      s = (r.x * x + r.y * y),
      xy = (r.x * y - r.y * x),
    )

  infix def antiGeometric(r: Pga2dPseudoScalar): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = r.i * x,
      y = r.i * y,
      w = r.i * w,
    )

  infix def antiGeometric(r: Pga2dPointCenter.type): Pga2dLineCentral =
    Pga2dLineCentral(
      x = y,
      y = -x,
    )

  infix def antiDot(r: Pga2dMotor): Pga2dMultivector =
    Pga2dMultivector(
      s = 0.0,
      w = 0.0,
      x = r.s * x,
      y = r.s * y,
      wx = 0.0,
      wy = 0.0,
      xy = 0.0,
      i = (r.wx * y - r.wy * x),
    )

  infix def antiDot(r: Pga2dLine): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = -r.w * y,
      y = r.w * x,
      w = (r.x * y - r.y * x),
    )

  infix def antiDot(r: Pga2dProjectivePoint): Pga2dPseudoScalar =
    Pga2dPseudoScalar(
      i = (r.x * x + r.y * y),
    )

  infix def antiDot(r: Pga2dRotor): Pga2dLineCentral =
    Pga2dLineCentral(
      x = r.s * x,
      y = r.s * y,
    )

  infix def antiDot(r: Pga2dProjectiveTranslator): Pga2dMultivector =
    Pga2dMultivector(
      s = 0.0,
      w = 0.0,
      x = r.s * x,
      y = r.s * y,
      wx = 0.0,
      wy = 0.0,
      xy = 0.0,
      i = (r.wx * y - r.wy * x),
    )

  infix def antiDot(r: Pga2dTranslator): Pga2dMultivector =
    Pga2dMultivector(
      s = 0.0,
      w = 0.0,
      x = x,
      y = y,
      wx = 0.0,
      wy = 0.0,
      xy = 0.0,
      i = (r.wx * y - r.wy * x),
    )

  infix def antiDot(r: Pga2dVector): Pga2dPseudoScalar =
    Pga2dPseudoScalar(
      i = (r.x * x + r.y * y),
    )

  infix def antiDot(r: Pga2dPoint): Pga2dPseudoScalar =
    Pga2dPseudoScalar(
      i = (r.x * x + r.y * y),
    )

  infix def antiDot(r: Pga2dLineCentral): Pga2dRotor =
    Pga2dRotor(
      s = 0.0,
      xy = (r.x * y - r.y * x),
    )

  infix def antiDot(r: Pga2dPseudoScalar): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = r.i * x,
      y = r.i * y,
      w = r.i * w,
    )

  infix def antiDotI(r: Pga2dProjectivePoint): Double =
    (r.x * x + r.y * y)

  infix def antiDotI(r: Pga2dVector): Double =
    (r.x * x + r.y * y)

  infix def antiDotI(r: Pga2dPoint): Double =
    (r.x * x + r.y * y)

  infix def antiWedge(r: Pga2dMotor): Pga2dLine =
    Pga2dLine(
      x = (r.xy * y - r.wx * w),
      y = (-r.wy * w - r.xy * x),
      w = (r.wx * x + r.wy * y),
    )

  inline infix def v(r: Pga2dMotor): Pga2dLine = antiWedge(r)

  inline infix def join(r: Pga2dMotor): Pga2dLine = antiWedge(r)

  infix def antiWedge(r: Pga2dLine): Double =
    (r.w * w + r.x * x + r.y * y)

  inline infix def v(r: Pga2dLine): Double = antiWedge(r)

  inline infix def join(r: Pga2dLine): Double = antiWedge(r)

  infix def antiWedge(r: Pga2dProjectivePoint): Pga2dLine =
    Pga2dLine(
      x = (r.w * y - r.y * w),
      y = (r.x * w - r.w * x),
      w = (r.y * x - r.x * y),
    )

  inline infix def v(r: Pga2dProjectivePoint): Pga2dLine = antiWedge(r)

  inline infix def join(r: Pga2dProjectivePoint): Pga2dLine = antiWedge(r)

  infix def antiWedge(r: Pga2dRotor): Pga2dLineCentral =
    Pga2dLineCentral(
      x = r.xy * y,
      y = -r.xy * x,
    )

  inline infix def v(r: Pga2dRotor): Pga2dLineCentral = antiWedge(r)

  inline infix def join(r: Pga2dRotor): Pga2dLineCentral = antiWedge(r)

  infix def antiWedge(r: Pga2dProjectiveTranslator): Pga2dLine =
    Pga2dLine(
      x = -r.wx * w,
      y = -r.wy * w,
      w = (r.wx * x + r.wy * y),
    )

  inline infix def v(r: Pga2dProjectiveTranslator): Pga2dLine = antiWedge(r)

  inline infix def join(r: Pga2dProjectiveTranslator): Pga2dLine = antiWedge(r)

  infix def antiWedge(r: Pga2dTranslator): Pga2dLine =
    Pga2dLine(
      x = -r.wx * w,
      y = -r.wy * w,
      w = (r.wx * x + r.wy * y),
    )

  inline infix def v(r: Pga2dTranslator): Pga2dLine = antiWedge(r)

  inline infix def join(r: Pga2dTranslator): Pga2dLine = antiWedge(r)

  infix def antiWedge(r: Pga2dVector): Pga2dLine =
    Pga2dLine(
      x = -r.y * w,
      y = r.x * w,
      w = (r.y * x - r.x * y),
    )

  inline infix def v(r: Pga2dVector): Pga2dLine = antiWedge(r)

  inline infix def join(r: Pga2dVector): Pga2dLine = antiWedge(r)

  infix def antiWedge(r: Pga2dPoint): Pga2dLine =
    Pga2dLine(
      x = (y - r.y * w),
      y = (-x + r.x * w),
      w = (r.y * x - r.x * y),
    )

  inline infix def v(r: Pga2dPoint): Pga2dLine = antiWedge(r)

  inline infix def join(r: Pga2dPoint): Pga2dLine = antiWedge(r)

  infix def antiWedge(r: Pga2dLineCentral): Double =
    (r.x * x + r.y * y)

  inline infix def v(r: Pga2dLineCentral): Double = antiWedge(r)

  inline infix def join(r: Pga2dLineCentral): Double = antiWedge(r)

  infix def antiWedge(r: Pga2dPseudoScalar): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = r.i * x,
      y = r.i * y,
      w = r.i * w,
    )

  inline infix def v(r: Pga2dPseudoScalar): Pga2dProjectivePoint = antiWedge(r)

  inline infix def join(r: Pga2dPseudoScalar): Pga2dProjectivePoint = antiWedge(r)

  infix def antiWedge(r: Pga2dPointCenter.type): Pga2dLineCentral =
    Pga2dLineCentral(
      x = y,
      y = -x,
    )

  inline infix def v(r: Pga2dPointCenter.type): Pga2dLineCentral = antiWedge(r)

  inline infix def join(r: Pga2dPointCenter.type): Pga2dLineCentral = antiWedge(r)

  infix def sandwich(r: Pga2dMotor): Pga2dMotor =
    val wMw = w * w
    Pga2dMotor(
      s = r.s * wMw,
      wx = (-r.wx * wMw + 2.0 * r.xy * w * y),
      wy = (-r.wy * wMw - 2.0 * r.xy * w * x),
      xy = r.xy * wMw,
    )

  infix def sandwich(r: Pga2dLine): Pga2dLine =
    val wMw = w * w
    Pga2dLine(
      x = -r.x * wMw,
      y = -r.y * wMw,
      w = (r.w * wMw + 2.0 * w * (r.x * x + r.y * y)),
    )

  infix def sandwich(r: Pga2dProjectivePoint): Pga2dProjectivePoint =
    val wMw = w * w
    Pga2dProjectivePoint(
      x = (-r.x * wMw + 2.0 * r.w * w * x),
      y = (-r.y * wMw + 2.0 * r.w * w * y),
      w = r.w * wMw,
    )

  infix def sandwich(r: Pga2dRotor): Pga2dMotor =
    val wMw = w * w
    Pga2dMotor(
      s = r.s * wMw,
      wx = 2.0 * r.xy * w * y,
      wy = -2.0 * r.xy * w * x,
      xy = r.xy * wMw,
    )

  infix def sandwich(r: Pga2dProjectiveTranslator): Pga2dProjectiveTranslator =
    val wMw = w * w
    Pga2dProjectiveTranslator(
      s = r.s * wMw,
      wx = -r.wx * wMw,
      wy = -r.wy * wMw,
    )

  infix def sandwich(r: Pga2dTranslator): Pga2dProjectiveTranslator =
    val wMw = w * w
    Pga2dProjectiveTranslator(
      s = wMw,
      wx = -r.wx * wMw,
      wy = -r.wy * wMw,
    )

  infix def sandwich(r: Pga2dVector): Pga2dVector =
    val wMw = w * w
    Pga2dVector(
      x = -r.x * wMw,
      y = -r.y * wMw,
    )

  infix def sandwich(r: Pga2dPoint): Pga2dProjectivePoint =
    val wMw = w * w
    Pga2dProjectivePoint(
      x = (-r.x * wMw + 2.0 * w * x),
      y = (-r.y * wMw + 2.0 * w * y),
      w = wMw,
    )

  infix def sandwich(r: Pga2dLineCentral): Pga2dLine =
    val wMw = w * w
    Pga2dLine(
      x = -r.x * wMw,
      y = -r.y * wMw,
      w = 2.0 * w * (r.x * x + r.y * y),
    )

  infix def sandwich(r: Pga2dPseudoScalar): Pga2dPseudoScalar =
    Pga2dPseudoScalar(
      i = r.i * w * w,
    )

  infix def sandwich(r: Pga2dPointCenter.type): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = 2.0 * w * x,
      y = 2.0 * w * y,
      w = w * w,
    )

  infix def reverseSandwich(r: Pga2dMotor): Pga2dMotor =
    val wMw = w * w
    Pga2dMotor(
      s = r.s * wMw,
      wx = (-r.wx * wMw + 2.0 * r.xy * w * y),
      wy = (-r.wy * wMw - 2.0 * r.xy * w * x),
      xy = r.xy * wMw,
    )

  infix def reverseSandwich(r: Pga2dLine): Pga2dLine =
    val wMw = w * w
    Pga2dLine(
      x = -r.x * wMw,
      y = -r.y * wMw,
      w = (r.w * wMw + 2.0 * w * (r.x * x + r.y * y)),
    )

  infix def reverseSandwich(r: Pga2dProjectivePoint): Pga2dProjectivePoint =
    val wMw = w * w
    Pga2dProjectivePoint(
      x = (-r.x * wMw + 2.0 * r.w * w * x),
      y = (-r.y * wMw + 2.0 * r.w * w * y),
      w = r.w * wMw,
    )

  infix def reverseSandwich(r: Pga2dRotor): Pga2dMotor =
    val wMw = w * w
    Pga2dMotor(
      s = r.s * wMw,
      wx = 2.0 * r.xy * w * y,
      wy = -2.0 * r.xy * w * x,
      xy = r.xy * wMw,
    )

  infix def reverseSandwich(r: Pga2dProjectiveTranslator): Pga2dProjectiveTranslator =
    val wMw = w * w
    Pga2dProjectiveTranslator(
      s = r.s * wMw,
      wx = -r.wx * wMw,
      wy = -r.wy * wMw,
    )

  infix def reverseSandwich(r: Pga2dTranslator): Pga2dProjectiveTranslator =
    val wMw = w * w
    Pga2dProjectiveTranslator(
      s = wMw,
      wx = -r.wx * wMw,
      wy = -r.wy * wMw,
    )

  infix def reverseSandwich(r: Pga2dVector): Pga2dVector =
    val wMw = w * w
    Pga2dVector(
      x = -r.x * wMw,
      y = -r.y * wMw,
    )

  infix def reverseSandwich(r: Pga2dPoint): Pga2dProjectivePoint =
    val wMw = w * w
    Pga2dProjectivePoint(
      x = (-r.x * wMw + 2.0 * w * x),
      y = (-r.y * wMw + 2.0 * w * y),
      w = wMw,
    )

  infix def reverseSandwich(r: Pga2dLineCentral): Pga2dLine =
    val wMw = w * w
    Pga2dLine(
      x = -r.x * wMw,
      y = -r.y * wMw,
      w = 2.0 * w * (r.x * x + r.y * y),
    )

  infix def reverseSandwich(r: Pga2dPseudoScalar): Pga2dPseudoScalar =
    Pga2dPseudoScalar(
      i = r.i * w * w,
    )

  infix def reverseSandwich(r: Pga2dPointCenter.type): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = 2.0 * w * x,
      y = 2.0 * w * y,
      w = w * w,
    )

  infix def cross(r: Pga2dMotor): Pga2dVector =
    Pga2dVector(
      x = (r.wx * w - r.xy * y),
      y = (r.wy * w + r.xy * x),
    )

  infix def cross(r: Pga2dLine): Pga2dLine =
    Pga2dLine(
      x = r.y * w,
      y = -r.x * w,
      w = (r.x * y - r.y * x),
    )

  infix def cross(r: Pga2dProjectivePoint): Pga2dVector =
    Pga2dVector(
      x = (r.y * w - r.w * y),
      y = (r.w * x - r.x * w),
    )

  infix def cross(r: Pga2dRotor): Pga2dVector =
    Pga2dVector(
      x = -r.xy * y,
      y = r.xy * x,
    )

  infix def cross(r: Pga2dProjectiveTranslator): Pga2dVector =
    Pga2dVector(
      x = r.wx * w,
      y = r.wy * w,
    )

  infix def cross(r: Pga2dTranslator): Pga2dVector =
    Pga2dVector(
      x = r.wx * w,
      y = r.wy * w,
    )

  infix def cross(r: Pga2dVector): Pga2dVector =
    Pga2dVector(
      x = r.y * w,
      y = -r.x * w,
    )

  infix def cross(r: Pga2dPoint): Pga2dVector =
    Pga2dVector(
      x = (-y + r.y * w),
      y = (x - r.x * w),
    )

  infix def cross(r: Pga2dLineCentral): Pga2dLine =
    Pga2dLine(
      x = r.y * w,
      y = -r.x * w,
      w = (r.x * y - r.y * x),
    )

  infix def cross(r: Pga2dPointCenter.type): Pga2dVector =
    Pga2dVector(
      x = -y,
      y = x,
    )


object Pga2dProjectivePoint:

  inline val componentsCount = 3

  val zero: Pga2dProjectivePoint = Pga2dProjectivePoint(0.0, 0.0, 0.0)

  def blade2(wx: Double, wy: Double, xy: Double): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = -wy,
      y = wx,
      w = xy,
    )

  def interpolate(a: Pga2dProjectivePoint, b: Pga2dProjectivePoint, t: Double): Pga2dProjectivePoint =
    a * (1.0 - t) + b * t