package me.kright.gametools.pga2d

import scala.annotation.targetName
import me.kright.gametools.flatarray.FlatDoubleSerializer
import me.kright.gametools.mathutil.CanEqualWithEps


/**
 * A point on the 2d plane, stored in dual representation with human-friendly fields x, y and constant w = 1.
 *
 * Variable fields: x, y.
 * Constant fields: w = 1.0.
 * Basis blade coefficients: wy = -x, wx = y, xy = 1.0.
 *
 * Generated by pgaNdCodeGen (me.kright.gametools.pga.codegen.scalagen.pga2d.runScalaCodeGen).
 * Do not edit by hand: change the generator and re-run it.
 */
final case class Pga2dPoint(x: Double = 0.0,
                            y: Double = 0.0) derives CanEqual, CanEqualWithEps, FlatDoubleSerializer:
  inline val w = 1.0

  inline def wy: Double = -x

  inline def wx: Double = y

  inline def xy: Double = 1.0

  override def toString: String =
    s"Pga2dPoint(x = $x, y = $y)"

  def dual: Pga2dLine =
    Pga2dLine(
      x = x,
      y = y,
      w = 1.0,
    )

  def weight: Pga2dVector =
    Pga2dVector(
      x = x,
      y = y,
    )

  def bulk: Pga2dPointCenter.type =
    Pga2dPointCenter

  @targetName("unaryMinus")
  def unary_- : Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = -x,
      y = -y,
      w = -1.0,
    )

  def reverse: Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = -x,
      y = -y,
      w = -1.0,
    )

  def antiReverse: Pga2dPoint =
    this

  def bulkNormSquare: Double = 1.0

  def bulkNorm: Double = 1.0

  def normalizedByBulk: Pga2dPoint = this

  def weightNormSquare: Double =
    (x * x + y * y)

  def weightNorm: Double =
    Math.sqrt(weightNormSquare)

  def normalizedByWeight =
    this / weightNorm

  def normSquare: Double =
    (1.0 + x * x + y * y)

  def norm: Double =
    Math.sqrt(normSquare)

  def normalizedByNorm =
    this / norm

  @targetName("times")
  def *(r: Double): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = r * x,
      y = r * y,
      w = r,
    )

  /** multiplies by the reciprocal: one division instead of one per component, at the cost of one extra rounding (~0.5 ulp) */
  @targetName("div")
  def /(r: Double): Pga2dProjectivePoint =
    this * (1.0 / r)

  infix def min(other: Pga2dPoint): Pga2dPoint =
    Pga2dPoint(math.min(x, other.x), math.min(y, other.y))

  infix def max(other: Pga2dPoint): Pga2dPoint =
    Pga2dPoint(math.max(x, other.x), math.max(y, other.y))

  def distanceTo(point: Pga2dPoint): Double =
    (this - point).norm

  @targetName("plus")
  def +(r: Pga2dProjectivePoint): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = (r.x + x),
      y = (r.y + y),
      w = (1.0 + r.w),
    )

  @targetName("minus")
  def -(r: Pga2dProjectivePoint): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = (x - r.x),
      y = (y - r.y),
      w = (1.0 - r.w),
    )

  def madd(r: Pga2dProjectivePoint, mult: Double): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = (x + mult * r.x),
      y = (y + mult * r.y),
      w = (1.0 + mult * r.w),
    )

  @targetName("plus")
  def +(r: Pga2dPoint): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = (r.x + x),
      y = (r.y + y),
      w = 2.0,
    )

  @targetName("minus")
  def -(r: Pga2dPoint): Pga2dVector =
    Pga2dVector(
      x = (x - r.x),
      y = (y - r.y),
    )

  def madd(r: Pga2dPoint, mult: Double): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = (x + mult * r.x),
      y = (y + mult * r.y),
      w = (1.0 + mult),
    )

  @targetName("plus")
  def +(r: Pga2dVector): Pga2dPoint =
    Pga2dPoint(
      x = (r.x + x),
      y = (r.y + y),
    )

  @targetName("minus")
  def -(r: Pga2dVector): Pga2dPoint =
    Pga2dPoint(
      x = (x - r.x),
      y = (y - r.y),
    )

  def madd(r: Pga2dVector, mult: Double): Pga2dPoint =
    Pga2dPoint(
      x = (x + mult * r.x),
      y = (y + mult * r.y),
    )

  /** componentwise product on the raw fields; NOT a geometric-algebra operation (basis-dependent) */
  def scale(r: Pga2dPoint): Pga2dPoint =
    Pga2dPoint(
      x = x * r.x,
      y = y * r.y,
    )

  /** componentwise 1/x on the raw fields (a zero field yields Infinity); NOT the multiplicative inverse */
  def reciprocal: Pga2dPoint =
    Pga2dPoint(
      x = 1.0 / x,
      y = 1.0 / y,
    )

  def toMultivector: Pga2dMultivector =
    Pga2dMultivector(
      s = 0.0,
      w = 0.0,
      x = 0.0,
      y = 0.0,
      wx = y,
      wy = -x,
      xy = 1.0,
      i = 0.0,
    )

  def toMotor: Pga2dMotor =
    Pga2dMotor(
      s = 0.0,
      wx = y,
      wy = -x,
      xy = 1.0,
    )

  def toRotorUnsafe: Pga2dRotor =
    Pga2dRotor(
      s = 0.0,
      xy = 1.0,
    )

  def toProjectivePoint: Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = x,
      y = y,
      w = 1.0,
    )

  def toProjectiveTranslatorUnsafe: Pga2dProjectiveTranslator =
    Pga2dProjectiveTranslator(
      s = 0.0,
      wx = y,
      wy = -x,
    )

  def toTranslatorUnsafe: Pga2dTranslator =
    Pga2dTranslator(
      wx = y,
      wy = -x,
    )

  def toVectorUnsafe: Pga2dVector =
    Pga2dVector(
      x = x,
      y = y,
    )

  /** fused -line.dot(point).geometric(line); w of the result is line.normSquare > 0, so w = 1 for a normalized line */
  def projectOntoLine(line: Pga2dLine): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = (line.x * (-line.w - line.y * y) + line.y * line.y * x),
      y = (line.y * (-line.w - line.x * x) + line.x * line.x * y),
      w = (line.x * line.x + line.y * line.y),
    )

  /** fused -line.dot(point).geometric(line); w of the result is line.normSquare > 0, so w = 1 for a normalized line */
  def projectOntoLine(line: Pga2dLineCentral): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = line.y * (line.y * x - line.x * y),
      y = line.x * (line.x * y - line.y * x),
      w = (line.x * line.x + line.y * line.y),
    )

  infix def geometric(r: Pga2dMotor): Pga2dMotor =
    Pga2dMotor(
      s = -r.xy,
      wx = (r.wy + r.s * y + r.xy * x),
      wy = (-r.wx + r.xy * y - r.s * x),
      xy = r.s,
    )

  infix def geometric(r: Pga2dLine): Pga2dMultivector =
    Pga2dMultivector(
      s = 0.0,
      w = (r.x * y - r.y * x),
      x = r.y,
      y = -r.x,
      wx = 0.0,
      wy = 0.0,
      xy = 0.0,
      i = (r.w + r.x * x + r.y * y),
    )

  infix def geometric(r: Pga2dRotor): Pga2dMotor =
    Pga2dMotor(
      s = -r.xy,
      wx = (r.s * y + r.xy * x),
      wy = (r.xy * y - r.s * x),
      xy = r.s,
    )

  infix def geometric(r: Pga2dProjectivePoint): Pga2dProjectiveTranslator =
    Pga2dProjectiveTranslator(
      s = -r.w,
      wx = (-r.x + r.w * x),
      wy = (-r.y + r.w * y),
    )

  infix def geometric(r: Pga2dProjectiveTranslator): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = (r.wx + r.s * x),
      y = (r.wy + r.s * y),
      w = r.s,
    )

  infix def geometric(r: Pga2dTranslator): Pga2dPoint =
    Pga2dPoint(
      x = (r.wx + x),
      y = (r.wy + y),
    )

  infix def geometric(r: Pga2dVector): Pga2dVector =
    Pga2dVector(
      x = r.y,
      y = -r.x,
    )

  infix def geometric(r: Pga2dPoint): Pga2dProjectiveTranslator =
    Pga2dProjectiveTranslator(
      s = -1.0,
      wx = (x - r.x),
      wy = (y - r.y),
    )

  infix def geometric(r: Pga2dLineCentral): Pga2dMultivector =
    Pga2dMultivector(
      s = 0.0,
      w = (r.x * y - r.y * x),
      x = r.y,
      y = -r.x,
      wx = 0.0,
      wy = 0.0,
      xy = 0.0,
      i = (r.x * x + r.y * y),
    )

  infix def geometric(r: Pga2dPseudoScalar): Pga2dLine =
    Pga2dLine(
      x = 0.0,
      y = 0.0,
      w = -r.i,
    )

  infix def geometric(r: Pga2dPointCenter.type): Pga2dProjectiveTranslator =
    Pga2dProjectiveTranslator(
      s = -1.0,
      wx = x,
      wy = y,
    )

  infix def dot(r: Pga2dMotor): Pga2dMotor =
    Pga2dMotor(
      s = -r.xy,
      wx = r.s * y,
      wy = -r.s * x,
      xy = r.s,
    )

  infix def dot(r: Pga2dLine): Pga2dLine =
    Pga2dLine(
      x = r.y,
      y = -r.x,
      w = (r.x * y - r.y * x),
    )

  infix def dot(r: Pga2dRotor): Pga2dMotor =
    Pga2dMotor(
      s = -r.xy,
      wx = r.s * y,
      wy = -r.s * x,
      xy = r.s,
    )

  infix def dot(r: Pga2dProjectivePoint): Double =
    -r.w

  infix def dot(r: Pga2dProjectiveTranslator): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = r.s * x,
      y = r.s * y,
      w = r.s,
    )

  infix def dot(r: Pga2dTranslator): Pga2dPoint =
    this

  infix def dot(r: Pga2dPoint): Double =
    -1.0

  infix def dot(r: Pga2dLineCentral): Pga2dLine =
    Pga2dLine(
      x = r.y,
      y = -r.x,
      w = (r.x * y - r.y * x),
    )

  infix def dot(r: Pga2dPseudoScalar): Pga2dLine =
    Pga2dLine(
      x = 0.0,
      y = 0.0,
      w = -r.i,
    )

  infix def dot(r: Pga2dPointCenter.type): Double =
    -1.0

  infix def wedge(r: Pga2dMotor): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = r.s * x,
      y = r.s * y,
      w = r.s,
    )

  inline infix def ^(r: Pga2dMotor): Pga2dProjectivePoint = wedge(r)

  inline infix def meet(r: Pga2dMotor): Pga2dProjectivePoint = wedge(r)

  infix def wedge(r: Pga2dLine): Pga2dPseudoScalar =
    Pga2dPseudoScalar(
      i = (r.w + r.x * x + r.y * y),
    )

  inline infix def ^(r: Pga2dLine): Pga2dPseudoScalar = wedge(r)

  inline infix def meet(r: Pga2dLine): Pga2dPseudoScalar = wedge(r)

  infix def wedge(r: Pga2dRotor): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = r.s * x,
      y = r.s * y,
      w = r.s,
    )

  inline infix def ^(r: Pga2dRotor): Pga2dProjectivePoint = wedge(r)

  inline infix def meet(r: Pga2dRotor): Pga2dProjectivePoint = wedge(r)

  infix def wedge(r: Pga2dProjectiveTranslator): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = r.s * x,
      y = r.s * y,
      w = r.s,
    )

  inline infix def ^(r: Pga2dProjectiveTranslator): Pga2dProjectivePoint = wedge(r)

  inline infix def meet(r: Pga2dProjectiveTranslator): Pga2dProjectivePoint = wedge(r)

  infix def wedge(r: Pga2dTranslator): Pga2dPoint =
    this

  inline infix def ^(r: Pga2dTranslator): Pga2dPoint = wedge(r)

  inline infix def meet(r: Pga2dTranslator): Pga2dPoint = wedge(r)

  infix def wedge(r: Pga2dLineCentral): Pga2dPseudoScalar =
    Pga2dPseudoScalar(
      i = (r.x * x + r.y * y),
    )

  inline infix def ^(r: Pga2dLineCentral): Pga2dPseudoScalar = wedge(r)

  inline infix def meet(r: Pga2dLineCentral): Pga2dPseudoScalar = wedge(r)

  infix def antiGeometric(r: Pga2dMotor): Pga2dMultivector =
    Pga2dMultivector(
      s = 0.0,
      w = (r.wx * x + r.wy * y),
      x = (-r.wx + r.s * x + r.xy * y),
      y = (-r.wy + r.s * y - r.xy * x),
      wx = 0.0,
      wy = 0.0,
      xy = 0.0,
      i = (r.wx * y - r.wy * x),
    )

  infix def antiGeometric(r: Pga2dLine): Pga2dMotor =
    Pga2dMotor(
      s = (r.w + r.x * x + r.y * y),
      wx = r.w * x,
      wy = r.w * y,
      xy = (r.x * y - r.y * x),
    )

  infix def antiGeometric(r: Pga2dRotor): Pga2dLineCentral =
    Pga2dLineCentral(
      x = (r.s * x + r.xy * y),
      y = (r.s * y - r.xy * x),
    )

  infix def antiGeometric(r: Pga2dProjectivePoint): Pga2dMultivector =
    Pga2dMultivector(
      s = 0.0,
      w = (r.y * x - r.x * y),
      x = (-r.y + r.w * y),
      y = (r.x - r.w * x),
      wx = 0.0,
      wy = 0.0,
      xy = 0.0,
      i = (r.x * x + r.y * y),
    )

  infix def antiGeometric(r: Pga2dProjectiveTranslator): Pga2dMultivector =
    Pga2dMultivector(
      s = 0.0,
      w = (r.wx * x + r.wy * y),
      x = (-r.wx + r.s * x),
      y = (-r.wy + r.s * y),
      wx = 0.0,
      wy = 0.0,
      xy = 0.0,
      i = (r.wx * y - r.wy * x),
    )

  infix def antiGeometric(r: Pga2dTranslator): Pga2dMultivector =
    Pga2dMultivector(
      s = 0.0,
      w = (r.wx * x + r.wy * y),
      x = (x - r.wx),
      y = (y - r.wy),
      wx = 0.0,
      wy = 0.0,
      xy = 0.0,
      i = (r.wx * y - r.wy * x),
    )

  infix def antiGeometric(r: Pga2dVector): Pga2dMultivector =
    Pga2dMultivector(
      s = 0.0,
      w = (r.y * x - r.x * y),
      x = -r.y,
      y = r.x,
      wx = 0.0,
      wy = 0.0,
      xy = 0.0,
      i = (r.x * x + r.y * y),
    )

  infix def antiGeometric(r: Pga2dPoint): Pga2dMultivector =
    Pga2dMultivector(
      s = 0.0,
      w = (r.y * x - r.x * y),
      x = (y - r.y),
      y = (r.x - x),
      wx = 0.0,
      wy = 0.0,
      xy = 0.0,
      i = (r.x * x + r.y * y),
    )

  infix def antiGeometric(r: Pga2dLineCentral): Pga2dRotor =
    Pga2dRotor(
      s = (r.x * x + r.y * y),
      xy = (r.x * y - r.y * x),
    )

  infix def antiGeometric(r: Pga2dPseudoScalar): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = r.i * x,
      y = r.i * y,
      w = r.i,
    )

  infix def antiGeometric(r: Pga2dPointCenter.type): Pga2dLineCentral =
    Pga2dLineCentral(
      x = y,
      y = -x,
    )

  infix def antiDot(r: Pga2dMotor): Pga2dMultivector =
    Pga2dMultivector(
      s = 0.0,
      w = 0.0,
      x = r.s * x,
      y = r.s * y,
      wx = 0.0,
      wy = 0.0,
      xy = 0.0,
      i = (r.wx * y - r.wy * x),
    )

  infix def antiDot(r: Pga2dLine): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = -r.w * y,
      y = r.w * x,
      w = (r.x * y - r.y * x),
    )

  infix def antiDot(r: Pga2dRotor): Pga2dLineCentral =
    Pga2dLineCentral(
      x = r.s * x,
      y = r.s * y,
    )

  infix def antiDot(r: Pga2dProjectivePoint): Pga2dPseudoScalar =
    Pga2dPseudoScalar(
      i = (r.x * x + r.y * y),
    )

  infix def antiDot(r: Pga2dProjectiveTranslator): Pga2dMultivector =
    Pga2dMultivector(
      s = 0.0,
      w = 0.0,
      x = r.s * x,
      y = r.s * y,
      wx = 0.0,
      wy = 0.0,
      xy = 0.0,
      i = (r.wx * y - r.wy * x),
    )

  infix def antiDot(r: Pga2dTranslator): Pga2dMultivector =
    Pga2dMultivector(
      s = 0.0,
      w = 0.0,
      x = x,
      y = y,
      wx = 0.0,
      wy = 0.0,
      xy = 0.0,
      i = (r.wx * y - r.wy * x),
    )

  infix def antiDot(r: Pga2dVector): Pga2dPseudoScalar =
    Pga2dPseudoScalar(
      i = (r.x * x + r.y * y),
    )

  infix def antiDot(r: Pga2dPoint): Pga2dPseudoScalar =
    Pga2dPseudoScalar(
      i = (r.x * x + r.y * y),
    )

  infix def antiDot(r: Pga2dLineCentral): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = 0.0,
      y = 0.0,
      w = (r.x * y - r.y * x),
    )

  infix def antiDot(r: Pga2dPseudoScalar): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = r.i * x,
      y = r.i * y,
      w = r.i,
    )

  infix def antiDotI(r: Pga2dProjectivePoint): Double =
    (r.x * x + r.y * y)

  infix def antiDotI(r: Pga2dVector): Double =
    (r.x * x + r.y * y)

  infix def antiDotI(r: Pga2dPoint): Double =
    (r.x * x + r.y * y)

  infix def antiWedge(r: Pga2dMotor): Pga2dLine =
    Pga2dLine(
      x = (-r.wx + r.xy * y),
      y = (-r.wy - r.xy * x),
      w = (r.wx * x + r.wy * y),
    )

  inline infix def v(r: Pga2dMotor): Pga2dLine = antiWedge(r)

  inline infix def join(r: Pga2dMotor): Pga2dLine = antiWedge(r)

  infix def antiWedge(r: Pga2dLine): Double =
    (r.w + r.x * x + r.y * y)

  inline infix def v(r: Pga2dLine): Double = antiWedge(r)

  inline infix def join(r: Pga2dLine): Double = antiWedge(r)

  infix def antiWedge(r: Pga2dRotor): Pga2dLineCentral =
    Pga2dLineCentral(
      x = r.xy * y,
      y = -r.xy * x,
    )

  inline infix def v(r: Pga2dRotor): Pga2dLineCentral = antiWedge(r)

  inline infix def join(r: Pga2dRotor): Pga2dLineCentral = antiWedge(r)

  infix def antiWedge(r: Pga2dProjectivePoint): Pga2dLine =
    Pga2dLine(
      x = (-r.y + r.w * y),
      y = (r.x - r.w * x),
      w = (r.y * x - r.x * y),
    )

  inline infix def v(r: Pga2dProjectivePoint): Pga2dLine = antiWedge(r)

  inline infix def join(r: Pga2dProjectivePoint): Pga2dLine = antiWedge(r)

  infix def antiWedge(r: Pga2dProjectiveTranslator): Pga2dLine =
    Pga2dLine(
      x = -r.wx,
      y = -r.wy,
      w = (r.wx * x + r.wy * y),
    )

  inline infix def v(r: Pga2dProjectiveTranslator): Pga2dLine = antiWedge(r)

  inline infix def join(r: Pga2dProjectiveTranslator): Pga2dLine = antiWedge(r)

  infix def antiWedge(r: Pga2dTranslator): Pga2dLine =
    Pga2dLine(
      x = -r.wx,
      y = -r.wy,
      w = (r.wx * x + r.wy * y),
    )

  inline infix def v(r: Pga2dTranslator): Pga2dLine = antiWedge(r)

  inline infix def join(r: Pga2dTranslator): Pga2dLine = antiWedge(r)

  infix def antiWedge(r: Pga2dVector): Pga2dLine =
    Pga2dLine(
      x = -r.y,
      y = r.x,
      w = (r.y * x - r.x * y),
    )

  inline infix def v(r: Pga2dVector): Pga2dLine = antiWedge(r)

  inline infix def join(r: Pga2dVector): Pga2dLine = antiWedge(r)

  infix def antiWedge(r: Pga2dPoint): Pga2dLine =
    Pga2dLine(
      x = (y - r.y),
      y = (r.x - x),
      w = (r.y * x - r.x * y),
    )

  inline infix def v(r: Pga2dPoint): Pga2dLine = antiWedge(r)

  inline infix def join(r: Pga2dPoint): Pga2dLine = antiWedge(r)

  infix def antiWedge(r: Pga2dLineCentral): Double =
    (r.x * x + r.y * y)

  inline infix def v(r: Pga2dLineCentral): Double = antiWedge(r)

  inline infix def join(r: Pga2dLineCentral): Double = antiWedge(r)

  infix def antiWedge(r: Pga2dPseudoScalar): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = r.i * x,
      y = r.i * y,
      w = r.i,
    )

  inline infix def v(r: Pga2dPseudoScalar): Pga2dProjectivePoint = antiWedge(r)

  inline infix def join(r: Pga2dPseudoScalar): Pga2dProjectivePoint = antiWedge(r)

  infix def antiWedge(r: Pga2dPointCenter.type): Pga2dLineCentral =
    Pga2dLineCentral(
      x = y,
      y = -x,
    )

  inline infix def v(r: Pga2dPointCenter.type): Pga2dLineCentral = antiWedge(r)

  inline infix def join(r: Pga2dPointCenter.type): Pga2dLineCentral = antiWedge(r)

  infix def sandwich(r: Pga2dMotor): Pga2dMotor =
    Pga2dMotor(
      s = r.s,
      wx = (-r.wx + 2.0 * r.xy * y),
      wy = (-r.wy - 2.0 * r.xy * x),
      xy = r.xy,
    )

  infix def sandwich(r: Pga2dLine): Pga2dLine =
    Pga2dLine(
      x = -r.x,
      y = -r.y,
      w = (r.w + 2.0 * r.x * x + 2.0 * r.y * y),
    )

  infix def sandwich(r: Pga2dRotor): Pga2dMotor =
    Pga2dMotor(
      s = r.s,
      wx = 2.0 * r.xy * y,
      wy = -2.0 * r.xy * x,
      xy = r.xy,
    )

  infix def sandwich(r: Pga2dProjectivePoint): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = (-r.x + 2.0 * r.w * x),
      y = (-r.y + 2.0 * r.w * y),
      w = r.w,
    )

  infix def sandwich(r: Pga2dProjectiveTranslator): Pga2dProjectiveTranslator =
    Pga2dProjectiveTranslator(
      s = r.s,
      wx = -r.wx,
      wy = -r.wy,
    )

  infix def sandwich(r: Pga2dTranslator): Pga2dTranslator =
    Pga2dTranslator(
      wx = -r.wx,
      wy = -r.wy,
    )

  infix def sandwich(r: Pga2dVector): Pga2dVector =
    -r

  infix def sandwich(r: Pga2dPoint): Pga2dPoint =
    Pga2dPoint(
      x = (-r.x + 2.0 * x),
      y = (-r.y + 2.0 * y),
    )

  infix def sandwich(r: Pga2dLineCentral): Pga2dLine =
    Pga2dLine(
      x = -r.x,
      y = -r.y,
      w = 2.0 * (r.x * x + r.y * y),
    )

  infix def sandwich(r: Pga2dPseudoScalar): Pga2dPseudoScalar =
    r

  infix def sandwich(r: Pga2dPointCenter.type): Pga2dPoint =
    Pga2dPoint(
      x = 2.0 * x,
      y = 2.0 * y,
    )

  infix def reverseSandwich(r: Pga2dMotor): Pga2dMotor =
    Pga2dMotor(
      s = r.s,
      wx = (-r.wx + 2.0 * r.xy * y),
      wy = (-r.wy - 2.0 * r.xy * x),
      xy = r.xy,
    )

  infix def reverseSandwich(r: Pga2dLine): Pga2dLine =
    Pga2dLine(
      x = -r.x,
      y = -r.y,
      w = (r.w + 2.0 * r.x * x + 2.0 * r.y * y),
    )

  infix def reverseSandwich(r: Pga2dRotor): Pga2dMotor =
    Pga2dMotor(
      s = r.s,
      wx = 2.0 * r.xy * y,
      wy = -2.0 * r.xy * x,
      xy = r.xy,
    )

  infix def reverseSandwich(r: Pga2dProjectivePoint): Pga2dProjectivePoint =
    Pga2dProjectivePoint(
      x = (-r.x + 2.0 * r.w * x),
      y = (-r.y + 2.0 * r.w * y),
      w = r.w,
    )

  infix def reverseSandwich(r: Pga2dProjectiveTranslator): Pga2dProjectiveTranslator =
    Pga2dProjectiveTranslator(
      s = r.s,
      wx = -r.wx,
      wy = -r.wy,
    )

  infix def reverseSandwich(r: Pga2dTranslator): Pga2dTranslator =
    Pga2dTranslator(
      wx = -r.wx,
      wy = -r.wy,
    )

  infix def reverseSandwich(r: Pga2dVector): Pga2dVector =
    -r

  infix def reverseSandwich(r: Pga2dPoint): Pga2dPoint =
    Pga2dPoint(
      x = (-r.x + 2.0 * x),
      y = (-r.y + 2.0 * y),
    )

  infix def reverseSandwich(r: Pga2dLineCentral): Pga2dLine =
    Pga2dLine(
      x = -r.x,
      y = -r.y,
      w = 2.0 * (r.x * x + r.y * y),
    )

  infix def reverseSandwich(r: Pga2dPseudoScalar): Pga2dPseudoScalar =
    r

  infix def reverseSandwich(r: Pga2dPointCenter.type): Pga2dPoint =
    Pga2dPoint(
      x = 2.0 * x,
      y = 2.0 * y,
    )

  infix def cross(r: Pga2dMotor): Pga2dVector =
    Pga2dVector(
      x = (r.wx - r.xy * y),
      y = (r.wy + r.xy * x),
    )

  infix def cross(r: Pga2dLine): Pga2dLine =
    Pga2dLine(
      x = r.y,
      y = -r.x,
      w = (r.x * y - r.y * x),
    )

  infix def cross(r: Pga2dRotor): Pga2dVector =
    Pga2dVector(
      x = -r.xy * y,
      y = r.xy * x,
    )

  infix def cross(r: Pga2dProjectivePoint): Pga2dVector =
    Pga2dVector(
      x = (r.y - r.w * y),
      y = (-r.x + r.w * x),
    )

  infix def cross(r: Pga2dProjectiveTranslator): Pga2dVector =
    Pga2dVector(
      x = r.wx,
      y = r.wy,
    )

  infix def cross(r: Pga2dTranslator): Pga2dVector =
    Pga2dVector(
      x = r.wx,
      y = r.wy,
    )

  infix def cross(r: Pga2dVector): Pga2dVector =
    Pga2dVector(
      x = r.y,
      y = -r.x,
    )

  infix def cross(r: Pga2dPoint): Pga2dVector =
    Pga2dVector(
      x = (r.y - y),
      y = (x - r.x),
    )

  infix def cross(r: Pga2dLineCentral): Pga2dLine =
    Pga2dLine(
      x = r.y,
      y = -r.x,
      w = (r.x * y - r.y * x),
    )

  infix def cross(r: Pga2dPointCenter.type): Pga2dVector =
    Pga2dVector(
      x = -y,
      y = x,
    )


object Pga2dPoint:

  inline val componentsCount = 2

  val center: Pga2dPoint =
    Pga2dPoint(0.0, 0.0)

  def blade2(wx: Double, wy: Double): Pga2dPoint =
    Pga2dPoint(
      x = -wy,
      y = wx,
    )

  def interpolate(a: Pga2dPoint, b: Pga2dPoint, t: Double): Pga2dPoint =
    (a.toVectorUnsafe * (1.0 - t) + b.toVectorUnsafe * t).toPointUnsafe

  def mid(a: Pga2dPoint, b: Pga2dPoint): Pga2dPoint =
    Pga2dPoint(
      x = (a.x + b.x) * 0.5,
      y = (a.y + b.y) * 0.5,
    )

  def mid(a: Pga2dPoint, b: Pga2dPoint, c: Pga2dPoint): Pga2dPoint =
    val m = 1.0 / 3.0
    Pga2dPoint(
      x = (a.x + b.x + c.x) * m,
      y = (a.y + b.y + c.y) * m,
    )