// Copyright (c) 2025 Igor Slobodskov
// SPDX-License-Identifier: MIT

#pragma once

#include "types.h"

// generated by com.github.kright.pga3d.codegen.cpp.ops.ReverseOpGenerator

namespace pga3d {
    constexpr Multivector reversed(const Multivector& a) noexcept { return {
        .s = a.s,
        .w = a.w,
        .x = a.x,
        .y = a.y,
        .z = a.z,
        .wx = -a.wx,
        .wy = -a.wy,
        .wz = -a.wz,
        .xy = -a.xy,
        .xz = -a.xz,
        .yz = -a.yz,
        .wxy = -a.wxy,
        .wxz = -a.wxz,
        .wyz = -a.wyz,
        .xyz = -a.xyz,
        .i = a.i
    }; }
    constexpr Multivector Multivector::reversed() const noexcept { return pga3d::reversed(*this); }

    constexpr Motor reversed(const Motor& a) noexcept { return {
        .s = a.s,
        .wx = -a.wx,
        .wy = -a.wy,
        .wz = -a.wz,
        .xy = -a.xy,
        .xz = -a.xz,
        .yz = -a.yz,
        .i = a.i
    }; }
    constexpr Motor Motor::reversed() const noexcept { return pga3d::reversed(*this); }

    constexpr Plane reversed(const Plane& a) noexcept { return {
        .x = a.x,
        .y = a.y,
        .z = a.z,
        .w = a.w
    }; }
    constexpr Plane Plane::reversed() const noexcept { return pga3d::reversed(*this); }

    constexpr Bivector reversed(const Bivector& a) noexcept { return {
        .wx = -a.wx,
        .wy = -a.wy,
        .wz = -a.wz,
        .xy = -a.xy,
        .xz = -a.xz,
        .yz = -a.yz
    }; }
    constexpr Bivector Bivector::reversed() const noexcept { return pga3d::reversed(*this); }

    constexpr ProjectivePoint reversed(const ProjectivePoint& a) noexcept { return {
        .x = -a.x,
        .y = -a.y,
        .z = -a.z,
        .w = -a.w
    }; }
    constexpr ProjectivePoint ProjectivePoint::reversed() const noexcept { return pga3d::reversed(*this); }

    constexpr Quaternion reversed(const Quaternion& a) noexcept { return {
        .s = a.s,
        .xy = -a.xy,
        .xz = -a.xz,
        .yz = -a.yz
    }; }
    constexpr Quaternion Quaternion::reversed() const noexcept { return pga3d::reversed(*this); }

    constexpr ProjectiveTranslator reversed(const ProjectiveTranslator& a) noexcept { return {
        .s = a.s,
        .wx = -a.wx,
        .wy = -a.wy,
        .wz = -a.wz
    }; }
    constexpr ProjectiveTranslator ProjectiveTranslator::reversed() const noexcept { return pga3d::reversed(*this); }

    constexpr Translator reversed(const Translator& a) noexcept { return {
        .wx = -a.wx,
        .wy = -a.wy,
        .wz = -a.wz
    }; }
    constexpr Translator Translator::reversed() const noexcept { return pga3d::reversed(*this); }

    constexpr Vector reversed(const Vector& a) noexcept { return {
        .x = -a.x,
        .y = -a.y,
        .z = -a.z
    }; }
    constexpr Vector Vector::reversed() const noexcept { return pga3d::reversed(*this); }

    constexpr ProjectivePoint reversed(const Point& a) noexcept { return {
        .x = -a.x,
        .y = -a.y,
        .z = -a.z,
        .w = -1.0
    }; }
    constexpr ProjectivePoint Point::reversed() const noexcept { return pga3d::reversed(*this); }

    constexpr PlaneIdeal reversed(const PlaneIdeal& a) noexcept { return {
        .x = a.x,
        .y = a.y,
        .z = a.z
    }; }
    constexpr PlaneIdeal PlaneIdeal::reversed() const noexcept { return pga3d::reversed(*this); }

    constexpr BivectorBulk reversed(const BivectorBulk& a) noexcept { return {
        .xy = -a.xy,
        .xz = -a.xz,
        .yz = -a.yz
    }; }
    constexpr BivectorBulk BivectorBulk::reversed() const noexcept { return pga3d::reversed(*this); }

    constexpr BivectorWeight reversed(const BivectorWeight& a) noexcept { return {
        .wx = -a.wx,
        .wy = -a.wy,
        .wz = -a.wz
    }; }
    constexpr BivectorWeight BivectorWeight::reversed() const noexcept { return pga3d::reversed(*this); }

    constexpr PseudoScalar reversed(const PseudoScalar& a) noexcept { return {
        .i = a.i
    }; }
    constexpr PseudoScalar PseudoScalar::reversed() const noexcept { return pga3d::reversed(*this); }

    constexpr ProjectivePoint reversed(const PointCenter& a) noexcept { return {
        .x = 0.0,
        .y = 0.0,
        .z = 0.0,
        .w = -1.0
    }; }
    constexpr ProjectivePoint PointCenter::reversed() const noexcept { return pga3d::reversed(*this); }

}