// Copyright (c) 2025 Igor Slobodskov
// SPDX-License-Identifier: MIT

#pragma once

#include "types.h"

// generated by com.github.kright.pga3d.codegen.cpp.ops.WedgeOpGenerator

namespace pga3d {
    [[nodiscard]] constexpr Multivector wedge(const Multivector& a,const Multivector& b) noexcept { return {
        .s = a.s * b.s,
        .w = (a.s * b.w + a.w * b.s),
        .x = (a.s * b.x + a.x * b.s),
        .y = (a.s * b.y + a.y * b.s),
        .z = (a.s * b.z + a.z * b.s),
        .wx = (a.s * b.wx + a.w * b.x + a.wx * b.s - a.x * b.w),
        .wy = (a.s * b.wy + a.w * b.y + a.wy * b.s - a.y * b.w),
        .wz = (a.s * b.wz + a.w * b.z + a.wz * b.s - a.z * b.w),
        .xy = (a.s * b.xy + a.x * b.y + a.xy * b.s - a.y * b.x),
        .xz = (a.s * b.xz + a.x * b.z + a.xz * b.s - a.z * b.x),
        .yz = (a.s * b.yz + a.y * b.z + a.yz * b.s - a.z * b.y),
        .wxy = (a.s * b.wxy + a.w * b.xy + a.wx * b.y + a.wxy * b.s + a.xy * b.w + a.y * b.wx - a.wy * b.x - a.x * b.wy),
        .wxz = (a.s * b.wxz + a.w * b.xz + a.wx * b.z + a.wxz * b.s + a.xz * b.w + a.z * b.wx - a.wz * b.x - a.x * b.wz),
        .wyz = (a.s * b.wyz + a.w * b.yz + a.wy * b.z + a.wyz * b.s + a.yz * b.w + a.z * b.wy - a.wz * b.y - a.y * b.wz),
        .xyz = (a.s * b.xyz + a.x * b.yz + a.xy * b.z + a.xyz * b.s + a.yz * b.x + a.z * b.xy - a.xz * b.y - a.y * b.xz),
        .i = (a.i * b.s + a.s * b.i + a.w * b.xyz + a.wx * b.yz + a.wxy * b.z + a.wyz * b.x + a.wz * b.xy + a.xy * b.wz + a.y * b.wxz + a.yz * b.wx - a.wxz * b.y - a.wy * b.xz - a.x * b.wyz - a.xyz * b.w - a.xz * b.wy - a.z * b.wxy)
    }; }
    [[nodiscard]] constexpr Multivector meet(const Multivector& a,const Multivector& b) noexcept { return wedge(a, b); }
    constexpr Multivector Multivector::wedge(const Multivector& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr Multivector Multivector::meet(const Multivector& b) const noexcept { return pga3d::wedge(*this, b); }


    [[nodiscard]] constexpr Motor wedge(const Motor& a,const Motor& b) noexcept { return {
        .s = a.s * b.s,
        .wx = (a.s * b.wx + a.wx * b.s),
        .wy = (a.s * b.wy + a.wy * b.s),
        .wz = (a.s * b.wz + a.wz * b.s),
        .xy = (a.s * b.xy + a.xy * b.s),
        .xz = (a.s * b.xz + a.xz * b.s),
        .yz = (a.s * b.yz + a.yz * b.s),
        .i = (a.i * b.s + a.s * b.i + a.wx * b.yz + a.wz * b.xy + a.xy * b.wz + a.yz * b.wx - a.wy * b.xz - a.xz * b.wy)
    }; }
    [[nodiscard]] constexpr Motor meet(const Motor& a,const Motor& b) noexcept { return wedge(a, b); }
    constexpr Motor Motor::wedge(const Motor& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr Motor Motor::meet(const Motor& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr Multivector wedge(const Motor& a,const Plane& b) noexcept { return {
        .s = 0.0,
        .w = a.s * b.w,
        .x = a.s * b.x,
        .y = a.s * b.y,
        .z = a.s * b.z,
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .wxy = (a.wx * b.y + a.xy * b.w - a.wy * b.x),
        .wxz = (a.wx * b.z + a.xz * b.w - a.wz * b.x),
        .wyz = (a.wy * b.z + a.yz * b.w - a.wz * b.y),
        .xyz = (a.xy * b.z + a.yz * b.x - a.xz * b.y),
        .i = 0.0
    }; }
    [[nodiscard]] constexpr Multivector meet(const Motor& a,const Plane& b) noexcept { return wedge(a, b); }
    constexpr Multivector Motor::wedge(const Plane& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr Multivector Motor::meet(const Plane& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr Motor wedge(const Motor& a,const Bivector& b) noexcept { return {
        .s = 0.0,
        .wx = a.s * b.wx,
        .wy = a.s * b.wy,
        .wz = a.s * b.wz,
        .xy = a.s * b.xy,
        .xz = a.s * b.xz,
        .yz = a.s * b.yz,
        .i = (a.wx * b.yz + a.wz * b.xy + a.xy * b.wz + a.yz * b.wx - a.wy * b.xz - a.xz * b.wy)
    }; }
    [[nodiscard]] constexpr Motor meet(const Motor& a,const Bivector& b) noexcept { return wedge(a, b); }
    constexpr Motor Motor::wedge(const Bivector& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr Motor Motor::meet(const Bivector& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr ProjectivePoint wedge(const Motor& a,const ProjectivePoint& b) noexcept { return {
        .x = a.s * b.x,
        .y = a.s * b.y,
        .z = a.s * b.z,
        .w = a.s * b.w
    }; }
    [[nodiscard]] constexpr ProjectivePoint meet(const Motor& a,const ProjectivePoint& b) noexcept { return wedge(a, b); }
    constexpr ProjectivePoint Motor::wedge(const ProjectivePoint& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr ProjectivePoint Motor::meet(const ProjectivePoint& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr Motor wedge(const Motor& a,const Quaternion& b) noexcept { return {
        .s = a.s * b.s,
        .wx = a.wx * b.s,
        .wy = a.wy * b.s,
        .wz = a.wz * b.s,
        .xy = (a.s * b.xy + a.xy * b.s),
        .xz = (a.s * b.xz + a.xz * b.s),
        .yz = (a.s * b.yz + a.yz * b.s),
        .i = (a.i * b.s + a.wx * b.yz + a.wz * b.xy - a.wy * b.xz)
    }; }
    [[nodiscard]] constexpr Motor meet(const Motor& a,const Quaternion& b) noexcept { return wedge(a, b); }
    constexpr Motor Motor::wedge(const Quaternion& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr Motor Motor::meet(const Quaternion& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr Motor wedge(const Motor& a,const ProjectiveTranslator& b) noexcept { return {
        .s = a.s * b.s,
        .wx = (a.s * b.wx + a.wx * b.s),
        .wy = (a.s * b.wy + a.wy * b.s),
        .wz = (a.s * b.wz + a.wz * b.s),
        .xy = a.xy * b.s,
        .xz = a.xz * b.s,
        .yz = a.yz * b.s,
        .i = (a.i * b.s + a.xy * b.wz + a.yz * b.wx - a.xz * b.wy)
    }; }
    [[nodiscard]] constexpr Motor meet(const Motor& a,const ProjectiveTranslator& b) noexcept { return wedge(a, b); }
    constexpr Motor Motor::wedge(const ProjectiveTranslator& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr Motor Motor::meet(const ProjectiveTranslator& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr Motor wedge(const Motor& a,const Translator& b) noexcept { return {
        .s = a.s,
        .wx = (a.wx + a.s * b.wx),
        .wy = (a.wy + a.s * b.wy),
        .wz = (a.wz + a.s * b.wz),
        .xy = a.xy,
        .xz = a.xz,
        .yz = a.yz,
        .i = (a.i + a.xy * b.wz + a.yz * b.wx - a.xz * b.wy)
    }; }
    [[nodiscard]] constexpr Motor meet(const Motor& a,const Translator& b) noexcept { return wedge(a, b); }
    constexpr Motor Motor::wedge(const Translator& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr Motor Motor::meet(const Translator& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr Vector wedge(const Motor& a,const Vector& b) noexcept { return {
        .x = a.s * b.x,
        .y = a.s * b.y,
        .z = a.s * b.z
    }; }
    [[nodiscard]] constexpr Vector meet(const Motor& a,const Vector& b) noexcept { return wedge(a, b); }
    constexpr Vector Motor::wedge(const Vector& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr Vector Motor::meet(const Vector& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr ProjectivePoint wedge(const Motor& a,const Point& b) noexcept { return {
        .x = a.s * b.x,
        .y = a.s * b.y,
        .z = a.s * b.z,
        .w = a.s
    }; }
    [[nodiscard]] constexpr ProjectivePoint meet(const Motor& a,const Point& b) noexcept { return wedge(a, b); }
    constexpr ProjectivePoint Motor::wedge(const Point& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr ProjectivePoint Motor::meet(const Point& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr Multivector wedge(const Motor& a,const PlaneIdeal& b) noexcept { return {
        .s = 0.0,
        .w = 0.0,
        .x = a.s * b.x,
        .y = a.s * b.y,
        .z = a.s * b.z,
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .wxy = (a.wx * b.y - a.wy * b.x),
        .wxz = (a.wx * b.z - a.wz * b.x),
        .wyz = (a.wy * b.z - a.wz * b.y),
        .xyz = (a.xy * b.z + a.yz * b.x - a.xz * b.y),
        .i = 0.0
    }; }
    [[nodiscard]] constexpr Multivector meet(const Motor& a,const PlaneIdeal& b) noexcept { return wedge(a, b); }
    constexpr Multivector Motor::wedge(const PlaneIdeal& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr Multivector Motor::meet(const PlaneIdeal& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr Motor wedge(const Motor& a,const BivectorBulk& b) noexcept { return {
        .s = 0.0,
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = a.s * b.xy,
        .xz = a.s * b.xz,
        .yz = a.s * b.yz,
        .i = (a.wx * b.yz + a.wz * b.xy - a.wy * b.xz)
    }; }
    [[nodiscard]] constexpr Motor meet(const Motor& a,const BivectorBulk& b) noexcept { return wedge(a, b); }
    constexpr Motor Motor::wedge(const BivectorBulk& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr Motor Motor::meet(const BivectorBulk& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr Motor wedge(const Motor& a,const BivectorWeight& b) noexcept { return {
        .s = 0.0,
        .wx = a.s * b.wx,
        .wy = a.s * b.wy,
        .wz = a.s * b.wz,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .i = (a.xy * b.wz + a.yz * b.wx - a.xz * b.wy)
    }; }
    [[nodiscard]] constexpr Motor meet(const Motor& a,const BivectorWeight& b) noexcept { return wedge(a, b); }
    constexpr Motor Motor::wedge(const BivectorWeight& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr Motor Motor::meet(const BivectorWeight& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr PseudoScalar wedge(const Motor& a,const PseudoScalar& b) noexcept { return {
        .i = a.s * b.i
    }; }
    [[nodiscard]] constexpr PseudoScalar meet(const Motor& a,const PseudoScalar& b) noexcept { return wedge(a, b); }
    constexpr PseudoScalar Motor::wedge(const PseudoScalar& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr PseudoScalar Motor::meet(const PseudoScalar& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr ProjectivePoint wedge(const Motor& a,const PointCenter& b) noexcept { return {
        .x = 0.0,
        .y = 0.0,
        .z = 0.0,
        .w = a.s
    }; }
    [[nodiscard]] constexpr ProjectivePoint meet(const Motor& a,const PointCenter& b) noexcept { return wedge(a, b); }
    constexpr ProjectivePoint Motor::wedge(const PointCenter& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr ProjectivePoint Motor::meet(const PointCenter& b) const noexcept { return pga3d::wedge(*this, b); }


    [[nodiscard]] constexpr Multivector wedge(const Plane& a,const Motor& b) noexcept { return {
        .s = 0.0,
        .w = a.w * b.s,
        .x = a.x * b.s,
        .y = a.y * b.s,
        .z = a.z * b.s,
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .wxy = (a.w * b.xy + a.y * b.wx - a.x * b.wy),
        .wxz = (a.w * b.xz + a.z * b.wx - a.x * b.wz),
        .wyz = (a.w * b.yz + a.z * b.wy - a.y * b.wz),
        .xyz = (a.x * b.yz + a.z * b.xy - a.y * b.xz),
        .i = 0.0
    }; }
    [[nodiscard]] constexpr Multivector meet(const Plane& a,const Motor& b) noexcept { return wedge(a, b); }
    constexpr Multivector Plane::wedge(const Motor& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr Multivector Plane::meet(const Motor& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr Bivector wedge(const Plane& a,const Plane& b) noexcept { return {
        .wx = (a.w * b.x - a.x * b.w),
        .wy = (a.w * b.y - a.y * b.w),
        .wz = (a.w * b.z - a.z * b.w),
        .xy = (a.x * b.y - a.y * b.x),
        .xz = (a.x * b.z - a.z * b.x),
        .yz = (a.y * b.z - a.z * b.y)
    }; }
    [[nodiscard]] constexpr Bivector meet(const Plane& a,const Plane& b) noexcept { return wedge(a, b); }
    constexpr Bivector Plane::wedge(const Plane& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr Bivector Plane::meet(const Plane& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr ProjectivePoint wedge(const Plane& a,const Bivector& b) noexcept { return {
        .x = (a.y * b.wz - a.w * b.yz - a.z * b.wy),
        .y = (a.w * b.xz + a.z * b.wx - a.x * b.wz),
        .z = (a.x * b.wy - a.w * b.xy - a.y * b.wx),
        .w = (a.x * b.yz + a.z * b.xy - a.y * b.xz)
    }; }
    [[nodiscard]] constexpr ProjectivePoint meet(const Plane& a,const Bivector& b) noexcept { return wedge(a, b); }
    constexpr ProjectivePoint Plane::wedge(const Bivector& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr ProjectivePoint Plane::meet(const Bivector& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr PseudoScalar wedge(const Plane& a,const ProjectivePoint& b) noexcept { return {
        .i = (a.w * b.w + a.x * b.x + a.y * b.y + a.z * b.z)
    }; }
    [[nodiscard]] constexpr PseudoScalar meet(const Plane& a,const ProjectivePoint& b) noexcept { return wedge(a, b); }
    constexpr PseudoScalar Plane::wedge(const ProjectivePoint& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr PseudoScalar Plane::meet(const ProjectivePoint& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr Multivector wedge(const Plane& a,const Quaternion& b) noexcept { return {
        .s = 0.0,
        .w = a.w * b.s,
        .x = a.x * b.s,
        .y = a.y * b.s,
        .z = a.z * b.s,
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .wxy = a.w * b.xy,
        .wxz = a.w * b.xz,
        .wyz = a.w * b.yz,
        .xyz = (a.x * b.yz + a.z * b.xy - a.y * b.xz),
        .i = 0.0
    }; }
    [[nodiscard]] constexpr Multivector meet(const Plane& a,const Quaternion& b) noexcept { return wedge(a, b); }
    constexpr Multivector Plane::wedge(const Quaternion& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr Multivector Plane::meet(const Quaternion& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr Multivector wedge(const Plane& a,const ProjectiveTranslator& b) noexcept { return {
        .s = 0.0,
        .w = a.w * b.s,
        .x = a.x * b.s,
        .y = a.y * b.s,
        .z = a.z * b.s,
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .wxy = (a.y * b.wx - a.x * b.wy),
        .wxz = (a.z * b.wx - a.x * b.wz),
        .wyz = (a.z * b.wy - a.y * b.wz),
        .xyz = 0.0,
        .i = 0.0
    }; }
    [[nodiscard]] constexpr Multivector meet(const Plane& a,const ProjectiveTranslator& b) noexcept { return wedge(a, b); }
    constexpr Multivector Plane::wedge(const ProjectiveTranslator& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr Multivector Plane::meet(const ProjectiveTranslator& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr Multivector wedge(const Plane& a,const Translator& b) noexcept { return {
        .s = 0.0,
        .w = a.w,
        .x = a.x,
        .y = a.y,
        .z = a.z,
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .wxy = (a.y * b.wx - a.x * b.wy),
        .wxz = (a.z * b.wx - a.x * b.wz),
        .wyz = (a.z * b.wy - a.y * b.wz),
        .xyz = 0.0,
        .i = 0.0
    }; }
    [[nodiscard]] constexpr Multivector meet(const Plane& a,const Translator& b) noexcept { return wedge(a, b); }
    constexpr Multivector Plane::wedge(const Translator& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr Multivector Plane::meet(const Translator& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr PseudoScalar wedge(const Plane& a,const Vector& b) noexcept { return {
        .i = (a.x * b.x + a.y * b.y + a.z * b.z)
    }; }
    [[nodiscard]] constexpr PseudoScalar meet(const Plane& a,const Vector& b) noexcept { return wedge(a, b); }
    constexpr PseudoScalar Plane::wedge(const Vector& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr PseudoScalar Plane::meet(const Vector& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr PseudoScalar wedge(const Plane& a,const Point& b) noexcept { return {
        .i = (a.w + a.x * b.x + a.y * b.y + a.z * b.z)
    }; }
    [[nodiscard]] constexpr PseudoScalar meet(const Plane& a,const Point& b) noexcept { return wedge(a, b); }
    constexpr PseudoScalar Plane::wedge(const Point& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr PseudoScalar Plane::meet(const Point& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr Bivector wedge(const Plane& a,const PlaneIdeal& b) noexcept { return {
        .wx = a.w * b.x,
        .wy = a.w * b.y,
        .wz = a.w * b.z,
        .xy = (a.x * b.y - a.y * b.x),
        .xz = (a.x * b.z - a.z * b.x),
        .yz = (a.y * b.z - a.z * b.y)
    }; }
    [[nodiscard]] constexpr Bivector meet(const Plane& a,const PlaneIdeal& b) noexcept { return wedge(a, b); }
    constexpr Bivector Plane::wedge(const PlaneIdeal& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr Bivector Plane::meet(const PlaneIdeal& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr ProjectivePoint wedge(const Plane& a,const BivectorBulk& b) noexcept { return {
        .x = -a.w * b.yz,
        .y = a.w * b.xz,
        .z = -a.w * b.xy,
        .w = (a.x * b.yz + a.z * b.xy - a.y * b.xz)
    }; }
    [[nodiscard]] constexpr ProjectivePoint meet(const Plane& a,const BivectorBulk& b) noexcept { return wedge(a, b); }
    constexpr ProjectivePoint Plane::wedge(const BivectorBulk& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr ProjectivePoint Plane::meet(const BivectorBulk& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr Vector wedge(const Plane& a,const BivectorWeight& b) noexcept { return {
        .x = (a.y * b.wz - a.z * b.wy),
        .y = (a.z * b.wx - a.x * b.wz),
        .z = (a.x * b.wy - a.y * b.wx)
    }; }
    [[nodiscard]] constexpr Vector meet(const Plane& a,const BivectorWeight& b) noexcept { return wedge(a, b); }
    constexpr Vector Plane::wedge(const BivectorWeight& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr Vector Plane::meet(const BivectorWeight& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr PseudoScalar wedge(const Plane& a,const PointCenter& b) noexcept { return {
        .i = a.w
    }; }
    [[nodiscard]] constexpr PseudoScalar meet(const Plane& a,const PointCenter& b) noexcept { return wedge(a, b); }
    constexpr PseudoScalar Plane::wedge(const PointCenter& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr PseudoScalar Plane::meet(const PointCenter& b) const noexcept { return pga3d::wedge(*this, b); }


    [[nodiscard]] constexpr Motor wedge(const Bivector& a,const Motor& b) noexcept { return {
        .s = 0.0,
        .wx = a.wx * b.s,
        .wy = a.wy * b.s,
        .wz = a.wz * b.s,
        .xy = a.xy * b.s,
        .xz = a.xz * b.s,
        .yz = a.yz * b.s,
        .i = (a.wx * b.yz + a.wz * b.xy + a.xy * b.wz + a.yz * b.wx - a.wy * b.xz - a.xz * b.wy)
    }; }
    [[nodiscard]] constexpr Motor meet(const Bivector& a,const Motor& b) noexcept { return wedge(a, b); }
    constexpr Motor Bivector::wedge(const Motor& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr Motor Bivector::meet(const Motor& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr ProjectivePoint wedge(const Bivector& a,const Plane& b) noexcept { return {
        .x = (a.wz * b.y - a.wy * b.z - a.yz * b.w),
        .y = (a.wx * b.z + a.xz * b.w - a.wz * b.x),
        .z = (a.wy * b.x - a.wx * b.y - a.xy * b.w),
        .w = (a.xy * b.z + a.yz * b.x - a.xz * b.y)
    }; }
    [[nodiscard]] constexpr ProjectivePoint meet(const Bivector& a,const Plane& b) noexcept { return wedge(a, b); }
    constexpr ProjectivePoint Bivector::wedge(const Plane& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr ProjectivePoint Bivector::meet(const Plane& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr PseudoScalar wedge(const Bivector& a,const Bivector& b) noexcept { return {
        .i = (a.wx * b.yz + a.wz * b.xy + a.xy * b.wz + a.yz * b.wx - a.wy * b.xz - a.xz * b.wy)
    }; }
    [[nodiscard]] constexpr PseudoScalar meet(const Bivector& a,const Bivector& b) noexcept { return wedge(a, b); }
    constexpr PseudoScalar Bivector::wedge(const Bivector& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr PseudoScalar Bivector::meet(const Bivector& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr Motor wedge(const Bivector& a,const Quaternion& b) noexcept { return {
        .s = 0.0,
        .wx = a.wx * b.s,
        .wy = a.wy * b.s,
        .wz = a.wz * b.s,
        .xy = a.xy * b.s,
        .xz = a.xz * b.s,
        .yz = a.yz * b.s,
        .i = (a.wx * b.yz + a.wz * b.xy - a.wy * b.xz)
    }; }
    [[nodiscard]] constexpr Motor meet(const Bivector& a,const Quaternion& b) noexcept { return wedge(a, b); }
    constexpr Motor Bivector::wedge(const Quaternion& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr Motor Bivector::meet(const Quaternion& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr Motor wedge(const Bivector& a,const ProjectiveTranslator& b) noexcept { return {
        .s = 0.0,
        .wx = a.wx * b.s,
        .wy = a.wy * b.s,
        .wz = a.wz * b.s,
        .xy = a.xy * b.s,
        .xz = a.xz * b.s,
        .yz = a.yz * b.s,
        .i = (a.xy * b.wz + a.yz * b.wx - a.xz * b.wy)
    }; }
    [[nodiscard]] constexpr Motor meet(const Bivector& a,const ProjectiveTranslator& b) noexcept { return wedge(a, b); }
    constexpr Motor Bivector::wedge(const ProjectiveTranslator& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr Motor Bivector::meet(const ProjectiveTranslator& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr Motor wedge(const Bivector& a,const Translator& b) noexcept { return {
        .s = 0.0,
        .wx = a.wx,
        .wy = a.wy,
        .wz = a.wz,
        .xy = a.xy,
        .xz = a.xz,
        .yz = a.yz,
        .i = (a.xy * b.wz + a.yz * b.wx - a.xz * b.wy)
    }; }
    [[nodiscard]] constexpr Motor meet(const Bivector& a,const Translator& b) noexcept { return wedge(a, b); }
    constexpr Motor Bivector::wedge(const Translator& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr Motor Bivector::meet(const Translator& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr ProjectivePoint wedge(const Bivector& a,const PlaneIdeal& b) noexcept { return {
        .x = (a.wz * b.y - a.wy * b.z),
        .y = (a.wx * b.z - a.wz * b.x),
        .z = (a.wy * b.x - a.wx * b.y),
        .w = (a.xy * b.z + a.yz * b.x - a.xz * b.y)
    }; }
    [[nodiscard]] constexpr ProjectivePoint meet(const Bivector& a,const PlaneIdeal& b) noexcept { return wedge(a, b); }
    constexpr ProjectivePoint Bivector::wedge(const PlaneIdeal& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr ProjectivePoint Bivector::meet(const PlaneIdeal& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr PseudoScalar wedge(const Bivector& a,const BivectorBulk& b) noexcept { return {
        .i = (a.wx * b.yz + a.wz * b.xy - a.wy * b.xz)
    }; }
    [[nodiscard]] constexpr PseudoScalar meet(const Bivector& a,const BivectorBulk& b) noexcept { return wedge(a, b); }
    constexpr PseudoScalar Bivector::wedge(const BivectorBulk& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr PseudoScalar Bivector::meet(const BivectorBulk& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr PseudoScalar wedge(const Bivector& a,const BivectorWeight& b) noexcept { return {
        .i = (a.xy * b.wz + a.yz * b.wx - a.xz * b.wy)
    }; }
    [[nodiscard]] constexpr PseudoScalar meet(const Bivector& a,const BivectorWeight& b) noexcept { return wedge(a, b); }
    constexpr PseudoScalar Bivector::wedge(const BivectorWeight& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr PseudoScalar Bivector::meet(const BivectorWeight& b) const noexcept { return pga3d::wedge(*this, b); }


    [[nodiscard]] constexpr ProjectivePoint wedge(const ProjectivePoint& a,const Motor& b) noexcept { return {
        .x = a.x * b.s,
        .y = a.y * b.s,
        .z = a.z * b.s,
        .w = a.w * b.s
    }; }
    [[nodiscard]] constexpr ProjectivePoint meet(const ProjectivePoint& a,const Motor& b) noexcept { return wedge(a, b); }
    constexpr ProjectivePoint ProjectivePoint::wedge(const Motor& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr ProjectivePoint ProjectivePoint::meet(const Motor& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr PseudoScalar wedge(const ProjectivePoint& a,const Plane& b) noexcept { return {
        .i = (-a.w * b.w - a.x * b.x - a.y * b.y - a.z * b.z)
    }; }
    [[nodiscard]] constexpr PseudoScalar meet(const ProjectivePoint& a,const Plane& b) noexcept { return wedge(a, b); }
    constexpr PseudoScalar ProjectivePoint::wedge(const Plane& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr PseudoScalar ProjectivePoint::meet(const Plane& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr ProjectivePoint wedge(const ProjectivePoint& a,const Quaternion& b) noexcept { return {
        .x = a.x * b.s,
        .y = a.y * b.s,
        .z = a.z * b.s,
        .w = a.w * b.s
    }; }
    [[nodiscard]] constexpr ProjectivePoint meet(const ProjectivePoint& a,const Quaternion& b) noexcept { return wedge(a, b); }
    constexpr ProjectivePoint ProjectivePoint::wedge(const Quaternion& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr ProjectivePoint ProjectivePoint::meet(const Quaternion& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr ProjectivePoint wedge(const ProjectivePoint& a,const ProjectiveTranslator& b) noexcept { return {
        .x = a.x * b.s,
        .y = a.y * b.s,
        .z = a.z * b.s,
        .w = a.w * b.s
    }; }
    [[nodiscard]] constexpr ProjectivePoint meet(const ProjectivePoint& a,const ProjectiveTranslator& b) noexcept { return wedge(a, b); }
    constexpr ProjectivePoint ProjectivePoint::wedge(const ProjectiveTranslator& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr ProjectivePoint ProjectivePoint::meet(const ProjectiveTranslator& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr ProjectivePoint wedge(const ProjectivePoint& a,const Translator& b) noexcept { return {
        .x = a.x,
        .y = a.y,
        .z = a.z,
        .w = a.w
    }; }
    [[nodiscard]] constexpr ProjectivePoint meet(const ProjectivePoint& a,const Translator& b) noexcept { return wedge(a, b); }
    constexpr ProjectivePoint ProjectivePoint::wedge(const Translator& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr ProjectivePoint ProjectivePoint::meet(const Translator& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr PseudoScalar wedge(const ProjectivePoint& a,const PlaneIdeal& b) noexcept { return {
        .i = (-a.x * b.x - a.y * b.y - a.z * b.z)
    }; }
    [[nodiscard]] constexpr PseudoScalar meet(const ProjectivePoint& a,const PlaneIdeal& b) noexcept { return wedge(a, b); }
    constexpr PseudoScalar ProjectivePoint::wedge(const PlaneIdeal& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr PseudoScalar ProjectivePoint::meet(const PlaneIdeal& b) const noexcept { return pga3d::wedge(*this, b); }


    [[nodiscard]] constexpr Motor wedge(const Quaternion& a,const Motor& b) noexcept { return {
        .s = a.s * b.s,
        .wx = a.s * b.wx,
        .wy = a.s * b.wy,
        .wz = a.s * b.wz,
        .xy = (a.s * b.xy + a.xy * b.s),
        .xz = (a.s * b.xz + a.xz * b.s),
        .yz = (a.s * b.yz + a.yz * b.s),
        .i = (a.s * b.i + a.xy * b.wz + a.yz * b.wx - a.xz * b.wy)
    }; }
    [[nodiscard]] constexpr Motor meet(const Quaternion& a,const Motor& b) noexcept { return wedge(a, b); }
    constexpr Motor Quaternion::wedge(const Motor& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr Motor Quaternion::meet(const Motor& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr Multivector wedge(const Quaternion& a,const Plane& b) noexcept { return {
        .s = 0.0,
        .w = a.s * b.w,
        .x = a.s * b.x,
        .y = a.s * b.y,
        .z = a.s * b.z,
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .wxy = a.xy * b.w,
        .wxz = a.xz * b.w,
        .wyz = a.yz * b.w,
        .xyz = (a.xy * b.z + a.yz * b.x - a.xz * b.y),
        .i = 0.0
    }; }
    [[nodiscard]] constexpr Multivector meet(const Quaternion& a,const Plane& b) noexcept { return wedge(a, b); }
    constexpr Multivector Quaternion::wedge(const Plane& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr Multivector Quaternion::meet(const Plane& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr Motor wedge(const Quaternion& a,const Bivector& b) noexcept { return {
        .s = 0.0,
        .wx = a.s * b.wx,
        .wy = a.s * b.wy,
        .wz = a.s * b.wz,
        .xy = a.s * b.xy,
        .xz = a.s * b.xz,
        .yz = a.s * b.yz,
        .i = (a.xy * b.wz + a.yz * b.wx - a.xz * b.wy)
    }; }
    [[nodiscard]] constexpr Motor meet(const Quaternion& a,const Bivector& b) noexcept { return wedge(a, b); }
    constexpr Motor Quaternion::wedge(const Bivector& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr Motor Quaternion::meet(const Bivector& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr ProjectivePoint wedge(const Quaternion& a,const ProjectivePoint& b) noexcept { return {
        .x = a.s * b.x,
        .y = a.s * b.y,
        .z = a.s * b.z,
        .w = a.s * b.w
    }; }
    [[nodiscard]] constexpr ProjectivePoint meet(const Quaternion& a,const ProjectivePoint& b) noexcept { return wedge(a, b); }
    constexpr ProjectivePoint Quaternion::wedge(const ProjectivePoint& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr ProjectivePoint Quaternion::meet(const ProjectivePoint& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr Quaternion wedge(const Quaternion& a,const Quaternion& b) noexcept { return {
        .s = a.s * b.s,
        .xy = (a.s * b.xy + a.xy * b.s),
        .xz = (a.s * b.xz + a.xz * b.s),
        .yz = (a.s * b.yz + a.yz * b.s)
    }; }
    [[nodiscard]] constexpr Quaternion meet(const Quaternion& a,const Quaternion& b) noexcept { return wedge(a, b); }
    constexpr Quaternion Quaternion::wedge(const Quaternion& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr Quaternion Quaternion::meet(const Quaternion& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr Motor wedge(const Quaternion& a,const ProjectiveTranslator& b) noexcept { return {
        .s = a.s * b.s,
        .wx = a.s * b.wx,
        .wy = a.s * b.wy,
        .wz = a.s * b.wz,
        .xy = a.xy * b.s,
        .xz = a.xz * b.s,
        .yz = a.yz * b.s,
        .i = (a.xy * b.wz + a.yz * b.wx - a.xz * b.wy)
    }; }
    [[nodiscard]] constexpr Motor meet(const Quaternion& a,const ProjectiveTranslator& b) noexcept { return wedge(a, b); }
    constexpr Motor Quaternion::wedge(const ProjectiveTranslator& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr Motor Quaternion::meet(const ProjectiveTranslator& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr Motor wedge(const Quaternion& a,const Translator& b) noexcept { return {
        .s = a.s,
        .wx = a.s * b.wx,
        .wy = a.s * b.wy,
        .wz = a.s * b.wz,
        .xy = a.xy,
        .xz = a.xz,
        .yz = a.yz,
        .i = (a.xy * b.wz + a.yz * b.wx - a.xz * b.wy)
    }; }
    [[nodiscard]] constexpr Motor meet(const Quaternion& a,const Translator& b) noexcept { return wedge(a, b); }
    constexpr Motor Quaternion::wedge(const Translator& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr Motor Quaternion::meet(const Translator& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr Vector wedge(const Quaternion& a,const Vector& b) noexcept { return {
        .x = a.s * b.x,
        .y = a.s * b.y,
        .z = a.s * b.z
    }; }
    [[nodiscard]] constexpr Vector meet(const Quaternion& a,const Vector& b) noexcept { return wedge(a, b); }
    constexpr Vector Quaternion::wedge(const Vector& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr Vector Quaternion::meet(const Vector& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr ProjectivePoint wedge(const Quaternion& a,const Point& b) noexcept { return {
        .x = a.s * b.x,
        .y = a.s * b.y,
        .z = a.s * b.z,
        .w = a.s
    }; }
    [[nodiscard]] constexpr ProjectivePoint meet(const Quaternion& a,const Point& b) noexcept { return wedge(a, b); }
    constexpr ProjectivePoint Quaternion::wedge(const Point& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr ProjectivePoint Quaternion::meet(const Point& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr Multivector wedge(const Quaternion& a,const PlaneIdeal& b) noexcept { return {
        .s = 0.0,
        .w = 0.0,
        .x = a.s * b.x,
        .y = a.s * b.y,
        .z = a.s * b.z,
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .wxy = 0.0,
        .wxz = 0.0,
        .wyz = 0.0,
        .xyz = (a.xy * b.z + a.yz * b.x - a.xz * b.y),
        .i = 0.0
    }; }
    [[nodiscard]] constexpr Multivector meet(const Quaternion& a,const PlaneIdeal& b) noexcept { return wedge(a, b); }
    constexpr Multivector Quaternion::wedge(const PlaneIdeal& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr Multivector Quaternion::meet(const PlaneIdeal& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr BivectorBulk wedge(const Quaternion& a,const BivectorBulk& b) noexcept { return {
        .xy = a.s * b.xy,
        .xz = a.s * b.xz,
        .yz = a.s * b.yz
    }; }
    [[nodiscard]] constexpr BivectorBulk meet(const Quaternion& a,const BivectorBulk& b) noexcept { return wedge(a, b); }
    constexpr BivectorBulk Quaternion::wedge(const BivectorBulk& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr BivectorBulk Quaternion::meet(const BivectorBulk& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr Motor wedge(const Quaternion& a,const BivectorWeight& b) noexcept { return {
        .s = 0.0,
        .wx = a.s * b.wx,
        .wy = a.s * b.wy,
        .wz = a.s * b.wz,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .i = (a.xy * b.wz + a.yz * b.wx - a.xz * b.wy)
    }; }
    [[nodiscard]] constexpr Motor meet(const Quaternion& a,const BivectorWeight& b) noexcept { return wedge(a, b); }
    constexpr Motor Quaternion::wedge(const BivectorWeight& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr Motor Quaternion::meet(const BivectorWeight& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr PseudoScalar wedge(const Quaternion& a,const PseudoScalar& b) noexcept { return {
        .i = a.s * b.i
    }; }
    [[nodiscard]] constexpr PseudoScalar meet(const Quaternion& a,const PseudoScalar& b) noexcept { return wedge(a, b); }
    constexpr PseudoScalar Quaternion::wedge(const PseudoScalar& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr PseudoScalar Quaternion::meet(const PseudoScalar& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr ProjectivePoint wedge(const Quaternion& a,const PointCenter& b) noexcept { return {
        .x = 0.0,
        .y = 0.0,
        .z = 0.0,
        .w = a.s
    }; }
    [[nodiscard]] constexpr ProjectivePoint meet(const Quaternion& a,const PointCenter& b) noexcept { return wedge(a, b); }
    constexpr ProjectivePoint Quaternion::wedge(const PointCenter& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr ProjectivePoint Quaternion::meet(const PointCenter& b) const noexcept { return pga3d::wedge(*this, b); }


    [[nodiscard]] constexpr Motor wedge(const ProjectiveTranslator& a,const Motor& b) noexcept { return {
        .s = a.s * b.s,
        .wx = (a.s * b.wx + a.wx * b.s),
        .wy = (a.s * b.wy + a.wy * b.s),
        .wz = (a.s * b.wz + a.wz * b.s),
        .xy = a.s * b.xy,
        .xz = a.s * b.xz,
        .yz = a.s * b.yz,
        .i = (a.s * b.i + a.wx * b.yz + a.wz * b.xy - a.wy * b.xz)
    }; }
    [[nodiscard]] constexpr Motor meet(const ProjectiveTranslator& a,const Motor& b) noexcept { return wedge(a, b); }
    constexpr Motor ProjectiveTranslator::wedge(const Motor& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr Motor ProjectiveTranslator::meet(const Motor& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr Multivector wedge(const ProjectiveTranslator& a,const Plane& b) noexcept { return {
        .s = 0.0,
        .w = a.s * b.w,
        .x = a.s * b.x,
        .y = a.s * b.y,
        .z = a.s * b.z,
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .wxy = (a.wx * b.y - a.wy * b.x),
        .wxz = (a.wx * b.z - a.wz * b.x),
        .wyz = (a.wy * b.z - a.wz * b.y),
        .xyz = 0.0,
        .i = 0.0
    }; }
    [[nodiscard]] constexpr Multivector meet(const ProjectiveTranslator& a,const Plane& b) noexcept { return wedge(a, b); }
    constexpr Multivector ProjectiveTranslator::wedge(const Plane& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr Multivector ProjectiveTranslator::meet(const Plane& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr Motor wedge(const ProjectiveTranslator& a,const Bivector& b) noexcept { return {
        .s = 0.0,
        .wx = a.s * b.wx,
        .wy = a.s * b.wy,
        .wz = a.s * b.wz,
        .xy = a.s * b.xy,
        .xz = a.s * b.xz,
        .yz = a.s * b.yz,
        .i = (a.wx * b.yz + a.wz * b.xy - a.wy * b.xz)
    }; }
    [[nodiscard]] constexpr Motor meet(const ProjectiveTranslator& a,const Bivector& b) noexcept { return wedge(a, b); }
    constexpr Motor ProjectiveTranslator::wedge(const Bivector& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr Motor ProjectiveTranslator::meet(const Bivector& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr ProjectivePoint wedge(const ProjectiveTranslator& a,const ProjectivePoint& b) noexcept { return {
        .x = a.s * b.x,
        .y = a.s * b.y,
        .z = a.s * b.z,
        .w = a.s * b.w
    }; }
    [[nodiscard]] constexpr ProjectivePoint meet(const ProjectiveTranslator& a,const ProjectivePoint& b) noexcept { return wedge(a, b); }
    constexpr ProjectivePoint ProjectiveTranslator::wedge(const ProjectivePoint& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr ProjectivePoint ProjectiveTranslator::meet(const ProjectivePoint& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr Motor wedge(const ProjectiveTranslator& a,const Quaternion& b) noexcept { return {
        .s = a.s * b.s,
        .wx = a.wx * b.s,
        .wy = a.wy * b.s,
        .wz = a.wz * b.s,
        .xy = a.s * b.xy,
        .xz = a.s * b.xz,
        .yz = a.s * b.yz,
        .i = (a.wx * b.yz + a.wz * b.xy - a.wy * b.xz)
    }; }
    [[nodiscard]] constexpr Motor meet(const ProjectiveTranslator& a,const Quaternion& b) noexcept { return wedge(a, b); }
    constexpr Motor ProjectiveTranslator::wedge(const Quaternion& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr Motor ProjectiveTranslator::meet(const Quaternion& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr ProjectiveTranslator wedge(const ProjectiveTranslator& a,const ProjectiveTranslator& b) noexcept { return {
        .s = a.s * b.s,
        .wx = (a.s * b.wx + a.wx * b.s),
        .wy = (a.s * b.wy + a.wy * b.s),
        .wz = (a.s * b.wz + a.wz * b.s)
    }; }
    [[nodiscard]] constexpr ProjectiveTranslator meet(const ProjectiveTranslator& a,const ProjectiveTranslator& b) noexcept { return wedge(a, b); }
    constexpr ProjectiveTranslator ProjectiveTranslator::wedge(const ProjectiveTranslator& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr ProjectiveTranslator ProjectiveTranslator::meet(const ProjectiveTranslator& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr ProjectiveTranslator wedge(const ProjectiveTranslator& a,const Translator& b) noexcept { return {
        .s = a.s,
        .wx = (a.wx + a.s * b.wx),
        .wy = (a.wy + a.s * b.wy),
        .wz = (a.wz + a.s * b.wz)
    }; }
    [[nodiscard]] constexpr ProjectiveTranslator meet(const ProjectiveTranslator& a,const Translator& b) noexcept { return wedge(a, b); }
    constexpr ProjectiveTranslator ProjectiveTranslator::wedge(const Translator& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr ProjectiveTranslator ProjectiveTranslator::meet(const Translator& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr Vector wedge(const ProjectiveTranslator& a,const Vector& b) noexcept { return {
        .x = a.s * b.x,
        .y = a.s * b.y,
        .z = a.s * b.z
    }; }
    [[nodiscard]] constexpr Vector meet(const ProjectiveTranslator& a,const Vector& b) noexcept { return wedge(a, b); }
    constexpr Vector ProjectiveTranslator::wedge(const Vector& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr Vector ProjectiveTranslator::meet(const Vector& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr ProjectivePoint wedge(const ProjectiveTranslator& a,const Point& b) noexcept { return {
        .x = a.s * b.x,
        .y = a.s * b.y,
        .z = a.s * b.z,
        .w = a.s
    }; }
    [[nodiscard]] constexpr ProjectivePoint meet(const ProjectiveTranslator& a,const Point& b) noexcept { return wedge(a, b); }
    constexpr ProjectivePoint ProjectiveTranslator::wedge(const Point& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr ProjectivePoint ProjectiveTranslator::meet(const Point& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr Multivector wedge(const ProjectiveTranslator& a,const PlaneIdeal& b) noexcept { return {
        .s = 0.0,
        .w = 0.0,
        .x = a.s * b.x,
        .y = a.s * b.y,
        .z = a.s * b.z,
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .wxy = (a.wx * b.y - a.wy * b.x),
        .wxz = (a.wx * b.z - a.wz * b.x),
        .wyz = (a.wy * b.z - a.wz * b.y),
        .xyz = 0.0,
        .i = 0.0
    }; }
    [[nodiscard]] constexpr Multivector meet(const ProjectiveTranslator& a,const PlaneIdeal& b) noexcept { return wedge(a, b); }
    constexpr Multivector ProjectiveTranslator::wedge(const PlaneIdeal& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr Multivector ProjectiveTranslator::meet(const PlaneIdeal& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr Motor wedge(const ProjectiveTranslator& a,const BivectorBulk& b) noexcept { return {
        .s = 0.0,
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = a.s * b.xy,
        .xz = a.s * b.xz,
        .yz = a.s * b.yz,
        .i = (a.wx * b.yz + a.wz * b.xy - a.wy * b.xz)
    }; }
    [[nodiscard]] constexpr Motor meet(const ProjectiveTranslator& a,const BivectorBulk& b) noexcept { return wedge(a, b); }
    constexpr Motor ProjectiveTranslator::wedge(const BivectorBulk& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr Motor ProjectiveTranslator::meet(const BivectorBulk& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr BivectorWeight wedge(const ProjectiveTranslator& a,const BivectorWeight& b) noexcept { return {
        .wx = a.s * b.wx,
        .wy = a.s * b.wy,
        .wz = a.s * b.wz
    }; }
    [[nodiscard]] constexpr BivectorWeight meet(const ProjectiveTranslator& a,const BivectorWeight& b) noexcept { return wedge(a, b); }
    constexpr BivectorWeight ProjectiveTranslator::wedge(const BivectorWeight& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr BivectorWeight ProjectiveTranslator::meet(const BivectorWeight& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr PseudoScalar wedge(const ProjectiveTranslator& a,const PseudoScalar& b) noexcept { return {
        .i = a.s * b.i
    }; }
    [[nodiscard]] constexpr PseudoScalar meet(const ProjectiveTranslator& a,const PseudoScalar& b) noexcept { return wedge(a, b); }
    constexpr PseudoScalar ProjectiveTranslator::wedge(const PseudoScalar& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr PseudoScalar ProjectiveTranslator::meet(const PseudoScalar& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr ProjectivePoint wedge(const ProjectiveTranslator& a,const PointCenter& b) noexcept { return {
        .x = 0.0,
        .y = 0.0,
        .z = 0.0,
        .w = a.s
    }; }
    [[nodiscard]] constexpr ProjectivePoint meet(const ProjectiveTranslator& a,const PointCenter& b) noexcept { return wedge(a, b); }
    constexpr ProjectivePoint ProjectiveTranslator::wedge(const PointCenter& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr ProjectivePoint ProjectiveTranslator::meet(const PointCenter& b) const noexcept { return pga3d::wedge(*this, b); }


    [[nodiscard]] constexpr Motor wedge(const Translator& a,const Motor& b) noexcept { return {
        .s = b.s,
        .wx = (b.wx + a.wx * b.s),
        .wy = (b.wy + a.wy * b.s),
        .wz = (b.wz + a.wz * b.s),
        .xy = b.xy,
        .xz = b.xz,
        .yz = b.yz,
        .i = (b.i + a.wx * b.yz + a.wz * b.xy - a.wy * b.xz)
    }; }
    [[nodiscard]] constexpr Motor meet(const Translator& a,const Motor& b) noexcept { return wedge(a, b); }
    constexpr Motor Translator::wedge(const Motor& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr Motor Translator::meet(const Motor& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr Multivector wedge(const Translator& a,const Plane& b) noexcept { return {
        .s = 0.0,
        .w = b.w,
        .x = b.x,
        .y = b.y,
        .z = b.z,
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .wxy = (a.wx * b.y - a.wy * b.x),
        .wxz = (a.wx * b.z - a.wz * b.x),
        .wyz = (a.wy * b.z - a.wz * b.y),
        .xyz = 0.0,
        .i = 0.0
    }; }
    [[nodiscard]] constexpr Multivector meet(const Translator& a,const Plane& b) noexcept { return wedge(a, b); }
    constexpr Multivector Translator::wedge(const Plane& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr Multivector Translator::meet(const Plane& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr Motor wedge(const Translator& a,const Bivector& b) noexcept { return {
        .s = 0.0,
        .wx = b.wx,
        .wy = b.wy,
        .wz = b.wz,
        .xy = b.xy,
        .xz = b.xz,
        .yz = b.yz,
        .i = (a.wx * b.yz + a.wz * b.xy - a.wy * b.xz)
    }; }
    [[nodiscard]] constexpr Motor meet(const Translator& a,const Bivector& b) noexcept { return wedge(a, b); }
    constexpr Motor Translator::wedge(const Bivector& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr Motor Translator::meet(const Bivector& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr ProjectivePoint wedge(const Translator& a,const ProjectivePoint& b) noexcept { return {
        .x = b.x,
        .y = b.y,
        .z = b.z,
        .w = b.w
    }; }
    [[nodiscard]] constexpr ProjectivePoint meet(const Translator& a,const ProjectivePoint& b) noexcept { return wedge(a, b); }
    constexpr ProjectivePoint Translator::wedge(const ProjectivePoint& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr ProjectivePoint Translator::meet(const ProjectivePoint& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr Motor wedge(const Translator& a,const Quaternion& b) noexcept { return {
        .s = b.s,
        .wx = a.wx * b.s,
        .wy = a.wy * b.s,
        .wz = a.wz * b.s,
        .xy = b.xy,
        .xz = b.xz,
        .yz = b.yz,
        .i = (a.wx * b.yz + a.wz * b.xy - a.wy * b.xz)
    }; }
    [[nodiscard]] constexpr Motor meet(const Translator& a,const Quaternion& b) noexcept { return wedge(a, b); }
    constexpr Motor Translator::wedge(const Quaternion& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr Motor Translator::meet(const Quaternion& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr ProjectiveTranslator wedge(const Translator& a,const ProjectiveTranslator& b) noexcept { return {
        .s = b.s,
        .wx = (b.wx + a.wx * b.s),
        .wy = (b.wy + a.wy * b.s),
        .wz = (b.wz + a.wz * b.s)
    }; }
    [[nodiscard]] constexpr ProjectiveTranslator meet(const Translator& a,const ProjectiveTranslator& b) noexcept { return wedge(a, b); }
    constexpr ProjectiveTranslator Translator::wedge(const ProjectiveTranslator& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr ProjectiveTranslator Translator::meet(const ProjectiveTranslator& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr Translator wedge(const Translator& a,const Translator& b) noexcept { return {
        .wx = (a.wx + b.wx),
        .wy = (a.wy + b.wy),
        .wz = (a.wz + b.wz)
    }; }
    [[nodiscard]] constexpr Translator meet(const Translator& a,const Translator& b) noexcept { return wedge(a, b); }
    constexpr Translator Translator::wedge(const Translator& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr Translator Translator::meet(const Translator& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr Vector wedge(const Translator& a,const Vector& b) noexcept { return {
        .x = b.x,
        .y = b.y,
        .z = b.z
    }; }
    [[nodiscard]] constexpr Vector meet(const Translator& a,const Vector& b) noexcept { return wedge(a, b); }
    constexpr Vector Translator::wedge(const Vector& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr Vector Translator::meet(const Vector& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr Point wedge(const Translator& a,const Point& b) noexcept { return {
        .x = b.x,
        .y = b.y,
        .z = b.z
    }; }
    [[nodiscard]] constexpr Point meet(const Translator& a,const Point& b) noexcept { return wedge(a, b); }
    constexpr Point Translator::wedge(const Point& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr Point Translator::meet(const Point& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr Multivector wedge(const Translator& a,const PlaneIdeal& b) noexcept { return {
        .s = 0.0,
        .w = 0.0,
        .x = b.x,
        .y = b.y,
        .z = b.z,
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .wxy = (a.wx * b.y - a.wy * b.x),
        .wxz = (a.wx * b.z - a.wz * b.x),
        .wyz = (a.wy * b.z - a.wz * b.y),
        .xyz = 0.0,
        .i = 0.0
    }; }
    [[nodiscard]] constexpr Multivector meet(const Translator& a,const PlaneIdeal& b) noexcept { return wedge(a, b); }
    constexpr Multivector Translator::wedge(const PlaneIdeal& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr Multivector Translator::meet(const PlaneIdeal& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr Motor wedge(const Translator& a,const BivectorBulk& b) noexcept { return {
        .s = 0.0,
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = b.xy,
        .xz = b.xz,
        .yz = b.yz,
        .i = (a.wx * b.yz + a.wz * b.xy - a.wy * b.xz)
    }; }
    [[nodiscard]] constexpr Motor meet(const Translator& a,const BivectorBulk& b) noexcept { return wedge(a, b); }
    constexpr Motor Translator::wedge(const BivectorBulk& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr Motor Translator::meet(const BivectorBulk& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr BivectorWeight wedge(const Translator& a,const BivectorWeight& b) noexcept { return {
        .wx = b.wx,
        .wy = b.wy,
        .wz = b.wz
    }; }
    [[nodiscard]] constexpr BivectorWeight meet(const Translator& a,const BivectorWeight& b) noexcept { return wedge(a, b); }
    constexpr BivectorWeight Translator::wedge(const BivectorWeight& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr BivectorWeight Translator::meet(const BivectorWeight& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr PseudoScalar wedge(const Translator& a,const PseudoScalar& b) noexcept { return {
        .i = b.i
    }; }
    [[nodiscard]] constexpr PseudoScalar meet(const Translator& a,const PseudoScalar& b) noexcept { return wedge(a, b); }
    constexpr PseudoScalar Translator::wedge(const PseudoScalar& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr PseudoScalar Translator::meet(const PseudoScalar& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr PointCenter wedge(const Translator& a,const PointCenter& b) noexcept { return {}; }
    [[nodiscard]] constexpr PointCenter meet(const Translator& a,const PointCenter& b) noexcept { return wedge(a, b); }
    constexpr PointCenter Translator::wedge(const PointCenter& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr PointCenter Translator::meet(const PointCenter& b) const noexcept { return pga3d::wedge(*this, b); }


    [[nodiscard]] constexpr Vector wedge(const Vector& a,const Motor& b) noexcept { return {
        .x = a.x * b.s,
        .y = a.y * b.s,
        .z = a.z * b.s
    }; }
    [[nodiscard]] constexpr Vector meet(const Vector& a,const Motor& b) noexcept { return wedge(a, b); }
    constexpr Vector Vector::wedge(const Motor& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr Vector Vector::meet(const Motor& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr PseudoScalar wedge(const Vector& a,const Plane& b) noexcept { return {
        .i = (-a.x * b.x - a.y * b.y - a.z * b.z)
    }; }
    [[nodiscard]] constexpr PseudoScalar meet(const Vector& a,const Plane& b) noexcept { return wedge(a, b); }
    constexpr PseudoScalar Vector::wedge(const Plane& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr PseudoScalar Vector::meet(const Plane& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr Vector wedge(const Vector& a,const Quaternion& b) noexcept { return {
        .x = a.x * b.s,
        .y = a.y * b.s,
        .z = a.z * b.s
    }; }
    [[nodiscard]] constexpr Vector meet(const Vector& a,const Quaternion& b) noexcept { return wedge(a, b); }
    constexpr Vector Vector::wedge(const Quaternion& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr Vector Vector::meet(const Quaternion& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr Vector wedge(const Vector& a,const ProjectiveTranslator& b) noexcept { return {
        .x = a.x * b.s,
        .y = a.y * b.s,
        .z = a.z * b.s
    }; }
    [[nodiscard]] constexpr Vector meet(const Vector& a,const ProjectiveTranslator& b) noexcept { return wedge(a, b); }
    constexpr Vector Vector::wedge(const ProjectiveTranslator& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr Vector Vector::meet(const ProjectiveTranslator& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr Vector wedge(const Vector& a,const Translator& b) noexcept { return {
        .x = a.x,
        .y = a.y,
        .z = a.z
    }; }
    [[nodiscard]] constexpr Vector meet(const Vector& a,const Translator& b) noexcept { return wedge(a, b); }
    constexpr Vector Vector::wedge(const Translator& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr Vector Vector::meet(const Translator& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr PseudoScalar wedge(const Vector& a,const PlaneIdeal& b) noexcept { return {
        .i = (-a.x * b.x - a.y * b.y - a.z * b.z)
    }; }
    [[nodiscard]] constexpr PseudoScalar meet(const Vector& a,const PlaneIdeal& b) noexcept { return wedge(a, b); }
    constexpr PseudoScalar Vector::wedge(const PlaneIdeal& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr PseudoScalar Vector::meet(const PlaneIdeal& b) const noexcept { return pga3d::wedge(*this, b); }


    [[nodiscard]] constexpr ProjectivePoint wedge(const Point& a,const Motor& b) noexcept { return {
        .x = a.x * b.s,
        .y = a.y * b.s,
        .z = a.z * b.s,
        .w = b.s
    }; }
    [[nodiscard]] constexpr ProjectivePoint meet(const Point& a,const Motor& b) noexcept { return wedge(a, b); }
    constexpr ProjectivePoint Point::wedge(const Motor& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr ProjectivePoint Point::meet(const Motor& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr PseudoScalar wedge(const Point& a,const Plane& b) noexcept { return {
        .i = (-b.w - a.x * b.x - a.y * b.y - a.z * b.z)
    }; }
    [[nodiscard]] constexpr PseudoScalar meet(const Point& a,const Plane& b) noexcept { return wedge(a, b); }
    constexpr PseudoScalar Point::wedge(const Plane& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr PseudoScalar Point::meet(const Plane& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr ProjectivePoint wedge(const Point& a,const Quaternion& b) noexcept { return {
        .x = a.x * b.s,
        .y = a.y * b.s,
        .z = a.z * b.s,
        .w = b.s
    }; }
    [[nodiscard]] constexpr ProjectivePoint meet(const Point& a,const Quaternion& b) noexcept { return wedge(a, b); }
    constexpr ProjectivePoint Point::wedge(const Quaternion& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr ProjectivePoint Point::meet(const Quaternion& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr ProjectivePoint wedge(const Point& a,const ProjectiveTranslator& b) noexcept { return {
        .x = a.x * b.s,
        .y = a.y * b.s,
        .z = a.z * b.s,
        .w = b.s
    }; }
    [[nodiscard]] constexpr ProjectivePoint meet(const Point& a,const ProjectiveTranslator& b) noexcept { return wedge(a, b); }
    constexpr ProjectivePoint Point::wedge(const ProjectiveTranslator& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr ProjectivePoint Point::meet(const ProjectiveTranslator& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr Point wedge(const Point& a,const Translator& b) noexcept { return {
        .x = a.x,
        .y = a.y,
        .z = a.z
    }; }
    [[nodiscard]] constexpr Point meet(const Point& a,const Translator& b) noexcept { return wedge(a, b); }
    constexpr Point Point::wedge(const Translator& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr Point Point::meet(const Translator& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr PseudoScalar wedge(const Point& a,const PlaneIdeal& b) noexcept { return {
        .i = (-a.x * b.x - a.y * b.y - a.z * b.z)
    }; }
    [[nodiscard]] constexpr PseudoScalar meet(const Point& a,const PlaneIdeal& b) noexcept { return wedge(a, b); }
    constexpr PseudoScalar Point::wedge(const PlaneIdeal& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr PseudoScalar Point::meet(const PlaneIdeal& b) const noexcept { return pga3d::wedge(*this, b); }


    [[nodiscard]] constexpr Multivector wedge(const PlaneIdeal& a,const Motor& b) noexcept { return {
        .s = 0.0,
        .w = 0.0,
        .x = a.x * b.s,
        .y = a.y * b.s,
        .z = a.z * b.s,
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .wxy = (a.y * b.wx - a.x * b.wy),
        .wxz = (a.z * b.wx - a.x * b.wz),
        .wyz = (a.z * b.wy - a.y * b.wz),
        .xyz = (a.x * b.yz + a.z * b.xy - a.y * b.xz),
        .i = 0.0
    }; }
    [[nodiscard]] constexpr Multivector meet(const PlaneIdeal& a,const Motor& b) noexcept { return wedge(a, b); }
    constexpr Multivector PlaneIdeal::wedge(const Motor& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr Multivector PlaneIdeal::meet(const Motor& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr Bivector wedge(const PlaneIdeal& a,const Plane& b) noexcept { return {
        .wx = -a.x * b.w,
        .wy = -a.y * b.w,
        .wz = -a.z * b.w,
        .xy = (a.x * b.y - a.y * b.x),
        .xz = (a.x * b.z - a.z * b.x),
        .yz = (a.y * b.z - a.z * b.y)
    }; }
    [[nodiscard]] constexpr Bivector meet(const PlaneIdeal& a,const Plane& b) noexcept { return wedge(a, b); }
    constexpr Bivector PlaneIdeal::wedge(const Plane& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr Bivector PlaneIdeal::meet(const Plane& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr ProjectivePoint wedge(const PlaneIdeal& a,const Bivector& b) noexcept { return {
        .x = (a.y * b.wz - a.z * b.wy),
        .y = (a.z * b.wx - a.x * b.wz),
        .z = (a.x * b.wy - a.y * b.wx),
        .w = (a.x * b.yz + a.z * b.xy - a.y * b.xz)
    }; }
    [[nodiscard]] constexpr ProjectivePoint meet(const PlaneIdeal& a,const Bivector& b) noexcept { return wedge(a, b); }
    constexpr ProjectivePoint PlaneIdeal::wedge(const Bivector& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr ProjectivePoint PlaneIdeal::meet(const Bivector& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr PseudoScalar wedge(const PlaneIdeal& a,const ProjectivePoint& b) noexcept { return {
        .i = (a.x * b.x + a.y * b.y + a.z * b.z)
    }; }
    [[nodiscard]] constexpr PseudoScalar meet(const PlaneIdeal& a,const ProjectivePoint& b) noexcept { return wedge(a, b); }
    constexpr PseudoScalar PlaneIdeal::wedge(const ProjectivePoint& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr PseudoScalar PlaneIdeal::meet(const ProjectivePoint& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr Multivector wedge(const PlaneIdeal& a,const Quaternion& b) noexcept { return {
        .s = 0.0,
        .w = 0.0,
        .x = a.x * b.s,
        .y = a.y * b.s,
        .z = a.z * b.s,
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .wxy = 0.0,
        .wxz = 0.0,
        .wyz = 0.0,
        .xyz = (a.x * b.yz + a.z * b.xy - a.y * b.xz),
        .i = 0.0
    }; }
    [[nodiscard]] constexpr Multivector meet(const PlaneIdeal& a,const Quaternion& b) noexcept { return wedge(a, b); }
    constexpr Multivector PlaneIdeal::wedge(const Quaternion& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr Multivector PlaneIdeal::meet(const Quaternion& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr Multivector wedge(const PlaneIdeal& a,const ProjectiveTranslator& b) noexcept { return {
        .s = 0.0,
        .w = 0.0,
        .x = a.x * b.s,
        .y = a.y * b.s,
        .z = a.z * b.s,
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .wxy = (a.y * b.wx - a.x * b.wy),
        .wxz = (a.z * b.wx - a.x * b.wz),
        .wyz = (a.z * b.wy - a.y * b.wz),
        .xyz = 0.0,
        .i = 0.0
    }; }
    [[nodiscard]] constexpr Multivector meet(const PlaneIdeal& a,const ProjectiveTranslator& b) noexcept { return wedge(a, b); }
    constexpr Multivector PlaneIdeal::wedge(const ProjectiveTranslator& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr Multivector PlaneIdeal::meet(const ProjectiveTranslator& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr Multivector wedge(const PlaneIdeal& a,const Translator& b) noexcept { return {
        .s = 0.0,
        .w = 0.0,
        .x = a.x,
        .y = a.y,
        .z = a.z,
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .wxy = (a.y * b.wx - a.x * b.wy),
        .wxz = (a.z * b.wx - a.x * b.wz),
        .wyz = (a.z * b.wy - a.y * b.wz),
        .xyz = 0.0,
        .i = 0.0
    }; }
    [[nodiscard]] constexpr Multivector meet(const PlaneIdeal& a,const Translator& b) noexcept { return wedge(a, b); }
    constexpr Multivector PlaneIdeal::wedge(const Translator& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr Multivector PlaneIdeal::meet(const Translator& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr PseudoScalar wedge(const PlaneIdeal& a,const Vector& b) noexcept { return {
        .i = (a.x * b.x + a.y * b.y + a.z * b.z)
    }; }
    [[nodiscard]] constexpr PseudoScalar meet(const PlaneIdeal& a,const Vector& b) noexcept { return wedge(a, b); }
    constexpr PseudoScalar PlaneIdeal::wedge(const Vector& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr PseudoScalar PlaneIdeal::meet(const Vector& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr PseudoScalar wedge(const PlaneIdeal& a,const Point& b) noexcept { return {
        .i = (a.x * b.x + a.y * b.y + a.z * b.z)
    }; }
    [[nodiscard]] constexpr PseudoScalar meet(const PlaneIdeal& a,const Point& b) noexcept { return wedge(a, b); }
    constexpr PseudoScalar PlaneIdeal::wedge(const Point& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr PseudoScalar PlaneIdeal::meet(const Point& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr BivectorBulk wedge(const PlaneIdeal& a,const PlaneIdeal& b) noexcept { return {
        .xy = (a.x * b.y - a.y * b.x),
        .xz = (a.x * b.z - a.z * b.x),
        .yz = (a.y * b.z - a.z * b.y)
    }; }
    [[nodiscard]] constexpr BivectorBulk meet(const PlaneIdeal& a,const PlaneIdeal& b) noexcept { return wedge(a, b); }
    constexpr BivectorBulk PlaneIdeal::wedge(const PlaneIdeal& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr BivectorBulk PlaneIdeal::meet(const PlaneIdeal& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr ProjectivePoint wedge(const PlaneIdeal& a,const BivectorBulk& b) noexcept { return {
        .x = 0.0,
        .y = 0.0,
        .z = 0.0,
        .w = (a.x * b.yz + a.z * b.xy - a.y * b.xz)
    }; }
    [[nodiscard]] constexpr ProjectivePoint meet(const PlaneIdeal& a,const BivectorBulk& b) noexcept { return wedge(a, b); }
    constexpr ProjectivePoint PlaneIdeal::wedge(const BivectorBulk& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr ProjectivePoint PlaneIdeal::meet(const BivectorBulk& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr Vector wedge(const PlaneIdeal& a,const BivectorWeight& b) noexcept { return {
        .x = (a.y * b.wz - a.z * b.wy),
        .y = (a.z * b.wx - a.x * b.wz),
        .z = (a.x * b.wy - a.y * b.wx)
    }; }
    [[nodiscard]] constexpr Vector meet(const PlaneIdeal& a,const BivectorWeight& b) noexcept { return wedge(a, b); }
    constexpr Vector PlaneIdeal::wedge(const BivectorWeight& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr Vector PlaneIdeal::meet(const BivectorWeight& b) const noexcept { return pga3d::wedge(*this, b); }


    [[nodiscard]] constexpr Motor wedge(const BivectorBulk& a,const Motor& b) noexcept { return {
        .s = 0.0,
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = a.xy * b.s,
        .xz = a.xz * b.s,
        .yz = a.yz * b.s,
        .i = (a.xy * b.wz + a.yz * b.wx - a.xz * b.wy)
    }; }
    [[nodiscard]] constexpr Motor meet(const BivectorBulk& a,const Motor& b) noexcept { return wedge(a, b); }
    constexpr Motor BivectorBulk::wedge(const Motor& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr Motor BivectorBulk::meet(const Motor& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr ProjectivePoint wedge(const BivectorBulk& a,const Plane& b) noexcept { return {
        .x = -a.yz * b.w,
        .y = a.xz * b.w,
        .z = -a.xy * b.w,
        .w = (a.xy * b.z + a.yz * b.x - a.xz * b.y)
    }; }
    [[nodiscard]] constexpr ProjectivePoint meet(const BivectorBulk& a,const Plane& b) noexcept { return wedge(a, b); }
    constexpr ProjectivePoint BivectorBulk::wedge(const Plane& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr ProjectivePoint BivectorBulk::meet(const Plane& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr PseudoScalar wedge(const BivectorBulk& a,const Bivector& b) noexcept { return {
        .i = (a.xy * b.wz + a.yz * b.wx - a.xz * b.wy)
    }; }
    [[nodiscard]] constexpr PseudoScalar meet(const BivectorBulk& a,const Bivector& b) noexcept { return wedge(a, b); }
    constexpr PseudoScalar BivectorBulk::wedge(const Bivector& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr PseudoScalar BivectorBulk::meet(const Bivector& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr BivectorBulk wedge(const BivectorBulk& a,const Quaternion& b) noexcept { return {
        .xy = a.xy * b.s,
        .xz = a.xz * b.s,
        .yz = a.yz * b.s
    }; }
    [[nodiscard]] constexpr BivectorBulk meet(const BivectorBulk& a,const Quaternion& b) noexcept { return wedge(a, b); }
    constexpr BivectorBulk BivectorBulk::wedge(const Quaternion& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr BivectorBulk BivectorBulk::meet(const Quaternion& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr Motor wedge(const BivectorBulk& a,const ProjectiveTranslator& b) noexcept { return {
        .s = 0.0,
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = a.xy * b.s,
        .xz = a.xz * b.s,
        .yz = a.yz * b.s,
        .i = (a.xy * b.wz + a.yz * b.wx - a.xz * b.wy)
    }; }
    [[nodiscard]] constexpr Motor meet(const BivectorBulk& a,const ProjectiveTranslator& b) noexcept { return wedge(a, b); }
    constexpr Motor BivectorBulk::wedge(const ProjectiveTranslator& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr Motor BivectorBulk::meet(const ProjectiveTranslator& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr Motor wedge(const BivectorBulk& a,const Translator& b) noexcept { return {
        .s = 0.0,
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = a.xy,
        .xz = a.xz,
        .yz = a.yz,
        .i = (a.xy * b.wz + a.yz * b.wx - a.xz * b.wy)
    }; }
    [[nodiscard]] constexpr Motor meet(const BivectorBulk& a,const Translator& b) noexcept { return wedge(a, b); }
    constexpr Motor BivectorBulk::wedge(const Translator& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr Motor BivectorBulk::meet(const Translator& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr ProjectivePoint wedge(const BivectorBulk& a,const PlaneIdeal& b) noexcept { return {
        .x = 0.0,
        .y = 0.0,
        .z = 0.0,
        .w = (a.xy * b.z + a.yz * b.x - a.xz * b.y)
    }; }
    [[nodiscard]] constexpr ProjectivePoint meet(const BivectorBulk& a,const PlaneIdeal& b) noexcept { return wedge(a, b); }
    constexpr ProjectivePoint BivectorBulk::wedge(const PlaneIdeal& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr ProjectivePoint BivectorBulk::meet(const PlaneIdeal& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr PseudoScalar wedge(const BivectorBulk& a,const BivectorWeight& b) noexcept { return {
        .i = (a.xy * b.wz + a.yz * b.wx - a.xz * b.wy)
    }; }
    [[nodiscard]] constexpr PseudoScalar meet(const BivectorBulk& a,const BivectorWeight& b) noexcept { return wedge(a, b); }
    constexpr PseudoScalar BivectorBulk::wedge(const BivectorWeight& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr PseudoScalar BivectorBulk::meet(const BivectorWeight& b) const noexcept { return pga3d::wedge(*this, b); }


    [[nodiscard]] constexpr Motor wedge(const BivectorWeight& a,const Motor& b) noexcept { return {
        .s = 0.0,
        .wx = a.wx * b.s,
        .wy = a.wy * b.s,
        .wz = a.wz * b.s,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .i = (a.wx * b.yz + a.wz * b.xy - a.wy * b.xz)
    }; }
    [[nodiscard]] constexpr Motor meet(const BivectorWeight& a,const Motor& b) noexcept { return wedge(a, b); }
    constexpr Motor BivectorWeight::wedge(const Motor& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr Motor BivectorWeight::meet(const Motor& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr Vector wedge(const BivectorWeight& a,const Plane& b) noexcept { return {
        .x = (a.wz * b.y - a.wy * b.z),
        .y = (a.wx * b.z - a.wz * b.x),
        .z = (a.wy * b.x - a.wx * b.y)
    }; }
    [[nodiscard]] constexpr Vector meet(const BivectorWeight& a,const Plane& b) noexcept { return wedge(a, b); }
    constexpr Vector BivectorWeight::wedge(const Plane& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr Vector BivectorWeight::meet(const Plane& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr PseudoScalar wedge(const BivectorWeight& a,const Bivector& b) noexcept { return {
        .i = (a.wx * b.yz + a.wz * b.xy - a.wy * b.xz)
    }; }
    [[nodiscard]] constexpr PseudoScalar meet(const BivectorWeight& a,const Bivector& b) noexcept { return wedge(a, b); }
    constexpr PseudoScalar BivectorWeight::wedge(const Bivector& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr PseudoScalar BivectorWeight::meet(const Bivector& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr Motor wedge(const BivectorWeight& a,const Quaternion& b) noexcept { return {
        .s = 0.0,
        .wx = a.wx * b.s,
        .wy = a.wy * b.s,
        .wz = a.wz * b.s,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .i = (a.wx * b.yz + a.wz * b.xy - a.wy * b.xz)
    }; }
    [[nodiscard]] constexpr Motor meet(const BivectorWeight& a,const Quaternion& b) noexcept { return wedge(a, b); }
    constexpr Motor BivectorWeight::wedge(const Quaternion& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr Motor BivectorWeight::meet(const Quaternion& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr BivectorWeight wedge(const BivectorWeight& a,const ProjectiveTranslator& b) noexcept { return {
        .wx = a.wx * b.s,
        .wy = a.wy * b.s,
        .wz = a.wz * b.s
    }; }
    [[nodiscard]] constexpr BivectorWeight meet(const BivectorWeight& a,const ProjectiveTranslator& b) noexcept { return wedge(a, b); }
    constexpr BivectorWeight BivectorWeight::wedge(const ProjectiveTranslator& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr BivectorWeight BivectorWeight::meet(const ProjectiveTranslator& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr BivectorWeight wedge(const BivectorWeight& a,const Translator& b) noexcept { return {
        .wx = a.wx,
        .wy = a.wy,
        .wz = a.wz
    }; }
    [[nodiscard]] constexpr BivectorWeight meet(const BivectorWeight& a,const Translator& b) noexcept { return wedge(a, b); }
    constexpr BivectorWeight BivectorWeight::wedge(const Translator& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr BivectorWeight BivectorWeight::meet(const Translator& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr Vector wedge(const BivectorWeight& a,const PlaneIdeal& b) noexcept { return {
        .x = (a.wz * b.y - a.wy * b.z),
        .y = (a.wx * b.z - a.wz * b.x),
        .z = (a.wy * b.x - a.wx * b.y)
    }; }
    [[nodiscard]] constexpr Vector meet(const BivectorWeight& a,const PlaneIdeal& b) noexcept { return wedge(a, b); }
    constexpr Vector BivectorWeight::wedge(const PlaneIdeal& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr Vector BivectorWeight::meet(const PlaneIdeal& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr PseudoScalar wedge(const BivectorWeight& a,const BivectorBulk& b) noexcept { return {
        .i = (a.wx * b.yz + a.wz * b.xy - a.wy * b.xz)
    }; }
    [[nodiscard]] constexpr PseudoScalar meet(const BivectorWeight& a,const BivectorBulk& b) noexcept { return wedge(a, b); }
    constexpr PseudoScalar BivectorWeight::wedge(const BivectorBulk& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr PseudoScalar BivectorWeight::meet(const BivectorBulk& b) const noexcept { return pga3d::wedge(*this, b); }


    [[nodiscard]] constexpr PseudoScalar wedge(const PseudoScalar& a,const Motor& b) noexcept { return {
        .i = a.i * b.s
    }; }
    [[nodiscard]] constexpr PseudoScalar meet(const PseudoScalar& a,const Motor& b) noexcept { return wedge(a, b); }
    constexpr PseudoScalar PseudoScalar::wedge(const Motor& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr PseudoScalar PseudoScalar::meet(const Motor& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr PseudoScalar wedge(const PseudoScalar& a,const Quaternion& b) noexcept { return {
        .i = a.i * b.s
    }; }
    [[nodiscard]] constexpr PseudoScalar meet(const PseudoScalar& a,const Quaternion& b) noexcept { return wedge(a, b); }
    constexpr PseudoScalar PseudoScalar::wedge(const Quaternion& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr PseudoScalar PseudoScalar::meet(const Quaternion& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr PseudoScalar wedge(const PseudoScalar& a,const ProjectiveTranslator& b) noexcept { return {
        .i = a.i * b.s
    }; }
    [[nodiscard]] constexpr PseudoScalar meet(const PseudoScalar& a,const ProjectiveTranslator& b) noexcept { return wedge(a, b); }
    constexpr PseudoScalar PseudoScalar::wedge(const ProjectiveTranslator& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr PseudoScalar PseudoScalar::meet(const ProjectiveTranslator& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr PseudoScalar wedge(const PseudoScalar& a,const Translator& b) noexcept { return {
        .i = a.i
    }; }
    [[nodiscard]] constexpr PseudoScalar meet(const PseudoScalar& a,const Translator& b) noexcept { return wedge(a, b); }
    constexpr PseudoScalar PseudoScalar::wedge(const Translator& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr PseudoScalar PseudoScalar::meet(const Translator& b) const noexcept { return pga3d::wedge(*this, b); }


    [[nodiscard]] constexpr ProjectivePoint wedge(const PointCenter& a,const Motor& b) noexcept { return {
        .x = 0.0,
        .y = 0.0,
        .z = 0.0,
        .w = b.s
    }; }
    [[nodiscard]] constexpr ProjectivePoint meet(const PointCenter& a,const Motor& b) noexcept { return wedge(a, b); }
    constexpr ProjectivePoint PointCenter::wedge(const Motor& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr ProjectivePoint PointCenter::meet(const Motor& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr PseudoScalar wedge(const PointCenter& a,const Plane& b) noexcept { return {
        .i = -b.w
    }; }
    [[nodiscard]] constexpr PseudoScalar meet(const PointCenter& a,const Plane& b) noexcept { return wedge(a, b); }
    constexpr PseudoScalar PointCenter::wedge(const Plane& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr PseudoScalar PointCenter::meet(const Plane& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr ProjectivePoint wedge(const PointCenter& a,const Quaternion& b) noexcept { return {
        .x = 0.0,
        .y = 0.0,
        .z = 0.0,
        .w = b.s
    }; }
    [[nodiscard]] constexpr ProjectivePoint meet(const PointCenter& a,const Quaternion& b) noexcept { return wedge(a, b); }
    constexpr ProjectivePoint PointCenter::wedge(const Quaternion& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr ProjectivePoint PointCenter::meet(const Quaternion& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr ProjectivePoint wedge(const PointCenter& a,const ProjectiveTranslator& b) noexcept { return {
        .x = 0.0,
        .y = 0.0,
        .z = 0.0,
        .w = b.s
    }; }
    [[nodiscard]] constexpr ProjectivePoint meet(const PointCenter& a,const ProjectiveTranslator& b) noexcept { return wedge(a, b); }
    constexpr ProjectivePoint PointCenter::wedge(const ProjectiveTranslator& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr ProjectivePoint PointCenter::meet(const ProjectiveTranslator& b) const noexcept { return pga3d::wedge(*this, b); }

    [[nodiscard]] constexpr PointCenter wedge(const PointCenter& a,const Translator& b) noexcept { return {}; }
    [[nodiscard]] constexpr PointCenter meet(const PointCenter& a,const Translator& b) noexcept { return wedge(a, b); }
    constexpr PointCenter PointCenter::wedge(const Translator& b) const noexcept { return pga3d::wedge(*this, b); }
    constexpr PointCenter PointCenter::meet(const Translator& b) const noexcept { return pga3d::wedge(*this, b); }


}