// Copyright (c) 2025 Igor Slobodskov
// SPDX-License-Identifier: MIT

#pragma once

#include "Motor.h"
#include "Rotor.h"
#include "Translator.h"

// generated by me.kright.gametools.pga.codegen.cpp3d.ops.TranslatorWithRotorGenerator

namespace pga3d {

    struct TranslatorWithRotor {
        Translator translator{};
        Rotor rotor{};

        static size_t constexpr componentsCount = Rotor::componentsCount + Translator::componentsCount;

        [[nodiscard]] constexpr std::array<double, componentsCount> toArray() const noexcept {
            // a compiler will optimize this
            return { translator.toArray()[0], translator.toArray()[1], translator.toArray()[2], rotor.toArray()[0], rotor.toArray()[1], rotor.toArray()[2], rotor.toArray()[3] };
        }

        [[nodiscard]] static constexpr TranslatorWithRotor from(const std::span<double, componentsCount>& values) noexcept {
            return {
                .translator = Translator::from(values.first<Translator::componentsCount>()),
                .rotor = Rotor::from(values.last<Rotor::componentsCount>())
            };
        }

        [[nodiscard]] constexpr Motor toMotor() const noexcept { return translator.geometric(rotor); }

        [[nodiscard]] constexpr RotorWithTranslator reversed() const noexcept;

        [[nodiscard]] constexpr RotorWithTranslator toRotorWithTranslator() const noexcept;

        [[nodiscard]] static constexpr TranslatorWithRotor id() noexcept { return { .translator = Translator::id(), .rotor = Rotor::id() }; }
    };

    struct RotorWithTranslator {
        Rotor rotor{};
        Translator translator{};

        static size_t constexpr componentsCount = Rotor::componentsCount + Translator::componentsCount;

        [[nodiscard]] constexpr std::array<double, componentsCount> toArray() const noexcept {
            // a compiler will optimize this
            return { rotor.toArray()[0], rotor.toArray()[1], rotor.toArray()[2], rotor.toArray()[3], translator.toArray()[0], translator.toArray()[1], translator.toArray()[2] };
        }

        [[nodiscard]] static constexpr RotorWithTranslator from(const std::span<double, componentsCount>& values) noexcept {
            return {
                .rotor = Rotor::from(values.first<Rotor::componentsCount>()),
                .translator = Translator::from(values.last<Translator::componentsCount>())
            };
        }

        [[nodiscard]] constexpr Motor toMotor() const noexcept { return rotor.geometric(translator); }

        [[nodiscard]] constexpr TranslatorWithRotor reversed() const noexcept;

        [[nodiscard]] constexpr TranslatorWithRotor toTranslatorWithRotor() const noexcept;

        [[nodiscard]] static constexpr RotorWithTranslator id() noexcept { return { .rotor = Rotor::id(), .translator = Translator::id() }; }
    };

    [[nodiscard]] constexpr RotorWithTranslator TranslatorWithRotor::reversed() const noexcept { return { .rotor = rotor.reversed(), .translator = translator.reversed() }; }
    [[nodiscard]] constexpr RotorWithTranslator TranslatorWithRotor::toRotorWithTranslator() const noexcept { return { .rotor = rotor, .translator = rotor.reversed().sandwich(translator).toTranslator() }; };
    [[nodiscard]] constexpr TranslatorWithRotor RotorWithTranslator::reversed() const noexcept { return { .translator = translator.reversed(), .rotor = rotor.reversed() }; }
    [[nodiscard]] constexpr TranslatorWithRotor RotorWithTranslator::toTranslatorWithRotor() const noexcept { return { .translator = rotor.sandwich(translator).toTranslator(), .rotor = rotor }; };
}